### ISSUE TITLE
java.lang.NullPointerException

### ISSUE THREAD

**Issue by ben-clayton** [google/gapid#1088]
```
java.lang.NullPointerException
 at com.google.gapid.models.AtomStream.resolve(AtomStream.java:174)
 at com.google.gapid.models.AtomStream.selectAtoms(AtomStream.java:163)
 at com.google.gapid.views.ThumbnailScrubber.lambda$new$1(ThumbnailScrubber.java:78)
 at org.eclipse.swt.widgets.EventTable.sendEvent(Unknown Source)
 at org.eclipse.swt.widgets.Display.sendEvent(Unknown Source)
 at org.eclipse.swt.widgets.Widget.sendEvent(Unknown Source)
 at org.eclipse.swt.widgets.Display.runDeferredEvents(Unknown Source)
 at org.eclipse.swt.widgets.Display.readAndDispatch(Unknown Source)
 at org.eclipse.jface.window.Window.runEventLoop(Window.java:818)
 at org.eclipse.jface.window.Window.open(Window.java:794)
 at com.google.gapid.Main$UI.show(Main.java:109)
 at com.google.gapid.Main.main(Main.java:67)
```

**Comment by pmuetschard** [comment]
This is a dupe of #938
