### ISSUE TITLE
Cannot get the package listing on Pixel C.

### ISSUE THREAD

**Issue by AWoloszyn** [google/gapid#1194]
Gapic does not give me a package list when asked on the Pixel C.
Tracing/replaying does work if I type in the package name manually.

```
Exception in thread "com.google.gapid.server.GapitPkgInfoProcess$1" java.lang.RuntimeException: The gapit command didn't produce the data marker.
        at com.google.gapid.server.GapitPkgInfoProcess.lambda$createStdoutHandler$0(GapitPkgInfoProcess.java:115)
        at com.google.gapid.server.ChildProcess$BinaryHandler.run(ChildProcess.java:245)
        at com.google.gapid.server.ChildProcess$OutputHandler.lambda$start$0(ChildProcess.java:156)
        at java.lang.Thread.run(Thread.java:745)
W20171013-144211399[server.ChildProcess-gapit][views.ActivityPickerDialog$2.onFailure] Failed to read package info
W20171013-144211399[server.ChildProcess-gapit][views.ActivityPickerDialog$2.onFailure] java.lang.Exception: The gapit command failed:
18:42:11.393 F: <gapit> Main failed
Error: getting package list
   Cause: Connecting to service port
   Cause:
   Cause: Timeout connecting to service
```

**Comment by ben-clayton** [comment]
Can you please look in logcat for the exception in the gapid APK?

**Comment by AWoloszyn** [comment]
```
10-16 15:21:08.060 15875 16410 E gapid-pkginfo: Error occurred
10-16 15:21:08.060 15875 16410 E gapid-pkginfo: java.util.concurrent.ExecutionException: android.content.res.Resources$NotFoundException: Resource ID #0x7f030000
10-16 15:21:08.060 15875 16410 E gapid-pkginfo:         at java.util.concurrent.FutureTask.report(FutureTask.java:94)
10-16 15:21:08.060 15875 16410 E gapid-pkginfo:         at java.util.concurrent.FutureTask.get(FutureTask.java:164)
10-16 15:21:08.060 15875 16410 E gapid-pkginfo:         at com.google.android.gapid.SocketWriter.connectAndWrite(SocketWriter.java:46)
10-16 15:21:08.060 15875 16410 E gapid-pkginfo:         at com.google.android.gapid.PackageInfoService.handleSendPackageInfo(PackageInfoService.java:240)
10-16 15:21:08.060 15875 16410 E gapid-pkginfo:         at com.google.android.gapid.PackageInfoService.onHandleIntent(PackageInfoService.java:205)
10-16 15:21:08.060 15875 16410 E gapid-pkginfo:         at android.app.IntentService$ServiceHandler.handleMessage(IntentService.java:68)
10-16 15:21:08.060 15875 16410 E gapid-pkginfo:         at android.os.Handler.dispatchMessage(Handler.java:102)
10-16 15:21:08.060 15875 16410 E gapid-pkginfo:         at android.os.Looper.loop(Looper.java:154)
10-16 15:21:08.060 15875 16410 E gapid-pkginfo:         at android.os.HandlerThread.run(HandlerThread.java:61)
10-16 15:21:08.060 15875 16410 E gapid-pkginfo: Caused by: android.content.res.Resources$NotFoundException: Resource ID #0x7f030000
10-16 15:21:08.060 15875 16410 E gapid-pkginfo:         at android.content.res.ResourcesImpl.getValueForDensity(ResourcesImpl.java:199)
10-16 15:21:08.060 15875 16410 E gapid-pkginfo:         at android.content.res.Resources.getDrawableForDensity(Resources.java:827)
10-16 15:21:08.060 15875 16410 E gapid-pkginfo:         at android.content.res.Resources.getDrawableForDensity(Resources.java:806)
10-16 15:21:08.060 15875 16410 E gapid-pkginfo:         at com.google.android.gapid.PackageInfoService$IconStore.data(PackageInfoService.java:452)
10-16 15:21:08.060 15875 16410 E gapid-pkginfo:         at com.google.android.gapid.PackageInfoService$IconStore.access$500(PackageInfoService.java:395)
10-16 15:21:08.060 15875 16410 E gapid-pkginfo:         at com.google.android.gapid.PackageInfoService$IconStore$1.build(PackageInfoService.java:427)
10-16 15:21:08.060 15875 16410 E gapid-pkginfo:         at com.google.android.gapid.PackageInfoService$IconStore$1.build(PackageInfoService.java:404)
10-16 15:21:08.060 15875 16410 E gapid-pkginfo:         at com.google.android.gapid.FileCache$1.scopedBuild(FileCache.java:94)
10-16 15:21:08.060 15875 16410 E gapid-pkginfo:         at com.google.android.gapid.FileCache$1.build(FileCache.java:46)
10-16 15:21:08.060 15875 16410 E gapid-pkginfo:         at com.google.android.gapid.Cache.get(Cache.java:55)
10-16 15:21:08.060 15875 16410 E gapid-pkginfo:         at com.google.android.gapid.PackageInfoService$IconStore.add(PackageInfoService.java:442)
10-16 15:21:08.060 15875 16410 E gapid-pkginfo:         at com.google.android.gapid.PackageInfoService.getPackageJson(PackageInfoService.java:368)
10-16 15:21:08.060 15875 16410 E gapid-pkginfo:         at com.google.android.gapid.PackageInfoService.getPackageInfo(PackageInfoService.java:280)
10-16 15:21:08.060 15875 16410 E gapid-pkginfo:         at com.google.android.gapid.PackageInfoService.access$200(PackageInfoService.java:61)
10-16 15:21:08.060 15875 16410 E gapid-pkginfo:         at com.google.android.gapid.PackageInfoService$1.call(PackageInfoService.java:233)
10-16 15:21:08.060 15875 16410 E gapid-pkginfo:         at com.google.android.gapid.PackageInfoService$1.call(PackageInfoService.java:228)
10-16 15:21:08.060 15875 16410 E gapid-pkginfo:         at java.util.concurrent.FutureTask.run(FutureTask.java:237)
10-16 15:21:08.060 15875 16410 E gapid-pkginfo:         at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133)
10-16 15:21:08.060 15875 16410 E gapid-pkginfo:         at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607)
10-16 15:21:08.060 15875 16410 E gapid-pkginfo:         at java.lang.Thread.run(Thread.java:761)
```
