### ISSUE TITLE
Framebuffer can't be shown after trace UE4 project

### ISSUE THREAD

**Issue by tiantian20007** [google/gapid#1205]
All Draw call, OpenGL command,  textures, Vertex data, Shaders and has been captured and shown correctly, except the framebuffer. All framebuffer view just showed: 
read tcp 127.0.0.1:64243->127.0.0.1:64241: wsarecv: An existing connection was forcibly closed by the remote host.

I'm using gapid 0.6.2 on win10 for Android project built by UnrealEngine 4.15 and run on Android 7.0 device.

.gfxtrace file:
[DemoProject_20171017_1813.zip](https://github.com/google/gapid/files/1393218/DemoProject_20171017_1813.zip)

![_20171017182304](https://user-images.githubusercontent.com/406098/31659909-406e112c-b368-11e7-9bff-9db61c5e5836.png)
![_20171017182311](https://user-images.githubusercontent.com/406098/31659912-44cbb21a-b368-11e7-8b2c-5a32c9df666b.png)

**Comment by ben-clayton** [comment]
Hi @tiantian20007,

Thank you for the bug report. It looks like the replay has crashed.
Are you happy to share the `.gfxtrace` file with me to investigate further?

Many thanks,
Ben

**Comment by tiantian20007** [comment]
.gfxtrace file attached

**Comment by ben-clayton** [comment]
Hi @tiantian20007 - thank you for the trace. I found and fixed an issue that may have caused the issue you were seeing. Please can you backup and replace the gapis.exe with this version:

[gapis.exe.zip](https://github.com/google/gapid/files/1395291/gapis.exe.zip)

And see if this fixes your issue?

Alternatively, you can wait until we push our next version (likely 0.9.0).

Many thanks,
Ben

**Comment by tiantian20007** [comment]
After replacing gapis.exe, the application cannot be launched by gapid.bat

**Comment by ben-clayton** [comment]
This might be due to Windows security. If you just try running gapis.exe do you get a notification about running the program downloaded from the internet? It so, confined the dialog, close the app and try the batch file again. 
If that doesn't work, we'll be pushing a new release shortly anyway.

**Comment by ben-clayton** [comment]
I've landed a whole bunch of other fixes specific for UE4. I'm moderately confident this (and other issues) are fixed. I'll try to get another release out this week.

**Comment by ben-clayton** [comment]
[v0.9.0 has been released](https://github.com/google/gapid/releases/tag/v0.9.0).
Please let me know if you're still having issues @tiantian20007!

**Comment by tiantian20007** [comment]
Yes, it's fixed.
However, I encounter another issue: can show 2D Array texture.
When I click on the 2D array texture, an error show:
![_20171103114044](https://user-images.githubusercontent.com/406098/32359871-dbc649a2-c08b-11e7-8cd0-97d544a2ea36.png)
BTW, I use OpenGL multi-view extension in my app.

**Comment by ben-clayton** [comment]
Hi @tiantian20007,

I'm sorry you're having more issues - please can you expand the `Details...` and post the exception callstack?

**Comment by tiantian20007** [comment]
org.eclipse.swt.SWTError: Item not added
	at org.eclipse.swt.SWT.error(Unknown Source)
	at org.eclipse.swt.SWT.error(Unknown Source)
	at org.eclipse.swt.SWT.error(Unknown Source)
	at org.eclipse.swt.widgets.Widget.error(Unknown Source)
	at org.eclipse.swt.widgets.Menu.createItem(Unknown Source)
	at org.eclipse.swt.widgets.MenuItem.<init>(Unknown Source)
	at com.google.gapid.widgets.Widgets.createMenuItem(Widgets.java:320)
	at com.google.gapid.views.TextureView$GotoAction.update(TextureView.java:572)
	at com.google.gapid.views.TextureView$GotoAction.setAtomIds(TextureView.java:562)
	at com.google.gapid.views.TextureView.updateSelection(TextureView.java:287)
	at com.google.gapid.views.TextureView.lambda$new$3(TextureView.java:146)
	at org.eclipse.swt.widgets.EventTable.sendEvent(Unknown Source)
	at org.eclipse.swt.widgets.Display.sendEvent(Unknown Source)
	at org.eclipse.swt.widgets.Widget.sendEvent(Unknown Source)
	at org.eclipse.swt.widgets.Display.runDeferredEvents(Unknown Source)
	at org.eclipse.swt.widgets.Display.readAndDispatch(Unknown Source)
	at org.eclipse.jface.window.Window.runEventLoop(Window.java:818)
	at org.eclipse.jface.window.Window.open(Window.java:794)
	at com.google.gapid.Main$UI.show(Main.java:110)
	at com.google.gapid.Main.main(Main.java:68)
