### ISSUE TITLE
Panic in vulkan.postImageData

### ISSUE THREAD

**Issue by pmuetschard** [google/gapid#1213]
GAPID Version: 0.9.0:0:developer
OS: linux amd64

Opening a trace of the LunarG "draw cube" Vulkan sample.

```
panic: runtime error: invalid memory address or nil pointer dereference [recovered]
	panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x185d729]

goroutine 25 [running]:
github.com/google/gapid/core/app/crash.Crash.func1()
	/usr/local/google/work/gapid/src/github.com/google/gapid/core/app/crash/crash.go:73 +0x115
sync.(*Once).Do(0x4450338, 0xc420868700)
	/usr/local/google/work/gapid/go/src/sync/once.go:44 +0xbe
github.com/google/gapid/core/app/crash.Crash(0x211e380, 0x3a7ecf0)
	/usr/local/google/work/gapid/src/github.com/google/gapid/core/app/crash/crash.go:74 +0x9c
github.com/google/gapid/core/app/crash.handler()
	/usr/local/google/work/gapid/src/github.com/google/gapid/core/app/crash/crash.go:48 +0x52
panic(0x211e380, 0x3a7ecf0)
	/usr/local/google/work/gapid/go/src/runtime/panic.go:489 +0x2cf
github.com/google/gapid/gapis/api/vulkan.postImageData(0x3ad0920, 0xc4204c7950, 0x7f5d69b09780, 0xc4203e33e0, 0xc4200fbb00, 0x10000002c, 0x1f4000001f4, 0xc0000000c0, 0x3aa93e0, 0xc4203cf3e0, ...)
	/usr/local/google/work/gapid/src/github.com/google/gapid/gapis/api/vulkan/read_framebuffer.go:203 +0x169
github.com/google/gapid/gapis/api/vulkan.(*readFramebuffer).Color.func1(0x3ad0920, 0xc4204c7950, 0x3b075e0, 0xc420801f00, 0x3aa93e0, 0xc4203cf3e0)
	/usr/local/google/work/gapid/src/github.com/google/gapid/gapis/api/vulkan/read_framebuffer.go:140 +0x531
github.com/google/gapid/gapis/api/vulkan.(*readFramebuffer).Transform(0xc4207c60f8, 0x3ad0920, 0xc4204c7950, 0x145, 0x3b075e0, 0xc420801f00, 0x3aa93e0, 0xc4203cf3e0)
	/usr/local/google/work/gapid/src/github.com/google/gapid/gapis/api/vulkan/read_framebuffer.go:63 +0x24c
github.com/google/gapid/gapis/api/transform.TransformWriter.MutateAndWrite(0xc4203e33e0, 0x3aa7120, 0xc4207c60f8, 0x3aa93e0, 0xc4203cf3e0, 0x3ad0920, 0xc4204c7950, 0x145, 0x3b075e0, 0xc420801f00)
	/usr/local/google/work/gapid/src/github.com/google/gapid/gapis/api/transform/transforms.go:98 +0x83
github.com/google/gapid/gapis/api/transform.(*TransformWriter).MutateAndWrite(0xc4203cf410, 0x3ad0920, 0xc4204c7950, 0x145, 0x3b075e0, 0xc420801f00)
	<autogenerated>:13 +0xa1
github.com/google/gapid/gapis/api/vulkan.(*VulkanTerminator).Transform(0xc4204c7ce0, 0x3ad0920, 0xc4204c7950, 0x145, 0x3b075e0, 0xc420801f00, 0x3aa93e0, 0xc4203cf410)
	/usr/local/google/work/gapid/src/github.com/google/gapid/gapis/api/vulkan/vulkan_terminator.go:436 +0x31d
github.com/google/gapid/gapis/api/transform.TransformWriter.MutateAndWrite(0xc4203e33e0, 0x3aa7020, 0xc4204c7ce0, 0x3aa93e0, 0xc4203cf410, 0x3ad0920, 0xc4204c7950, 0x145, 0x3b075e0, 0xc420801f00)
	/usr/local/google/work/gapid/src/github.com/google/gapid/gapis/api/transform/transforms.go:98 +0x83
github.com/google/gapid/gapis/api/transform.(*TransformWriter).MutateAndWrite(0xc4203cf440, 0x3ad0920, 0xc4204c7950, 0x145, 0x3b075e0, 0xc420801f00)
	<autogenerated>:13 +0xa1
github.com/google/gapid/gapis/api/vulkan.(*makeAttachementReadable).Transform(0xc4204c7bf0, 0x3ad0920, 0xc4204c7950, 0x145, 0x3b075e0, 0xc420801f00, 0x3aa93e0, 0xc4203cf440)
	/usr/local/google/work/gapid/src/github.com/google/gapid/gapis/api/vulkan/replay.go:385 +0x1151
github.com/google/gapid/gapis/api/transform.TransformWriter.MutateAndWrite(0xc4203e33e0, 0x3aa70e0, 0xc4204c7bf0, 0x3aa93e0, 0xc4203cf440, 0x3ad0920, 0xc4204c7950, 0x145, 0x3b075e0, 0xc420801f00)
	/usr/local/google/work/gapid/src/github.com/google/gapid/gapis/api/transform/transforms.go:98 +0x83
github.com/google/gapid/gapis/api/transform.(*TransformWriter).MutateAndWrite(0xc4203cf470, 0x3ad0920, 0xc4204c7950, 0x145, 0x3b075e0, 0xc420801f00)
	<autogenerated>:13 +0xa1
github.com/google/gapid/gapis/api/transform.(*DCE).Flush(0xc42080ea80, 0x3ad0920, 0xc4204c7950, 0x3aa93e0, 0xc4203cf470)
	/usr/local/google/work/gapid/src/github.com/google/gapid/gapis/api/transform/dce.go:143 +0x665
github.com/google/gapid/gapis/api/transform.Transforms.Transform(0xc420a0e280, 0x6, 0x8, 0x3ad0920, 0xc4204c7950, 0xc420379ee8, 0x0, 0x0, 0x3aa71e0, 0xc420434e70)
	/usr/local/google/work/gapid/src/github.com/google/gapid/gapis/api/transform/transforms.go:44 +0x32c
github.com/google/gapid/gapis/api/vulkan.API.Replay(0x3ad0920, 0xc4204c7950, 0xc4207c60e8, 0xc4207c60f0, 0x22f1460, 0xc420819b60, 0xc4204c7680, 0x2, 0x2, 0x3b54300, ...)
	/usr/local/google/work/gapid/src/github.com/google/gapid/gapis/api/vulkan/replay.go:659 +0xe44
github.com/google/gapid/gapis/api/vulkan.(*API).Replay(0x44502b0, 0x3ad0920, 0xc4204c7950, 0xc4207c60e8, 0xc4207c60f0, 0x22f1460, 0xc420819b60, 0xc4204c7680, 0x2, 0x2, ...)
	<autogenerated>:10340 +0xfb
github.com/google/gapid/gapis/replay.(*Manager).execute(0xc42028bae0, 0x3ad0920, 0xc4204c7950, 0x281e6459679e9ead, 0x48424fece71347fc, 0x2c7e0d2cc552bb31, 0xb8511a9b7886d58c, 0x332ec26ac4077c54, 0x22f1460, 0xc420819b60, ...)
	/usr/local/google/work/gapid/src/github.com/google/gapid/gapis/replay/batch.go:134 +0xa04
github.com/google/gapid/gapis/replay.(*Manager).batch(0xc42028bae0, 0x3ad0920, 0xc4204c7650, 0xc420499500, 0x2, 0x2, 0x223f920, 0xc4207c1ae8, 0x22f63e0, 0xc420522eb0, ...)
	/usr/local/google/work/gapid/src/github.com/google/gapid/gapis/replay/batch.go:67 +0x514
github.com/google/gapid/gapis/replay.(*Manager).(github.com/google/gapid/gapis/replay.batch)-fm(0x3ad0920, 0xc42027d8c0, 0xc420499500, 0x2, 0x2, 0x223f920, 0xc4207c1ae8, 0x22f63e0, 0xc420522eb0, 0x1)
	/usr/local/google/work/gapid/src/github.com/google/gapid/gapis/replay/manager.go:126 +0x93
github.com/google/gapid/gapis/replay/scheduler.(*bin).exec(0xc420a0e100, 0x3ad0920, 0xc42027d8c0, 0xc42038a180)
	/usr/local/google/work/gapid/src/github.com/google/gapid/gapis/replay/scheduler/scheduler.go:243 +0x2d8
github.com/google/gapid/gapis/replay/scheduler.(*Scheduler).run(0xc42038c420, 0x3ad0920, 0xc42027d8c0)
	/usr/local/google/work/gapid/src/github.com/google/gapid/gapis/replay/scheduler/scheduler.go:176 +0x469
github.com/google/gapid/gapis/replay/scheduler.New.func1()
	/usr/local/google/work/gapid/src/github.com/google/gapid/gapis/replay/scheduler/scheduler.go:73 +0x3c
github.com/google/gapid/core/app/crash.Go.func1(0xc42038c440)
	/usr/local/google/work/gapid/src/github.com/google/gapid/core/app/crash/crash.go:57 +0x43
created by github.com/google/gapid/core/app/crash.Go
	/usr/local/google/work/gapid/src/github.com/google/gapid/core/app/crash/crash.go:58 +0x3f
```

**Comment by AWoloszyn** [comment]
I am so far unable to reproduce.

The callstack seems to point to:

```
	device := GetState(s).Devices[vkDevice]
	vkPhysicalDevice := device.PhysicalDevice
	physicalDevice := GetState(s).PhysicalDevices[vkPhysicalDevice]
```
Which is incredibly odd, this is implying that GetState(s).Devices[vkDevice] returns nullptr, which means we are trying to get a device off a queue, and the device doesn't exist. Which means that the queue should not exist?

Would you mind trying to turn off dead-code elimination and see if that fixes your issue. (Possibly also send me the trace in question).

**Comment by pmuetschard** [comment]
Trace file: https://drive.google.com/open?id=0B1KipO2Z_BxDMjlwbXJNam9PMEE

**Comment by AWoloszyn** [comment]
I think this is no longer an issue.
