### ISSUE TITLE
On GAPIC exit: Unhandled exception in the UI thread.

### ISSUE THREAD

**Issue by tomgoogle** [google/gapid#1273]
GAPID Version: 0.9.0:440:38bedfbac19fca9b7c37d99d32aaf3f0f223e303
OS: mac os x x86_64

Please provide detailed steps that led to the error and copy-paste the stack trace.
Extra details from the logs and the trace file would be extra helpful.

```
java.lang.NullPointerException
	at org.eclipse.swt.widgets.Display.readAndDispatch(Unknown Source)
	at org.eclipse.jface.window.Window.runEventLoop(Window.java:818)
	at org.eclipse.jface.window.Window.open(Window.java:794)
	at com.google.gapid.Main$UI.show(Main.java:109)
	at com.google.gapid.Main.main(Main.java:67)
```

I think I had the Capture Trace window open when the above happened, and when I tried to reproduce it, I got another callstack:

```
java.lang.NullPointerException
	at org.eclipse.swt.widgets.Display.readAndDispatch(Unknown Source)
	at org.eclipse.jface.window.Window.runEventLoop(Window.java:818)
	at org.eclipse.jface.window.Window.open(Window.java:794)
	at com.google.gapid.views.TracerDialog.loadDevicesAndShowDialog(TracerDialog.java:153)
	at com.google.gapid.views.TracerDialog.showTracingDialog(TracerDialog.java:117)
	at com.google.gapid.MainWindow.lambda$createFileMenu$10(MainWindow.java:314)
	at com.google.gapid.MainWindow$MenuItems$1.run(MainWindow.java:637)
	at org.eclipse.jface.action.Action.runWithEvent(Action.java:473)
	at org.eclipse.jface.action.ActionContributionItem.handleWidgetSelection(ActionContributionItem.java:565)
	at org.eclipse.jface.action.ActionContributionItem.lambda$4(ActionContributionItem.java:397)
	at org.eclipse.swt.widgets.EventTable.sendEvent(Unknown Source)
	at org.eclipse.swt.widgets.Display.sendEvent(Unknown Source)
	at org.eclipse.swt.widgets.Widget.sendEvent(Unknown Source)
	at org.eclipse.swt.widgets.Widget.sendEvent(Unknown Source)
	at org.eclipse.swt.widgets.Widget.sendEvent(Unknown Source)
	at org.eclipse.swt.widgets.Widget.notifyListeners(Unknown Source)
	at org.eclipse.swt.widgets.Display.runDeferredEvents(Unknown Source)
	at org.eclipse.swt.widgets.Display.readAndDispatch(Unknown Source)
	at org.eclipse.jface.window.Window.runEventLoop(Window.java:818)
	at org.eclipse.jface.window.Window.open(Window.java:794)
	at com.google.gapid.Main$UI.show(Main.java:109)
	at com.google.gapid.Main.main(Main.java:67)
```

**Comment by pmuetschard** [comment]
argh, for some reason quitting the app while a dialog is running causes the dialog to exit as if the ok button was pressed....
