### ISSUE TITLE
Unhandled exception in the UI thread. (UndeclaredThrowableException)

### ISSUE THREAD

**Issue by ben-clayton** [google/gapid#1323]
On OSX @ 7f6628d4c572427f78b5c3a85d5aebbf771d25c7:

```
org.eclipse.swt.SWTException: Failed to execute runnable (java.lang.reflect.UndeclaredThrowableException)
	at org.eclipse.swt.SWT.error(Unknown Source)
	at org.eclipse.swt.SWT.error(Unknown Source)
	at org.eclipse.swt.widgets.Synchronizer.runAsyncMessages(Unknown Source)
	at org.eclipse.swt.widgets.Display.runAsyncMessages(Unknown Source)
	at org.eclipse.swt.widgets.Display.readAndDispatch(Unknown Source)
	at org.eclipse.jface.window.Window.runEventLoop(Window.java:818)
	at org.eclipse.jface.window.Window.open(Window.java:794)
	at com.google.gapid.Main$UI.show(Main.java:110)
	at com.google.gapid.Main.main(Main.java:68)
Caused by: java.lang.reflect.UndeclaredThrowableException
	at com.sun.proxy.$Proxy7.onStateLoaded(Unknown Source)
	at com.google.gapid.models.ApiState.fireLoadedEvent(ApiState.java:114)
	at com.google.gapid.models.ModelBase.updateSuccess(ModelBase.java:98)
	at com.google.gapid.models.ModelBase$1.onUiThreadSuccess(ModelBase.java:74)
	at com.google.gapid.rpc.UiErrorCallback.onUiThread(UiErrorCallback.java:34)
	at com.google.gapid.rpc.UiErrorCallback.onUiThread(UiErrorCallback.java:25)
	at com.google.gapid.rpc.UiCallback.lambda$onFinish$0(UiCallback.java:46)
	at com.google.gapid.widgets.Widgets.ifNotDisposed(Widgets.java:119)
	at com.google.gapid.widgets.Widgets.lambda$scheduleIfNotDisposed$1(Widgets.java:147)
	at com.google.gapid.widgets.Widgets.lambda$schedule$0(Widgets.java:139)
	at org.eclipse.swt.widgets.RunnableLock.run(Unknown Source)
	... 7 more
Caused by: java.lang.reflect.InvocationTargetException
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.google.gapid.util.Events$ListenerCollectionImpl.invoke(Events.java:167)
	... 18 more
Caused by: java.lang.RuntimeException: Unexpected path case: PATH_NOT_SET
	at com.google.gapid.util.Paths.dispatchAny(Paths.java:421)
	at com.google.gapid.util.Paths.dispatch(Paths.java:431)
	at com.google.gapid.util.Paths.toNode(Paths.java:249)
	at com.google.gapid.util.Paths.find(Paths.java:233)
	at com.google.gapid.util.Paths.findGlobalState(Paths.java:242)
	at com.google.gapid.views.StateView.updateExpansionState(StateView.java:249)
	at com.google.gapid.views.StateView.onStateLoaded(StateView.java:217)
	... 23 more
```

**Comment by ben-clayton** [comment]
Assuming fixed. Will reopen if seen again.
