### ISSUE TITLE
SWTError: Item not added

### ISSUE THREAD

**Issue by ben-clayton** [google/gapid#1327]
Forked from: #1205

Clicking on a texture array causes the following unhandled exception:

```
org.eclipse.swt.SWTError: Item not added
at org.eclipse.swt.SWT.error(Unknown Source)
at org.eclipse.swt.SWT.error(Unknown Source)
at org.eclipse.swt.SWT.error(Unknown Source)
at org.eclipse.swt.widgets.Widget.error(Unknown Source)
at org.eclipse.swt.widgets.Menu.createItem(Unknown Source)
at org.eclipse.swt.widgets.MenuItem.(Unknown Source)
at com.google.gapid.widgets.Widgets.createMenuItem(Widgets.java:320)
at com.google.gapid.views.TextureView$GotoAction.update(TextureView.java:572)
at com.google.gapid.views.TextureView$GotoAction.setAtomIds(TextureView.java:562)
at com.google.gapid.views.TextureView.updateSelection(TextureView.java:287)
at com.google.gapid.views.TextureView.lambda$new$3(TextureView.java:146)
at org.eclipse.swt.widgets.EventTable.sendEvent(Unknown Source)
at org.eclipse.swt.widgets.Display.sendEvent(Unknown Source)
at org.eclipse.swt.widgets.Widget.sendEvent(Unknown Source)
at org.eclipse.swt.widgets.Display.runDeferredEvents(Unknown Source)
at org.eclipse.swt.widgets.Display.readAndDispatch(Unknown Source)
at org.eclipse.jface.window.Window.runEventLoop(Window.java:818)
at org.eclipse.jface.window.Window.open(Window.java:794)
at com.google.gapid.Main$UI.show(Main.java:110)
at com.google.gapid.Main.main(Main.java:68)
```

**Comment by ben-clayton** [comment]
Seems likely that there were just a stupid number of entries in the jump-to menu, causing the OS to error when building the drop-down menu.
We should cope with large reference lists like this.
