### ISSUE TITLE
The gapis server has exited with an error code of: 2

### ISSUE THREAD

**Issue by ivasku** [google/gapid#1339]
GAPID Version: 0.9.0:462:d99eabb1f78d31ec29a36a7a4838c8ce64c4a6de
OS: windows 8.1 amd64

The application encountered an error:
The gapis server has exited with an error code of: 2

Please check the logs for details.

```
panic: interface conversion: interface {} is *capture.Record, not *capture.Capture

goroutine 494 [running]:
github.com/google/gapid/gapis/capture.ResolveFromID(0x3807fa0, 0xc0422c8510, 0x7ea832d9bec285b0, 0xe8e33fe74e26f181, 0xc0d0a758e8, 0xc0422f4058, 0xc0422c8570, 0xc04215a0e0)
	T:/src/github/src/github.com/google/gapid/gapis/capture/capture.go:151 +0xbd
github.com/google/gapid/gapis/capture.ResolveFromPath(0x3807fa0, 0xc0422c8510, 0xc0422f4058, 0x20, 0xc042090000, 0x9)
	T:/src/github/src/github.com/google/gapid/gapis/capture/capture.go:156 +0xda
github.com/google/gapid/gapis/server.(*server).LoadCapture(0xc04231c3c0, 0x3807fa0, 0xc0422c8510, 0xc0422c8150, 0x2d, 0xc042303a30, 0x40f52a, 0x2057fe0)
	T:/src/github/src/github.com/google/gapid/gapis/server/server.go:186 +0x168
github.com/google/gapid/gapis/server.(*grpcServer).LoadCapture(0xc0422cd650, 0x68f0000, 0xc04211fbc0, 0xc0421661d0, 0x0, 0x0, 0x0)
	T:/src/github/src/github.com/google/gapid/gapis/server/grpc.go:271 +0x11c
github.com/google/gapid/gapis/service._Gapid_LoadCapture_Handler.func1(0x68f0000, 0xc04211fbc0, 0x1f1aaa0, 0xc0421661d0, 0xc0422bdc01, 0x411b01, 0x20, 0x1ed6180)
	T:/src/github/src/github.com/google/gapid/gapis/service/service.pb.go:5591 +0x90
github.com/google/gapid/core/app/auth.ServerInterceptor.func1(0x68f0000, 0xc04211fbc0, 0x1f1aaa0, 0xc0421661d0, 0xc04211bac0, 0xc04211bb60, 0x0, 0xc042199b50, 0x411baf, 0x70)
	T:/src/github/src/github.com/google/gapid/core/app/auth/auth.go:82 +0x169
github.com/google/gapid/gapis/service._Gapid_LoadCapture_Handler(0x21b86e0, 0xc0422cd650, 0x68f0000, 0xc04211fbc0, 0xc042086070, 0xc0422e9ea0, 0x0, 0x0, 0xc0421720e0, 0x0)
	T:/src/github/src/github.com/google/gapid/gapis/service/service.pb.go:5593 +0x17e
google.golang.org/grpc.(*Server).processUnaryRPC(0xc0423311e0, 0x380c180, 0xc04230e1c0, 0xc042356300, 0xc0422cd7a0, 0x38991f0, 0xc0422c8060, 0x0, 0x0)
	T:/src/github/src/github.com/google/gapid/third_party/src/google.golang.org/grpc/server.go:719 +0xaa7
google.golang.org/grpc.(*Server).handleStream(0xc0423311e0, 0x380c180, 0xc04230e1c0, 0xc042356300, 0xc0422c8060)
	T:/src/github/src/github.com/google/gapid/third_party/src/google.golang.org/grpc/server.go:905 +0x1268
google.golang.org/grpc.(*Server).serveStreams.func1.1(0xc0422f8150, 0xc0423311e0, 0x380c180, 0xc04230e1c0, 0xc042356300)
	T:/src/github/src/github.com/google/gapid/third_party/src/google.golang.org/grpc/server.go:478 +0xb0
created by google.golang.org/grpc.(*Server).serveStreams.func1
	T:/src/github/src/github.com/google/gapid/third_party/src/google.golang.org/grpc/server.go:479 +0xa8
```

**Comment by ben-clayton** [comment]
Hi @ivasku,

This should definitely not happen. Are you able to share the trace with me?

Many thanks,
Ben

**Comment by ben-clayton** [comment]
I've found a bug that can cause this error to happen if the file format is too old.
Are you attempting to open a `.gfxtrace` file created by `v0.5.1` or older of GAPID by any chance?

**Comment by ivasku** [comment]
Hey, 

To share the trace file? It is 0 kn in size. 

No, I don`t have any trace file. I am attempting to run a new trace. It finds the device, the activity to open. It opens the app and it is stuck at splash screen and just sitting like that. After a while when I stop it, I get the error I reported.

**Comment by ben-clayton** [comment]
Oh - that's not good. What device are you attempting to trace on?

**Comment by ivasku** [comment]
On nexus 5. I don`t have the phone at the time at me, but I believe it is for sure api 21+

**Comment by ivasku** [comment]
Here is a screenshot, it just sits like this and the app is stuck at splash screen. After a while after not happening anything I stop the capture and the error I pasted when I filed this bug.

![gapid1](https://user-images.githubusercontent.com/5948031/32480321-6265e12a-c38e-11e7-9270-fb79b0620a66.PNG)

**Comment by ben-clayton** [comment]
Interesting, thank you for the info so far.
To help us try and reproduce, please can you try to answer the following:

1. The device is an original Nexus 5, correct?
2. What build of Android is the device running?
3. Are you using any sort of middleware? Unity or Unreal? If so what version?
4. If you aren't using any middleware, what technology are you using?
   1. Pure Java? Pure NDK? 
   2. If you use the NDK, how do you load the OpenGL ES functions? Do you use static linking? Or do you `dlopen()` the library and `dlsym()` the functions?
5. Is there anything in logcat that could help diagnose the issue?
6. Are you also running Android Studio at the same time as trying to take a trace? If so, do you get the same issue if it is closed?

Thank you!
Ben

**Comment by ivasku** [comment]
1. Yes. Lg Nexus 5 (hammerhead board).
2. Android 6.0.1 , Api 23
3. No.
4.1. I am using java with  NDK.3
4.2. I am initializing the OpenGL ES from Java, and onDrawFrame I call my render functions which are in c++. My main .so file which is build is built as SHARED library. I am using a external sound library which has cpu-features.c where it uses `void* libc_handle = dlopen("libc.so", RTLD_NOW);` . Other than that , no.
5. No. The app just stand still, no errors or anything interesting.
6. At first I was using with Android Studio closed, but I tried both ways, it doesn`t change except when it is opened it cannot connect to the device.

If I can help please let me know.
Adrian

**Comment by ben-clayton** [comment]
There's nothing you've listed here that looks suspicious.

Are you comfortable sending me the APK to debug what's going wrong? If so my email address is 
<img width="146" alt="myemail" src="https://user-images.githubusercontent.com/11505236/32493506-fbf0d210-c3b5-11e7-80c2-8a6cff330f6e.png">

Thanks,
Ben

**Comment by ivasku** [comment]
Sorry, but I don`t have the permission to share the project until it goes live. It is not up to me...

**Comment by ben-clayton** [comment]
No problem. Do you have any other APKs that you can share that exhibit this issue? Like a previously shipped game, or a simple asset-free level?

**Comment by ivasku** [comment]
Let me check on that and if I can do something I`l let you know.

**Comment by ben-clayton** [comment]
Closing due to inactivity
