### ISSUE TITLE
Loading capture * .gfxtrace, report: panic: runtime error: index out of range

### ISSUE THREAD

**Issue by zhenian** [google/gapid#134]
```
I20170324-093527524[main][models.Capture.loadCapture] Loading capture /ws/gpu/training_20170323_1156.gfxtrace...
W20170324-093528956[server.ChildProcess$LoggingStringHandler][server.ChildProcess$LoggingStringHandler.lambda$new$71] gapis: panic: runtime error: index out of range
W20170324-093528956[server.ChildProcess$LoggingStringHandler][server.ChildProcess$LoggingStringHandler.lambda$new$71] gapis:
W20170324-093528957[server.ChildProcess$LoggingStringHandler][server.ChildProcess$LoggingStringHandler.lambda$new$71] gapis: goroutine 75 [running]:
W20170324-093528957[server.ChildProcess$LoggingStringHandler][server.ChildProcess$LoggingStringHandler.lambda$new$71] gapis: github.com/google/gapid/gapis/gfxapi/gles.moveClientVBsToVAs(0x766d360, 0xc422357e90, 0xc421aec190, 0xc422ba9d70, 0x0, 0xffffffffffffffff, 0x297, 0x7672c40, 0xc4205326f0, 0xc4200ae310, ...)
W20170324-093528957[server.ChildProcess$LoggingStringHandler][server.ChildProcess$LoggingStringHandler.lambda$new$71] gapis: 	/myenv/go/src/github.com/google/gapid/gapis/gfxapi/gles/compat.go:1071 +0x611
W20170324-093528957[server.ChildProcess$LoggingStringHandler][server.ChildProcess$LoggingStringHandler.lambda$new$71] gapis: github.com/google/gapid/gapis/gfxapi/gles.compat.func4(0x766d360, 0xc422357e90, 0x297, 0x7672c40, 0xc4205326f0, 0x76130e0, 0xc422ba9f20)
W20170324-093528958[server.ChildProcess$LoggingStringHandler][server.ChildProcess$LoggingStringHandler.lambda$new$71] gapis: 	/myenv/go/src/github.com/google/gapid/gapis/gfxapi/gles/compat.go:521 +0x15fd
W20170324-093528958[server.ChildProcess$LoggingStringHandler][server.ChildProcess$LoggingStringHandler.lambda$new$71] gapis: github.com/google/gapid/gapis/atom/transform.transform.Transform(0x5fbd6d9, 0x6, 0xc420659f40, 0x766d360, 0xc422357e90, 0x297, 0x7672c40, 0xc4205326f0, 0x76130e0, 0xc422ba9f20)
W20170324-093528958[server.ChildProcess$LoggingStringHandler][server.ChildProcess$LoggingStringHandler.lambda$new$71] gapis: 	/myenv/go/src/github.com/google/gapid/gapis/atom/transform/transforms.go:75 +0x75
W20170324-093528958[server.ChildProcess$LoggingStringHandler][server.ChildProcess$LoggingStringHandler.lambda$new$71] gapis: github.com/google/gapid/gapis/atom/transform.(*transform).Transform(0xc421c9dc00, 0x766d360, 0xc422357e90, 0x297, 0x7672c40, 0xc4205326f0, 0x76130e0, 0xc422ba9f20)
W20170324-093528958[server.ChildProcess$LoggingStringHandler][server.ChildProcess$LoggingStringHandler.lambda$new$71] gapis: 	<autogenerated>:10 +0xb1
W20170324-093528961[server.ChildProcess$LoggingStringHandler][server.ChildProcess$LoggingStringHandler.lambda$new$71] gapis: github.com/google/gapid/gapis/atom/transform.TransformWriter.MutateAndWrite(0xc4200ae310, 0x7613120, 0xc421c9dc00, 0x76130e0, 0xc422ba9f20, 0x766d360, 0xc422357e90, 0x297, 0x7672c40, 0xc4205326f0)
W20170324-093528961[server.ChildProcess$LoggingStringHandler][server.ChildProcess$LoggingStringHandler.lambda$new$71] gapis: 	/myenv/go/src/github.com/google/gapid/gapis/atom/transform/transforms.go:98 +0x83
W20170324-093528961[server.ChildProcess$LoggingStringHandler][server.ChildProcess$LoggingStringHandler.lambda$new$71] gapis: github.com/google/gapid/gapis/atom/transform.(*TransformWriter).MutateAndWrite(0xc422ba9f50, 0x766d360, 0xc422357e90, 0x297, 0x7672c40, 0xc4205326f0)
W20170324-093528961[server.ChildProcess$LoggingStringHandler][server.ChildProcess$LoggingStringHandler.lambda$new$71] gapis: 	<autogenerated>:8 +0xa1
W20170324-093528961[server.ChildProcess$LoggingStringHandler][server.ChildProcess$LoggingStringHandler.lambda$new$71] gapis: github.com/google/gapid/gapis/gfxapi/gles.(*readFramebuffer).Transform(0xc422bae090, 0x766d360, 0xc422357e90, 0x297, 0x7672c40, 0xc4205326f0, 0x76130e0, 0xc422ba9f50)
W20170324-093528961[server.ChildProcess$LoggingStringHandler][server.ChildProcess$LoggingStringHandler.lambda$new$71] gapis: 	/myenv/go/src/github.com/google/gapid/gapis/gfxapi/gles/read_framebuffer.go:45 +0x73
W20170324-093528962[server.ChildProcess$LoggingStringHandler][server.ChildProcess$LoggingStringHandler.lambda$new$71] gapis: github.com/google/gapid/gapis/atom/transform.TransformWriter.MutateAndWrite(0xc4200ae310, 0x76111e0, 0xc422bae090, 0x76130e0, 0xc422ba9f50, 0x766d360, 0xc422357e90, 0x297, 0x7672c40, 0xc4205326f0)
W20170324-093528962[server.ChildProcess$LoggingStringHandler][server.ChildProcess$LoggingStringHandler.lambda$new$71] gapis: 	/myenv/go/src/github.com/google/gapid/gapis/atom/transform/transforms.go:98 +0x83
W20170324-093528962[server.ChildProcess$LoggingStringHandler][server.ChildProcess$LoggingStringHandler.lambda$new$71] gapis: github.com/google/gapid/gapis/atom/transform.(*TransformWriter).MutateAndWrite(0xc422ba9f80, 0x766d360, 0xc422357e90, 0x297, 0x7672c40, 0xc4205326f0)
W20170324-093528962[server.ChildProcess$LoggingStringHandler][server.ChildProcess$LoggingStringHandler.lambda$new$71] gapis: 	<autogenerated>:8 +0xa1
W20170324-093528963[Thread-1][server.GapisConnection$GRpcGapisConnection$LogMonitorThread.run] getLogStream() threw unexpected exception
W20170324-093528963[server.ChildProcess$LoggingStringHandler][server.ChildProcess$LoggingStringHandler.lambda$new$71] gapis: github.com/google/gapid/gapis/gfxapi/gles.undefinedFramebuffer.func1(0x766d360, 0xc422357e90, 0x297, 0x7672c40, 0xc4205326f0, 0x76130e0, 0xc422ba9f80)
W20170324-093528963[server.ChildProcess$LoggingStringHandler][server.ChildProcess$LoggingStringHandler.lambda$new$71] gapis: 	/myenv/go/src/github.com/google/gapid/gapis/gfxapi/gles/undefined_framebuffer.go:32 +0x9c
W20170324-093528963[server.ChildProcess$LoggingStringHandler][server.ChildProcess$LoggingStringHandler.lambda$new$71] gapis: github.com/google/gapid/gapis/atom/transform.transform.Transform(0x5fca805, 0x10, 0xc421c9da20, 0x766d360, 0xc422357e90, 0x297, 0x7672c40, 0xc4205326f0, 0x76130e0, 0xc422ba9f80)
W20170324-093528964[server.ChildProcess$LoggingStringHandler][server.ChildProcess$LoggingStringHandler.lambda$new$71] gapis: 	/myenv/go/src/github.com/google/gapid/gapis/atom/transform/transforms.go:75 +0x75
W20170324-093528964[server.ChildProcess$LoggingStringHandler][server.ChildProcess$LoggingStringHandler.lambda$new$71] gapis: github.com/google/gapid/gapis/atom/transform.(*transform).Transform(0xc421c9da40, 0x766d360, 0xc422357e90, 0x297, 0x7672c40, 0xc4205326f0, 0x76130e0, 0xc422ba9f80)
W20170324-093528964[server.ChildProcess$LoggingStringHandler][server.ChildProcess$LoggingStringHandler.lambda$new$71] gapis: 	<autogenerated>:10 +0xb1
W20170324-093528965[server.ChildProcess$LoggingStringHandler][server.ChildProcess$LoggingStringHandler.lambda$new$71] gapis: github.com/google/gapid/gapis/atom/transform.TransformWriter.MutateAndWrite(0xc4200ae310, 0x7613120, 0xc421c9da40, 0x76130e0, 0xc422ba9f80, 0x766d360, 0xc422357e90, 0x297, 0x7672c40, 0xc4205326f0)
E20170324-093528963[grpc-default-executor-2][models.CaptureDependentModel.processResult] LoadData error
E20170324-093528963[grpc-default-executor-2][models.CaptureDependentModel.processResult] java.util.concurrent.ExecutionException: io.grpc.StatusRuntimeException: UNAVAILABLE: End of stream or IOException
E20170324-093528963[grpc-default-executor-2][models.CaptureDependentModel.processResult] 	at com.google.common.util.concurrent.AbstractFuture.getDoneValue(AbstractFuture.java:500)
E20170324-093528963[grpc-default-executor-2][models.CaptureDependentModel.processResult] 	at com.google.common.util.concurrent.AbstractFuture.get(AbstractFuture.java:459)
E20170324-093528963[grpc-default-executor-2][models.CaptureDependentModel.processResult] 	at com.google.common.util.concurrent.AbstractFuture$TrustedFuture.get(AbstractFuture.java:76)
E20170324-093528963[grpc-default-executor-2][models.CaptureDependentModel.processResult] 	at com.google.common.util.concurrent.Uninterruptibles.getUninterruptibly(Uninterruptibles.java:142)
E20170324-093528963[grpc-default-executor-2][models.CaptureDependentModel.processResult] 	at com.google.gapid.rpclib.rpccore.Rpc$Result.get(Rpc.java:148)
E20170324-093528963[grpc-default-executor-2][models.CaptureDependentModel.processResult] 	at com.google.gapid.models.CaptureDependentModel.processResult(CaptureDependentModel.java:106)
E20170324-093528963[grpc-default-executor-2][models.CaptureDependentModel.processResult] 	at com.google.gapid.models.CaptureDependentModel$2.onRpcThread(CaptureDependentModel.java:84)
E20170324-093528963[grpc-default-executor-2][models.CaptureDependentModel.processResult] 	at com.google.gapid.models.CaptureDependentModel$2.onRpcThread(CaptureDependentModel.java:81)
E20170324-093528963[grpc-default-executor-2][models.CaptureDependentModel.processResult] 	at com.google.gapid.util.UiCallback.onFinish(UiCallback.java:46)
E20170324-093528963[grpc-default-executor-2][models.CaptureDependentModel.processResult] 	at com.google.gapid.rpclib.rpccore.Rpc$1.run(Rpc.java:100)
E20170324-093528963[grpc-default-executor-2][models.CaptureDependentModel.processResult] 	at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:435)
E20170324-093528963[grpc-default-executor-2][models.CaptureDependentModel.processResult] 	at com.google.common.util.concurrent.AbstractFuture.executeListener(AbstractFuture.java:900)
E20170324-093528963[grpc-default-executor-2][models.CaptureDependentModel.processResult] 	at com.google.common.util.concurrent.AbstractFuture.complete(AbstractFuture.java:811)
E20170324-093528963[grpc-default-executor-2][models.CaptureDependentModel.processResult] 	at com.google.common.util.concurrent.AbstractFuture.setException(AbstractFuture.java:675)
E20170324-093528963[grpc-default-executor-2][models.CaptureDependentModel.processResult] 	at com.google.common.util.concurrent.AbstractTransformFuture.run(AbstractTransformFuture.java:112)
E20170324-093528963[grpc-default-executor-2][models.CaptureDependentModel.processResult] 	at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:435)
E20170324-093528963[grpc-default-executor-2][models.CaptureDependentModel.processResult] 	at com.google.common.util.concurrent.AbstractFuture.executeListener(AbstractFuture.java:900)
E20170324-093528963[grpc-default-executor-2][models.CaptureDependentModel.processResult] 	at com.google.common.util.concurrent.AbstractFuture.complete(AbstractFuture.java:811)
E20170324-093528963[grpc-default-executor-2][models.CaptureDependentModel.processResult] 	at com.google.common.util.concurrent.AbstractFuture.setException(AbstractFuture.java:675)
E20170324-093528963[grpc-default-executor-2][models.CaptureDependentModel.processResult] 	at com.google.common.util.concurrent.AbstractTransformFuture.run(AbstractTransformFuture.java:112)
E20170324-093528963[grpc-default-executor-2][models.CaptureDependentModel.processResult] 	at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:435)
E20170324-093528963[grpc-default-executor-2][models.CaptureDependentModel.processResult] 	at com.google.common.util.concurrent.AbstractFuture.executeListener(AbstractFuture.java:900)
E20170324-093528963[grpc-default-executor-2][models.CaptureDependentModel.processResult] 	at com.google.common.util.concurrent.AbstractFuture.complete(AbstractFuture.java:811)
E20170324-093528963[grpc-default-executor-2][models.CaptureDependentModel.processResult] 	at com.google.common.util.concurrent.AbstractFuture.setException(AbstractFuture.java:675)
E20170324-093528963[grpc-default-executor-2][models.CaptureDependentModel.processResult] 	at io.grpc.stub.ClientCalls$GrpcFuture.setException(ClientCalls.java:466)
E20170324-093528963[grpc-default-executor-2][models.CaptureDependentModel.processResult] 	at io.grpc.stub.ClientCalls$UnaryStreamToFuture.onClose(ClientCalls.java:442)
E20170324-093528963[grpc-default-executor-2][models.CaptureDependentModel.processResult] 	at io.grpc.internal.ClientCallImpl$ClientStreamListenerImpl.close(ClientCallImpl.java:481)
E20170324-093528963[grpc-default-executor-2][models.CaptureDependentModel.processResult] 	at io.grpc.internal.ClientCallImpl$ClientStreamListenerImpl.access$600(ClientCallImpl.java:398)
E20170324-093528963[grpc-default-executor-2][models.CaptureDependentModel.processResult] 	at io.grpc.internal.ClientCallImpl$ClientStreamListenerImpl$1StreamClosed.runInContext(ClientCallImpl.java:513)
E20170324-093528963[grpc-default-executor-2][models.CaptureDependentModel.processResult] 	at io.grpc.internal.ContextRunnable.run(ContextRunnable.java:52)
E20170324-093528963[grpc-default-executor-2][models.CaptureDependentModel.processResult] 	at io.grpc.internal.SerializingExecutor$TaskRunner.run(SerializingExecutor.java:154)
E20170324-093528963[grpc-default-executor-2][models.CaptureDependentModel.processResult] 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
E20170324-093528963[grpc-default-executor-2][models.CaptureDependentModel.processResult] 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
E20170324-093528963[grpc-default-executor-2][models.CaptureDependentModel.processResult] 	at java.lang.Thread.run(Thread.java:745)
E20170324-093528963[grpc-default-executor-2][models.CaptureDependentModel.processResult] Caused by: io.grpc.StatusRuntimeException: UNAVAILABLE: End of stream or IOException
E20170324-093528963[grpc-default-executor-2][models.CaptureDependentModel.processResult] 	at io.grpc.Status.asRuntimeException(Status.java:545)
E20170324-093528963[grpc-default-executor-2][models.CaptureDependentModel.processResult] 	... 9 more
W20170324-093528963[server.ChildProcess$LoggingStringHandler][server.ChildProcess$LoggingStringHandler.lambda$new$71] gapis: 	/myenv/go/src/github.com/google/gapid/gapis/atom/transform/transforms.go:98 +0x83
W20170324-093529021[server.ChildProcess$LoggingStringHandler][server.ChildProcess$LoggingStringHandler.lambda$new$71] gapis: github.com/google/gapid/gapis/atom/transform.(*TransformWriter).MutateAndWrite(0xc422ba9fb0, 0x766d360, 0xc422357e90, 0x297, 0x7672c40, 0xc4205326f0)
W20170324-093529022[server.ChildProcess$LoggingStringHandler][server.ChildProcess$LoggingStringHandler.lambda$new$71] gapis: 	<autogenerated>:8 +0xa1
W20170324-093529022[server.ChildProcess$LoggingStringHandler][server.ChildProcess$LoggingStringHandler.lambda$new$71] gapis: github.com/google/gapid/gapis/gfxapi/gles.(*findIssues).Transform(0xc422ba9bc0, 0x766d360, 0xc422357e90, 0x297, 0x7672c40, 0xc4205326f0, 0x76130e0, 0xc422ba9fb0)
W20170324-093529022[server.ChildProcess$LoggingStringHandler][server.ChildProcess$LoggingStringHandler.lambda$new$71] gapis: 	/myenv/go/src/github.com/google/gapid/gapis/gfxapi/gles/find_issues.go:102 +0x168
W20170324-093529022[server.ChildProcess$LoggingStringHandler][server.ChildProcess$LoggingStringHandler.lambda$new$71] gapis: github.com/google/gapid/gapis/atom/transform.TransformWriter.MutateAndWrite(0xc4200ae310, 0x76111a0, 0xc422ba9bc0, 0x76130e0, 0xc422ba9fb0, 0x766d360, 0xc4220ff380, 0x297, 0x7672c40, 0xc4205326f0)
W20170324-093529040[server.ChildProcess$LoggingStringHandler][server.ChildProcess$LoggingStringHandler.lambda$new$71] gapis: 	/myenv/go/src/github.com/google/gapid/gapis/atom/transform/transforms.go:98 +0x83
W20170324-093529041[server.ChildProcess$LoggingStringHandler][server.ChildProcess$LoggingStringHandler.lambda$new$71] gapis: github.com/google/gapid/gapis/atom/transform.(*TransformWriter).MutateAndWrite(0xc422b7e000, 0x766d360, 0xc4220ff380, 0x297, 0x7672c40, 0xc4205326f0)
W20170324-093529041[server.ChildProcess$LoggingStringHandler][server.ChildProcess$LoggingStringHandler.lambda$new$71] gapis: 	<autogenerated>:8 +0xa1
W20170324-093529041[server.ChildProcess$LoggingStringHandler][server.ChildProcess$LoggingStringHandler.lambda$new$71] gapis: github.com/google/gapid/gapis/atom/transform.Transforms.Transform(0xc42053bd80, 0x5, 0x8, 0x766d360, 0xc4220ff380, 0xc420caa000, 0x3987, 0x3987, 0x76113a0, 0xc421eb64c0)
W20170324-093529041[server.ChildProcess$LoggingStringHandler][server.ChildProcess$LoggingStringHandler.lambda$new$71] gapis: 	/myenv/go/src/github.com/google/gapid/gapis/atom/transform/transforms.go:40 +0x1ba
W20170324-093529041[server.ChildProcess$LoggingStringHandler][server.ChildProcess$LoggingStringHandler.lambda$new$71] gapis: github.com/google/gapid/gapis/gfxapi/gles.api.Replay(0x766d360, 0xc4220fed20, 0xc421eba008, 0xc421eba010, 0x5c2d8a0, 0x776cbe0, 0xc422548100, 0x1, 0x1, 0x76cfda0, ...)
W20170324-093529042[server.ChildProcess$LoggingStringHandler][server.ChildProcess$LoggingStringHandler.lambda$new$71] gapis: 	/myenv/go/src/github.com/google/gapid/gapis/gfxapi/gles/replay.go:211 +0xba3
W20170324-093529042[server.ChildProcess$LoggingStringHandler][server.ChildProcess$LoggingStringHandler.lambda$new$71] gapis: github.com/google/gapid/gapis/gfxapi/gles.(*api).Replay(0x776cbe0, 0x766d360, 0xc4220fed20, 0xc421eba008, 0xc421eba010, 0x5c2d8a0, 0x776cbe0, 0xc422548100, 0x1, 0x1, ...)
W20170324-093529042[server.ChildProcess$LoggingStringHandler][server.ChildProcess$LoggingStringHandler.lambda$new$71] gapis: 	<autogenerated>:2420 +0xfb
W20170324-093529042[server.ChildProcess$LoggingStringHandler][server.ChildProcess$LoggingStringHandler.lambda$new$71] gapis: github.com/google/gapid/gapis/replay.(*batcher).send(0xc42214a930, 0x766d360, 0xc4220fed20, 0xc422548100, 0x1, 0x1, 0x0, 0x0)
W20170324-093529042[server.ChildProcess$LoggingStringHandler][server.ChildProcess$LoggingStringHandler.lambda$new$71] gapis: 	/myenv/go/src/github.com/google/gapid/gapis/replay/batcher.go:178 +0x934
W20170324-093529042[server.ChildProcess$LoggingStringHandler][server.ChildProcess$LoggingStringHandler.lambda$new$71] gapis: github.com/google/gapid/gapis/replay.(*batcher).run(0xc42214a930, 0x766d360, 0xc422160d80)
W20170324-093529042[server.ChildProcess$LoggingStringHandler][server.ChildProcess$LoggingStringHandler.lambda$new$71] gapis: 	/myenv/go/src/github.com/google/gapid/gapis/replay/batcher.go:95 +0x5f9
W20170324-093529043[server.ChildProcess$LoggingStringHandler][server.ChildProcess$LoggingStringHandler.lambda$new$71] gapis: created by github.com/google/gapid/gapis/replay.(*Manager).getBatchStream
W20170324-093529043[server.ChildProcess$LoggingStringHandler][server.ChildProcess$LoggingStringHandler.lambda$new$71] gapis: 	/myenv/go/src/github.com/google/gapid/gapis/replay/manager.go:55 +0x3f9
W20170324-093529043[server.ChildProcess-gapis][server.ChildProcess.onExit] The gapis process exited with a non-zero exit value: 2
I20170324-093529043[server.ChildProcess-gapis][server.ChildProcess.shutdown] Shutting down gapis
```

**Comment by ben-clayton** [comment]
David - Its possible this is a bug introduced with your state flattening.

I suspect the [`glBufferData`](https://github.com/google/gapid/blob/4b31e3254949782dbafaf565ba9a8541e592e4d2/gapis/gfxapi/gles/compat.go#L1061) call here is making the addresses in [this loop](https://github.com/google/gapid/blob/4b31e3254949782dbafaf565ba9a8541e592e4d2/gapis/gfxapi/gles/compat.go#L1065-L1076) not match those in [this loop](https://github.com/google/gapid/blob/4b31e3254949782dbafaf565ba9a8541e592e4d2/gapis/gfxapi/gles/compat.go#L1018-L1037), although its not immediately clear to me how.

@zhenian would you be happy to share the trace file with us? This would greatly help us in identifying the issue.

**Comment by dsrbecky** [comment]
I do not think it is related to the state flattening - if anything, the state changes should ensure the state is consistent.

I am betting the index count for atom 663 is zero, which makes the first loop a no-op.  I feel very uneasy about the inclusive "last" index.  I will try to fix that and see if that helps.

**Comment by ben-clayton** [comment]
Reopening - I'd like @zhenian to confirm this fixes the issue.

**Comment by ben-clayton** [comment]
No reply. Closing.
