### ISSUE TITLE
The gapis process exited with a non-zero exit value: -1

### ISSUE THREAD

**Issue by tangcenris** [google/gapid#1349]
I run with lastest gapid 0.9 release in windows 7, and with command "gapid --console", I got the below:

```
Starting D:\software\android develop\gapid-0.9.0-windows\gapid\jre\bin\java.exe D:\software\android develop\gapid-0.9.0-windows\gapid\lib\gapic.jar
I20171108-145850421[main][server.GapiPaths.checkForTools] Looking for GAPID in D:\software\android develop\gapid-0.9.0-windows\gapid -> D:\software\android develop\gapid-0.9.0-windows\gapid\gapis.exe
I20171108-145850460[server.ChildProcess-gapis][server.ChildProcess.runProcess] Starting gapis as [D:\software\android develop\gapid-0.9.0-windows\gapid\gapis.exe, -log-file, C:\Users\T00316~1\AppData\
Local\Temp\gapis.log, -log-level, Info, -gapir-args, --log C:\\Users\\T00316~1\\AppData\\Local\\Temp\\gapir.log --log-level I, --strings, D:\software\android develop\gapid-0.9.0-windows\gapid\strings,
 --gapis-auth-token, aUPZDvfk, --idle-timeout, 60000ms]
I20171108-145851879[server.ChildProcess$LoggingStringHandler][server.ChildProcess$LoggingStringHandler.lambda$new$0] gapis: 06:58:51.879 I: <gapis> Logging to: C:\Users\T00316~1\AppData\Local\Temp\gap
is.log
I20171108-145851906[server.ChildProcess$LoggingStringHandler][server.ChildProcess$LoggingStringHandler.lambda$new$0] gapis: Bound on port '11418'
I20171108-145851906[server.ChildProcess$LoggingStringHandler][server.GapisProcess.lambda$createStdoutHandler$2] Detected gapis startup on port 11418
I20171108-145851909[server.ChildProcess$LoggingStringHandler][server.GapisProcess.lambda$new$1] Established a new client connection to 11418
I20171108-145852016[server.ChildProcess$LoggingStringHandler][io.grpc.internal.ManagedChannelImpl.<init>] [ManagedChannelImpl@22af4b52] Created with target localhost:11418
I20171108-145852264[main][Server.fetchServerInfo] Server info: name: "PEKY2T003165281" version_minor: 9
I20171108-145853322[main][server.ChildProcess.shutdown] Shutting down gapis
I20171108-145853323[server.ChildProcess-gapis][server.ChildProcess.runProcess] Killing gapis
Exception in thread "main" org.eclipse.swt.SWTError: No more handles
        at org.eclipse.swt.SWT.error(Unknown Source)W20171108-145853324[server.ChildProcess-gapis][server.ChildProcess.onExit] The gapis process exited with a non-zero exit value: -1

        at org.eclipse.swt.SWT.error(Unknown Source)
        at org.eclipse.swt.SWT.error(Unknown Source)I20171108-145853325[server.ChildProcess-gapis][server.ChildProcess.shutdown] Shutting down gapis

        at com.google.gapid.glcanvas.GlCanvas$Context.createContext(GlCanvas.java:160)
        at com.google.gapid.glcanvas.GlCanvas.<init>(GlCanvas.java:59)
        at com.google.gapid.widgets.ScenePanel.<init>(ScenePanel.java:52)
        at com.google.gapid.widgets.ImagePanel$ImageComponent.<init>(ImagePanel.java:692)
        at com.google.gapid.widgets.ImagePanel.lambda$new$0(ImagePanel.java:132)
        at com.google.gapid.widgets.LoadablePanel.<init>(LoadablePanel.java:56)
        at com.google.gapid.widgets.LoadablePanel.create(LoadablePanel.java:61)
        at com.google.gapid.widgets.ImagePanel.<init>(ImagePanel.java:131)
        at com.google.gapid.views.FramebufferView.<init>(FramebufferView.java:102)
        at com.google.gapid.MainWindow$MainTab.lambda$getFolders$1(MainWindow.java:486)
        at com.google.gapid.widgets.TabArea$Folder.addTab(TabArea.java:502)
        at com.google.gapid.widgets.TabArea$Folder.<init>(TabArea.java:493)
        at com.google.gapid.widgets.TabArea.<init>(TabArea.java:76)
        at com.google.gapid.MainWindow$4.createBottomControl(MainWindow.java:241)
        at com.google.gapid.widgets.FixedTopSplitter.<init>(FixedTopSplitter.java:39)
        at com.google.gapid.MainWindow$4.<init>(MainWindow.java:233)
        at com.google.gapid.MainWindow.createContents(MainWindow.java:233)
        at org.eclipse.jface.window.Window.create(Window.java:426)
        at org.eclipse.jface.window.Window.open(Window.java:783)
        at com.google.gapid.Main$UI.show(Main.java:110)
        at com.google.gapid.Main.main(Main.java:68)
I20171108-145853330[OkHttpClientTransport][io.grpc.internal.ManagedChannelImpl.maybeTerminateChannel] [ManagedChannelImpl@22af4b52] Terminated
W20171108-145853331[grpc-okhttp-0][io.grpc.okhttp.AsyncFrameWriter$14.run] Failed closing connection
W20171108-145853331[grpc-okhttp-0][io.grpc.okhttp.AsyncFrameWriter$14.run] java.net.SocketException: Connection reset by peer: socket write error
W20171108-145853331[grpc-okhttp-0][io.grpc.okhttp.AsyncFrameWriter$14.run]      at java.net.SocketOutputStream.socketWrite0(Native Method)
W20171108-145853331[grpc-okhttp-0][io.grpc.okhttp.AsyncFrameWriter$14.run]      at java.net.SocketOutputStream.socketWrite(SocketOutputStream.java:111)
W20171108-145853331[grpc-okhttp-0][io.grpc.okhttp.AsyncFrameWriter$14.run]      at java.net.SocketOutputStream.write(SocketOutputStream.java:155)
W20171108-145853331[grpc-okhttp-0][io.grpc.okhttp.AsyncFrameWriter$14.run]      at okio.Okio$1.write(Okio.java:80)
W20171108-145853331[grpc-okhttp-0][io.grpc.okhttp.AsyncFrameWriter$14.run]      at okio.AsyncTimeout$1.write(AsyncTimeout.java:155)
W20171108-145853331[grpc-okhttp-0][io.grpc.okhttp.AsyncFrameWriter$14.run]      at okio.RealBufferedSink.close(RealBufferedSink.java:234)
W20171108-145853331[grpc-okhttp-0][io.grpc.okhttp.AsyncFrameWriter$14.run]      at io.grpc.okhttp.internal.framed.Http2$Writer.close(Http2.java:568)
W20171108-145853331[grpc-okhttp-0][io.grpc.okhttp.AsyncFrameWriter$14.run]      at io.grpc.okhttp.AsyncFrameWriter$14.run(AsyncFrameWriter.java:221)
W20171108-145853331[grpc-okhttp-0][io.grpc.okhttp.AsyncFrameWriter$14.run]      at io.grpc.internal.SerializingExecutor$TaskRunner.run(SerializingExecutor.java:154)
W20171108-145853331[grpc-okhttp-0][io.grpc.okhttp.AsyncFrameWriter$14.run]      at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
W20171108-145853331[grpc-okhttp-0][io.grpc.okhttp.AsyncFrameWriter$14.run]      at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
W20171108-145853331[grpc-okhttp-0][io.grpc.okhttp.AsyncFrameWriter$14.run]      at java.lang.Thread.run(Thread.java:748)

Press enter to continue
```
--------------------------------------------------

what's wrong?

**Comment by tangcenris** [comment]
I ran on a window 7 virtual machine, I am not sure if it is the reason it failed.   My target device is an android o version phone.

**Comment by tangcenris** [comment]
I confirmed there is no GPU support in my windows 7 virtual machine.

**Comment by ben-clayton** [comment]
Hi @tangcenris. Thank you for checking.

Unfortunately this is a requirement for using GAPID. I've created bugs to track better error reporting and documenting this requirement.

I hope you find a machine that has an OpenGL driver! Please note that GAPID also works for macOS and Linux, if this helps at all.

Cheers,
Ben
