### ISSUE TITLE
Unhandled exception in the UI thread on exit

### ISSUE THREAD

**Issue by tomgoogle** [google/gapid#1383]
GAPID Version: 0.9.1:497:11540482ad650abb0c1ab25f066bc5ee379ab257
OS: mac os x x86_64

java.lang.NullPointerException
	at org.eclipse.swt.widgets.Display.readAndDispatch(Unknown Source)
	at org.eclipse.jface.window.Window.runEventLoop(Window.java:818)
	at org.eclipse.jface.window.Window.open(Window.java:794)
	at com.google.gapid.Main$UI.show(Main.java:133)
	at com.google.gapid.Main.main(Main.java:71)

Please provide detailed steps that led to the error and copy-paste the stack trace:

Tracing UE4 Paris demo. Was browsing around the Geometry view before quitting GAPID and observed this panic.

Extra details from the logs and the trace file would be extra helpful.

**Comment by AWoloszyn** [comment]
There has been no movement on this in a long time. I am going to close this.
