### ISSUE TITLE
The gapis server has exited with an error code of: 2

### ISSUE THREAD

**Issue by maunvz** [google/gapid#1703]
GAPID Version: 1.0.3:1f697082aba0d859e4685158ff93711d35cdbe49
OS: windows 10 amd64

Please provide detailed steps that led to the error and copy-paste the stack trace.
Extra details from the logs and the trace file would be extra helpful.

I'm trying to debug my app using GAPID but when it finishes capturing the trace it throws this error and fails to open the captured trace. I've copy-pasted the log below. 

The device is a OnePlus 5T running android 8.0.0. From the logs, it appears that GAPID is having trouble with the GL_INT datatype?

-----------------------------------------
```
panic: Unknown data type GL_INT [recovered]
	panic: Panic at command 3893:glDrawArrays(draw_mode: GL_ZERO, first_index: 0, indices_count: 1000):
Unknown data type GL_INT [recovered]
	panic: Panic at command 3893:glDrawArrays(draw_mode: GL_ZERO, first_index: 0, indices_count: 1000):
Unknown data type GL_INT

goroutine 21 [running]:
github.com/google/gapid/core/app/crash.Crash(0x204cfc0, 0xc05611a580)
	T:/src/github/src/github.com/google/gapid/core/app/crash/crash.go:89 +0xbb
github.com/google/gapid/core/app/crash.handler()
	T:/src/github/src/github.com/google/gapid/core/app/crash/crash.go:56 +0x59
panic(0x204cfc0, 0xc05611a580)
	T:/src/go/src/runtime/panic.go:489 +0x2dd
github.com/google/gapid/gapis/api.ForeachCmd.func1(0xc059d2d968, 0xc059d2d990)
	T:/src/github/src/github.com/google/gapid/gapis/api/cmd_foreach.go:39 +0x173
panic(0x204cfc0, 0xc05611a550)
	T:/src/go/src/runtime/panic.go:489 +0x2dd
github.com/google/gapid/gapis/api/gles.DataTypeSize(0x1404, 0xc058929c80)
	T:/src/github/src/github.com/google/gapid/gapis/api/gles/vertex_attribute_array.go:36 +0x11c
github.com/google/gapid/gapis/api/gles.moveClientVBsToVAs(0x3f34d40, 0xc05894c720, 0xc05610e910, 0xc058929c80, 0x3e800000000, 0xf35, 0x3f4c180, 0xc042c78400, 0xc0426dbec0, 0xc058dc7000, ...)
	T:/src/github/src/github.com/google/gapid/gapis/api/gles/compat_client.go:187 +0x8df
github.com/google/gapid/gapis/api/gles.compat.func4(0x3f34d40, 0xc05894c720, 0xf35, 0x3f4c180, 0xc042c78400, 0x3efe280, 0xc058929dd0)
	T:/src/github/src/github.com/google/gapid/gapis/api/gles/compat.go:512 +0xb5cc
github.com/google/gapid/gapis/api/transform.transform.Transform(0x265caea, 0x6, 0xc0558bedc0, 0x3f34d40, 0xc05894c720, 0xf35, 0x3f4c180, 0xc042c78400, 0x3efe280, 0xc058929dd0)
	T:/src/github/src/github.com/google/gapid/gapis/api/transform/transforms.go:75 +0x7c
github.com/google/gapid/gapis/api/transform.(*transform).Transform(0xc057ef21e0, 0x3f34d40, 0xc05894c720, 0xf35, 0x3f4c180, 0xc042c78400, 0x3efe280, 0xc058929dd0)
	<autogenerated>:15 +0xb8
github.com/google/gapid/gapis/api/transform.TransformWriter.MutateAndWrite(0xc0426dbec0, 0x3efe2c0, 0xc057ef21e0, 0x3efe280, 0xc058929dd0, 0x3f34d40, 0xc05894c720, 0xf35, 0x3f4c180, 0xc042c78400)
	T:/src/github/src/github.com/google/gapid/gapis/api/transform/transforms.go:98 +0x8a
github.com/google/gapid/gapis/api/transform.(*TransformWriter).MutateAndWrite(0xc058929e00, 0x3f34d40, 0xc05894c720, 0xf35, 0x3f4c180, 0xc042c78400)
	<autogenerated>:13 +0xa8
github.com/google/gapid/gapis/api/transform.(*Tasks).Transform(0xc057ef2060, 0x3f34d40, 0xc05894c720, 0xf35, 0x3f4c180, 0xc042c78400, 0x3efe280, 0xc058929e00)
	T:/src/github/src/github.com/google/gapid/gapis/api/transform/tasks.go:46 +0x167
github.com/google/gapid/gapis/api/transform.TransformWriter.MutateAndWrite(0xc0426dbec0, 0x3efbd80, 0xc057ef2060, 0x3efe280, 0xc058929e00, 0x3f34d40, 0xc05894c720, 0xf35, 0x3f4c180, 0xc042c78400)
	T:/src/github/src/github.com/google/gapid/gapis/api/transform/transforms.go:98 +0x8a
github.com/google/gapid/gapis/api/transform.(*TransformWriter).MutateAndWrite(0xc058929e30, 0x3f34d40, 0xc05894c720, 0xf35, 0x3f4c180, 0xc042c78400)
	<autogenerated>:13 +0xa8
github.com/google/gapid/gapis/api/gles.undefinedFramebuffer.func1(0x3f34d40, 0xc05894c720, 0xf35, 0x3f4c180, 0xc042c78400, 0x3efe280, 0xc058929e30)
	T:/src/github/src/github.com/google/gapid/gapis/api/gles/undefined_framebuffer.go:31 +0xa3
github.com/google/gapid/gapis/api/transform.transform.Transform(0x266c557, 0x10, 0xc057ef20e0, 0x3f34d40, 0xc05894c720, 0xf35, 0x3f4c180, 0xc042c78400, 0x3efe280, 0xc058929e30)
	T:/src/github/src/github.com/google/gapid/gapis/api/transform/transforms.go:75 +0x7c
github.com/google/gapid/gapis/api/transform.(*transform).Transform(0xc057ef2100, 0x3f34d40, 0xc05894c720, 0xf35, 0x3f4c180, 0xc042c78400, 0x3efe280, 0xc058929e30)
	<autogenerated>:15 +0xb8
github.com/google/gapid/gapis/api/transform.TransformWriter.MutateAndWrite(0xc0426dbec0, 0x3efe2c0, 0xc057ef2100, 0x3efe280, 0xc058929e30, 0x3f34d40, 0xc05894c720, 0xf35, 0x3f4c180, 0xc042c78400)
	T:/src/github/src/github.com/google/gapid/gapis/api/transform/transforms.go:98 +0x8a
github.com/google/gapid/gapis/api/transform.(*TransformWriter).MutateAndWrite(0xc058929e60, 0x3f34d40, 0xc05894c720, 0xf35, 0x3f4c180, 0xc042c78400)
	<autogenerated>:13 +0xa8
github.com/google/gapid/gapis/api/transform.(*DeadCodeElimination).Flush.func2(0x3f34d40, 0xc05894c720, 0xf35, 0x3f4c180, 0xc042c78400, 0x0, 0x0)
	T:/src/github/src/github.com/google/gapid/gapis/api/transform/dead_code_elimination.go:95 +0xb7
github.com/google/gapid/gapis/api.ForeachCmd(0x3f34d40, 0xc057e3b2c0, 0xc054a7a000, 0x38ef, 0x7800, 0xc059d2da40, 0x0, 0x0)
	T:/src/github/src/github.com/google/gapid/gapis/api/cmd_foreach.go:46 +0x14c
github.com/google/gapid/gapis/api/transform.(*DeadCodeElimination).Flush(0xc057ef2040, 0x3f34d40, 0xc057e3b2c0, 0x3efe280, 0xc058929e60)
	T:/src/github/src/github.com/google/gapid/gapis/api/transform/dead_code_elimination.go:100 +0x1cd
github.com/google/gapid/gapis/api/transform.Transforms.Transform(0xc0577c9e00, 0x5, 0x8, 0x3f34d40, 0xc057e3b2c0, 0xc059d2dc48, 0x0, 0x0, 0x3efc140, 0xc056af3870)
	T:/src/github/src/github.com/google/gapid/gapis/api/transform/transforms.go:44 +0x333
github.com/google/gapid/gapis/api/gles.API.Replay(0x3f34d40, 0xc057e3b0b0, 0xc058b2a388, 0xc058b2a380, 0x23897e0, 0xc058c64500, 0xc042090b40, 0x18, 0x18, 0x40d7ea0, ...)
	T:/src/github/src/github.com/google/gapid/gapis/api/gles/replay.go:223 +0xef3
github.com/google/gapid/gapis/api/gles.(*API).Replay(0x40f5328, 0x3f34d40, 0xc057e3b0b0, 0xc058b2a388, 0xc058b2a380, 0x23897e0, 0xc058c64500, 0xc042090b40, 0x18, 0x18, ...)
	<autogenerated>:4419 +0x102
github.com/google/gapid/gapis/replay.(*Manager).execute.func1()
	T:/src/github/src/github.com/google/gapid/gapis/replay/batch.go:153 +0x193
github.com/google/gapid/core/app/benchmark.(*DurationCounter).Time(0xc042196660, 0xc04202c258)
	T:/src/github/src/github.com/google/gapid/core/app/benchmark/counter.go:163 +0x82
github.com/google/gapid/gapis/replay.(*Manager).execute(0xc042364f40, 0x3f34d40, 0xc057e3b0b0, 0x3f00940, 0xc042338950, 0x6e5eeac3ac0cdbb1, 0x622e6b4d5720f9c5, 0x92691442d54b4491, 0x63064093985d8ce, 0x30c34c35289258d9, ...)
	T:/src/github/src/github.com/google/gapid/gapis/replay/batch.go:154 +0x9eb
github.com/google/gapid/gapis/replay.(*Manager).batch.func1(0x3f00940, 0xc042338950, 0xc04202c5f8, 0x3985d8ce92691442, 0x289258d906306409, 0xac0cdbb130c34c35, 0x5720f9c56e5eeac3, 0xd54b4491622e6b4d, 0x23897e0, 0xc058c64500, ...)
	T:/src/github/src/github.com/google/gapid/gapis/replay/batch.go:82 +0x4ba
github.com/google/gapid/gapis/replay.(*Manager).batch(0xc042364f40, 0x3f34d40, 0xc057e3aea0, 0xc042402700, 0x18, 0x19, 0x22a47c0, 0xc0581e2e20, 0x23a0460, 0xc054dfb9a0, ...)
	T:/src/github/src/github.com/google/gapid/gapis/replay/batch.go:83 +0x343
github.com/google/gapid/gapis/replay.(*Manager).(github.com/google/gapid/gapis/replay.batch)-fm(0x3f34d40, 0xc042335260, 0xc042402700, 0x18, 0x19, 0x22a47c0, 0xc0581e2e20, 0x23a0460, 0xc054dfb9a0, 0x1)
	T:/src/github/src/github.com/google/gapid/gapis/replay/manager.go:126 +0x9a
github.com/google/gapid/gapis/replay/scheduler.(*bin).exec(0xc05829c900, 0x3f34d40, 0xc042335260, 0xc042338ab0)
	T:/src/github/src/github.com/google/gapid/gapis/replay/scheduler/scheduler.go:243 +0x2df
github.com/google/gapid/gapis/replay/scheduler.(*Scheduler).run(0xc042365120, 0x3f34d40, 0xc042335260)
	T:/src/github/src/github.com/google/gapid/gapis/replay/scheduler/scheduler.go:176 +0x470
github.com/google/gapid/gapis/replay/scheduler.New.func1()
	T:/src/github/src/github.com/google/gapid/gapis/replay/scheduler/scheduler.go:73 +0x43
github.com/google/gapid/core/app/crash.Go.func1(0xc042365140)
	T:/src/github/src/github.com/google/gapid/core/app/crash/crash.go:65 +0x4a
created by github.com/google/gapid/core/app/crash.Go
	T:/src/github/src/github.com/google/gapid/core/app/crash/crash.go:66 +0x46
```

**Comment by ben-clayton** [comment]
Fixed by 4830f686e82196e037477e1d943da029f405655b
