### ISSUE TITLE
Gapid crashes on SaschaWillems texturesparseresidency sample

### ISSUE THREAD

**Issue by iburinoc** [google/gapid#1961]
GAPID records a trace of [texturesparseresidency](https://github.com/SaschaWillems/Vulkan/blob/master/examples/texturesparseresidency/texturesparseresidency.cpp) fine but then crashes when trying to inspect it:
```
21:53:24.261 E: <gapis> panic: aborted(vkErrorInvalidHandle) [recovered]
21:53:24.261 E: <gapis> 	panic: Panic at command 463:vkQueueBindSparse(queue: 94095970133344, bindInfoCount: 1, pBindInfo: 0x000055946cc61940, fence: 0) → VK_SUCCESS:
21:53:24.261 E: <gapis> aborted(vkErrorInvalidHandle) [recovered]
21:53:24.261 E: <gapis> 	panic: 
21:53:24.261 E: <gapis> --- *resolve.SynchronizationResolvable ---
21:53:24.261 E: <gapis>  capture:<id:<data:"/J\036\301\203\357\025\363\266}O\201oZ\327\035\352m\363B" > > 
21:53:24.261 E: <gapis>  Store():
21:53:24.261 E: <gapis>   gapis/database/database.go:50  github.com/google/gapid/gapis/database.Build
21:53:24.261 E: <gapis>   gapis/resolve/synchronization_data.go:30  github.com/google/gapid/gapis/resolve.SyncData
21:53:24.261 E: <gapis>   gapis/resolve/command_tree.go:190  github.com/google/gapid/gapis/resolve.(*CommandTreeResolvable).Resolve
21:53:24.261 E: <gapis>   gapis/database/memory.go:127  github.com/google/gapid/gapis/database.(*record).resolve
21:53:24.261 E: <gapis>   gapis/database/memory.go:214  github.com/google/gapid/gapis/database.(*memory).resolveLocked.func1
21:53:24.261 E: <gapis>   core/app/crash/crash.go:65  github.com/google/gapid/core/app/crash.Go.func1
21:53:24.261 E: <gapis> 
21:53:24.261 E: <gapis>  Build() #0:
21:53:24.261 E: <gapis>   gapis/database/database.go:54  github.com/google/gapid/gapis/database.Build
21:53:24.261 E: <gapis>   gapis/resolve/synchronization_data.go:30  github.com/google/gapid/gapis/resolve.SyncData
21:53:24.261 E: <gapis>   gapis/resolve/command_tree.go:190  github.com/google/gapid/gapis/resolve.(*CommandTreeResolvable).Resolve
21:53:24.261 E: <gapis>   gapis/database/memory.go:127  github.com/google/gapid/gapis/database.(*record).resolve
21:53:24.261 E: <gapis>   gapis/database/memory.go:214  github.com/google/gapid/gapis/database.(*memory).resolveLocked.func1
21:53:24.261 E: <gapis>   core/app/crash/crash.go:65  github.com/google/gapid/core/app/crash.Go.func1
21:53:24.261 E: <gapis> 
21:53:24.261 E: <gapis> --- *resolve.CommandTreeResolvable ---
21:53:24.261 E: <gapis>  path:<capture:<id:<data:"/J\036\301\203\357\025\363\266}O\201oZ\327\035\352m\363B" > > filter:<> > 
21:53:24.261 E: <gapis>  Store():
21:53:24.261 E: <gapis>   gapis/resolve/command_tree.go:43  github.com/google/gapid/gapis/resolve.CommandTree
21:53:24.261 E: <gapis>   gapis/resolve/resolve.go:270  github.com/google/gapid/gapis/resolve.ResolveInternal
21:53:24.261 E: <gapis>   gapis/resolve/resolve.go:245  github.com/google/gapid/gapis/resolve.ResolveService
21:53:24.261 E: <gapis>   gapis/resolve/get.go:35  github.com/google/gapid/gapis/resolve.(*GetResolvable).Resolve
21:53:24.261 E: <gapis>   gapis/database/memory.go:127  github.com/google/gapid/gapis/database.(*record).resolve
21:53:24.261 E: <gapis>   gapis/database/memory.go:214  github.com/google/gapid/gapis/database.(*memory).resolveLocked.func1
21:53:24.261 E: <gapis>   core/app/crash/crash.go:65  github.com/google/gapid/core/app/crash.Go.func1
21:53:24.261 E: <gapis> 
21:53:24.261 E: <gapis>  Build() #0:
21:53:24.261 E: <gapis>   gapis/database/database.go:44  github.com/google/gapid/gapis/database.Resolve
21:53:24.261 E: <gapis>   gapis/resolve/command_tree.go:95  github.com/google/gapid/gapis/resolve.CommandTreeNode
21:53:24.261 E: <gapis>   gapis/resolve/resolve.go:272  github.com/google/gapid/gapis/resolve.ResolveInternal
21:53:24.261 E: <gapis>   gapis/resolve/resolve.go:245  github.com/google/gapid/gapis/resolve.ResolveService
21:53:24.261 E: <gapis>   gapis/resolve/get.go:35  github.com/google/gapid/gapis/resolve.(*GetResolvable).Resolve
21:53:24.261 E: <gapis>   gapis/database/memory.go:127  github.com/google/gapid/gapis/database.(*record).resolve
21:53:24.261 E: <gapis>   gapis/database/memory.go:214  github.com/google/gapid/gapis/database.(*memory).resolveLocked.func1
21:53:24.261 E: <gapis>   core/app/crash/crash.go:65  github.com/google/gapid/core/app/crash.Go.func1
21:53:24.261 E: <gapis> 
21:53:24.261 E: <gapis> --- *resolve.GetResolvable ---
21:53:24.261 E: <gapis>  path:<command_tree_node:<tree:<data:"&\232!d\330\251_\241\230\034x\264\"1}?\225\342x\031" > > > 
21:53:24.261 E: <gapis>  Store():
21:53:24.261 E: <gapis>   gapis/database/database.go:50  github.com/google/gapid/gapis/database.Build
21:53:24.261 E: <gapis>   gapis/resolve/get.go:27  github.com/google/gapid/gapis/resolve.Get
21:53:24.261 E: <gapis>   gapis/server/server.go:273  github.com/google/gapid/gapis/server.(*server).Get
21:53:24.261 E: <gapis>   gapis/server/grpc.go:167  github.com/google/gapid/gapis/server.(*grpcServer).Get
21:53:24.261 E: <gapis>   bazel-out/k8-fastbuild/bin/gapis/service/linux_amd64_stripped/service_go_proto~/github.com/google/gapid/gapis/service/service.pb.go:6017  github.com/google/gapid/gapis/service._Gapid_Get_Handler.func1
21:53:24.261 E: <gapis>   core/app/auth/auth.go:110  github.com/google/gapid/core/app/auth.ServerInterceptor.func1
21:53:24.261 E: <gapis>   bazel-out/k8-fastbuild/bin/gapis/service/linux_amd64_stripped/service_go_proto~/github.com/google/gapid/gapis/service/service.pb.go:6019  github.com/google/gapid/gapis/service._Gapid_Get_Handler
21:53:24.261 E: <gapis>   external/org_golang_google_grpc/server.go:719  google.golang.org/grpc.(*Server).processUnaryRPC
21:53:24.261 E: <gapis>   external/org_golang_google_grpc/server.go:905  google.golang.org/grpc.(*Server).handleStream
21:53:24.261 E: <gapis> 
21:53:24.261 E: <gapis>  Build() #0:
21:53:24.261 E: <gapis>   gapis/database/database.go:54  github.com/google/gapid/gapis/database.Build
21:53:24.261 E: <gapis>   gapis/resolve/get.go:27  github.com/google/gapid/gapis/resolve.Get
21:53:24.261 E: <gapis>   gapis/server/server.go:273  github.com/google/gapid/gapis/server.(*server).Get
21:53:24.261 E: <gapis>   gapis/server/grpc.go:167  github.com/google/gapid/gapis/server.(*grpcServer).Get
21:53:24.261 E: <gapis>   bazel-out/k8-fastbuild/bin/gapis/service/linux_amd64_stripped/service_go_proto~/github.com/google/gapid/gapis/service/service.pb.go:6017  github.com/google/gapid/gapis/service._Gapid_Get_Handler.func1
21:53:24.261 E: <gapis>   core/app/auth/auth.go:110  github.com/google/gapid/core/app/auth.ServerInterceptor.func1
21:53:24.261 E: <gapis>   bazel-out/k8-fastbuild/bin/gapis/service/linux_amd64_stripped/service_go_proto~/github.com/google/gapid/gapis/service/service.pb.go:6019  github.com/google/gapid/gapis/service._Gapid_Get_Handler
21:53:24.261 E: <gapis>   external/org_golang_google_grpc/server.go:719  google.golang.org/grpc.(*Server).processUnaryRPC
21:53:24.261 E: <gapis>   external/org_golang_google_grpc/server.go:905  google.golang.org/grpc.(*Server).handleStream
21:53:24.261 E: <gapis>  [recovered]
21:53:24.261 E: <gapis> 	panic: 
21:53:24.261 E: <gapis> --- *resolve.SynchronizationResolvable ---
21:53:24.261 E: <gapis>  capture:<id:<data:"/J\036\301\203\357\025\363\266}O\201oZ\327\035\352m\363B" > > 
21:53:24.261 E: <gapis>  Store():
21:53:24.261 E: <gapis>   gapis/database/database.go:50  github.com/google/gapid/gapis/database.Build
21:53:24.261 E: <gapis>   gapis/resolve/synchronization_data.go:30  github.com/google/gapid/gapis/resolve.SyncData
21:53:24.261 E: <gapis>   gapis/resolve/command_tree.go:190  github.com/google/gapid/gapis/resolve.(*CommandTreeResolvable).Resolve
21:53:24.261 E: <gapis>   gapis/database/memory.go:127  github.com/google/gapid/gapis/database.(*record).resolve
21:53:24.261 E: <gapis>   gapis/database/memory.go:214  github.com/google/gapid/gapis/database.(*memory).resolveLocked.func1
21:53:24.261 E: <gapis>   core/app/crash/crash.go:65  github.com/google/gapid/core/app/crash.Go.func1
21:53:24.261 E: <gapis> 
21:53:24.261 E: <gapis>  Build() #0:
21:53:24.261 E: <gapis>   gapis/database/database.go:54  github.com/google/gapid/gapis/database.Build
21:53:24.261 E: <gapis>   gapis/resolve/synchronization_data.go:30  github.com/google/gapid/gapis/resolve.SyncData
21:53:24.261 E: <gapis>   gapis/resolve/command_tree.go:190  github.com/google/gapid/gapis/resolve.(*CommandTreeResolvable).Resolve
21:53:24.261 E: <gapis>   gapis/database/memory.go:127  github.com/google/gapid/gapis/database.(*record).resolve
21:53:24.261 E: <gapis>   gapis/database/memory.go:214  github.com/google/gapid/gapis/database.(*memory).resolveLocked.func1
21:53:24.261 E: <gapis>   core/app/crash/crash.go:65  github.com/google/gapid/core/app/crash.Go.func1
21:53:24.261 E: <gapis> 
21:53:24.261 E: <gapis> --- *resolve.CommandTreeResolvable ---
21:53:24.261 E: <gapis>  path:<capture:<id:<data:"/J\036\301\203\357\025\363\266}O\201oZ\327\035\352m\363B" > > filter:<> > 
21:53:24.261 E: <gapis>  Store():
21:53:24.261 E: <gapis>   gapis/resolve/command_tree.go:43  github.com/google/gapid/gapis/resolve.CommandTree
21:53:24.261 E: <gapis>   gapis/resolve/resolve.go:270  github.com/google/gapid/gapis/resolve.ResolveInternal
21:53:24.261 E: <gapis>   gapis/resolve/resolve.go:245  github.com/google/gapid/gapis/resolve.ResolveService
21:53:24.261 E: <gapis>   gapis/resolve/get.go:35  github.com/google/gapid/gapis/resolve.(*GetResolvable).Resolve
21:53:24.261 E: <gapis>   gapis/database/memory.go:127  github.com/google/gapid/gapis/database.(*record).resolve
21:53:24.261 E: <gapis>   gapis/database/memory.go:214  github.com/google/gapid/gapis/database.(*memory).resolveLocked.func1
21:53:24.261 E: <gapis>   core/app/crash/crash.go:65  github.com/google/gapid/core/app/crash.Go.func1
21:53:24.261 E: <gapis> 
21:53:24.261 E: <gapis>  Build() #0:
21:53:24.261 E: <gapis>   gapis/database/database.go:44  github.com/google/gapid/gapis/database.Resolve
21:53:24.261 E: <gapis>   gapis/resolve/command_tree.go:95  github.com/google/gapid/gapis/resolve.CommandTreeNode
21:53:24.261 E: <gapis>   gapis/resolve/resolve.go:272  github.com/google/gapid/gapis/resolve.ResolveInternal
21:53:24.261 E: <gapis>   gapis/resolve/resolve.go:245  github.com/google/gapid/gapis/resolve.ResolveService
21:53:24.262 E: <gapis>   gapis/resolve/get.go:35  github.com/google/gapid/gapis/resolve.(*GetResolvable).Resolve
21:53:24.262 E: <gapis>   gapis/database/memory.go:127  github.com/google/gapid/gapis/database.(*record).resolve
21:53:24.262 E: <gapis>   gapis/database/memory.go:214  github.com/google/gapid/gapis/database.(*memory).resolveLocked.func1
21:53:24.262 E: <gapis>   core/app/crash/crash.go:65  github.com/google/gapid/core/app/crash.Go.func1
21:53:24.262 E: <gapis> 
21:53:24.262 E: <gapis> --- *resolve.GetResolvable ---
21:53:24.262 E: <gapis>  path:<command_tree_node:<tree:<data:"&\232!d\330\251_\241\230\034x\264\"1}?\225\342x\031" > > > 
21:53:24.262 E: <gapis>  Store():
21:53:24.262 E: <gapis>   gapis/database/database.go:50  github.com/google/gapid/gapis/database.Build
21:53:24.262 E: <gapis>   gapis/resolve/get.go:27  github.com/google/gapid/gapis/resolve.Get
21:53:24.262 E: <gapis>   gapis/server/server.go:273  github.com/google/gapid/gapis/server.(*server).Get
21:53:24.262 E: <gapis>   gapis/server/grpc.go:167  github.com/google/gapid/gapis/server.(*grpcServer).Get
21:53:24.262 E: <gapis>   bazel-out/k8-fastbuild/bin/gapis/service/linux_amd64_stripped/service_go_proto~/github.com/google/gapid/gapis/service/service.pb.go:6017  github.com/google/gapid/gapis/service._Gapid_Get_Handler.func1
21:53:24.262 E: <gapis>   core/app/auth/auth.go:110  github.com/google/gapid/core/app/auth.ServerInterceptor.func1
21:53:24.262 E: <gapis>   bazel-out/k8-fastbuild/bin/gapis/service/linux_amd64_stripped/service_go_proto~/github.com/google/gapid/gapis/service/service.pb.go:6019  github.com/google/gapid/gapis/service._Gapid_Get_Handler
21:53:24.262 E: <gapis>   external/org_golang_google_grpc/server.go:719  google.golang.org/grpc.(*Server).processUnaryRPC
21:53:24.262 E: <gapis>   external/org_golang_google_grpc/server.go:905  google.golang.org/grpc.(*Server).handleStream
21:53:24.262 E: <gapis> 
21:53:24.262 E: <gapis>  Build() #0:
21:53:24.262 E: <gapis>   gapis/database/database.go:54  github.com/google/gapid/gapis/database.Build
21:53:24.262 E: <gapis>   gapis/resolve/get.go:27  github.com/google/gapid/gapis/resolve.Get
21:53:24.262 E: <gapis>   gapis/server/server.go:273  github.com/google/gapid/gapis/server.(*server).Get
21:53:24.262 E: <gapis>   gapis/server/grpc.go:167  github.com/google/gapid/gapis/server.(*grpcServer).Get
21:53:24.262 E: <gapis>   bazel-out/k8-fastbuild/bin/gapis/service/linux_amd64_stripped/service_go_proto~/github.com/google/gapid/gapis/service/service.pb.go:6017  github.com/google/gapid/gapis/service._Gapid_Get_Handler.func1
21:53:24.262 E: <gapis>   core/app/auth/auth.go:110  github.com/google/gapid/core/app/auth.ServerInterceptor.func1
21:53:24.262 E: <gapis>   bazel-out/k8-fastbuild/bin/gapis/service/linux_amd64_stripped/service_go_proto~/github.com/google/gapid/gapis/service/service.pb.go:6019  github.com/google/gapid/gapis/service._Gapid_Get_Handler
21:53:24.262 E: <gapis>   external/org_golang_google_grpc/server.go:719  google.golang.org/grpc.(*Server).processUnaryRPC
21:53:24.262 E: <gapis>   external/org_golang_google_grpc/server.go:905  google.golang.org/grpc.(*Server).handleStream
21:53:24.262 E: <gapis> 
21:53:24.262 E: <gapis> 
21:53:24.262 E: <gapis> goroutine 14 [running]:
21:53:24.263 E: <gapis> github.com/google/gapid/core/app/crash.Crash(0x329a4e0, 0xc422bef990)
21:53:24.263 E: <gapis> 	core/app/crash/crash.go:89 +0xa7
21:53:24.263 E: <gapis> github.com/google/gapid/core/app/crash.handler()
21:53:24.263 E: <gapis> 	core/app/crash/crash.go:56 +0x52
21:53:24.263 E: <gapis> panic(0x329a4e0, 0xc422bef990)
21:53:24.263 E: <gapis> 	GOROOT/src/runtime/panic.go:505 +0x229
21:53:24.263 E: <gapis> github.com/google/gapid/gapis/database.(*memory).resolvePanicHandler(0xc42020a120, 0x3e0aee0, 0xc4223b8e40)
21:53:24.263 E: <gapis> 	gapis/database/debug.go:106 +0x7c8
21:53:24.263 E: <gapis> panic(0x32c3e80, 0xc422beed10)
21:53:24.263 E: <gapis> 	GOROOT/src/runtime/panic.go:505 +0x229
21:53:24.263 E: <gapis> github.com/google/gapid/gapis/api.ForeachCmd.func1(0xc422f13c30, 0xc422f13c58)
21:53:24.263 E: <gapis> 	gapis/api/cmd_foreach.go:39 +0x162
21:53:24.263 E: <gapis> panic(0x3605bc0, 0xc422f3f5a0)
21:53:24.263 E: <gapis> 	GOROOT/src/runtime/panic.go:505 +0x229
21:53:24.263 E: <gapis> github.com/google/gapid/gapis/api/vulkan.API.ResolveSynchronization.func6(0x3e0aee0, 0xc4223b9d70, 0x1cf, 0x3e48ce0, 0xc4200637a0, 0x0, 0x0)
21:53:24.263 E: <gapis> 	gapis/api/vulkan/vulkan.go:356 +0xa1
21:53:24.263 E: <gapis> github.com/google/gapid/gapis/api.ForeachCmd(0x3e0aee0, 0xc4223b8ff0, 0xc422ce8000, 0x9435, 0x9600, 0xc422f13dd0, 0x0, 0x0)
21:53:24.263 E: <gapis> 	gapis/api/cmd_foreach.go:46 +0x148
21:53:24.263 E: <gapis> github.com/google/gapid/gapis/api/vulkan.API.ResolveSynchronization(0x3e0aee0, 0xc4223b8ff0, 0xc4223b8ea0, 0xc420f02028, 0x37c9d01, 0x7f166c12c9b0)
21:53:24.263 E: <gapis> 	gapis/api/vulkan/vulkan.go:353 +0x577
21:53:24.263 E: <gapis> github.com/google/gapid/gapis/resolve.(*SynchronizationResolvable).Resolve(0xc4204c0708, 0x3e0aee0, 0xc4223b8e40, 0x3dc3820, 0xc4204c0708, 0x1, 0x3dc5ee0)
21:53:24.263 E: <gapis> 	gapis/resolve/synchronization_data.go:55 +0x227
21:53:24.263 E: <gapis> github.com/google/gapid/gapis/database.(*record).resolve(0xc42225c060, 0x3e0aee0, 0xc4223b8e40, 0x3e0aee0, 0xc4223b8e40)
21:53:24.263 E: <gapis> 	gapis/database/memory.go:127 +0xe5
21:53:24.263 E: <gapis> github.com/google/gapid/gapis/database.(*memory).resolveLocked.func1()
21:53:24.263 E: <gapis> 	gapis/database/memory.go:214 +0x9f
21:53:24.263 E: <gapis> github.com/google/gapid/core/app/crash.Go.func1(0xc4223b8e70)
21:53:24.263 E: <gapis> 	core/app/crash/crash.go:65 +0x43
21:53:24.263 E: <gapis> created by github.com/google/gapid/core/app/crash.Go
21:53:24.263 E: <gapis> 	core/app/crash/crash.go:63 +0x3f
2018/06/06 17:53:24 transport: http2Client.notifyError got notified that the client transport was broken EOF.
21:53:24.271 E: <gapit> rpc error: code = 13 desc = transport is closing
21:53:24.271 E: <gapit> Main failed
Error: Failed to load the node at: command-tree<269a2164d8a95fa1981c78b422317d3f95e27819>[]
   Cause: rpc error: code = 13 desc = transport is closing
```

**Comment by AWoloszyn** [comment]
Is this fixed now with https://github.com/google/gapid/pull/1966

**Comment by iburinoc** [comment]
Yes it seems to be running correctly now.
