### ISSUE TITLE
Editing Shader Source in GLES MEC Trace Fails

### ISSUE THREAD

**Issue by pmuetschard** [google/gapid#2066]
Editing shader source in a GLES mid execution capture trace fails:

```
error in com.google.gapid.views.ShaderView$1.onRpcThread
com.google.gapid.server.Client$InternalServerErrorException: Couldn't find resource
	at com.google.gapid.server.Client.throwIfError(Client.java:259)
	at com.google.gapid.server.Client.lambda$set$10(Client.java:107)
	at com.google.common.util.concurrent.AbstractTransformFuture$AsyncTransformFuture.doTransform(AbstractTransformFuture.java:211)
	at com.google.common.util.concurrent.AbstractTransformFuture$AsyncTransformFuture.doTransform(AbstractTransformFuture.java:200)
	at com.google.common.util.concurrent.AbstractTransformFuture.run(AbstractTransformFuture.java:130)
	at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:435)
	at com.google.common.util.concurrent.AbstractFuture.executeListener(AbstractFuture.java:900)
	at com.google.common.util.concurrent.AbstractFuture.complete(AbstractFuture.java:811)
	at com.google.common.util.concurrent.AbstractFuture.set(AbstractFuture.java:653)
	at io.grpc.stub.ClientCalls$GrpcFuture.set(ClientCalls.java:461)
	at io.grpc.stub.ClientCalls$UnaryStreamToFuture.onClose(ClientCalls.java:440)
	at io.grpc.internal.ClientCallImpl$ClientStreamListenerImpl.close(ClientCallImpl.java:481)
	at io.grpc.internal.ClientCallImpl$ClientStreamListenerImpl.access$600(ClientCallImpl.java:398)
	at io.grpc.internal.ClientCallImpl$ClientStreamListenerImpl$1StreamClosed.runInContext(ClientCallImpl.java:513)
	at io.grpc.internal.ContextRunnable.run(ContextRunnable.java:52)
	at io.grpc.internal.SerializingExecutor$TaskRunner.run(SerializingExecutor.java:154)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: com.google.gapid.server.Client$Stack: For request: RPC->set(resource_data { ID { data: 49e433ca1469dcf8b92b2849cbffb55380ec16da } after { capture { ID { data: 7b55a40991d1460d295abebae9586bab48fdf984 } } indices: 1105 } }, resource_data { shader { type: Fragment source: "#version 100\n\n\nprecision highp float;\nuniform sampler2D _MainTex;\nuniform lowp samplerCube _EnvTex;\nuniform highp float _Multiplier;\nvarying highp vec2 xlv_TEXCOORD0;\nvarying highp vec3 xlv_TEXCOORD1;\nvoid main ()\n{\n  lowp vec4 finalColor_1;\n  lowp vec4 tmpvar_2;\n  tmpvar_2 = texture2D (_MainTex, xlv_TEXCOORD0);\n  finalColor_1.w = tmpvar_2.w;\n  lowp vec4 tmpvar_3;\n  tmpvar_3 = textureCube (_EnvTex, xlv_TEXCOORD1);\n  highp vec3 tmpvar_4;\n  tmpvar_4 = (tmpvar_3 * (tmpvar_2.w * _Multiplier)).xyz;\n  finalColor_1.xyz = (tmpvar_2.xyz + tmpvar_4);\n  gl_FragData[0] = finalColor_1.brg;\n}" } })
	at com.google.gapid.server.Client.call(Client.java:243)
	at com.google.gapid.server.Client.set(Client.java:100)
	at com.google.gapid.views.ShaderView.lambda$createShaderTab$2(ShaderView.java:141)
	at com.google.gapid.views.ShaderView$Type.updateShader(ShaderView.java:651)
	at com.google.gapid.views.ShaderView$ShaderPanel.lambda$new$0(ShaderView.java:337)
	at org.eclipse.swt.widgets.EventTable.sendEvent(Unknown Source)
	at org.eclipse.swt.widgets.Display.sendEvent(Unknown Source)
	at org.eclipse.swt.widgets.Widget.sendEvent(Unknown Source)
	at org.eclipse.swt.widgets.Widget.sendEvent(Unknown Source)
	at org.eclipse.swt.widgets.Widget.sendEvent(Unknown Source)
	at org.eclipse.swt.widgets.Widget.notifyListeners(Unknown Source)
	at org.eclipse.swt.widgets.Display.runDeferredEvents(Unknown Source)
	at org.eclipse.swt.widgets.Display.readAndDispatch(Unknown Source)
	at org.eclipse.jface.window.Window.runEventLoop(Window.java:818)
	at org.eclipse.jface.window.Window.open(Window.java:794)
	at com.google.gapid.Main$UI.show(Main.java:118)
	at com.google.gapid.Main.main(Main.java:73)
```

**Comment by pmuetschard** [comment]
See similar issue for Vulkan: #1821

**Comment by ben-clayton** [comment]
Looks like we could do with some tests!
