### ISSUE TITLE
Gfxtrace from "The Talos Principle" using Vulkan fails to create video

### ISSUE THREAD

**Issue by MarkY-LunarG** [google/gapid#2089]
GAPID 1.1.0 on Windows 10 64-bit (Dell XPS 15 w/ 16GB RAM)

I've created a capture of the Steam Game "The Talos Principle" with the Graphics API switched to Vulkan.  I had GAPID trigger steam and was able to generate a trace loading the game (appiD 257510) and played for < 1 minute before exiting out completely.  

Upon completion I try to play it back as a video and it failed.  The command I used was:

```
   gapit video -out talos_principle.mp4 <gfxtrace>
```

 1. It first failed because it says it requires FFMPEG to be installed, but this wasn't listed in any documentation I could see.  Please add this (or any other requirement) to the documentation.
2. Once I installed FFMPEG it seemed to fail connecting to a server

Here's a dump of my output when trying to load the trace file.
[talos_video_error.txt](https://github.com/google/gapid/files/2229372/talos_video_error.txt)

**Comment by ben-clayton** [comment]
Relevant part of the crash log:

```
16:56:09.462 E: <gapis.exe> runtime: out of memory: cannot allocate 8323072-byte block (34349023232 in use)
16:56:09.462 E: <gapis.exe> fatal error: out of memory
16:56:09.462 E: <gapis.exe> 
16:56:09.462 E: <gapis.exe> runtime stack:
16:56:09.463 E: <gapis.exe> runtime.throw(0x33be6f7, 0xd)
16:56:09.463 E: <gapis.exe> 	GOROOT/src/runtime/panic.go:616 +0x88
16:56:09.463 E: <gapis.exe> runtime.largeAlloc(0x7ea000, 0xc195cf0100, 0x4)
16:56:09.470 E: <gapis.exe> 	GOROOT/src/runtime/malloc.go:828 +0x117
16:56:09.470 E: <gapis.exe> runtime.mallocgc.func1()
16:56:09.470 E: <gapis.exe> 	GOROOT/src/runtime/malloc.go:721 +0x4d
16:56:09.470 E: <gapis.exe> runtime.systemstack(0x0)
16:56:09.470 E: <gapis.exe> 	bazel-out/x64_windows-opt/bin/external/io_bazel_rules_go/windows_amd64_stripped/stdlib~/src/runtime/asm_amd64.s:409 +0x7e
16:56:09.470 E: <gapis.exe> runtime.mstart()
16:56:09.470 E: <gapis.exe> 	GOROOT/src/runtime/proc.go:1175
16:56:09.470 E: <gapis.exe> 
16:56:09.470 E: <gapis.exe> goroutine 53 [running]:
16:56:09.470 E: <gapis.exe> runtime.systemstack_switch()
16:56:09.470 E: <gapis.exe> 	bazel-out/x64_windows-opt/bin/external/io_bazel_rules_go/windows_amd64_stripped/stdlib~/src/runtime/asm_amd64.s:363 fp=0xc46bd64e80 sp=0xc46bd64e78 pc=0x457e30
16:56:09.470 E: <gapis.exe> runtime.mallocgc(0x7ea000, 0x0, 0x0, 0xc83ef22000)
16:56:09.470 E: <gapis.exe> 	GOROOT/src/runtime/malloc.go:720 +0x8e1 fp=0xc46bd64f20 sp=0xc46bd64e80 pc=0x412651
16:56:09.470 E: <gapis.exe> runtime.growslice(0x2a60dc0, 0x6ac44a0, 0x0, 0x0, 0x7e9000, 0xc80077dfa0, 0x62f728, 0xc8408c600b)
16:56:09.470 E: <gapis.exe> 	GOROOT/src/runtime/slice.go:172 +0x224 fp=0xc46bd64f88 sp=0xc46bd64f20 pc=0x443874
16:56:09.470 E: <gapis.exe> github.com/golang/protobuf/proto.unmarshalBytesValue(0xc8408c6011, 0x7e9000, 0x7e9004, 0xc3dc024e48, 0x2, 0xc8408c600c, 0x7e9005, 0x7e9005, 0x0, 0x0)
16:56:09.470 E: <gapis.exe> 	external/com_github_golang_protobuf/proto/table_unmarshal.go:1517 +0x1b1 fp=0xc46bd64ff8 sp=0xc46bd64f88 pc=0x635211
16:56:09.470 E: <gapis.exe> github.com/golang/protobuf/proto.(*unmarshalInfo).unmarshal(0xc466d81040, 0xc3dc024e40, 0xc8408c600a, 0x7e9007, 0x7e9007, 0x4f2173, 0xc04241ae10)
16:56:09.470 E: <gapis.exe> 	external/com_github_golang_protobuf/proto/table_unmarshal.go:171 +0x7be fp=0xc46bd65150 sp=0xc46bd64ff8 pc=0x62b34e
16:56:09.470 E: <gapis.exe> github.com/golang/protobuf/proto.makeUnmarshalMessageSlicePtr.func1(0xc8408c600a, 0x7e9007, 0x7e900b, 0xc3dc024c80, 0x2, 0x43ea3a, 0x2ee3380, 0xc3007245c0, 0x2f64f80, 0xc46bd65260)
16:56:09.470 E: <gapis.exe> 	external/com_github_golang_protobuf/proto/table_unmarshal.go:1588 +0x178 fp=0xc46bd651f0 sp=0xc46bd65150 pc=0x641028
16:56:09.470 E: <gapis.exe> github.com/golang/protobuf/proto.(*unmarshalInfo).unmarshal(0xc3363370e0, 0xc3dc024c80, 0xc8408c6005, 0x7e900c, 0x7e900c, 0x4cfbd6, 0x2bed920)
16:56:09.470 E: <gapis.exe> 	external/com_github_golang_protobuf/proto/table_unmarshal.go:171 +0x7be fp=0xc46bd65348 sp=0xc46bd651f0 pc=0x62b34e
16:56:09.470 E: <gapis.exe> github.com/golang/protobuf/proto.makeUnmarshalMessagePtr.func1(0xc8408c6005, 0x7e900c, 0x7e9010, 0xc10d25eb38, 0x2, 0xc042454780, 0x3460ee0, 0xc2084af980, 0xc0424547a8, 0xc46bd65440)
16:56:09.470 E: <gapis.exe> 	external/com_github_golang_protobuf/proto/table_unmarshal.go:1562 +0x131 fp=0xc46bd653e0 sp=0xc46bd65348 pc=0x640bd1
16:56:09.470 E: <gapis.exe> github.com/golang/protobuf/proto.makeUnmarshalOneof.func1(0xc8408c6001, 0x7e9010, 0x7e9010, 0xc38a2a1770, 0x2, 0xc04207ef00, 0xc27cd65358, 0xc27cd65360, 0xc042254000, 0x3)
16:56:09.470 E: <gapis.exe> 	external/com_github_golang_protobuf/proto/table_unmarshal.go:1746 +0xf3 fp=0xc46bd65478 sp=0xc46bd653e0 pc=0x642583
16:56:09.470 E: <gapis.exe> github.com/golang/protobuf/proto.(*unmarshalInfo).unmarshal(0xc336336fa0, 0xc38a2a1770, 0xc8408c6000, 0x7e9011, 0x7e9011, 0x29484be0, 0x0)
16:56:09.470 E: <gapis.exe> 	external/com_github_golang_protobuf/proto/table_unmarshal.go:171 +0x7be fp=0xc46bd655d0 sp=0xc46bd65478 pc=0x62b34e
16:56:09.470 E: <gapis.exe> github.com/golang/protobuf/proto.(*InternalMessageInfo).Unmarshal(0x6a90580, 0x37adde0, 0xc38a2a1770, 0xc8408c6000, 0x7e9011, 0x7e9011, 0x8bf2e01, 0x29484be0)
16:56:09.470 E: <gapis.exe> 	external/com_github_golang_protobuf/proto/table_unmarshal.go:63 +0x7c fp=0xc46bd65638 sp=0xc46bd655d0 pc=0x62a94c
16:56:09.470 E: <gapis.exe> github.com/google/gapid/gapir/replay_service.(*ReplayResponse).XXX_Unmarshal(0xc38a2a1770, 0xc8408c6000, 0x7e9011, 0x7e9011, 0xc38a2a1770, 0x2dc4001)
16:56:09.470 E: <gapis.exe> 	bazel-out/x64_windows-opt/bin/gapir/replay_service/windows_amd64_stripped/replay_service_go_proto~/github.com/google/gapid/gapir/replay_service/service.pb.go:686 +0x68 fp=0xc46bd65688 sp=0xc46bd65638 pc=0x886ac8
16:56:09.471 E: <gapis.exe> github.com/golang/protobuf/proto.Unmarshal(0xc8408c6000, 0x7e9011, 0x7e9011, 0x37adde0, 0xc38a2a1770, 0xc400ab6e40, 0x7e9011)
```

**Comment by MarkY-LunarG** [comment]
FYI, I checked during the replay, and I see over 26GB of RAM being used before it dies.

**Comment by MarkY-LunarG** [comment]
Also, I'm using `ffmpeg-20180723-0bb5cd8-win64-shared` for FFMPEG.
