### ISSUE TITLE
Tracing Failed   Cause: Could not start trace   Cause: loadGAPII   Cause: timeout

### ISSUE THREAD

**Issue by tobine** [google/gapid#2247]
GAPID Version: 1.1.1:7518e133266b9d4cd841516146c829e50e1adb9e
OS: windows 10 amd64

Please provide detailed steps that led to the error and copy-paste the stack trace.
Extra details from the logs and the trace file would be extra helpful.

Was attempting to trace Candy Crush Saga on Pixel2 with current Windows build of GAPID. The message about waiting for the debugger to attach appears and then disappears and the screen is black and just stays black. Tracing hangs at that point and no data is captured. Stack trace below:
```
com.google.gapid.server.Client$InternalServerErrorException: Tracing Failed
   Cause: Could not start trace
   Cause: loadGAPII
   Cause: timeout
	at com.google.gapid.server.Client.throwIfError(Client.java:296)
	at com.google.gapid.server.Client.lambda$streamTrace$52(Client.java:270)
	at com.google.gapid.server.GapidClientGrpc$StreamHandler.onNext(GapidClientGrpc.java:217)
	at io.grpc.stub.ClientCalls$StreamObserverToCallListenerAdapter.onMessage(ClientCalls.java:382)
	at io.grpc.internal.ClientCallImpl$ClientStreamListenerImpl$1MessageRead.runInContext(ClientCallImpl.java:458)
	at io.grpc.internal.ContextRunnable.run(ContextRunnable.java:52)
	at io.grpc.internal.SerializingExecutor$TaskRunner.run(SerializingExecutor.java:154)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: com.google.gapid.server.Client$Stack: For request: RPC->streamTrace()
	at com.google.gapid.server.Client.streamTrace(Client.java:267)
	at com.google.gapid.server.Tracer.trace(Tracer.java:41)
	at com.google.gapid.views.TracerDialog.showTracingDialog(TracerDialog.java:126)
	at com.google.gapid.views.WelcomeDialog$2.lambda$createDialogArea$4(WelcomeDialog.java:185)
	at org.eclipse.swt.widgets.EventTable.sendEvent(Unknown Source)
	at org.eclipse.swt.widgets.Display.sendEvent(Unknown Source)
	at org.eclipse.swt.widgets.Widget.sendEvent(Unknown Source)
	at org.eclipse.swt.widgets.Widget.sendEvent(Unknown Source)
	at org.eclipse.swt.widgets.Widget.sendSelectionEvent(Unknown Source)
	at org.eclipse.swt.widgets.Link.WM_LBUTTONUP(Unknown Source)
	at org.eclipse.swt.widgets.Control.windowProc(Unknown Source)
	at org.eclipse.swt.widgets.Display.windowProc(Unknown Source)
	at org.eclipse.swt.internal.win32.OS.DispatchMessageW(Native Method)
	at org.eclipse.swt.internal.win32.OS.DispatchMessage(Unknown Source)
	at org.eclipse.swt.widgets.Display.readAndDispatch(Unknown Source)
	at org.eclipse.jface.window.Window.runEventLoop(Window.java:818)
	at org.eclipse.jface.window.Window.open(Window.java:794)
	at com.google.gapid.views.WelcomeDialog.showWelcomeDialog(WelcomeDialog.java:209)
	at com.google.gapid.Main$UI.startUp(Main.java:151)
	at org.eclipse.swt.widgets.RunnableLock.run(Unknown Source)
	at org.eclipse.swt.widgets.Synchronizer.runAsyncMessages(Unknown Source)
	at org.eclipse.swt.widgets.Display.runAsyncMessages(Unknown Source)
	at org.eclipse.swt.widgets.Display.readAndDispatch(Unknown Source)
	at org.eclipse.jface.window.Window.runEventLoop(Window.java:818)
	at org.eclipse.jface.window.Window.open(Window.java:794)
	at com.google.gapid.Main$UI.show(Main.java:118)
	at com.google.gapid.Main.main(Main.java:73)
```

**Comment by pmuetschard** [comment]
I think this is due to the 1s timeout when trying to connect to the adb forwarded socket.
