### ISSUE TITLE
shadertools.ParseDescriptorSets is crashing

### ISSUE THREAD

**Issue by Qining** [google/gapid#2248]
When testing a Vulkan title, GAPID crashes at shadertools.go: line 359 in `ParseDescriptorSets`.

Below is the dump:
```
fatal error: unexpected signal during runtime execution
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x7f365014a646]

runtime stack:
runtime.throw(0x4e7a818, 0x2a)
	GOROOT/src/runtime/panic.go:616 +0x81
runtime.sigpanic()
	GOROOT/src/runtime/signal_unix.go:372 +0x28e

goroutine 163546 [syscall]:
runtime.cgocall(0x3aedd80, 0xc5ab39d188, 0x29)
	GOROOT/src/runtime/cgocall.go:128 +0x64 fp=0xc5ab39d148 sp=0xc5ab39d110 pc=0x4f77a4
github.com/google/gapid/gapis/shadertools._Cfunc_spvReflectCreateShaderModule(0x2e60, 0xc45da65000, 0xc5df230d80, 0x0)
	bazel-out/k8-opt/bin/external/gapid/gapis/shadertools/linux_amd64_stripped/go_default_library.cgo_codegen%/_cgo_gotypes.go:548 +0x4d fp=0xc5ab39d188 sp=0xc5ab39d148 pc=0xdb824d
github.com/google/gapid/gapis/shadertools.ParseDescriptorSets.func3(0x2e60, 0xc45da65000, 0xc5df230d80, 0xc45da65000)
	shadertools.go:359 +0xe1 fp=0xc5ab39d1c0 sp=0xc5ab39d188 pc=0xdb8f31
github.com/google/gapid/gapis/shadertools.ParseDescriptorSets(0xc45da65000, 0xb98, 0xb98, 0xc462b9a2fa, 0x4, 0x0, 0x0, 0x0)
	shadertools.go:359 +0xe6 fp=0xc5ab39d2b8 sp=0xc5ab39d1c0 pc=0xdb7626
github.com/google/gapid/gapis/api/vulkan.pipelineResourceData(0x52d5300, 0xc589b28720, 0xc4662ee620, 0xc5c1751fb0, 0xc59d2c79f0, 0x3523b01, 0x0, 0xab39dd00, 0x94f3, 0x7200000000004335, ...)
	external/gapid/gapis/api/vulkan/resources.go:1138 +0xe6e fp=0xc5ab39db80 sp=0xc5ab39d2b8 pc=0x332598e
github.com/google/gapid/gapis/api/vulkan.GraphicsPipelineObjectʳ.ResourceData(0xc588687340, 0x352bff9, 0x52d5300, 0xc589b28720, 0xc4662ee620, 0x3e445e0, 0xc5df1dce40, 0xc5ab39de00)
	external/gapid/gapis/api/vulkan/resources.go:944 +0x10c fp=0xc5ab39dbe8 sp=0xc5ab39db80 pc=0x3323ffc
github.com/google/gapid/gapis/api/vulkan.(*GraphicsPipelineObjectʳ).ResourceData(0xc5c6ef9e50, 0x52d5300, 0xc589b28720, 0xc4662ee620, 0xc5c9a6eb40, 0x0, 0x0)
	<autogenerated>:1 +0x67 fp=0xc5ab39dc38 sp=0xc5ab39dbe8 pc=0x3931e77
github.com/google/gapid/gapis/resolve.buildResources(0x52d5300, 0xc589b28720, 0xc45ef06240, 0xc547acfbc0, 0x52d5300, 0xc589b28720)
	external/gapid/gapis/resolve/resource_data.go:110 +0x5bd fp=0xc5ab39de48 sp=0xc5ab39dc38 pc=0xb8466d
github.com/google/gapid/gapis/resolve.(*AllResourceDataResolvable).Resolve(0xc589b284e0, 0x52d5300, 0xc589b28660, 0xc589b28660, 0xc4ce449718, 0x2, 0x2)
	external/gapid/gapis/resolve/resource_data.go:44 +0x77 fp=0xc5ab39de88 sp=0xc5ab39de48 pc=0xb84047
github.com/google/gapid/gapis/database.(*record).resolve(0xc4612fc000, 0x52d5300, 0xc589b28660, 0x0, 0x0)
	external/gapid/gapis/database/memory.go:130 +0x228 fp=0xc5ab39df48 sp=0xc5ab39de88 pc=0x9cf838
github.com/google/gapid/gapis/database.(*memory).resolveLocked.func1()
	external/gapid/gapis/database/memory.go:222 +0xcc fp=0xc5ab39dfb8 sp=0xc5ab39df48 pc=0x9d117c
github.com/google/gapid/core/app/crash.Go.func1(0xc589b28570)
	external/gapid/core/app/crash/crash.go:65 +0x43 fp=0xc5ab39dfd8 sp=0xc5ab39dfb8 pc=0x610123
runtime.goexit()
	GOROOT/src/runtime/asm_amd64.s:2361 +0x1 fp=0xc5ab39dfe0 sp=0xc5ab39dfd8 pc=0x54e8b1
created by github.com/google/gapid/core/app/crash.Go
	external/gapid/core/app/crash/crash.go:63 +0x3f

goroutine 1 [IO wait, 8 minutes]:
internal/poll.runtime_pollWait(0x7f3651224af0, 0x72, 0x0)
	GOROOT/src/runtime/netpoll.go:173 +0x57
internal/poll.(*pollDesc).wait(0xc420052698, 0x72, 0xc4204a4000, 0x0, 0x0)
	GOROOT/src/internal/poll/fd_poll_runtime.go:85 +0x9b
internal/poll.(*pollDesc).waitRead(0xc420052698, 0xffffffffffffff00, 0x0, 0x0)
	GOROOT/src/internal/poll/fd_poll_runtime.go:90 +0x3d
internal/poll.(*FD).Accept(0xc420052680, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0)
	GOROOT/src/internal/poll/fd_unix.go:372 +0x1a8
net.(*netFD).accept(0xc420052680, 0xc4205c6008, 0x0, 0x0)
	GOROOT/src/net/fd_unix.go:238 +0x42
net.(*TCPListener).accept(0xc4205ccc10, 0x54afe0, 0xc420543890, 0xc420543898)
	GOROOT/src/net/tcpsock_posix.go:136 +0x2e
net.(*TCPListener).Accept(0xc4205ccc10, 0x4ec32a8, 0xc4205e48f0, 0x52eb880, 0xc4205c6008)
	GOROOT/src/net/tcpsock.go:259 +0x49
google.golang.org/grpc.(*Server).Serve(0xc4205e48f0, 0x52d05c0, 0xc4205ccc10, 0x0, 0x0)
	external/org_golang_google_grpc/server.go:377 +0x169
github.com/google/gapid/core/net/grpcutil.ServeWithListener(0x52d5300, 0xc420034390, 0x52d05c0, 0xc4205ccc10, 0xc4205f0cb0, 0xc42015fad8, 0x1, 0x1, 0x0, 0x0)
	external/gapid/core/net/grpcutil/server.go:51 +0x275
github.com/google/gapid/gapis/server.NewWithListener(0x52d5300, 0xc420034390, 0x52d05c0, 0xc4205ccc10, 0xc420582180, 0xc420064038, 0x1, 0x1, 0x1, 0x7ffea63e4cf8, ...)
	external/gapid/gapis/server/grpc.go:60 +0x2d5
github.com/google/gapid/gapis/server.Listen(0x52d5300, 0xc420034390, 0x4e10b75, 0xb, 0xc420582180, 0xc420064038, 0x1, 0x1, 0x1, 0x7ffea63e4cf8, ...)
	external/gapid/gapis/server/grpc.go:49 +0xcc
main.run(0x52d5300, 0xc420034390, 0xc42003e000, 0x52d5300)
	external/gapid/cmd/gapis/main.go:141 +0x603
github.com/google/gapid/core/app.Run(0x4ec35e0)
	external/gapid/core/app/run.go:249 +0x3a3
main.main()
	external/gapid/cmd/gapis/main.go:71 +0x77

goroutine 5 [syscall, 8 minutes]:
os/signal.signal_recv(0x0)
	GOROOT/src/runtime/sigqueue.go:139 +0xa6
os/signal.loop()
	GOROOT/src/os/signal/signal_unix.go:22 +0x22
created by os/signal.init.0
	GOROOT/src/os/signal/signal_unix.go:28 +0x41

goroutine 84 [select, 8 minutes, locked to thread]:
runtime.gopark(0x4ec3e18, 0x0, 0x4e09057, 0x6, 0x18, 0x1)
	GOROOT/src/runtime/proc.go:291 +0x11a
runtime.selectgo(0xc420480750, 0xc4200400c0)
	GOROOT/src/runtime/select.go:392 +0xe50
runtime.ensureSigM.func1()
	GOROOT/src/runtime/signal_unix.go:549 +0x1f4
runtime.goexit()
	GOROOT/src/runtime/asm_amd64.s:2361 +0x1

goroutine 9 [chan receive, 8 minutes]:
github.com/google/gapid/core/log.Channel.func1()
	external/gapid/core/log/channel.go:30 +0xa7
github.com/google/gapid/core/app/crash.Go.func1(0xc420017fb0)
	external/gapid/core/app/crash/crash.go:65 +0x43
created by github.com/google/gapid/core/app/crash.Go
	external/gapid/core/app/crash/crash.go:63 +0x3f

goroutine 73 [chan receive, 8 minutes]:
github.com/google/gapid/core/app.handleAbortSignals.func1()
	external/gapid/core/app/atexit.go:95 +0x4e
github.com/google/gapid/core/app/crash.Go.func1(0xc42039e000)
	external/gapid/core/app/crash/crash.go:65 +0x43
created by github.com/google/gapid/core/app/crash.Go
	external/gapid/core/app/crash/crash.go:63 +0x3f

goroutine 74 [chan receive, 8 minutes]:
github.com/google/gapid/core/app.AddCleanup.func1()
	external/gapid/core/app/atexit.go:58 +0x8e
github.com/google/gapid/core/app/crash.Go.func1(0xc420034180)
	external/gapid/core/app/crash/crash.go:65 +0x43
created by github.com/google/gapid/core/app/crash.Go
	external/gapid/core/app/crash/crash.go:63 +0x3f

goroutine 75 [select, 8 minutes]:
reflect.rselect(0xc4202b4080, 0x2, 0x2, 0xc420036600, 0x2)
	GOROOT/src/runtime/select.go:624 +0x17d
reflect.Select(0xc4205469a0, 0x2, 0x64, 0xc420036600, 0x12, 0x0, 0x0, 0x52d5300)
	GOROOT/src/reflect/value.go:2065 +0x5c0
github.com/google/gapid/gapis/replay/scheduler.(*Scheduler).run(0xc42039ede0, 0x52d5300, 0xc4200380c0)
	external/gapid/gapis/replay/scheduler/scheduler.go:148 +0x632
github.com/google/gapid/gapis/replay/scheduler.New.func1()
	external/gapid/gapis/replay/scheduler/scheduler.go:74 +0x3c
github.com/google/gapid/core/app/crash.Go.func1(0xc42039ee00)
	external/gapid/core/app/crash/crash.go:65 +0x43
created by github.com/google/gapid/core/app/crash.Go
	external/gapid/core/app/crash/crash.go:63 +0x3f

goroutine 76 [select]:
github.com/google/gapid/core/os/android/adb.Monitor(0x52d5300, 0xc420034390, 0xc4200340c0, 0xb2d05e00, 0x0, 0x0)
	external/gapid/core/os/android/adb/device.go:82 +0x2b1
main.monitorAndroidDevices(0x52d5300, 0xc420034390, 0xc4200340c0, 0xc42004bf98)
	external/gapid/cmd/gapis/main.go:171 +0x79
main.run.func1()
	external/gapid/cmd/gapis/main.go:120 +0x5b
github.com/google/gapid/core/app/crash.Go.func1(0xc420034990)
	external/gapid/core/app/crash/crash.go:65 +0x43
created by github.com/google/gapid/core/app/crash.Go
	external/gapid/core/app/crash/crash.go:63 +0x3f

goroutine 163552 [select, 2 minutes]:
github.com/google/gapid/gapis/database.(*memory).resolveLocked(0xc42039e200, 0x52d5300, 0xc5d2fb1cb0, 0x57f293cf61bbee7e, 0x19b086815555033c, 0x6172a357, 0x0, 0x0, 0x0, 0x0)
	external/gapid/gapis/database/memory.go:244 +0x25b
github.com/google/gapid/gapis/database.(*memory).Resolve(0xc42039e200, 0x52d5300, 0xc5d2fb1cb0, 0x57f293cf61bbee7e, 0x19b086815555033c, 0x19b086816172a357, 0x0, 0x0, 0x0, 0x0)
	external/gapid/gapis/database/memory.go:181 +0xa0
github.com/google/gapid/gapis/database.Build(0x52d5300, 0xc5d2fb1cb0, 0x520fd40, 0xc5d2fb1ce0, 0xc420a29830, 0xc5c0459d30, 0x10, 0xc5c0459d28)
	external/gapid/gapis/database/database.go:54 +0x124
github.com/google/gapid/gapis/resolve.ResourceData(0x52d5300, 0xc5d2fb1cb0, 0xc5c0027200, 0xc5c0027260, 0xc5dfe1ad78, 0x1, 0x1, 0x52d5300)
	external/gapid/gapis/resolve/resource_data.go:123 +0x82
github.com/google/gapid/gapis/resolve.ResolveInternal(0x52d5300, 0xc5d2fb1cb0, 0x52d6200, 0xc5c0027200, 0xc5c0027260, 0x0, 0x0, 0x0, 0x0)
	external/gapid/gapis/resolve/resolve.go:361 +0xd95
github.com/google/gapid/gapis/resolve.ResolveService(0x52d5300, 0xc5d2fb1c20, 0x52d6200, 0xc5c0027200, 0xc5c0027260, 0xc5d2fb1c20, 0xc5dfe1ae98, 0x10, 0xc5dfe1ae90)
	external/gapid/gapis/resolve/resolve.go:293 +0x57
github.com/google/gapid/gapis/resolve.(*GetResolvable).Resolve(0xc5c00276e0, 0x52d5300, 0xc5d2fb1c20, 0xc5d2fb1b60, 0xc4ce479f18, 0x2, 0x2)
	external/gapid/gapis/resolve/get.go:33 +0xcf
github.com/google/gapid/gapis/database.(*record).resolve(0xc4612fc900, 0x52d5300, 0xc5d2fb1b60, 0x0, 0x0)
	external/gapid/gapis/database/memory.go:130 +0x228
github.com/google/gapid/gapis/database.(*memory).resolveLocked.func1()
	external/gapid/gapis/database/memory.go:222 +0xcc
github.com/google/gapid/core/app/crash.Go.func1(0xc5c0027770)
	external/gapid/core/app/crash/crash.go:65 +0x43
created by github.com/google/gapid/core/app/crash.Go
	external/gapid/core/app/crash/crash.go:63 +0x3f

goroutine 131 [select, 8 minutes]:
github.com/google/gapid/gapis/server.(*server).GetLogStream(0xc4204a47c0, 0x52d5300, 0xc420039a10, 0x5229580, 0xc420577a60, 0x0, 0x0)
	external/gapid/gapis/server/server.go:389 +0x2a4
github.com/google/gapid/gapis/server.(*grpcServer).GetLogStream(0xc4205c5ce0, 0xc4204e08c0, 0x52db980, 0xc420577a40, 0x0, 0x0)
	external/gapid/gapis/server/grpc.go:446 +0x198
github.com/google/gapid/gapis/service._Gapid_GetLogStream_Handler(0x4c372c0, 0xc4205c5ce0, 0x52daba0, 0xc4204e2500, 0xc420480e48, 0xc4200b0800)
	bazel-out/k8-opt/bin/external/gapid/gapis/service/linux_amd64_stripped/service_go_proto%/github.com/google/gapid/gapis/service/service.pb.go:9722 +0x111
google.golang.org/grpc.(*Server).processStreamingRPC(0xc4205e48f0, 0x52dbaa0, 0xc4203b4380, 0xc4200b0800, 0xc4205c5e30, 0x87e5ae0, 0xc4200395f0, 0x0, 0x0)
	external/org_golang_google_grpc/server.go:819 +0x6bd
google.golang.org/grpc.(*Server).handleStream(0xc4205e48f0, 0x52dbaa0, 0xc4203b4380, 0xc4200b0800, 0xc4200395f0)
	external/org_golang_google_grpc/server.go:909 +0xfee
google.golang.org/grpc.(*Server).serveStreams.func1.1(0xc42046a230, 0xc4205e48f0, 0x52dbaa0, 0xc4203b4380, 0xc4200b0800)
	external/org_golang_google_grpc/server.go:478 +0x9f
created by google.golang.org/grpc.(*Server).serveStreams.func1
	external/org_golang_google_grpc/server.go:476 +0xa1

goroutine 93 [IO wait]:
internal/poll.runtime_pollWait(0x7f3651224d60, 0x72, 0xc42030fac0)
	GOROOT/src/runtime/netpoll.go:173 +0x57
internal/poll.(*pollDesc).wait(0xc420052918, 0x72, 0xffffffffffffff00, 0x521b800, 0x87efc48)
	GOROOT/src/internal/poll/fd_poll_runtime.go:85 +0x9b
internal/poll.(*pollDesc).waitRead(0xc420052918, 0xc42054e000, 0x1000, 0x1000)
	GOROOT/src/internal/poll/fd_poll_runtime.go:90 +0x3d
internal/poll.(*FD).Read(0xc420052900, 0xc42054e000, 0x1000, 0x1000, 0x0, 0x0, 0x0)
	GOROOT/src/internal/poll/fd_unix.go:157 +0x17d
net.(*netFD).Read(0xc420052900, 0xc42054e000, 0x1000, 0x1000, 0x54, 0x0, 0x0)
	GOROOT/src/net/fd_unix.go:202 +0x4f
net.(*conn).Read(0xc420064080, 0xc42054e000, 0x1000, 0x1000, 0x0, 0x0, 0x0)
	GOROOT/src/net/net.go:176 +0x6a
bufio.(*Reader).Read(0xc4200542a0, 0xc4203a6470, 0x4, 0x4, 0x40, 0x8020, 0x40)
	GOROOT/src/bufio/bufio.go:216 +0x238
io.ReadAtLeast(0x52045c0, 0xc4200542a0, 0xc4203a6470, 0x4, 0x4, 0x4, 0xc42032c000, 0x0, 0xc4201b2138)
	GOROOT/src/io/io.go:309 +0x86
io.ReadFull(0x52045c0, 0xc4200542a0, 0xc4203a6470, 0x4, 0x4, 0xc, 0xc, 0xc42032c000)
	GOROOT/src/io/io.go:327 +0x58
golang.org/x/crypto/ssh.(*gcmCipher).readPacket(0xc4203a6460, 0xc400027644, 0x52045c0, 0xc4200542a0, 0x3b, 0x3b, 0x801f, 0x0, 0x0)
	external/org_golang_x_crypto/ssh/cipher.go:374 +0x7c
golang.org/x/crypto/ssh.(*connectionState).readPacket(0xc4202a8120, 0xc4200542a0, 0xc42030ff30, 0x4f9d27, 0xc4200543c0, 0xc4205efda0, 0xc42030ffb0)
	external/org_golang_x_crypto/ssh/transport.go:130 +0x68
golang.org/x/crypto/ssh.(*transport).readPacket(0xc4202a8120, 0x0, 0x3b, 0x3b, 0x0, 0x0)
	external/org_golang_x_crypto/ssh/transport.go:114 +0x37
golang.org/x/crypto/ssh.(*handshakeTransport).readOnePacket(0xc4201b8160, 0xc42030ff00, 0xc4669c50c0, 0x3b, 0x3b, 0x0, 0x0)
	external/org_golang_x_crypto/ssh/handshake.go:374 +0x48
golang.org/x/crypto/ssh.(*handshakeTransport).readLoop(0xc4201b8160)
	external/org_golang_x_crypto/ssh/handshake.go:197 +0x3c
created by golang.org/x/crypto/ssh.newClientTransport
	external/org_golang_x_crypto/ssh/handshake.go:134 +0x1a6

goroutine 80 [select]:
github.com/google/gapid/gapis/server.(*grpcServer).stopIfIdle(0xc4205c5ce0, 0x52d5300, 0xc420034390, 0xc4205e48f0, 0xdf8475800)
	external/gapid/gapis/server/grpc.go:121 +0x231
github.com/google/gapid/gapis/server.NewWithListener.func2.1()
	external/gapid/gapis/server/grpc.go:70 +0x4e
github.com/google/gapid/core/app/crash.Go.func1(0xc420052780)
	external/gapid/core/app/crash/crash.go:65 +0x43
created by github.com/google/gapid/core/app/crash.Go
	external/gapid/core/app/crash/crash.go:63 +0x3f

goroutine 13 [IO wait]:
internal/poll.runtime_pollWait(0x7f3651224f00, 0x72, 0xc420538990)
	GOROOT/src/runtime/netpoll.go:173 +0x57
internal/poll.(*pollDesc).wait(0xc4201b0718, 0x72, 0xffffffffffffff00, 0x521b800, 0x87efc48)
	GOROOT/src/internal/poll/fd_poll_runtime.go:85 +0x9b
internal/poll.(*pollDesc).waitRead(0xc4201b0718, 0xc4204d8000, 0x8000, 0x8000)
	GOROOT/src/internal/poll/fd_poll_runtime.go:90 +0x3d
internal/poll.(*FD).Read(0xc4201b0700, 0xc4204d8000, 0x8000, 0x8000, 0x0, 0x0, 0x0)
	GOROOT/src/internal/poll/fd_unix.go:157 +0x17d
net.(*netFD).Read(0xc4201b0700, 0xc4204d8000, 0x8000, 0x8000, 0x474e7c0, 0x47e42a0, 0x40a8600)
	GOROOT/src/net/fd_unix.go:202 +0x4f
net.(*conn).Read(0xc4205c6008, 0xc4204d8000, 0x8000, 0x8000, 0x0, 0x0, 0x0)
	GOROOT/src/net/net.go:176 +0x6a
bufio.(*Reader).Read(0xc4205641e0, 0xc4202b2038, 0x9, 0x9, 0xc420538b90, 0x537d75, 0xc5037e2a00)
	GOROOT/src/bufio/bufio.go:216 +0x238
io.ReadAtLeast(0x52045c0, 0xc4205641e0, 0xc4202b2038, 0x9, 0x9, 0x9, 0x8e7456, 0xc456de6ea8, 0x0)
	GOROOT/src/io/io.go:309 +0x86
io.ReadFull(0x52045c0, 0xc4205641e0, 0xc4202b2038, 0x9, 0x9, 0xc456de6ea8, 0x5211a80, 0xc456de7020)
	GOROOT/src/io/io.go:327 +0x58
golang.org/x/net/http2.readFrameHeader(0xc4202b2038, 0x9, 0x9, 0x52045c0, 0xc4205641e0, 0x0, 0x0, 0x0, 0x5204900)
	external/org_golang_x_net/http2/frame.go:237 +0x7b
golang.org/x/net/http2.(*Framer).ReadFrame(0xc4202b2000, 0x5, 0x5, 0x0, 0x0)
	external/org_golang_x_net/http2/frame.go:469 +0xa4
google.golang.org/grpc/transport.(*framer).readFrame(0xc420560090, 0xc456de6fc0, 0xc456de6fc0, 0x0, 0x0)
	external/org_golang_google_grpc/transport/http_util.go:508 +0x2f
google.golang.org/grpc/transport.(*http2Server).HandleStreams(0xc4203b4380, 0xc420560120, 0x4ec32e0)
	external/org_golang_google_grpc/transport/http2_server.go:307 +0x297
google.golang.org/grpc.(*Server).serveStreams(0xc4205e48f0, 0x52dbaa0, 0xc4203b4380)
	external/org_golang_google_grpc/server.go:474 +0x139
google.golang.org/grpc.(*Server).serveHTTP2Transport(0xc4205e48f0, 0x52eb880, 0xc4205c6008, 0x0, 0x0)
	external/org_golang_google_grpc/server.go:467 +0x3ac
google.golang.org/grpc.(*Server).handleRawConn(0xc4205e48f0, 0x52eb880, 0xc4205c6008)
	external/org_golang_google_grpc/server.go:438 +0x44f
created by google.golang.org/grpc.(*Server).Serve
	external/org_golang_google_grpc/server.go:407 +0x530

goroutine 14 [select, 2 minutes]:
google.golang.org/grpc/transport.(*http2Server).controller(0xc4203b4380)
```

**Comment by Qining** [comment]
Closing this as the issue has already been fixed.
