### ISSUE TITLE
Aborted command when resolving the sync data causes gapis panic

### ISSUE THREAD

**Issue by pmuetschard** [google/gapid#2257]
An aborted command when resolving the sync data for vulkan causes a panic in gapis.

```
panic: aborted(vkErrorInvalidHandle) [recovered]
                panic: Panic at command 1225:vkCreateImageView(device: 492397318176, pCreateInfo: 0x000000729d1fc0e0, pAllocator: 0, pView: 0x00000072a7bac8a0) → VK_SUCCESS:
aborted(vkErrorInvalidHandle) [recovered]
                panic:
--- *resolve.SynchronizationResolvable ---
capture:<id:<data:"9K¥3147¥341¥220F|¥n¥341¥035Q¥345¥355¥301¥352v¥¥P¥244" > >
 Store():
  gapis/database/database.go:50  github.com/google/gapid/gapis/database.Build
  gapis/resolve/synchronization_data.go:30  github.com/google/gapid/gapis/resolve.SyncData
  gapis/resolve/events.go:34  github.com/google/gapid/gapis/resolve.Events
  gapis/resolve/resolve.go:278  github.com/google/gapid/gapis/resolve.ResolveInternal
  gapis/resolve/resolve.go:239  github.com/google/gapid/gapis/resolve.ResolveService
  gapis/resolve/get.go:35  github.com/google/gapid/gapis/resolve.(*GetResolvable).Resolve
  gapis/database/memory.go:127  github.com/google/gapid/gapis/database.(*record).resolve
  gapis/database/memory.go:214  github.com/google/gapid/gapis/database.(*memory).resolveLocked.func1
  core/app/crash/crash.go:65  github.com/google/gapid/core/app/crash.Go.func1
 
Build() #0:
  gapis/database/database.go:54  github.com/google/gapid/gapis/database.Build
  gapis/resolve/synchronization_data.go:30  github.com/google/gapid/gapis/resolve.SyncData
  gapis/resolve/events.go:34  github.com/google/gapid/gapis/resolve.Events
  gapis/resolve/resolve.go:278  github.com/google/gapid/gapis/resolve.ResolveInternal
  gapis/resolve/resolve.go:239  github.com/google/gapid/gapis/resolve.ResolveService
  gapis/resolve/get.go:35  github.com/google/gapid/gapis/resolve.(*GetResolvable).Resolve
  gapis/database/memory.go:127  github.com/google/gapid/gapis/database.(*record).resolve
  gapis/database/memory.go:214  github.com/google/gapid/gapis/database.(*memory).resolveLocked.func1
  core/app/crash/crash.go:65  github.com/google/gapid/core/app/crash.Go.func1
Build() #1:
  gapis/database/database.go:54  github.com/google/gapid/gapis/database.Build
  gapis/resolve/synchronization_data.go:30  github.com/google/gapid/gapis/resolve.SyncData
  gapis/resolve/report.go:63  github.com/google/gapid/gapis/resolve.(*ReportResolvable).Resolve
  gapis/database/memory.go:127  github.com/google/gapid/gapis/database.(*record).resolve
  gapis/database/memory.go:214  github.com/google/gapid/gapis/database.(*memory).resolveLocked.func1
  core/app/crash/crash.go:65  github.com/google/gapid/core/app/crash.Go.func1
Build() #2:
  gapis/database/database.go:54  github.com/google/gapid/gapis/database.Build
  gapis/resolve/synchronization_data.go:30  github.com/google/gapid/gapis/resolve.SyncData
  gapis/resolve/command_tree.go:190  github.com/google/gapid/gapis/resolve.(*CommandTreeResolvable).Resolve
  gapis/database/memory.go:127  github.com/google/gapid/gapis/database.(*record).resolve
  gapis/database/memory.go:214  github.com/google/gapid/gapis/database.(*memory).resolveLocked.func1
  core/app/crash/crash.go:65  github.com/google/gapid/core/app/crash.Go.func1
 
--- *resolve.GetResolvable ---
path:<events:<capture:<id:<data:"9K¥3147¥341¥220F|¥n¥341¥035Q¥345¥355¥301¥352v¥¥P¥244" > > last_in_frame:true > >
 Store():
  gapis/database/database.go:50  github.com/google/gapid/gapis/database.Build
  gapis/resolve/get.go:27  github.com/google/gapid/gapis/resolve.Get
  gapis/server/server.go:259  github.com/google/gapid/gapis/server.(*server).Get
  gapis/server/grpc.go:167  github.com/google/gapid/gapis/server.(*grpcServer).Get
  bazel-out/x64_windows-opt/bin/gapis/service/windows_amd64/service_go_proto‾/github.com/google/gapid/gapis/service/service.pb.go:5617  github.com/google/gapid/gapis/service._Gapid_Get_Handler.func1
  core/app/auth/auth.go:110  github.com/google/gapid/core/app/auth.ServerInterceptor.func1
  bazel-out/x64_windows-opt/bin/gapis/service/windows_amd64/service_go_proto‾/github.com/google/gapid/gapis/service/service.pb.go:5619  github.com/google/gapid/gapis/service._Gapid_Get_Handler
  external/org_golang_google_grpc/server.go:719  google.golang.org/grpc.(*Server).processUnaryRPC
  external/org_golang_google_grpc/server.go:905  google.golang.org/grpc.(*Server).handleStream
 
Build() #0:
  gapis/database/database.go:54  github.com/google/gapid/gapis/database.Build
  gapis/resolve/get.go:27  github.com/google/gapid/gapis/resolve.Get
  gapis/server/server.go:259  github.com/google/gapid/gapis/server.(*server).Get
  gapis/server/grpc.go:167  github.com/google/gapid/gapis/server.(*grpcServer).Get
  bazel-out/x64_windows-opt/bin/gapis/service/windows_amd64/service_go_proto‾/github.com/google/gapid/gapis/service/service.pb.go:5617  github.com/google/gapid/gapis/service._Gapid_Get_Handler.func1
  core/app/auth/auth.go:110  github.com/google/gapid/core/app/auth.ServerInterceptor.func1
  bazel-out/x64_windows-opt/bin/gapis/service/windows_amd64/service_go_proto‾/github.com/google/gapid/gapis/service/service.pb.go:5619  github.com/google/gapid/gapis/service._Gapid_Get_Handler
  external/org_golang_google_grpc/server.go:719  google.golang.org/grpc.(*Server).processUnaryRPC
  external/org_golang_google_grpc/server.go:905  google.golang.org/grpc.(*Server).handleStream
[recovered]
                panic:
--- *resolve.SynchronizationResolvable ---
capture:<id:<data:"9K¥3147¥341¥220F|¥n¥341¥035Q¥345¥355¥301¥352v¥¥P¥244" > >
 Store():
  gapis/database/database.go:50  github.com/google/gapid/gapis/database.Build
  gapis/resolve/synchronization_data.go:30  github.com/google/gapid/gapis/resolve.SyncData
  gapis/resolve/events.go:34  github.com/google/gapid/gapis/resolve.Events
  gapis/resolve/resolve.go:278  github.com/google/gapid/gapis/resolve.ResolveInternal
  gapis/resolve/resolve.go:239  github.com/google/gapid/gapis/resolve.ResolveService
  gapis/resolve/get.go:35  github.com/google/gapid/gapis/resolve.(*GetResolvable).Resolve
  gapis/database/memory.go:127  github.com/google/gapid/gapis/database.(*record).resolve
  gapis/database/memory.go:214  github.com/google/gapid/gapis/database.(*memory).resolveLocked.func1
  core/app/crash/crash.go:65  github.com/google/gapid/core/app/crash.Go.func1
 
Build() #0:
  gapis/database/database.go:54  github.com/google/gapid/gapis/database.Build
  gapis/resolve/synchronization_data.go:30  github.com/google/gapid/gapis/resolve.SyncData
  gapis/resolve/events.go:34  github.com/google/gapid/gapis/resolve.Events
  gapis/resolve/resolve.go:278  github.com/google/gapid/gapis/resolve.ResolveInternal
  gapis/resolve/resolve.go:239  github.com/google/gapid/gapis/resolve.ResolveService
  gapis/resolve/get.go:35  github.com/google/gapid/gapis/resolve.(*GetResolvable).Resolve
  gapis/database/memory.go:127  github.com/google/gapid/gapis/database.(*record).resolve
  gapis/database/memory.go:214  github.com/google/gapid/gapis/database.(*memory).resolveLocked.func1
  core/app/crash/crash.go:65  github.com/google/gapid/core/app/crash.Go.func1
Build() #1:
  gapis/database/database.go:54  github.com/google/gapid/gapis/database.Build
  gapis/resolve/synchronization_data.go:30  github.com/google/gapid/gapis/resolve.SyncData
  gapis/resolve/report.go:63  github.com/google/gapid/gapis/resolve.(*ReportResolvable).Resolve
  gapis/database/memory.go:127  github.com/google/gapid/gapis/database.(*record).resolve
  gapis/database/memory.go:214  github.com/google/gapid/gapis/database.(*memory).resolveLocked.func1
  core/app/crash/crash.go:65  github.com/google/gapid/core/app/crash.Go.func1
Build() #2:
  gapis/database/database.go:54  github.com/google/gapid/gapis/database.Build
  gapis/resolve/synchronization_data.go:30  github.com/google/gapid/gapis/resolve.SyncData
  gapis/resolve/command_tree.go:190  github.com/google/gapid/gapis/resolve.(*CommandTreeResolvable).Resolve
  gapis/database/memory.go:127  github.com/google/gapid/gapis/database.(*record).resolve
  gapis/database/memory.go:214  github.com/google/gapid/gapis/database.(*memory).resolveLocked.func1
  core/app/crash/crash.go:65  github.com/google/gapid/core/app/crash.Go.func1
 
--- *resolve.GetResolvable ---
path:<events:<capture:<id:<data:"9K¥3147¥341¥220F|¥n¥341¥035Q¥345¥355¥301¥352v¥¥P¥244" > > last_in_frame:true > >
 Store():
  gapis/database/database.go:50  github.com/google/gapid/gapis/database.Build
  gapis/resolve/get.go:27  github.com/google/gapid/gapis/resolve.Get
  gapis/server/server.go:259  github.com/google/gapid/gapis/server.(*server).Get
  gapis/server/grpc.go:167  github.com/google/gapid/gapis/server.(*grpcServer).Get
  bazel-out/x64_windows-opt/bin/gapis/service/windows_amd64/service_go_proto‾/github.com/google/gapid/gapis/service/service.pb.go:5617  github.com/google/gapid/gapis/service._Gapid_Get_Handler.func1
  core/app/auth/auth.go:110  github.com/google/gapid/core/app/auth.ServerInterceptor.func1
  bazel-out/x64_windows-opt/bin/gapis/service/windows_amd64/service_go_proto‾/github.com/google/gapid/gapis/service/service.pb.go:5619  github.com/google/gapid/gapis/service._Gapid_Get_Handler
  external/org_golang_google_grpc/server.go:719  google.golang.org/grpc.(*Server).processUnaryRPC
  external/org_golang_google_grpc/server.go:905  google.golang.org/grpc.(*Server).handleStream
 
Build() #0:
  gapis/database/database.go:54  github.com/google/gapid/gapis/database.Build
  gapis/resolve/get.go:27  github.com/google/gapid/gapis/resolve.Get
  gapis/server/server.go:259  github.com/google/gapid/gapis/server.(*server).Get
  gapis/server/grpc.go:167  github.com/google/gapid/gapis/server.(*grpcServer).Get
  bazel-out/x64_windows-opt/bin/gapis/service/windows_amd64/service_go_proto‾/github.com/google/gapid/gapis/service/service.pb.go:5617  github.com/google/gapid/gapis/service._Gapid_Get_Handler.func1
  core/app/auth/auth.go:110  github.com/google/gapid/core/app/auth.ServerInterceptor.func1
  bazel-out/x64_windows-opt/bin/gapis/service/windows_amd64/service_go_proto‾/github.com/google/gapid/gapis/service/service.pb.go:5619  github.com/google/gapid/gapis/service._Gapid_Get_Handler
  external/org_golang_google_grpc/server.go:719  google.golang.org/grpc.(*Server).processUnaryRPC
  external/org_golang_google_grpc/server.go:905  google.golang.org/grpc.(*Server).handleStream
 
 
goroutine 45735 [running]:
github.com/google/gapid/core/app/crash.Crash(0x1e6e600, 0xc04bcfd510)
                core/app/crash/crash.go:89 +0xae
github.com/google/gapid/core/app/crash.handler()
                core/app/crash/crash.go:56 +0x59
panic(0x1e6e600, 0xc04bcfd510)
                GOROOT/src/runtime/panic.go:505 +0x237
github.com/google/gapid/gapis/database.(*memory).resolvePanicHandler(0xc0422c5020, 0x26d7380, 0xc05098e780)
                gapis/database/debug.go:106 +0x7cf
panic(0x1e95ac0, 0xc04bcfce00)
                GOROOT/src/runtime/panic.go:505 +0x237
github.com/google/gapid/gapis/api.ForeachCmd.func1(0xc0545f7c30, 0xc0545f7c58)
                gapis/api/cmd_foreach.go:39 +0x169
panic(0x219dfc0, 0xc04fa4b760)
                GOROOT/src/runtime/panic.go:505 +0x237
github.com/google/gapid/gapis/api/vulkan.API.ResolveSynchronization.func6(0x26d7380, 0xc05098f530, 0x4c9, 0x2708960, 0xc044bee050, 0x0, 0x0)
                gapis/api/vulkan/vulkan.go:347 +0xa8
github.com/google/gapid/gapis/api.ForeachCmd(0x26d7380, 0xc05098e900, 0xc049830000, 0x255db, 0x2d600, 0xc0545f7dd0, 0x0, 0x0)
                gapis/api/cmd_foreach.go:46 +0x14f
github.com/google/gapid/gapis/api/vulkan.API.ResolveSynchronization(0x26d7380, 0xc05098e900, 0xc05098e7e0, 0xc04d0b2588, 0x2391601, 0x8374888)
                gapis/api/vulkan/vulkan.go:344 +0x57e
github.com/google/gapid/gapis/resolve.(*SynchronizationResolvable).Resolve(0xc04d0b25a0, 0x26d7380, 0xc05098e780, 0x2691000, 0xc04d0b25a0, 0x1, 0x2693460)
                gapis/resolve/synchronization_data.go:55 +0x22e
github.com/google/gapid/gapis/database.(*record).resolve(0xc0495119e0, 0x26d7380, 0xc05098e780, 0x26d7380, 0xc05098e780)
                gapis/database/memory.go:127 +0xec
github.com/google/gapid/gapis/database.(*memory).resolveLocked.func1()
                gapis/database/memory.go:214 +0xa6
github.com/google/gapid/core/app/crash.Go.func1(0xc05098e7b0)
                core/app/crash/crash.go:65 +0x4a
created by github.com/google/gapid/core/app/crash.Go
                core/app/crash/crash.go:63 +0x46
```

**Comment by AWoloszyn** [comment]
We have removed most aborts in the api language, and now have explicit wrapping of calls. This should be fixed.
