### ISSUE TITLE
Tracing Failed   Cause: Could not start trace   Cause: Installing gapid.apk   Cause: Installing gapid.apk   Cause: Process returned error   Cause: exit status 1

### ISSUE THREAD

**Issue by kerrytazi** [google/gapid#2331]
GAPID Version: 1.2.0:493d1ed1849d2196c5548268b041488e69f38479
OS: windows 7 amd64
Device: Redmi 4A
Android: 7.1.2

Stack trace:
```
com.google.gapid.server.Client$InternalServerErrorException: Tracing Failed
   Cause: Could not start trace
   Cause: Installing gapid.apk
   Cause: Installing gapid.apk
   Cause: Process returned error
   Cause: exit status 1
	at com.google.gapid.server.Client.throwIfError(Client.java:290)
	at com.google.gapid.server.Client.lambda$streamTrace$49(Client.java:264)
	at com.google.gapid.server.GapidClientGrpc$StreamHandler.onNext(GapidClientGrpc.java:208)
	at io.grpc.stub.ClientCalls$StreamObserverToCallListenerAdapter.onMessage(ClientCalls.java:382)
	at io.grpc.internal.ClientCallImpl$ClientStreamListenerImpl$1MessageRead.runInContext(ClientCallImpl.java:458)
	at io.grpc.internal.ContextRunnable.run(ContextRunnable.java:52)
	at io.grpc.internal.SerializingExecutor$TaskRunner.run(SerializingExecutor.java:154)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: com.google.gapid.server.Client$Stack: For request: RPC->streamTrace()
	at com.google.gapid.server.Client.streamTrace(Client.java:261)
	at com.google.gapid.server.Tracer.trace(Tracer.java:41)
	at com.google.gapid.views.TracerDialog.showTracingDialog(TracerDialog.java:128)
	at com.google.gapid.MainWindow.lambda$createFileMenu$11(MainWindow.java:318)
	at com.google.gapid.MainWindow$MenuItems$1.run(MainWindow.java:655)
	at org.eclipse.jface.action.Action.runWithEvent(Action.java:473)
	at org.eclipse.jface.action.ActionContributionItem.handleWidgetSelection(ActionContributionItem.java:565)
	at org.eclipse.jface.action.ActionContributionItem.lambda$4(ActionContributionItem.java:397)
	at org.eclipse.swt.widgets.EventTable.sendEvent(Unknown Source)
	at org.eclipse.swt.widgets.Display.sendEvent(Unknown Source)
	at org.eclipse.swt.widgets.Widget.sendEvent(Unknown Source)
	at org.eclipse.swt.widgets.Display.runDeferredEvents(Unknown Source)
	at org.eclipse.swt.widgets.Display.readAndDispatch(Unknown Source)
	at org.eclipse.jface.window.Window.runEventLoop(Window.java:818)
	at org.eclipse.jface.window.Window.open(Window.java:794)
	at com.google.gapid.Main$UI.show(Main.java:118)
	at com.google.gapid.Main.main(Main.java:73)

```

logcat:

```
10-31 00:11:22.984 12542 12560 E ContactDirectoryManager: onPackageChanged: com.google.android.gapid.aarch64
10-31 00:11:22.984 12542 12560 E ContactDirectoryManager: android.content.pm.PackageManager$NameNotFoundException: com.google.android.gapid.aarch64
10-31 00:11:22.984 12542 12560 E ContactDirectoryManager: 	at android.app.ApplicationPackageManager.getPackageInfoAsUser(ApplicationPackageManager.java:149)
10-31 00:11:22.984 12542 12560 E ContactDirectoryManager: 	at android.app.ApplicationPackageManager.getPackageInfo(ApplicationPackageManager.java:132)
10-31 00:11:22.984 12542 12560 E ContactDirectoryManager: 	at com.android.providers.contacts.ContactDirectoryManager.onPackageChanged(ContactDirectoryManager.java:400)
10-31 00:11:22.984 12542 12560 E ContactDirectoryManager: 	at com.android.providers.contacts.ContactsProvider2.performBackgroundTask(ContactsProvider2.java:1962)
10-31 00:11:22.984 12542 12560 E ContactDirectoryManager: 	at com.android.providers.contacts.ContactsProvider2$1.handleMessage(ContactsProvider2.java:1725)
10-31 00:11:22.984 12542 12560 E ContactDirectoryManager: 	at android.os.Handler.dispatchMessage(Handler.java:102)
10-31 00:11:22.984 12542 12560 E ContactDirectoryManager: 	at android.os.Looper.loop(Looper.java:163)
10-31 00:11:22.984 12542 12560 E ContactDirectoryManager: 	at android.os.HandlerThread.run(HandlerThread.java:61)
10-31 00:11:22.994 12542 12542 D VoicemailCleanupService: startForeground
10-31 00:11:23.013 12542 14193 D VoicemailCleanupService: Cleaning up data for package: com.google.android.gapid.aarch64
10-31 00:11:23.071 13612 14204 D MicloudPushService: push service action : android.intent.action.PACKAGE_REMOVED sBindStatus:0
10-31 00:11:23.079 13644 13644 I VSC-AppInstallReceiver: action: android.intent.action.PACKAGE_REMOVED, packageName: com.google.android.gapid.aarch64
10-31 00:11:23.108 12542 12542 D VoicemailCleanupService: stopForeground

10-31 00:11:23.365  1476  1532 W XSpaceManagerService: update XSpace App: packageName:com.google.android.gapid.aarch64, user:UserHandle{0}, action:android.intent.action.PACKAGE_REMOVED

10-31 00:11:32.881  1476  6391 W ActivityManager: Unable to start service Intent { act=com.google.android.gapid.action.SEND_DEV_INFO cmp=com.google.android.gapid.aarch64/com.google.android.gapid.DeviceInfoService } U=0: not found

10-31 00:18:54.738 15939 15939 I art     : Late-enabling -Xcheck:jni
10-31 00:18:54.756 15592 15592 D AppActiveReceiver: receive app active broadcast for: com.google.android.gapid.aarch64, install from: com.google.android.packageinstaller
10-31 00:18:54.760 15939 15939 D TidaProvider: TidaProvider()
10-31 00:18:54.774 15939 15939 W ReflectionUtils: 
10-31 00:18:54.774 15939 15939 W ReflectionUtils: java.lang.NoSuchMethodException: android.os.MessageQueue#enableMonitor()#bestmatch
10-31 00:18:54.774 15939 15939 W ReflectionUtils: 	at miui.util.ReflectionUtils.findMethodBestMatch(ReflectionUtils.java:338)
10-31 00:18:54.774 15939 15939 W ReflectionUtils: 	at miui.util.ReflectionUtils.findMethodBestMatch(ReflectionUtils.java:375)
10-31 00:18:54.774 15939 15939 W ReflectionUtils: 	at miui.util.ReflectionUtils.callMethod(ReflectionUtils.java:800)
10-31 00:18:54.774 15939 15939 W ReflectionUtils: 	at miui.util.ReflectionUtils.tryCallMethod(ReflectionUtils.java:818)
10-31 00:18:54.774 15939 15939 W ReflectionUtils: 	at android.os.BaseLooper.enableMonitor(BaseLooper.java:47)
10-31 00:18:54.774 15939 15939 W ReflectionUtils: 	at android.os.Looper.prepareMainLooper(Looper.java:112)
10-31 00:18:54.774 15939 15939 W ReflectionUtils: 	at android.app.ActivityThread.main(ActivityThread.java:6211)
10-31 00:18:54.774 15939 15939 W ReflectionUtils: 	at java.lang.reflect.Method.invoke(Native Method)
10-31 00:18:54.774 15939 15939 W ReflectionUtils: 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:904)
10-31 00:18:54.774 15939 15939 W ReflectionUtils: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:794)
10-31 00:18:54.774 15939 15939 V BoostFramework: BoostFramework() : mPerf = com.qualcomm.qti.Performance@f326923
10-31 00:18:54.859 15939 15962 I Adreno-EGL: <qeglDrvAPI_eglInitialize:379>: EGL 1.4 QUALCOMM build: Nondeterministic_AU_msm8937_64_LA.UM.5.5.R1__release_AU (I83a540a04a)
10-31 00:18:54.859 15939 15962 I Adreno-EGL: OpenGL ES Shader Compiler Version: XE031.09.00.04
10-31 00:18:54.859 15939 15962 I Adreno-EGL: Build Date: 09/18/17 Mon
10-31 00:18:54.859 15939 15962 I Adreno-EGL: Local Branch: 
10-31 00:18:54.859 15939 15962 I Adreno-EGL: Remote Branch: quic/gfx-adreno.lnx.1.0.r5-rel
10-31 00:18:54.859 15939 15962 I Adreno-EGL: Local Patches: NONE
10-31 00:18:54.859 15939 15962 I Adreno-EGL: Reconstruct Branch: NOTHING

10-31 00:18:54.866 15939 15962 W Adreno-ES20: <get_gpu_clk:229>: open failed: errno 13
10-31 00:18:54.872 15939 15962 I vulkan  : no Vulkan HAL present, using stub HAL
10-31 00:18:54.872 15939 15962 D vulkan  : searching for layers in '/data/app/com.google.android.gapid.aarch64-1/lib/arm64'
10-31 00:18:54.873 15939 15962 D vulkan  : added global layer 'VirtualSwapchain' from library '/data/app/com.google.android.gapid.aarch64-1/lib/arm64/libVkLayer_VirtualSwapchain.so'
10-31 00:18:54.884 15939 15962 D vulkan  : searching for layers in '/system/fake-libs64'
10-31 00:18:54.887 15939 15962 D vulkan  : searching for layers in '/data/app/com.google.android.gapid.aarch64-1/base.apk!/lib/arm64-v8a'

10-31 00:19:15.187 15939 16001 W ResourceType: Failure getting entry for 0x09020000 (t=1 e=0) (error -75)
10-31 00:19:16.890 15939 15945 I art     : Do partial code cache collection, code=30KB, data=29KB
10-31 00:19:16.891 15939 15945 I art     : After code cache collection, code=30KB, data=29KB
10-31 00:19:16.891 15939 15945 I art     : Increasing code cache capacity to 128KB
```

Steps to reproduce:
Install `gapid-aarch64.apk` on the device
Open `gapid.exe`
File -> Capture Trace
Choose Device, Application and Output Directory
Press OK
Waiting ~10 secs until error

**Comment by AWoloszyn** [comment]
Can you try without installing gapid manually?
(Actually remove gapid from the device entirely) The program should handle installing it for you as needed.

**Comment by kerrytazi** [comment]
program does not handle installation for me

**Comment by AWoloszyn** [comment]
Can you try to manually install both 32 and 64-bit versions of the apk?

**Comment by kerrytazi** [comment]
Manual install of 32-bit version helps. now i can capture the trace.

**Comment by AWoloszyn** [comment]
Do you happen to know why it doesn't install?
We should just be doing the equivalent of
`adb install -r -g`.

**Comment by kerrytazi** [comment]
Just tried: `.\adb.exe install -r -g gapid\gapid-armeabi.apk`
And got: `adb: failed to install gapid\gapid-armeabi.apk:`
Install via USB: enabled.
Previous apks deleted before install.

**Comment by g0wen** [comment]
My device is running Android 8.1, using a Mac.

Following the above steps I got a different error.

command: `adb install -r -g gapid-armeabi.apk`
output: `adb: failed to install gapid-armeabi.apk: Security exception: You need the android.permission.INSTALL_GRANT_RUNTIME_PERMISSIONS permission to use the PackageManager.INSTALL_GRANT_RUNTIME_PERMISSIONS flag`
`java.lang.SecurityException: You need the android.permission.INSTALL_GRANT_RUNTIME_PERMISSIONS permission to use the PackageManager.INSTALL_GRANT_RUNTIME_PERMISSIONS flag
	at com.android.server.pm.PackageInstallerService.createSessionInternal(PackageInstallerService.java:454)
	at com.android.server.pm.PackageInstallerService.createSession(PackageInstallerService.java:420)
	at com.android.server.pm.PackageManagerShellCommand.doCreateSession(PackageManagerShellCommand.java:1383)
	at com.android.server.pm.PackageManagerShellCommand.runInstall(PackageManagerShellCommand.java:201)
	at com.android.server.pm.PackageManagerShellCommand.onCommand(PackageManagerShellCommand.java:109)
	at android.os.ShellCommand.exec(ShellCommand.java:96)
	at com.android.server.pm.PackageManagerService.onShellCommand(PackageManagerService.java:23134)`

I already had `USB Debugging` enabled.
I discovered that there is a second setting I had to set in my Developer Options: `USB Debugging (Security settings)`


It would probably be helpful if the GAPID user interface presented these errors (if it does, then in a more obvious way). As I had to hunt to find this issue to find out what commands to run in order to figure out my actual issue.
