### ISSUE TITLE
The gapis server has exited with an error code of: 2

### ISSUE THREAD

**Issue by y-novikov** [google/gapid#2356]
GAPID Version: 1.2.1:developer
OS: linux amd64

Happens when opening the attached trace of angle_end2end_tests on Nexus 5X.
[org.chromium.native_test_20181107_1249.gfxtrace.zip](https://github.com/google/gapid/files/2558581/org.chromium.native_test_20181107_1249.gfxtrace.zip)

panic: runtime error: invalid memory address or nil pointer dereference [recovered]
	panic: Panic at command 1139:vkDestroyImage(device: 514417378880, image: 176, pAllocator: 0):
runtime error: invalid memory address or nil pointer dereference [recovered]
	panic: 
--- *resolve.FramebufferChangesResolvable ---
 capture:<ID:<data:"8\022\302\025tK\035`\037\030\342}9\202\377\301'>\3700" > > config:<replay_device:<ID:<data:"\255\344|\302\331Y\007\256\3365\341\204\270\276\000e2\342\000\223" > > > 
 Store():
  gapis/database/database.go:50  github.com/google/gapid/gapis/database.Build
  gapis/resolve/framebuffer_changes.go:34  github.com/google/gapid/gapis/resolve.FramebufferChanges
  gapis/resolve/framebuffer_attachment.go:79  github.com/google/gapid/gapis/resolve.(*FramebufferAttachmentResolvable).Resolve
  gapis/database/memory.go:130  github.com/google/gapid/gapis/database.(*record).resolve
  gapis/database/memory.go:222  github.com/google/gapid/gapis/database.(*memory).resolveLocked.func1
  core/app/crash/crash.go:65  github.com/google/gapid/core/app/crash.Go.func1

 Build() #0:
  gapis/database/database.go:54  github.com/google/gapid/gapis/database.Build
  gapis/resolve/framebuffer_changes.go:34  github.com/google/gapid/gapis/resolve.FramebufferChanges
  gapis/resolve/framebuffer_attachment.go:79  github.com/google/gapid/gapis/resolve.(*FramebufferAttachmentResolvable).Resolve
  gapis/database/memory.go:130  github.com/google/gapid/gapis/database.(*record).resolve
  gapis/database/memory.go:222  github.com/google/gapid/gapis/database.(*memory).resolveLocked.func1
  core/app/crash/crash.go:65  github.com/google/gapid/core/app/crash.Go.func1

--- *resolve.FramebufferAttachmentResolvable ---
 replay_settings:<device:<ID:<data:"\255\344|\302\331Y\007\256\3365\341\204\270\276\000e2\342\000\223" > > disable_replay_optimization:true > after:<capture:<ID:<data:"8\022\302\025tK\035`\037\030\342}9\202\377\301'>\3700" > > indices:986 > attachment:Color0 settings:<max_width:192 max_height:192 > hints:<preview:true > config:<replay_device:<ID:<data:"\255\344|\302\331Y\007\256\3365\341\204\270\276\000e2\342\000\223" > > > 
 Store():
  gapis/resolve/framebuffer_attachment.go:62  github.com/google/gapid/gapis/resolve.FramebufferAttachment
  gapis/resolve/thumbnail.go:52  github.com/google/gapid/gapis/resolve.CommandThumbnail
  gapis/resolve/thumbnail.go:33  github.com/google/gapid/gapis/resolve.Thumbnail
  gapis/resolve/resolve.go:377  github.com/google/gapid/gapis/resolve.ResolveInternal
  gapis/resolve/resolve.go:293  github.com/google/gapid/gapis/resolve.ResolveService
  gapis/resolve/get.go:33  github.com/google/gapid/gapis/resolve.(*GetResolvable).Resolve
  gapis/database/memory.go:130  github.com/google/gapid/gapis/database.(*record).resolve
  gapis/database/memory.go:222  github.com/google/gapid/gapis/database.(*memory).resolveLocked.func1
  core/app/crash/crash.go:65  github.com/google/gapid/core/app/crash.Go.func1

 Build() #0:
  gapis/database/database.go:44  github.com/google/gapid/gapis/database.Resolve
  gapis/resolve/resolve.go:87  github.com/google/gapid/gapis/resolve.ImageInfo
  gapis/resolve/resolve.go:345  github.com/google/gapid/gapis/resolve.ResolveInternal
  gapis/resolve/as.go:29  github.com/google/gapid/gapis/resolve.As
  gapis/resolve/resolve.go:311  github.com/google/gapid/gapis/resolve.ResolveInternal
  gapis/resolve/resolve.go:293  github.com/google/gapid/gapis/resolve.ResolveService
  gapis/resolve/get.go:33  github.com/google/gapid/gapis/resolve.(*GetResolvable).Resolve
  gapis/database/memory.go:130  github.com/google/gapid/gapis/database.(*record).resolve
  gapis/database/memory.go:222  github.com/google/gapid/gapis/database.(*memory).resolveLocked.func1

--- *resolve.GetResolvable ---
 path:<as:<image_format:<uncompressed:<format:<components:<data_type:<integer:<bits:8 > > sampling:<normalized:true > channel:R > components:<data_type:<integer:<bits:8 > > sampling:<normalized:true > channel:G > components:<data_type:<integer:<bits:8 > > sampling:<normalized:true > channel:B > components:<data_type:<integer:<bits:8 > > sampling:<normalized:true > channel:A > > > > image_info:<ID:<data:"\264\230L\3776\221!\332>D\256\306\300\025&\376\213\267\247\330" > > > > config:<replay_device:<ID:<data:"\255\344|\302\331Y\007\256\3365\341\204\270\276\000e2\342\000\223" > > > 
 Store():
  gapis/database/database.go:50  github.com/google/gapid/gapis/database.Build
  gapis/resolve/get.go:26  github.com/google/gapid/gapis/resolve.Get
  gapis/resolve/thumbnail.go:75  github.com/google/gapid/gapis/resolve.CommandThumbnail
  gapis/resolve/thumbnail.go:33  github.com/google/gapid/gapis/resolve.Thumbnail
  gapis/resolve/resolve.go:377  github.com/google/gapid/gapis/resolve.ResolveInternal
  gapis/resolve/resolve.go:293  github.com/google/gapid/gapis/resolve.ResolveService
  gapis/resolve/get.go:33  github.com/google/gapid/gapis/resolve.(*GetResolvable).Resolve
  gapis/database/memory.go:130  github.com/google/gapid/gapis/database.(*record).resolve
  gapis/database/memory.go:222  github.com/google/gapid/gapis/database.(*memory).resolveLocked.func1

 Build() #0:
  gapis/database/database.go:54  github.com/google/gapid/gapis/database.Build
  gapis/resolve/get.go:26  github.com/google/gapid/gapis/resolve.Get
  gapis/resolve/thumbnail.go:75  github.com/google/gapid/gapis/resolve.CommandThumbnail
  gapis/resolve/thumbnail.go:33  github.com/google/gapid/gapis/resolve.Thumbnail
  gapis/resolve/resolve.go:377  github.com/google/gapid/gapis/resolve.ResolveInternal
  gapis/resolve/resolve.go:293  github.com/google/gapid/gapis/resolve.ResolveService
  gapis/resolve/get.go:33  github.com/google/gapid/gapis/resolve.(*GetResolvable).Resolve
  gapis/database/memory.go:130  github.com/google/gapid/gapis/database.(*record).resolve
  gapis/database/memory.go:222  github.com/google/gapid/gapis/database.(*memory).resolveLocked.func1
 Build() #1:
  gapis/database/database.go:54  github.com/google/gapid/gapis/database.Build
  gapis/resolve/get.go:26  github.com/google/gapid/gapis/resolve.Get
  gapis/resolve/thumbnail.go:75  github.com/google/gapid/gapis/resolve.CommandThumbnail
  gapis/resolve/thumbnail.go:109  github.com/google/gapid/gapis/resolve.CommandTreeNodeThumbnail
  gapis/resolve/thumbnail.go:35  github.com/google/gapid/gapis/resolve.Thumbnail
  gapis/resolve/resolve.go:377  github.com/google/gapid/gapis/resolve.ResolveInternal
  gapis/resolve/resolve.go:293  github.com/google/gapid/gapis/resolve.ResolveService
  gapis/resolve/get.go:33  github.com/google/gapid/gapis/resolve.(*GetResolvable).Resolve
  gapis/database/memory.go:130  github.com/google/gapid/gapis/database.(*record).resolve

--- *resolve.GetResolvable ---
 path:<thumbnail:<desired_max_width:192 desired_max_height:192 desired_format:<uncompressed:<format:<components:<data_type:<integer:<bits:8 > > sampling:<normalized:true > channel:R > components:<data_type:<integer:<bits:8 > > sampling:<normalized:true > channel:G > components:<data_type:<integer:<bits:8 > > sampling:<normalized:true > channel:B > components:<data_type:<integer:<bits:8 > > sampling:<normalized:true > channel:A > > > > command:<capture:<ID:<data:"8\022\302\025tK\035`\037\030\342}9\202\377\301'>\3700" > > indices:986 > disable_optimization:true > > config:<replay_device:<ID:<data:"\255\344|\302\331Y\007\256\3365\341\204\270\276\000e2\342\000\223" > > > 
 Store():
  gapis/database/database.go:50  github.com/google/gapid/gapis/database.Build
  gapis/resolve/get.go:26  github.com/google/gapid/gapis/resolve.Get
  gapis/server/server.go:355  github.com/google/gapid/gapis/server.(*server).Get
  gapis/server/grpc.go:170  github.com/google/gapid/gapis/server.(*grpcServer).Get
  bazel-out/k8-fastbuild/bin/gapis/service/linux_amd64_stripped/service_go_proto%/github.com/google/gapid/gapis/service/service.pb.go:9492  github.com/google/gapid/gapis/service._Gapid_Get_Handler.func1
  core/app/auth/auth.go:110  github.com/google/gapid/core/app/auth.ServerInterceptor.func1
  bazel-out/k8-fastbuild/bin/gapis/service/linux_amd64_stripped/service_go_proto%/github.com/google/gapid/gapis/service/service.pb.go:9494  github.com/google/gapid/gapis/service._Gapid_Get_Handler
  external/org_golang_google_grpc/server.go:719  google.golang.org/grpc.(*Server).processUnaryRPC
  external/org_golang_google_grpc/server.go:905  google.golang.org/grpc.(*Server).handleStream

 Build() #0:
  gapis/database/database.go:54  github.com/google/gapid/gapis/database.Build
  gapis/resolve/get.go:26  github.com/google/gapid/gapis/resolve.Get
  gapis/server/server.go:355  github.com/google/gapid/gapis/server.(*server).Get
  gapis/server/grpc.go:170  github.com/google/gapid/gapis/server.(*grpcServer).Get
  bazel-out/k8-fastbuild/bin/gapis/service/linux_amd64_stripped/service_go_proto%/github.com/google/gapid/gapis/service/service.pb.go:9492  github.com/google/gapid/gapis/service._Gapid_Get_Handler.func1
  core/app/auth/auth.go:110  github.com/google/gapid/core/app/auth.ServerInterceptor.func1
  bazel-out/k8-fastbuild/bin/gapis/service/linux_amd64_stripped/service_go_proto%/github.com/google/gapid/gapis/service/service.pb.go:9494  github.com/google/gapid/gapis/service._Gapid_Get_Handler
  external/org_golang_google_grpc/server.go:719  google.golang.org/grpc.(*Server).processUnaryRPC
  external/org_golang_google_grpc/server.go:905  google.golang.org/grpc.(*Server).handleStream
 [recovered]
	panic: 
--- *resolve.FramebufferChangesResolvable ---
 capture:<ID:<data:"8\022\302\025tK\035`\037\030\342}9\202\377\301'>\3700" > > config:<replay_device:<ID:<data:"\255\344|\302\331Y\007\256\3365\341\204\270\276\000e2\342\000\223" > > > 
 Store():
  gapis/database/database.go:50  github.com/google/gapid/gapis/database.Build
  gapis/resolve/framebuffer_changes.go:34  github.com/google/gapid/gapis/resolve.FramebufferChanges
  gapis/resolve/framebuffer_attachment.go:79  github.com/google/gapid/gapis/resolve.(*FramebufferAttachmentResolvable).Resolve
  gapis/database/memory.go:130  github.com/google/gapid/gapis/database.(*record).resolve
  gapis/database/memory.go:222  github.com/google/gapid/gapis/database.(*memory).resolveLocked.func1
  core/app/crash/crash.go:65  github.com/google/gapid/core/app/crash.Go.func1

 Build() #0:
  gapis/database/database.go:54  github.com/google/gapid/gapis/database.Build
  gapis/resolve/framebuffer_changes.go:34  github.com/google/gapid/gapis/resolve.FramebufferChanges
  gapis/resolve/framebuffer_attachment.go:79  github.com/google/gapid/gapis/resolve.(*FramebufferAttachmentResolvable).Resolve
  gapis/database/memory.go:130  github.com/google/gapid/gapis/database.(*record).resolve
  gapis/database/memory.go:222  github.com/google/gapid/gapis/database.(*memory).resolveLocked.func1
  core/app/crash/crash.go:65  github.com/google/gapid/core/app/crash.Go.func1

--- *resolve.FramebufferAttachmentResolvable ---
 replay_settings:<device:<ID:<data:"\255\344|\302\331Y\007\256\3365\341\204\270\276\000e2\342\000\223" > > disable_replay_optimization:true > after:<capture:<ID:<data:"8\022\302\025tK\035`\037\030\342}9\202\377\301'>\3700" > > indices:986 > attachment:Color0 settings:<max_width:192 max_height:192 > hints:<preview:true > config:<replay_device:<ID:<data:"\255\344|\302\331Y\007\256\3365\341\204\270\276\000e2\342\000\223" > > > 
 Store():
  gapis/resolve/framebuffer_attachment.go:62  github.com/google/gapid/gapis/resolve.FramebufferAttachment
  gapis/resolve/thumbnail.go:52  github.com/google/gapid/gapis/resolve.CommandThumbnail
  gapis/resolve/thumbnail.go:33  github.com/google/gapid/gapis/resolve.Thumbnail
  gapis/resolve/resolve.go:377  github.com/google/gapid/gapis/resolve.ResolveInternal
  gapis/resolve/resolve.go:293  github.com/google/gapid/gapis/resolve.ResolveService
  gapis/resolve/get.go:33  github.com/google/gapid/gapis/resolve.(*GetResolvable).Resolve
  gapis/database/memory.go:130  github.com/google/gapid/gapis/database.(*record).resolve
  gapis/database/memory.go:222  github.com/google/gapid/gapis/database.(*memory).resolveLocked.func1
  core/app/crash/crash.go:65  github.com/google/gapid/core/app/crash.Go.func1

 Build() #0:
  gapis/database/database.go:44  github.com/google/gapid/gapis/database.Resolve
  gapis/resolve/resolve.go:87  github.com/google/gapid/gapis/resolve.ImageInfo
  gapis/resolve/resolve.go:345  github.com/google/gapid/gapis/resolve.ResolveInternal
  gapis/resolve/as.go:29  github.com/google/gapid/gapis/resolve.As
  gapis/resolve/resolve.go:311  github.com/google/gapid/gapis/resolve.ResolveInternal
  gapis/resolve/resolve.go:293  github.com/google/gapid/gapis/resolve.ResolveService
  gapis/resolve/get.go:33  github.com/google/gapid/gapis/resolve.(*GetResolvable).Resolve
  gapis/database/memory.go:130  github.com/google/gapid/gapis/database.(*record).resolve
  gapis/database/memory.go:222  github.com/google/gapid/gapis/database.(*memory).resolveLocked.func1

--- *resolve.GetResolvable ---
 path:<as:<image_format:<uncompressed:<format:<components:<data_type:<integer:<bits:8 > > sampling:<normalized:true > channel:R > components:<data_type:<integer:<bits:8 > > sampling:<normalized:true > channel:G > components:<data_type:<integer:<bits:8 > > sampling:<normalized:true > channel:B > components:<data_type:<integer:<bits:8 > > sampling:<normalized:true > channel:A > > > > image_info:<ID:<data:"\264\230L\3776\221!\332>D\256\306\300\025&\376\213\267\247\330" > > > > config:<replay_device:<ID:<data:"\255\344|\302\331Y\007\256\3365\341\204\270\276\000e2\342\000\223" > > > 
 Store():
  gapis/database/database.go:50  github.com/google/gapid/gapis/database.Build
  gapis/resolve/get.go:26  github.com/google/gapid/gapis/resolve.Get
  gapis/resolve/thumbnail.go:75  github.com/google/gapid/gapis/resolve.CommandThumbnail
  gapis/resolve/thumbnail.go:33  github.com/google/gapid/gapis/resolve.Thumbnail
  gapis/resolve/resolve.go:377  github.com/google/gapid/gapis/resolve.ResolveInternal
  gapis/resolve/resolve.go:293  github.com/google/gapid/gapis/resolve.ResolveService
  gapis/resolve/get.go:33  github.com/google/gapid/gapis/resolve.(*GetResolvable).Resolve
  gapis/database/memory.go:130  github.com/google/gapid/gapis/database.(*record).resolve
  gapis/database/memory.go:222  github.com/google/gapid/gapis/database.(*memory).resolveLocked.func1

 Build() #0:
  gapis/database/database.go:54  github.com/google/gapid/gapis/database.Build
  gapis/resolve/get.go:26  github.com/google/gapid/gapis/resolve.Get
  gapis/resolve/thumbnail.go:75  github.com/google/gapid/gapis/resolve.CommandThumbnail
  gapis/resolve/thumbnail.go:33  github.com/google/gapid/gapis/resolve.Thumbnail
  gapis/resolve/resolve.go:377  github.com/google/gapid/gapis/resolve.ResolveInternal
  gapis/resolve/resolve.go:293  github.com/google/gapid/gapis/resolve.ResolveService
  gapis/resolve/get.go:33  github.com/google/gapid/gapis/resolve.(*GetResolvable).Resolve
  gapis/database/memory.go:130  github.com/google/gapid/gapis/database.(*record).resolve
  gapis/database/memory.go:222  github.com/google/gapid/gapis/database.(*memory).resolveLocked.func1
 Build() #1:
  gapis/database/database.go:54  github.com/google/gapid/gapis/database.Build
  gapis/resolve/get.go:26  github.com/google/gapid/gapis/resolve.Get
  gapis/resolve/thumbnail.go:75  github.com/google/gapid/gapis/resolve.CommandThumbnail
  gapis/resolve/thumbnail.go:109  github.com/google/gapid/gapis/resolve.CommandTreeNodeThumbnail
  gapis/resolve/thumbnail.go:35  github.com/google/gapid/gapis/resolve.Thumbnail
  gapis/resolve/resolve.go:377  github.com/google/gapid/gapis/resolve.ResolveInternal
  gapis/resolve/resolve.go:293  github.com/google/gapid/gapis/resolve.ResolveService
  gapis/resolve/get.go:33  github.com/google/gapid/gapis/resolve.(*GetResolvable).Resolve
  gapis/database/memory.go:130  github.com/google/gapid/gapis/database.(*record).resolve

--- *resolve.GetResolvable ---
 path:<thumbnail:<desired_max_width:192 desired_max_height:192 desired_format:<uncompressed:<format:<components:<data_type:<integer:<bits:8 > > sampling:<normalized:true > channel:R > components:<data_type:<integer:<bits:8 > > sampling:<normalized:true > channel:G > components:<data_type:<integer:<bits:8 > > sampling:<normalized:true > channel:B > components:<data_type:<integer:<bits:8 > > sampling:<normalized:true > channel:A > > > > command:<capture:<ID:<data:"8\022\302\025tK\035`\037\030\342}9\202\377\301'>\3700" > > indices:986 > disable_optimization:true > > config:<replay_device:<ID:<data:"\255\344|\302\331Y\007\256\3365\341\204\270\276\000e2\342\000\223" > > > 
 Store():
  gapis/database/database.go:50  github.com/google/gapid/gapis/database.Build
  gapis/resolve/get.go:26  github.com/google/gapid/gapis/resolve.Get
  gapis/server/server.go:355  github.com/google/gapid/gapis/server.(*server).Get
  gapis/server/grpc.go:170  github.com/google/gapid/gapis/server.(*grpcServer).Get
  bazel-out/k8-fastbuild/bin/gapis/service/linux_amd64_stripped/service_go_proto%/github.com/google/gapid/gapis/service/service.pb.go:9492  github.com/google/gapid/gapis/service._Gapid_Get_Handler.func1
  core/app/auth/auth.go:110  github.com/google/gapid/core/app/auth.ServerInterceptor.func1
  bazel-out/k8-fastbuild/bin/gapis/service/linux_amd64_stripped/service_go_proto%/github.com/google/gapid/gapis/service/service.pb.go:9494  github.com/google/gapid/gapis/service._Gapid_Get_Handler
  external/org_golang_google_grpc/server.go:719  google.golang.org/grpc.(*Server).processUnaryRPC
  external/org_golang_google_grpc/server.go:905  google.golang.org/grpc.(*Server).handleStream

 Build() #0:
  gapis/database/database.go:54  github.com/google/gapid/gapis/database.Build
  gapis/resolve/get.go:26  github.com/google/gapid/gapis/resolve.Get
  gapis/server/server.go:355  github.com/google/gapid/gapis/server.(*server).Get
  gapis/server/grpc.go:170  github.com/google/gapid/gapis/server.(*grpcServer).Get
  bazel-out/k8-fastbuild/bin/gapis/service/linux_amd64_stripped/service_go_proto%/github.com/google/gapid/gapis/service/service.pb.go:9492  github.com/google/gapid/gapis/service._Gapid_Get_Handler.func1
  core/app/auth/auth.go:110  github.com/google/gapid/core/app/auth.ServerInterceptor.func1
  bazel-out/k8-fastbuild/bin/gapis/service/linux_amd64_stripped/service_go_proto%/github.com/google/gapid/gapis/service/service.pb.go:9494  github.com/google/gapid/gapis/service._Gapid_Get_Handler
  external/org_golang_google_grpc/server.go:719  google.golang.org/grpc.(*Server).processUnaryRPC
  external/org_golang_google_grpc/server.go:905  google.golang.org/grpc.(*Server).handleStream

[signal SIGSEGV: segmentation violation code=0x1 addr=0x60 pc=0x37ee974]

goroutine 1170 [running]:
github.com/google/gapid/core/app/crash.Crash(0x48bb580, 0xc420a42a60)
	core/app/crash/crash.go:89 +0xa7
github.com/google/gapid/core/app/crash.handler()
	core/app/crash/crash.go:56 +0x52
panic(0x48bb580, 0xc420a42a60)
	GOROOT/src/runtime/panic.go:502 +0x229
github.com/google/gapid/gapis/database.(*memory).resolvePanicHandler(0xc4204a8980, 0x595a7e0, 0xc42059adb0)
	gapis/database/debug.go:106 +0x7c8
panic(0x48f50e0, 0xc420633a30)
	GOROOT/src/runtime/panic.go:502 +0x229
github.com/google/gapid/gapis/api.ForeachCmd.func1(0xc420655d18, 0xc420655d48)
	gapis/api/cmd_foreach.go:43 +0x162
panic(0x4a35f20, 0x8f935c0)
	GOROOT/src/runtime/panic.go:502 +0x229
github.com/google/gapid/gapis/api/vulkan.ImageObjectʳ.Info(...)
	bazel-out/k8-fastbuild/genfiles/gapis/api/vulkan/api.go:62641
github.com/google/gapid/gapis/api/vulkan.(*State).getSubmitAttachmentInfo(0xc420a12000, 0xc400000002, 0x98f40b0, 0xc420888468, 0x13, 0x13, 0xc4205bb980)
	gapis/api/vulkan/state.go:57 +0x444
github.com/google/gapid/gapis/api/vulkan.(*State).getFramebufferAttachmentInfo(0xc420a12000, 0xc400000002, 0x0, 0x0, 0x0, 0x588a080, 0xc420633a10)
	gapis/api/vulkan/state.go:123 +0x41
github.com/google/gapid/gapis/api/vulkan.API.GetFramebufferAttachmentInfo(0x595a7e0, 0xc42059af60, 0xc420761500, 0x1, 0x1, 0xc42086a380, 0x77b258c4f0, 0x2, 0x0, 0x0, ...)
	gapis/api/vulkan/vulkan.go:109 +0x6c
github.com/google/gapid/gapis/resolve.(*FramebufferChangesResolvable).Resolve.func1(0xc42086a380, 0xc4207614f8, 0x1, 0x1, 0x599a200, 0xc4207cd810)
	gapis/resolve/framebuffer_changes.go:83 +0x53b
github.com/google/gapid/gapis/api/sync.MutateWithSubcommands.func1(0x595a7e0, 0xc420457440, 0x473, 0x599a200, 0xc4207cd810, 0x0, 0x0)
	gapis/api/sync/sync.go:180 +0x156
github.com/google/gapid/gapis/api.ForeachCmd(0x595a7e0, 0xc42059bd10, 0xc4206bc000, 0x4dc, 0x500, 0xc420655dc0, 0x0, 0x0)
	gapis/api/cmd_foreach.go:50 +0x23e
github.com/google/gapid/gapis/api/sync.MutateWithSubcommands(0x595a7e0, 0xc42059aff0, 0xc42063f170, 0xc4206bc000, 0x4dc, 0x500, 0xc4209681a0, 0x0, 0xc4209681a0, 0x0, ...)
	gapis/api/sync/sync.go:174 +0x1d5
github.com/google/gapid/gapis/resolve.(*FramebufferChangesResolvable).Resolve(0xc42059ac30, 0x595a7e0, 0xc42059af60, 0xc42059ae70, 0xc42037d718, 0x2, 0x2)
	gapis/resolve/framebuffer_changes.go:99 +0x1d4
github.com/google/gapid/gapis/database.(*record).resolve(0xc420828780, 0x595a7e0, 0xc42059ae70, 0x0, 0x0)
	gapis/database/memory.go:130 +0x228
github.com/google/gapid/gapis/database.(*memory).resolveLocked.func1()
	gapis/database/memory.go:222 +0xcc
github.com/google/gapid/core/app/crash.Go.func1(0xc42059acc0)
	core/app/crash/crash.go:65 +0x43
created by github.com/google/gapid/core/app/crash.Go
	core/app/crash/crash.go:63 +0x3f

**Comment by crazii** [comment]
+1

**Comment by y-novikov** [comment]
I have debugged this a bit, and the issue is that ca.Image() isNil in gapis/api/vulkan/state.go:57
Guess it's not set properly somewhere.
I've worked around the crash with
			if ca, ok := lastDrawInfo.Framebuffer().ImageAttachments().Lookup(attRef.Attachment()); ok {
				if !ca.Image().IsNil() {
					return ca.Image().Info().Extent().Width(),
						ca.Image().Info().Extent().Height(),
						ca.Image().Info().Fmt(),
						attRef.Attachment(), true, nil
				}
			}

**Comment by AWoloszyn** [comment]
It looks like we are trying to get the last-used framebuffer somewhere odd.
After the image-view has been destroyed. Looking at your trace, it looks like the only place that will occur is during clean-up. Your fix will work for now, I will add it, but we need some more robust clean-up handling.
