### ISSUE TITLE
Tracing Failed   Cause: Could not start trace   Cause: loadGAPII   Cause: Exception raised calling: public static void java.lang.System.load(java.lang.String)java.lang.UnsatisfiedLinkError: dlopen failed: cannot locate symbol "__aeabi_memclr4" referenced by "/data/app/com.google.android.gapid.armeabi-1/lib/arm/libgapii.so"...

### ISSUE THREAD

**Issue by someonelikeypp** [google/gapid#2389]
GAPID Version: 1.2.1:9acb3d602489c7389134f043d4a1e9c12b6e3ff5
OS: mac os x x86_64

Please provide detailed steps that led to the error and copy-paste the stack trace.
Extra details from the logs and the trace file would be extra helpful.

**Comment by someonelikeypp** [comment]
> What device is this running on?

Meitu m6
I lowered the version to 1.0.3 and solve this problem. thx all the same.

**Comment by Gohan** [comment]
I had encountered same problem
![image](https://user-images.githubusercontent.com/212567/49495453-fc39cb00-f89d-11e8-8b33-5fa7b2f890e8.png)

**Comment by Gohan** [comment]
Version 1.2.1:9acb3d602489c7389134f043d4a1e9c12b6e3ff5

**Comment by stolk** [comment]
I am getting this is GAPID v1.21 on a Huawei Honor 2 tablet, that is running Android 6.0.1.

```
com.google.gapid.server.Client$InternalServerErrorException: Tracing Failed
   Cause: Could not start trace
   Cause: loadGAPII
   Cause: Exception raised calling: public static void java.lang.System.load(java.lang.String)
java.lang.UnsatisfiedLinkError: dlopen failed: cannot locate symbol "__aeabi_memclr4" referenced by "/data/app/com.google.android.gapid.armeabi-1/lib/arm/libgapii.so"...
	at com.google.gapid.server.Client.throwIfError(Client.java:290)
	at com.google.gapid.server.Client.lambda$streamTrace$49(Client.java:264)
	at com.google.gapid.server.GapidClientGrpc$StreamHandler.onNext(GapidClientGrpc.java:208)
	at io.grpc.stub.ClientCalls$StreamObserverToCallListenerAdapter.onMessage(ClientCalls.java:382)
	at io.grpc.internal.ClientCallImpl$ClientStreamListenerImpl$1MessageRead.runInContext(ClientCallImpl.java:458)
	at io.grpc.internal.ContextRunnable.run(ContextRunnable.java:52)
	at io.grpc.internal.SerializingExecutor$TaskRunner.run(SerializingExecutor.java:154)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1135)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.lang.Thread.run(Thread.java:844)
Caused by: com.google.gapid.server.Client$Stack: For request: RPC->streamTrace()
	at com.google.gapid.server.Client.streamTrace(Client.java:261)
	at com.google.gapid.server.Tracer.trace(Tracer.java:41)
	at com.google.gapid.views.TracerDialog.showTracingDialog(TracerDialog.java:128)
	at com.google.gapid.MainWindow.lambda$createFileMenu$11(MainWindow.java:318)
	at com.google.gapid.MainWindow$MenuItems$1.run(MainWindow.java:655)
	at org.eclipse.jface.action.Action.runWithEvent(Action.java:473)
	at org.eclipse.jface.action.ActionContributionItem.handleWidgetSelection(ActionContributionItem.java:565)
	at org.eclipse.jface.action.ActionContributionItem.lambda$4(ActionContributionItem.java:397)
	at org.eclipse.swt.widgets.EventTable.sendEvent(Unknown Source)
	at org.eclipse.swt.widgets.Display.sendEvent(Unknown Source)
	at org.eclipse.swt.widgets.Widget.sendEvent(Unknown Source)
	at org.eclipse.swt.widgets.Display.runDeferredEvents(Unknown Source)
	at org.eclipse.swt.widgets.Display.readAndDispatch(Unknown Source)
	at org.eclipse.jface.window.Window.runEventLoop(Window.java:818)
	at org.eclipse.jface.window.Window.open(Window.java:794)
	at com.google.gapid.Main$UI.show(Main.java:118)
	at com.google.gapid.Main.main(Main.java:73)
```

**Comment by stolk** [comment]
> I am getting the same error with GAPID v1.21 on a Huawei Honor 2 tablet, that is running Android 6.0.1.

Just tried v1.3.1 and got the same error on the 6.0.1 tablet.

I am building gapid from source now, with latest NDK and SDK 28, to see if that helps. Slow going though... it compiled 10K files or so, and is still going. Did I see bazel compile llvm from scratch? Will report back.

**Comment by AWoloszyn** [comment]
Thanks for testing that.
You likely did see bazel compile parts of llvm (once per ABI). It is a dependency of our interception library

https://github.com/google/gapid/tree/master/gapii/interceptor-lib/cc

FYI: You can turn off unused ABIs, by commenting out the apks you do not need from the root BUILD.bazel file, this can help with initial build times significantly. After your first build, incremental builds are much better.

**Comment by stolk** [comment]
So.... the build from source succeeded. I am still getting the `__aeabi_memclr4` error with NDK r19 and SDK 28.

I think it may have something to do with the ABI.

I run this on a 64-bit device. And gapid seems to install **two APKs** for it:

- **GAPID - aarch64**
- **GAPID - armeabi**

Is this so that it can handle both 32b and 64b apps on the device?

Or should it have only one of them installed? I think the 64b version in installed when you connect to the device with gapid, but the 32b version gets installed later. Maybe when a capture is started or something?

Is this expected behaviour?

**Comment by pmuetschard** [comment]
> Is this so that it can handle both 32b and 64b apps on the device?

Yes. The interceptor is a library that is loaded into the traced app's namespace and has to thus match the ABI of the traced application. If you uninstall both apps and then launch GAPID, you should see it only install the 64bit version on a 64bit device first. You should only see it install the 32bit one, if you request to trace a 32bit application.

The problem here is that, even though we specify 16 as the min SDK, the native code all gets built targeting 26. Yikes. The minimum SDK for is is 21, so you should be good to go if you patch in my change from #2645.
