### ISSUE TITLE
wsarecv: An existing connection was forcibly closed by the remote host

### ISSUE THREAD

**Issue by joez** [google/gapid#2502]
GAPID Version: 1.2.1:9acb3d602489c7389134f043d4a1e9c12b6e3ff5
OS: windows 10 amd64

* No Android Studio is running
* emulator.exe -avd Nexus_5_API_25
* gapid.exe
* File -> Capture Trace
* Select device in emulator
* Select android.intent.action.MAIN:com.android.calculator2/com.android.calculator2.Calculator
* Details in the attached screenshot

```
com.google.gapid.server.Client$InternalServerErrorException: Tracing Failed
   Cause: Could not start trace
   Cause: Connecting to JDWP
   Cause: read tcp 127.0.0.1:53175->127.0.0.1:53128: wsarecv: An existing connection was forcibly closed by the remote host.
	at com.google.gapid.server.Client.throwIfError(Client.java:290)
	at com.google.gapid.server.Client.lambda$streamTrace$49(Client.java:264)
	at com.google.gapid.server.GapidClientGrpc$StreamHandler.onNext(GapidClientGrpc.java:208)
	at io.grpc.stub.ClientCalls$StreamObserverToCallListenerAdapter.onMessage(ClientCalls.java:382)
	at io.grpc.internal.ClientCallImpl$ClientStreamListenerImpl$1MessageRead.runInContext(ClientCallImpl.java:458)
	at io.grpc.internal.ContextRunnable.run(ContextRunnable.java:52)
	at io.grpc.internal.SerializingExecutor$TaskRunner.run(SerializingExecutor.java:154)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: com.google.gapid.server.Client$Stack: For request: RPC->streamTrace()
	at com.google.gapid.server.Client.streamTrace(Client.java:261)
	at com.google.gapid.server.Tracer.trace(Tracer.java:41)
	at com.google.gapid.views.TracerDialog.showTracingDialog(TracerDialog.java:128)
	at com.google.gapid.MainWindow.lambda$createFileMenu$11(MainWindow.java:318)
	at com.google.gapid.MainWindow$MenuItems$1.run(MainWindow.java:655)
	at org.eclipse.jface.action.Action.runWithEvent(Action.java:473)
	at org.eclipse.jface.action.ActionContributionItem.handleWidgetSelection(ActionContributionItem.java:565)
	at org.eclipse.jface.action.ActionContributionItem.lambda$4(ActionContributionItem.java:397)
	at org.eclipse.swt.widgets.EventTable.sendEvent(Unknown Source)
	at org.eclipse.swt.widgets.Display.sendEvent(Unknown Source)
	at org.eclipse.swt.widgets.Widget.sendEvent(Unknown Source)
	at org.eclipse.swt.widgets.Display.runDeferredEvents(Unknown Source)
	at org.eclipse.swt.widgets.Display.readAndDispatch(Unknown Source)
	at org.eclipse.jface.window.Window.runEventLoop(Window.java:818)
	at org.eclipse.jface.window.Window.open(Window.java:794)
	at com.google.gapid.Main$UI.show(Main.java:118)
	at com.google.gapid.Main.main(Main.java:73)

01:52:00.323 I: <gapis> Adding new device
01:52:00.323 I: <gapis> New scheduler for device: 92514cc0fa08664d369249a788e8f3de2a61ad82
01:52:00.323 I: <gapis> New trace scheduler for device: 92514cc0fa08664d369249a788e8f3de2a61ad82 JUGUANGZ-MOBL1
01:52:00.349 I: <gapis> Starting grpc server
01:52:00.835 I: [Try ABI: x86⇒gapidapk.EnsureInstalled] <gapis> Examining gapid.apk on host...
01:52:00.847 I: [Try ABI: x86⇒gapidapk.EnsureInstalled] <gapis> Looking for gapid.apk...
01:52:01.325 I: [Try ABI: x86⇒gapidapk.EnsureInstalled] <gapis> Found gapid package...
01:52:01.331 I: [startDevInfoService] <gapis> Attempt to start service: com.google.android.gapid.DeviceInfoService
01:52:01.964 I: <gapis> Adding new device
01:52:01.964 I: <gapis> Adding new device
01:52:01.964 I: <gapis> New scheduler for device: e2cb06e772028a11b64bef85ed00f32c34407c96
01:52:01.964 I: <gapis> New trace scheduler for device: e2cb06e772028a11b64bef85ed00f32c34407c96 Google Android SDK built for x86
01:52:10.106 I: <gapis> Device is rooted
01:52:10.171 I: <gapis> Starting with options {ObserveFrameFrequency:0 ObserveDrawFrequency:0 StartFrame:0 FramesToCapture:0 APIs:10 Flags:1 AdditionalFlags:}
01:52:10.234 I: [start] <gapis> Turning device screen on
01:52:10.299 I: [start] <gapis> Checking for lockscreen
01:52:10.367 W: [start] <gapis> Couldn't determine lockscreen state: 
   Cause: Couldn't get lockscreen state
01:52:10.375 I: [start] <gapis> Checking gapid.apk is installed
01:52:10.375 I: [gapidapk.EnsureInstalled⇒start] <gapis> Examining gapid.apk on host...
01:52:10.382 I: [gapidapk.EnsureInstalled⇒start] <gapis> Looking for gapid.apk...
01:52:10.785 I: [gapidapk.EnsureInstalled⇒start] <gapis> Found gapid package...
01:52:10.785 I: [start] <gapis> Forwarding
01:52:10.842 I: [start] <gapis> Starting activity in debug mode
01:52:41.108 I: [start] <gapis> Forwarding TCP port 53025 -> JDWP pid 4717
01:52:41.165 I: [start] <gapis> Connecting to JDWP
01:52:41.169 I: [start] <gapis> Failed to connect to the application: read tcp 127.0.0.1:53028->127.0.0.1:53025: wsarecv: An existing connection was forcibly closed by the remote host.. Retrying...
01:52:42.173 I: [start] <gapis> Failed to connect to the application: read tcp 127.0.0.1:53031->127.0.0.1:53025: wsarecv: An existing connection was forcibly closed by the remote host.. Retrying...
01:52:43.181 I: [start] <gapis> Failed to connect to the application: read tcp 127.0.0.1:53032->127.0.0.1:53025: wsarecv: An existing connection was forcibly closed by the remote host.. Retrying...
01:52:44.184 I: [start] <gapis> Failed to connect to the application: read tcp 127.0.0.1:53033->127.0.0.1:53025: wsarecv: An existing connection was forcibly closed by the remote host.. Retrying...
01:52:45.189 I: [start] <gapis> Failed to connect to the application: read tcp 127.0.0.1:53036->127.0.0.1:53025: wsarecv: An existing connection was forcibly closed by the remote host.. Retrying...
01:52:46.199 I: [start] <gapis> Failed to connect to the application: read tcp 127.0.0.1:53037->127.0.0.1:53025: wsarecv: An existing connection was forcibly closed by the remote host.. Retrying...
01:52:47.204 I: [start] <gapis> Failed to connect to the application: read tcp 127.0.0.1:53038->127.0.0.1:53025: wsarecv: An existing connection was forcibly closed by the remote host.. Retrying...
01:52:48.208 I: [start] <gapis> Failed to connect to the application: read tcp 127.0.0.1:53041->127.0.0.1:53025: wsarecv: An existing connection was forcibly closed by the remote host.. Retrying...
01:52:49.220 I: [start] <gapis> Failed to connect to the application: read tcp 127.0.0.1:53042->127.0.0.1:53025: wsarecv: An existing connection was forcibly closed by the remote host.. Retrying...
01:52:50.224 I: [start] <gapis> Failed to connect to the application: read tcp 127.0.0.1:53043->127.0.0.1:53025: wsarecv: An existing connection was forcibly closed by the remote host.. Retrying...
01:52:50.693 I: <gapis> Device is rooted
01:52:50.759 I: <gapis> Starting with options {ObserveFrameFrequency:0 ObserveDrawFrequency:0 StartFrame:0 FramesToCapture:0 APIs:10 Flags:1 AdditionalFlags:}
01:52:50.826 I: [start] <gapis> Turning device screen on
01:52:50.898 I: [start] <gapis> Checking for lockscreen
01:52:50.962 W: [start] <gapis> Couldn't determine lockscreen state: 
   Cause: Couldn't get lockscreen state
01:52:50.971 I: [start] <gapis> Checking gapid.apk is installed
01:52:50.971 I: [gapidapk.EnsureInstalled⇒start] <gapis> Examining gapid.apk on host...
01:52:50.982 I: [gapidapk.EnsureInstalled⇒start] <gapis> Looking for gapid.apk...
01:52:51.424 I: [gapidapk.EnsureInstalled⇒start] <gapis> Found gapid package...
01:52:51.424 I: [start] <gapis> Forwarding
01:52:51.481 I: [start] <gapis> Starting activity in debug mode
01:53:02.285 I: [start] <gapis> Forwarding TCP port 53128 -> JDWP pid 4792
01:53:02.345 I: [start] <gapis> Connecting to JDWP
01:53:02.349 I: [start] <gapis> Failed to connect to the application: read tcp 127.0.0.1:53131->127.0.0.1:53128: wsarecv: An existing connection was forcibly closed by the remote host.. Retrying...
01:53:03.354 I: [start] <gapis> Failed to connect to the application: read tcp 127.0.0.1:53136->127.0.0.1:53128: wsarecv: An existing connection was forcibly closed by the remote host.. Retrying...
01:53:04.357 I: [start] <gapis> Failed to connect to the application: read tcp 127.0.0.1:53141->127.0.0.1:53128: wsarecv: An existing connection was forcibly closed by the remote host.. Retrying...
01:53:05.370 I: [start] <gapis> Failed to connect to the application: read tcp 127.0.0.1:53142->127.0.0.1:53128: wsarecv: An existing connection was forcibly closed by the remote host.. Retrying...
01:53:06.380 I: [start] <gapis> Failed to connect to the application: read tcp 127.0.0.1:53148->127.0.0.1:53128: wsarecv: An existing connection was forcibly closed by the remote host.. Retrying...
01:53:07.383 I: [start] <gapis> Failed to connect to the application: read tcp 127.0.0.1:53153->127.0.0.1:53128: wsarecv: An existing connection was forcibly closed by the remote host.. Retrying...
01:53:08.388 I: [start] <gapis> Failed to connect to the application: read tcp 127.0.0.1:53156->127.0.0.1:53128: wsarecv: An existing connection was forcibly closed by the remote host.. Retrying...
01:53:09.394 I: [start] <gapis> Failed to connect to the application: read tcp 127.0.0.1:53160->127.0.0.1:53128: wsarecv: An existing connection was forcibly closed by the remote host.. Retrying...
01:53:10.398 I: [start] <gapis> Failed to connect to the application: read tcp 127.0.0.1:53169->127.0.0.1:53128: wsarecv: An existing connection was forcibly closed by the remote host.. Retrying...
01:53:11.404 I: [start] <gapis> Failed to connect to the application: read tcp 127.0.0.1:53175->127.0.0.1:53128: wsarecv: An existing connection was forcibly closed by the remote host.. Retrying...
```

![gapid-fail-on-official-emulator-1](https://user-images.githubusercontent.com/90181/50429110-3a536900-08f7-11e9-9003-0a53a160a7f7.jpg)
![gapid-fail-on-official-emulator-2](https://user-images.githubusercontent.com/90181/50429112-3a536900-08f7-11e9-8aa1-9fd422294e9b.jpg)

**Comment by AWoloszyn** [comment]
Do you happen to have the output of `adb logcat`. That may help us figure out what is going on.

**Comment by AWoloszyn** [comment]
Closing, please add a comment if you happen to have more information, and I will re-open.
