### ISSUE TITLE
Tracing Failed   Cause: Could not start trace   Cause: Connecting to JDWP   Cause: read tcp 127.0.0.1:33224->127.0.0.1:34207: read: connection reset by peer

### ISSUE THREAD

**Issue by malk321** [google/gapid#2505]
GAPID Version: 1.2.1:9acb3d602489c7389134f043d4a1e9c12b6e3ff5
OS: linux amd64

Just can not debug any Android apk

com.google.gapid.server.Client$InternalServerErrorException: Tracing Failed
   Cause: Could not start trace
   Cause: Connecting to JDWP
   Cause: read tcp 127.0.0.1:52362->127.0.0.1:45105: read: connection reset by peer
	at com.google.gapid.server.Client.throwIfError(Client.java:290)
	at com.google.gapid.server.Client.lambda$streamTrace$49(Client.java:264)
	at com.google.gapid.server.GapidClientGrpc$StreamHandler.onNext(GapidClientGrpc.java:208)
	at io.grpc.stub.ClientCalls$StreamObserverToCallListenerAdapter.onMessage(ClientCalls.java:382)
	at io.grpc.internal.ClientCallImpl$ClientStreamListenerImpl$1MessageRead.runInContext(ClientCallImpl.java:458)
	at io.grpc.internal.ContextRunnable.run(ContextRunnable.java:52)
	at io.grpc.internal.SerializingExecutor$TaskRunner.run(SerializingExecutor.java:154)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: com.google.gapid.server.Client$Stack: For request: RPC->streamTrace()
	at com.google.gapid.server.Client.streamTrace(Client.java:261)
	at com.google.gapid.server.Tracer.trace(Tracer.java:41)
	at com.google.gapid.views.TracerDialog.showTracingDialog(TracerDialog.java:128)
	at com.google.gapid.views.WelcomeDialog$2.lambda$createDialogArea$4(WelcomeDialog.java:150)
	at org.eclipse.swt.widgets.EventTable.sendEvent(Unknown Source)
	at org.eclipse.swt.widgets.Display.sendEvent(Unknown Source)
	at org.eclipse.swt.widgets.Widget.sendEvent(Unknown Source)
	at org.eclipse.swt.widgets.Widget.sendEvent(Unknown Source)
	at org.eclipse.swt.widgets.Widget.sendSelectionEvent(Unknown Source)
	at org.eclipse.swt.widgets.Link.gtk_button_release_event(Unknown Source)
	at org.eclipse.swt.widgets.Widget.windowProc(Unknown Source)
	at org.eclipse.swt.widgets.Control.windowProc(Unknown Source)
	at org.eclipse.swt.widgets.Display.windowProc(Unknown Source)
	at org.eclipse.swt.internal.gtk.OS._gtk_main_do_event(Native Method)
	at org.eclipse.swt.internal.gtk.OS.gtk_main_do_event(Unknown Source)
	at org.eclipse.swt.widgets.Display.eventProc(Unknown Source)
	at org.eclipse.swt.internal.gtk.OS._g_main_context_iteration(Native Method)
	at org.eclipse.swt.internal.gtk.OS.g_main_context_iteration(Unknown Source)
	at org.eclipse.swt.widgets.Display.readAndDispatch(Unknown Source)
	at org.eclipse.jface.window.Window.runEventLoop(Window.java:818)
	at org.eclipse.jface.window.Window.open(Window.java:794)
	at com.google.gapid.views.WelcomeDialog.showWelcomeDialog(WelcomeDialog.java:174)
	at com.google.gapid.Main$UI.startUp(Main.java:151)
	at org.eclipse.swt.widgets.RunnableLock.run(Unknown Source)
	at org.eclipse.swt.widgets.Synchronizer.runAsyncMessages(Unknown Source)
	at org.eclipse.swt.widgets.Display.runAsyncMessages(Unknown Source)
	at org.eclipse.swt.widgets.Display.readAndDispatch(Unknown Source)
	at org.eclipse.jface.window.Window.runEventLoop(Window.java:818)
	at org.eclipse.jface.window.Window.open(Window.java:794)
	at com.google.gapid.Main$UI.show(Main.java:118)
	at com.google.gapid.Main.main(Main.java:73)

**Comment by pmuetschard** [comment]
Sorry for the late reply. Could you please try again on our latest version of GAPID and if it still fails could you please provide some more information like: what's the device? Android version? what app? what does `adb logcat` show?

**Comment by malk321** [comment]
Device: Oneplus
Android version: Android P
app: chrome, Gmail and any other app

here is log:
[log.txt](https://github.com/google/gapid/files/3016483/log.txt)

**Comment by pmuetschard** [comment]
From the log and the error above, it looks like GAPID cannot connect to the JDWP debugger on the device. I can see in the log references to the "waiting for debugger" dialog, but I do not see any error nor the standard debugger messages afterwards.

Note, you can only trace non-debuggable apps (such as GMail, Chrome or any other app from the Play Store) on userdebug builds. Can you try tracing an app you built from source and that has the debuggable flag set in the manifest?

**Comment by malk321** [comment]
Yes, I can trace debug app.
