### ISSUE TITLE
The gapis server has exited with an error code of: 2

### ISSUE THREAD

**Issue by yangtianrui95** [google/gapid#2506]
GAPID Version: 1.2.0:493d1ed1849d2196c5548268b041488e69f38479
OS: mac os x x86_64

Please provide detailed steps that led to the error and copy-paste the stack trace.
Extra details from the logs and the trace file would be extra helpful.

**Comment by yangtianrui95** [comment]
panic: (app.ExitCode) (0x7bcbfe0,0x8d0b4b0)

goroutine 376 [running]:
github.com/google/gapid/core/app.wrapHandler.func1(0xc429f1ab40)
	core/app/log.go:46 +0x8a
github.com/google/gapid/core/log.handler.Handle(0xc420211460, 0xc420211480, 0xc429f1ab40)
	core/log/handler.go:35 +0x30
github.com/google/gapid/core/log.(*Broadcaster).Handle(0xc42037f170, 0xc429f1ab40)
	core/log/broadcast.go:50 +0x92
github.com/google/gapid/core/log.(*Indirect).Handle(0xc2f1e60, 0xc429f1ab40)
	core/log/indirect.go:54 +0x58
github.com/google/gapid/core/log.(*Logger).Logf(0xc420162a00, 0x100000005, 0x89987b8, 0x29, 0xc420f804d0, 0x1, 0x1)
	core/log/log.go:108 +0xc0
github.com/google/gapid/core/log.(*Logger).F(0xc420162a00, 0x89987b8, 0x29, 0xcc9ed01, 0xc420f804d0, 0x1, 0x1)
	core/log/log.go:92 +0x6e
github.com/google/gapid/core/log.(*Logger).Fatalf(0xc420162a00, 0x89987b8, 0x29, 0xc420f804d0, 0x1, 0x1)
	core/log/log.go:180 +0x62
google.golang.org/grpc/grpclog.Fatalf(0x89987b8, 0x29, 0xc420f804d0, 0x1, 0x1)
	external/org_golang_google_grpc/grpclog/logger.go:72 +0x67
google.golang.org/grpc.(*Server).sendResponse(0xc420252820, 0x8df92a0, 0xc4200b20e0, 0xc420226b00, 0x8501de0, 0xc424166330, 0x8d48940, 0xc327790, 0xc4206bb4ac, 0x0, ...)
	external/org_golang_google_grpc/server.go:591 +0x162
google.golang.org/grpc.(*Server).processUnaryRPC(0xc420252820, 0x8df92a0, 0xc4200b20e0, 0xc420226b00, 0xc42048a810, 0xc2c6208, 0xc420fc1050, 0x0, 0x0)
	external/org_golang_google_grpc/server.go:744 +0xc41
google.golang.org/grpc.(*Server).handleStream(0xc420252820, 0x8df92a0, 0xc4200b20e0, 0xc420226b00, 0xc420fc1050)
	external/org_golang_google_grpc/server.go:905 +0x1052
google.golang.org/grpc.(*Server).serveStreams.func1.1(0xc420352010, 0xc420252820, 0x8df92a0, 0xc4200b20e0, 0xc420226b00)
	external/org_golang_google_grpc/server.go:478 +0x9f
created by google.golang.org/grpc.(*Server).serveStreams.func1
	external/org_golang_google_grpc/server.go:476 +0xa1

**Comment by yangtianrui95** [comment]
Here is the gfxtrace file.
[gfxtrace.zip](https://github.com/google/gapid/files/2718016/gfxtrace.zip)

**Comment by AWoloszyn** [comment]
We have made a bunch of changes from 1.2 to 1.5. Would you mind testing the latest?
