### ISSUE TITLE
Tracing Failed   Cause: Could not start trace   Cause: Installing gapid.apk   Cause: Installing gapid.apk   Cause: Process returned error   Cause: exit status 1

### ISSUE THREAD

**Issue by PatriceJiang** [google/gapid#2515]
GAPID Version: 1.2.1:9acb3d602489c7389134f043d4a1e9c12b6e3ff5
OS: mac os x x86_64
Device: Android 7, Mi Max2, MIUI 10 

1. can not list device, I had to manually install gapid.apk through `adb` command.
2. can not trace, installing 32bit apk doesn't help. 

alert dialog:
```
The application encountered an error:
Tracing Failed
   Cause: Could not start trace
   Cause: Installing gapid.apk
   Cause: Installing gapid.apk
   Cause: Process returned error
   Cause: exit status 1
```
log panel:

<img width="661" alt="screen shot 2019-01-04 at 9 30 24 am" src="https://user-images.githubusercontent.com/40414978/50669963-72e3f880-1003-11e9-9b39-08ac7ca3f29b.png">

stacktrace: 

```
com.google.gapid.server.Client$InternalServerErrorException: Tracing Failed
   Cause: Could not start trace
   Cause: Installing gapid.apk
   Cause: Installing gapid.apk
   Cause: Process returned error
   Cause: exit status 1
	at com.google.gapid.server.Client.throwIfError(Client.java:290)
	at com.google.gapid.server.Client.lambda$streamTrace$49(Client.java:264)
	at com.google.gapid.server.GapidClientGrpc$StreamHandler.onNext(GapidClientGrpc.java:208)
	at io.grpc.stub.ClientCalls$StreamObserverToCallListenerAdapter.onMessage(ClientCalls.java:382)
	at io.grpc.internal.ClientCallImpl$ClientStreamListenerImpl$1MessageRead.runInContext(ClientCallImpl.java:458)
	at io.grpc.internal.ContextRunnable.run(ContextRunnable.java:52)
	at io.grpc.internal.SerializingExecutor$TaskRunner.run(SerializingExecutor.java:154)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: com.google.gapid.server.Client$Stack: For request: RPC->streamTrace()
	at com.google.gapid.server.Client.streamTrace(Client.java:261)
	at com.google.gapid.server.Tracer.trace(Tracer.java:41)
	at com.google.gapid.views.TracerDialog.showTracingDialog(TracerDialog.java:128)
	at com.google.gapid.MainWindow.lambda$createFileMenu$11(MainWindow.java:318)
	at com.google.gapid.MainWindow$MenuItems$1.run(MainWindow.java:655)
	at org.eclipse.jface.action.Action.runWithEvent(Action.java:473)
	at org.eclipse.jface.action.ActionContributionItem.handleWidgetSelection(ActionContributionItem.java:565)
	at org.eclipse.jface.action.ActionContributionItem.lambda$4(ActionContributionItem.java:397)
	at org.eclipse.swt.widgets.EventTable.sendEvent(Unknown Source)
	at org.eclipse.swt.widgets.Display.sendEvent(Unknown Source)
	at org.eclipse.swt.widgets.Widget.sendEvent(Unknown Source)
	at org.eclipse.swt.widgets.Widget.sendEvent(Unknown Source)
	at org.eclipse.swt.widgets.Widget.sendEvent(Unknown Source)
	at org.eclipse.swt.widgets.Widget.notifyListeners(Unknown Source)
	at org.eclipse.swt.widgets.Display.runDeferredEvents(Unknown Source)
	at org.eclipse.swt.widgets.Display.readAndDispatch(Unknown Source)
	at org.eclipse.jface.window.Window.runEventLoop(Window.java:818)
	at org.eclipse.jface.window.Window.open(Window.java:794)
	at com.google.gapid.Main$UI.show(Main.java:118)
	at com.google.gapid.Main.main(Main.java:73)

```

**Comment by PatriceJiang** [comment]
`adb install -g -r /Applications/GAPID.app/Contents/MacOS/gapid-armeabi.apk `

reports error: 

```
adb: failed to install /Applications/GAPID.app//Contents/MacOS/gapid-armeabi.apk: Security exception: You need the android.permission.INSTALL_GRANT_RUNTIME_PERMISSIONS permission to use the PackageManager.INSTALL_GRANT_RUNTIME_PERMISSIONS flag

java.lang.SecurityException: You need the android.permission.INSTALL_GRANT_RUNTIME_PERMISSIONS permission to use the PackageManager.INSTALL_GRANT_RUNTIME_PERMISSIONS flag
	at com.android.server.pm.PackageInstallerService.createSessionInternal(PackageInstallerService.java:601)
	at com.android.server.pm.PackageInstallerService.createSession(PackageInstallerService.java:571)
	at com.android.server.pm.PackageManagerShellCommand.doCreateSession(PackageManagerShellCommand.java:1172)
	at com.android.server.pm.PackageManagerShellCommand.runInstall(PackageManagerShellCommand.java:168)
	at com.android.server.pm.PackageManagerShellCommand.onCommand(PackageManagerShellCommand.java:99)
	at android.os.ShellCommand.exec(ShellCommand.java:94)
	at com.android.server.pm.PackageManagerService.onShellCommand(PackageManagerService.java:19220)
	at android.os.Binder.she
```

**Comment by AWoloszyn** [comment]
It looks like you need some settings on your phone updated.
Developer Options:
  Install via USB - Allow installing apps via USB
  USB debugging (Security Settings)- Allow granting permissions and simulating input via USB debugging

**Comment by AWoloszyn** [comment]
Please comment on this issue if it is still a problem.
