### ISSUE TITLE
Unhandled exception in the UI thread.

### ISSUE THREAD

**Issue by paulthomson** [google/gapid#2557]
GAPID Version: 1.2.1:developer
OS: linux amd64

I had searched for "texture" in the commands panel. I clicked on a few commands. Not really sure what happened. This is running a debug build so might be slower than normal. 

```
org.eclipse.swt.SWTException: Failed to execute runnable (java.lang.IllegalStateException: Querying children before loaded)
	at org.eclipse.swt.SWT.error(SWT.java:4595)
	at org.eclipse.swt.SWT.error(SWT.java:4510)
	at org.eclipse.swt.widgets.Synchronizer.runAsyncMessages(Synchronizer.java:188)
	at org.eclipse.swt.widgets.Display.runAsyncMessages(Display.java:5026)
	at org.eclipse.swt.widgets.Display.readAndDispatch(Display.java:4586)
	at org.eclipse.jface.window.Window.runEventLoop(Window.java:821)
	at org.eclipse.jface.window.Window.open(Window.java:797)
	at com.google.gapid.Main$UI.show(Main.java:119)
	at com.google.gapid.Main.main(Main.java:68)
Caused by: java.lang.IllegalStateException: Querying children before loaded
	at com.google.common.base.Preconditions.checkState(Preconditions.java:507)
	at com.google.gapid.models.ApiState$Node.getOrCreateChildren(ApiState.java:212)
	at com.google.gapid.models.ApiState$Node.getChildren(ApiState.java:207)
	at com.google.gapid.views.StateView$StateTree$1.getChildNodes(StateView.java:349)
	at com.google.gapid.views.StateView$StateTree$1.getChildNodes(StateView.java:341)
	at com.google.gapid.widgets.LinkifiedTree$ContentProvider.getChildren(LinkifiedTree.java:250)
	at org.eclipse.jface.viewers.AbstractTreeViewer.getRawChildren(AbstractTreeViewer.java:1422)
	at org.eclipse.jface.viewers.TreeViewer.getRawChildren(TreeViewer.java:350)
	at org.eclipse.jface.viewers.StructuredViewer.getFilteredChildren(StructuredViewer.java:903)
	at org.eclipse.jface.viewers.AbstractTreeViewer.getSortedChildren(AbstractTreeViewer.java:621)
	at org.eclipse.jface.viewers.AbstractTreeViewer.createChildren(AbstractTreeViewer.java:815)
	at org.eclipse.jface.viewers.TreeViewer.createChildren(TreeViewer.java:604)
	at org.eclipse.jface.viewers.AbstractTreeViewer.createChildren(AbstractTreeViewer.java:766)
	at org.eclipse.jface.viewers.AbstractTreeViewer.setExpandedState(AbstractTreeViewer.java:2518)
	at com.google.gapid.widgets.LinkifiedTree.setExpandedState(LinkifiedTree.java:188)
	at com.google.gapid.views.StateView.setExpanded(StateView.java:281)
	at com.google.gapid.views.StateView$2.onUiThread(StateView.java:274)
	at com.google.gapid.views.StateView$2.onUiThread(StateView.java:264)
	at com.google.gapid.rpc.UiCallback.lambda$onFinish$0(UiCallback.java:46)
	at com.google.gapid.widgets.Widgets.ifNotDisposed(Widgets.java:119)
	at com.google.gapid.widgets.Widgets.lambda$scheduleIfNotDisposed$1(Widgets.java:147)
	at com.google.gapid.widgets.Widgets.lambda$schedule$0(Widgets.java:139)
	at org.eclipse.swt.widgets.RunnableLock.run(RunnableLock.java:40)
	at org.eclipse.swt.widgets.Synchronizer.runAsyncMessages(Synchronizer.java:185)
	... 6 more

```

**Comment by paulthomson** [comment]
OK I can just keep clicking on two adjacent commands and I eventually get another error:

```
org.eclipse.swt.SWTException: Failed to execute runnable (java.lang.NullPointerException)
	at org.eclipse.swt.SWT.error(SWT.java:4595)
	at org.eclipse.swt.SWT.error(SWT.java:4510)
	at org.eclipse.swt.widgets.Synchronizer.runAsyncMessages(Synchronizer.java:188)
	at org.eclipse.swt.widgets.Display.runAsyncMessages(Display.java:5026)
	at org.eclipse.swt.widgets.Display.readAndDispatch(Display.java:4586)
	at org.eclipse.jface.window.Window.runEventLoop(Window.java:821)
	at org.eclipse.jface.window.Window.open(Window.java:797)
	at com.google.gapid.Main$UI.show(Main.java:119)
	at com.google.gapid.Main.main(Main.java:68)
Caused by: java.lang.NullPointerException
	at com.google.gapid.views.StateView.updateExpansionState(StateView.java:252)
	at com.google.gapid.views.StateView.setExpanded(StateView.java:284)
	at com.google.gapid.views.StateView$2.onUiThread(StateView.java:274)
	at com.google.gapid.views.StateView$2.onUiThread(StateView.java:264)
	at com.google.gapid.rpc.UiCallback.lambda$onFinish$0(UiCallback.java:46)
	at com.google.gapid.widgets.Widgets.ifNotDisposed(Widgets.java:119)
	at com.google.gapid.widgets.Widgets.lambda$scheduleIfNotDisposed$1(Widgets.java:147)
	at com.google.gapid.widgets.Widgets.lambda$schedule$0(Widgets.java:139)
	at org.eclipse.swt.widgets.RunnableLock.run(RunnableLock.java:40)
	at org.eclipse.swt.widgets.Synchronizer.runAsyncMessages(Synchronizer.java:185)
	... 6 more

```

**Comment by paulthomson** [comment]
Commit hash: 8f82279e76320114a63fed44c88b19a25162a4cf
I ran with: `bazel run -c dbg //cmd/gapid`
Then I clicked on lots of different adjacent commands.

Trace file and apk shared offline in "GapidTraces" prefixed with "ui-exception-".
