### ISSUE TITLE
Failed to load image

### ISSUE THREAD

**Issue by stolk** [google/gapid#2579]
My Android app is misbehaving on the Emulator, so I thought I would analyze it w gapid.

I can capture a trace, but when trying to analyze:
```
Couldn't get framebuffer attachment
Cause: communicating with gapir
Cause: recv
Cause: rpc error: code = 13 desc = transport is closing
```

With latest prebuild linux version.

logcat:
```
W20190131-113036515[grpc-default-executor-0][util.Logging.throttleLogRpcError] Failed to load image
W20190131-113036515[grpc-default-executor-0][util.Logging.throttleLogRpcError] com.google.gapid.server.Client$InternalServerErrorException: Couldn't get framebuffer attachment
   Cause: Communicating with gapir
   Cause: Recv
   Cause: rpc error: code = 13 desc = transport is closing
W20190131-113036515[grpc-default-executor-0][util.Logging.throttleLogRpcError] 	at com.google.gapid.server.Client.throwIfError(Client.java:290)
W20190131-113036515[grpc-default-executor-0][util.Logging.throttleLogRpcError] 	at com.google.gapid.server.Client.lambda$get$7(Client.java:98)
W20190131-113036515[grpc-default-executor-0][util.Logging.throttleLogRpcError] 	at com.google.common.util.concurrent.AbstractTransformFuture$AsyncTransformFuture.doTransform(AbstractTransformFuture.java:211)
W20190131-113036515[grpc-default-executor-0][util.Logging.throttleLogRpcError] 	at com.google.common.util.concurrent.AbstractTransformFuture$AsyncTransformFuture.doTransform(AbstractTransformFuture.java:200)
W20190131-113036515[grpc-default-executor-0][util.Logging.throttleLogRpcError] 	at com.google.common.util.concurrent.AbstractTransformFuture.run(AbstractTransformFuture.java:130)
W20190131-113036515[grpc-default-executor-0][util.Logging.throttleLogRpcError] 	at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:435)
W20190131-113036515[grpc-default-executor-0][util.Logging.throttleLogRpcError] 	at com.google.common.util.concurrent.AbstractFuture.executeListener(AbstractFuture.java:900)
W20190131-113036515[grpc-default-executor-0][util.Logging.throttleLogRpcError] 	at com.google.common.util.concurrent.AbstractFuture.complete(AbstractFuture.java:811)
W20190131-113036515[grpc-default-executor-0][util.Logging.throttleLogRpcError] 	at com.google.common.util.concurrent.AbstractFuture.set(AbstractFuture.java:653)
W20190131-113036515[grpc-default-executor-0][util.Logging.throttleLogRpcError] 	at com.google.common.util.concurrent.AbstractTransformFuture$TransformFuture.setResult(AbstractTransformFuture.java:245)
W20190131-113036515[grpc-default-executor-0][util.Logging.throttleLogRpcError] 	at com.google.common.util.concurrent.AbstractTransformFuture.run(AbstractTransformFuture.java:177)
W20190131-113036515[grpc-default-executor-0][util.Logging.throttleLogRpcError] 	at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:435)
W20190131-113036515[grpc-default-executor-0][util.Logging.throttleLogRpcError] 	at com.google.common.util.concurrent.AbstractFuture.executeListener(AbstractFuture.java:900)
W20190131-113036515[grpc-default-executor-0][util.Logging.throttleLogRpcError] 	at com.google.common.util.concurrent.AbstractFuture.complete(AbstractFuture.java:811)
W20190131-113036515[grpc-default-executor-0][util.Logging.throttleLogRpcError] 	at com.google.common.util.concurrent.AbstractFuture.set(AbstractFuture.java:653)
W20190131-113036515[grpc-default-executor-0][util.Logging.throttleLogRpcError] 	at io.grpc.stub.ClientCalls$GrpcFuture.set(ClientCalls.java:461)
W20190131-113036515[grpc-default-executor-0][util.Logging.throttleLogRpcError] 	at io.grpc.stub.ClientCalls$UnaryStreamToFuture.onClose(ClientCalls.java:440)
W20190131-113036515[grpc-default-executor-0][util.Logging.throttleLogRpcError] 	at io.grpc.internal.ClientCallImpl$ClientStreamListenerImpl.close(ClientCallImpl.java:481)
W20190131-113036515[grpc-default-executor-0][util.Logging.throttleLogRpcError] 	at io.grpc.internal.ClientCallImpl$ClientStreamListenerImpl.access$600(ClientCallImpl.java:398)
W20190131-113036515[grpc-default-executor-0][util.Logging.throttleLogRpcError] 	at io.grpc.internal.ClientCallImpl$ClientStreamListenerImpl$1StreamClosed.runInContext(ClientCallImpl.java:513)
W20190131-113036515[grpc-default-executor-0][util.Logging.throttleLogRpcError] 	at io.grpc.internal.ContextRunnable.run(ContextRunnable.java:52)
W20190131-113036515[grpc-default-executor-0][util.Logging.throttleLogRpcError] 	at io.grpc.internal.SerializingExecutor$TaskRunner.run(SerializingExecutor.java:154)
W20190131-113036515[grpc-default-executor-0][util.Logging.throttleLogRpcError] 	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1135)
W20190131-113036515[grpc-default-executor-0][util.Logging.throttleLogRpcError] 	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
W20190131-113036515[grpc-default-executor-0][util.Logging.throttleLogRpcError] 	at java.base/java.lang.Thread.run(Thread.java:844)
W20190131-113036515[grpc-default-executor-0][util.Logging.throttleLogRpcError] Caused by: com.google.gapid.server.Client$Stack: For request: RPC->get(blob { ID { data: 977ab8f486bc215ca0e7cf975f739ade9d7a7e24 } }, ID { data: b84b880985fc47747f48784b39689772d1fc0b04 })
W20190131-113036515[grpc-default-executor-0][util.Logging.throttleLogRpcError] 	at com.google.gapid.server.Client.call(Client.java:274)
W20190131-113036515[grpc-default-executor-0][util.Logging.throttleLogRpcError] 	at com.google.gapid.server.Client.get(Client.java:90)
W20190131-113036515[grpc-default-executor-0][util.Logging.throttleLogRpcError] 	at com.google.gapid.image.FetchedImage$SingleFacedLevel.doLoad(FetchedImage.java:394)
W20190131-113036515[grpc-default-executor-0][util.Logging.throttleLogRpcError] 	at com.google.gapid.image.FetchedImage$Level.get(FetchedImage.java:323)
W20190131-113036515[grpc-default-executor-0][util.Logging.throttleLogRpcError] 	at com.google.gapid.image.FetchedImage$Layer.getImage(FetchedImage.java:282)
W20190131-113036515[grpc-default-executor-0][util.Logging.throttleLogRpcError] 	at com.google.gapid.image.FetchedImage.getImage(FetchedImage.java:257)
W20190131-113036515[grpc-default-executor-0][util.Logging.throttleLogRpcError] 	at com.google.gapid.image.FetchedImage.lambda$loadImage$6(FetchedImage.java:117)
W20190131-113036515[grpc-default-executor-0][util.Logging.throttleLogRpcError] 	at com.google.common.util.concurrent.AbstractTransformFuture$AsyncTransformFuture.doTransform(AbstractTransformFuture.java:211)
W20190131-113036515[grpc-default-executor-0][util.Logging.throttleLogRpcError] 	at com.google.common.util.concurrent.AbstractTransformFuture$AsyncTransformFuture.doTransform(AbstractTransformFuture.java:200)
W20190131-113036515[grpc-default-executor-0][util.Logging.throttleLogRpcError] 	at com.google.common.util.concurrent.AbstractTransformFuture.run(AbstractTransformFuture.java:130)
W20190131-113036515[grpc-default-executor-0][util.Logging.throttleLogRpcError] 	at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:435)
W20190131-113036515[grpc-default-executor-0][util.Logging.throttleLogRpcError] 	at com.google.common.util.concurrent.AbstractFuture.executeListener(AbstractFuture.java:900)
W20190131-113036515[grpc-default-executor-0][util.Logging.throttleLogRpcError] 	at com.google.common.util.concurrent.AbstractFuture.complete(AbstractFuture.java:811)
W20190131-113036515[grpc-default-executor-0][util.Logging.throttleLogRpcError] 	at com.google.common.util.concurrent.AbstractFuture.set(AbstractFuture.java:653)
W20190131-113036515[grpc-default-executor-0][util.Logging.throttleLogRpcError] 	at com.google.common.util.concurrent.AbstractTransformFuture$TransformFuture.setResult(AbstractTransformFuture.java:245)
W20190131-113036515[grpc-default-executor-0][util.Logging.throttleLogRpcError] 	at com.google.common.util.concurrent.AbstractTransformFuture.run(AbstractTransformFuture.java:177)
W20190131-113036515[grpc-default-executor-0][util.Logging.throttleLogRpcError] 	at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:435)
W20190131-113036515[grpc-default-executor-0][util.Logging.throttleLogRpcError] 	at com.google.common.util.concurrent.AbstractFuture.executeListener(AbstractFuture.java:900)
W20190131-113036515[grpc-default-executor-0][util.Logging.throttleLogRpcError] 	at com.google.common.util.concurrent.AbstractFuture.complete(AbstractFuture.java:811)
W20190131-113036515[grpc-default-executor-0][util.Logging.throttleLogRpcError] 	at com.google.common.util.concurrent.AbstractFuture.setFuture(AbstractFuture.java:711)
W20190131-113036515[grpc-default-executor-0][util.Logging.throttleLogRpcError] 	at com.google.common.util.concurrent.AbstractTransformFuture$AsyncTransformFuture.setResult(AbstractTransformFuture.java:221)
W20190131-113036515[grpc-default-executor-0][util.Logging.throttleLogRpcError] 	at com.google.common.util.concurrent.AbstractTransformFuture$AsyncTransformFuture.setResult(AbstractTransformFuture.java:200)
W20190131-113036515[grpc-default-executor-0][util.Logging.throttleLogRpcError] 	at com.google.common.util.concurrent.AbstractTransformFuture.run(AbstractTransformFuture.java:177)
W20190131-113036515[grpc-default-executor-0][util.Logging.throttleLogRpcError] 	... 20 more

```

**Comment by AWoloszyn** [comment]
Is there anything interesting in
`adb logcat` ? It looks like the replay crashed, but not much other information in that callstack.

**Comment by stolk** [comment]
Also, I can report that it can retrieve all the colour textures, but not the depth texture:
![image](https://user-images.githubusercontent.com/455280/52081721-d3594d80-254f-11e9-98fa-006315d706b2.png)

**Comment by stolk** [comment]
> Is there anything interesting in
> `adb logcat` ? It looks like the replay crashed, but not much other information in that callstack.

Ah, I also found:

`adbd    : failed to connect to socket 'localfilesystem:/data/data/com.google.android.gapid.x86/files/gapir-x86': Permission denied`

**Comment by AWoloszyn** [comment]
https://github.com/google/gapid/releases/tag/v1.3.1 was just release, and should help fix this issue. If there is still a problem let me know and I will re-open.
