### ISSUE TITLE
Unhandled exception in the UI thread.

### ISSUE THREAD

**Issue by kaizer1** [google/gapid#2587]
GAPID Version: 1.3.1:44c6681a66df5e84e2cd8e56fbd8f968be2fafd6
OS: mac os x x86_64

Please provide detailed steps that led to the error and copy-paste the stack trace.
Extra details from the logs and the trace file would be extra helpful.

My Trace : 
java.lang.NullPointerException
	at com.google.gapid.widgets.TabArea.layoutComputeSize(TabArea.java:344)
	at com.google.gapid.widgets.TabArea$1.computeSize(TabArea.java:68)
	at org.eclipse.swt.widgets.Composite.computeSize(Composite.java:229)
	at org.eclipse.swt.layout.FormData.computeSize(FormData.java:120)
	at org.eclipse.swt.layout.FormData.getWidth(FormData.java:149)
	at org.eclipse.swt.layout.FormData.getRightAttachment(FormData.java:250)
	at org.eclipse.swt.layout.FormLayout.computeWidth(FormLayout.java:271)
	at org.eclipse.swt.layout.FormLayout.layout(FormLayout.java:338)
	at org.eclipse.swt.layout.FormLayout.computeSize(FormLayout.java:245)
	at org.eclipse.swt.widgets.Composite.computeSize(Composite.java:229)
	at org.eclipse.swt.layout.GridData.computeSize(GridData.java:494)
	at org.eclipse.swt.layout.GridLayout.layout(GridLayout.java:224)
	at org.eclipse.swt.layout.GridLayout.computeSize(GridLayout.java:167)
	at org.eclipse.swt.widgets.Composite.computeSize(Composite.java:229)
	at org.eclipse.swt.custom.StackLayout.computeSize(StackLayout.java:101)
	at org.eclipse.swt.widgets.Composite.computeSize(Composite.java:229)
	at org.eclipse.swt.custom.StackLayout.computeSize(StackLayout.java:101)
	at org.eclipse.swt.widgets.Composite.computeSize(Composite.java:229)
	at org.eclipse.swt.layout.GridData.computeSize(GridData.java:494)
	at org.eclipse.swt.layout.GridLayout.layout(GridLayout.java:224)
	at org.eclipse.swt.layout.GridLayout.layout(GridLayout.java:200)
	at org.eclipse.swt.widgets.Composite.updateLayout(Composite.java:1267)
	at org.eclipse.swt.widgets.Composite.updateLayout(Composite.java:1273)
	at org.eclipse.swt.widgets.Composite.setLayoutDeferred(Composite.java:1143)
	at org.eclipse.swt.widgets.Display.runDeferredLayouts(Display.java:4140)
	at org.eclipse.swt.widgets.Display.readAndDispatch(Display.java:3719)
	at org.eclipse.jface.window.Window.runEventLoop(Window.java:821)
	at org.eclipse.jface.window.Window.open(Window.java:797)
	at com.google.gapid.views.ErrorDialog.showErrorDialog(ErrorDialog.java:161)
	at com.google.gapid.views.ErrorDialog.showErrorDialog(ErrorDialog.java:62)
	at com.google.gapid.Main$UI.lambda$registerWindowExceptionHandler$0(Main.java:113)
	at org.eclipse.jface.window.Window.runEventLoop(Window.java:825)
	at org.eclipse.jface.window.Window.open(Window.java:797)
	at com.google.gapid.Main$UI.show(Main.java:119)
	at com.google.gapid.Main.main(Main.java:68)

Error pops up at the entrance to the program, enter and fails. After I close with an error, the program stops (hangs)

**Comment by pmuetschard** [comment]
This is the same as #2624
