### ISSUE TITLE
Replay of Vulkan Bloom Sample Crashes

### ISSUE THREAD

**Issue by pmuetschard** [google/gapid#2597]
Replaying a simple trace of the bloom sample crashes in the dependency graph:
[trace.zip](https://github.com/google/gapid/files/2850657/trace.zip)

```
panic: runtime error: invalid memory address or nil pointer dereference [recovered]
	panic: Panic at command 657:vkQueueSubmit(queue: 3728921136, submitCount: 1, pSubmits: 0xde46b74c, fence: 0) → VK_SUCCESS:
runtime error: invalid memory address or nil pointer dereference [recovered]
	panic: 
--- *dependencygraph2.DependencyGraph2Resolvable ---
 capture:<ID:<data:"\327%\211\225\375\252\340S\247\212\221\360\007gV\031\224\313\001\266" > > mergeSubCmdNodes:true 
 Store():
  gapis/database/database.go:55  github.com/google/gapid/gapis/database.Build
  gapis/resolve/dependencygraph2/resolvables.go:29  github.com/google/gapid/gapis/resolve/dependencygraph2.GetDependencyGraph
  gapis/server/server.go:258  github.com/google/gapid/gapis/server.(*server).LoadCapture.func1
  core/app/crash/crash.go:65  github.com/google/gapid/core/app/crash.Go.func1

 Build() #0:
  gapis/database/database.go:59  github.com/google/gapid/gapis/database.Build
  gapis/resolve/dependencygraph2/resolvables.go:29  github.com/google/gapid/gapis/resolve/dependencygraph2.GetDependencyGraph
  gapis/server/server.go:258  github.com/google/gapid/gapis/server.(*server).LoadCapture.func1
  core/app/crash/crash.go:65  github.com/google/gapid/core/app/crash.Go.func1
 [recovered]
	panic: 
--- *dependencygraph2.DependencyGraph2Resolvable ---
 capture:<ID:<data:"\327%\211\225\375\252\340S\247\212\221\360\007gV\031\224\313\001\266" > > mergeSubCmdNodes:true 
 Store():
  gapis/database/database.go:55  github.com/google/gapid/gapis/database.Build
  gapis/resolve/dependencygraph2/resolvables.go:29  github.com/google/gapid/gapis/resolve/dependencygraph2.GetDependencyGraph
  gapis/server/server.go:258  github.com/google/gapid/gapis/server.(*server).LoadCapture.func1
  core/app/crash/crash.go:65  github.com/google/gapid/core/app/crash.Go.func1

 Build() #0:
  gapis/database/database.go:59  github.com/google/gapid/gapis/database.Build
  gapis/resolve/dependencygraph2/resolvables.go:29  github.com/google/gapid/gapis/resolve/dependencygraph2.GetDependencyGraph
  gapis/server/server.go:258  github.com/google/gapid/gapis/server.(*server).LoadCapture.func1
  core/app/crash/crash.go:65  github.com/google/gapid/core/app/crash.Go.func1

[signal SIGSEGV: segmentation violation code=0x1 addr=0x10 pc=0x62b6947]

goroutine 434 [running]:
github.com/google/gapid/core/app/crash.Crash(0x8c6b7a0, 0xc000b0bab0)
	core/app/crash/crash.go:89 +0xa7
github.com/google/gapid/core/app/crash.handler()
	core/app/crash/crash.go:56 +0x52
panic(0x8c6b7a0, 0xc000b0bab0)
	GOROOT/src/runtime/panic.go:513 +0x1b9
github.com/google/gapid/gapis/database.(*memory).resolvePanicHandler(0xc0002eeae0, 0x9e7fa80, 0xc000452270)
	gapis/database/debug.go:106 +0x7af
panic(0x8cb4300, 0xc000b0b900)
	GOROOT/src/runtime/panic.go:513 +0x1b9
github.com/google/gapid/gapis/api.ForeachCmd.func1(0xc00005fd18, 0xc00005fd48)
	gapis/api/cmd_foreach.go:43 +0x152
panic(0x8e0ce80, 0xe9ab950)
	GOROOT/src/runtime/panic.go:513 +0x1b9
github.com/google/gapid/gapis/api/vulkan.ImageAspectʳ.Layersʷ(0x0, 0x0, 0x9e7fa80, 0xc000453170, 0x9ec6de0, 0xc0002166e0, 0xc000216601, 0x400345001, 0x0, 0x0)
	bazel-out/darwin-fastbuild/genfiles/gapis/api/vulkan/api.go:64310 +0x37
github.com/google/gapid/gapis/api/vulkan.subAccessImageSubresourceSlice(0x9e7fa80, 0xc000453170, 0x9ec6220, 0xc00092a4e0, 0x291, 0xc0010a83f0, 0xc000207f10, 0xc000174900, 0xc66d2230, 0x0, ...)
	bazel-out/darwin-fastbuild/genfiles/gapis/api/vulkan/mutate.go:1066 +0x13d2
github.com/google/gapid/gapis/api/vulkan.subAccessImageSubresource(0x9e7fa80, 0xc000453170, 0x9ec6220, 0xc00092a4e0, 0x291, 0xc0010a83f0, 0xc000207f10, 0xc000174900, 0xc66d2230, 0x0, ...)
	bazel-out/darwin-fastbuild/genfiles/gapis/api/vulkan/mutate.go:1122 +0x146
github.com/google/gapid/gapis/api/vulkan.subAccessImageView(0x9e7fa80, 0xc000453170, 0x9ec6220, 0xc00092a4e0, 0x291, 0xc0010a83f0, 0xc000207f10, 0xc000174900, 0xc66d2230, 0x0, ...)
	bazel-out/darwin-fastbuild/genfiles/gapis/api/vulkan/mutate.go:1163 +0x8e1
github.com/google/gapid/gapis/api/vulkan.subWriteImageView(0x9e7fa80, 0xc000453170, 0x9ec6220, 0xc00092a4e0, 0x291, 0xc0010a83f0, 0xc000207f10, 0xc000174900, 0xc66d2230, 0x0, ...)
	bazel-out/darwin-fastbuild/genfiles/gapis/api/vulkan/mutate.go:1180 +0xf0
github.com/google/gapid/gapis/api/vulkan.subLoadImageAttachment(0x9e7fa80, 0xc000453170, 0x9ec6220, 0xc00092a4e0, 0x291, 0xc0010a83f0, 0xc000207f10, 0xc000174900, 0xc66d2230, 0x0, ...)
	bazel-out/darwin-fastbuild/genfiles/gapis/api/vulkan/mutate.go:5323 +0x908
github.com/google/gapid/gapis/api/vulkan.subDovkCmdBeginRenderPass(0x9e7fa80, 0xc000453170, 0x9ec6220, 0xc00092a4e0, 0x291, 0xc0010a83f0, 0xc000207f10, 0xc000174900, 0xc66d2230, 0x0, ...)
	bazel-out/darwin-fastbuild/genfiles/gapis/api/vulkan/mutate.go:5219 +0x6d4
github.com/google/gapid/gapis/api/vulkan.subCallCommand(0x9e7fa80, 0xc000453170, 0x9ec6220, 0xc00092a4e0, 0x291, 0xc0010a83f0, 0xc000207f10, 0xc000174900, 0xc66d2230, 0x0, ...)
	bazel-out/darwin-fastbuild/genfiles/gapis/api/vulkan/mutate.go:5161 +0x9773
github.com/google/gapid/gapis/api/vulkan.subExecPendingCommands(0x9e7fa80, 0xc000453170, 0x9ec6220, 0xc00092a4e0, 0x291, 0xc0010a83f0, 0xc000207f10, 0xc000174900, 0xc66d2230, 0x0, ...)
	bazel-out/darwin-fastbuild/genfiles/gapis/api/vulkan/mutate.go:4973 +0x4cb8
github.com/google/gapid/gapis/api/vulkan.(*VkQueueSubmit).Mutate(0xc00092a4e0, 0x9e7fa80, 0xc000453170, 0x291, 0xc000207f10, 0x0, 0x9ec6de0, 0xc0002166e0, 0x0, 0x0)
	bazel-out/darwin-fastbuild/genfiles/gapis/api/vulkan/mutate.go:16446 +0x551a
github.com/google/gapid/gapis/resolve/dependencygraph2.BuildDependencyGraph.func1(0x9e7fa80, 0xc000453170, 0x291, 0x9ec6220, 0xc00092a4e0, 0x0, 0x0)
	gapis/resolve/dependencygraph2/dependency_graph_builder.go:344 +0x7d
github.com/google/gapid/gapis/api.ForeachCmd(0x9e7fa80, 0xc000452db0, 0xc0007d0000, 0x331, 0x400, 0xc0004502c0, 0x0, 0x0)
	gapis/api/cmd_foreach.go:54 +0x270
github.com/google/gapid/gapis/resolve/dependencygraph2.BuildDependencyGraph(0x9e7fa80, 0xc000452420, 0xc000000001, 0xc000650240, 0xea55338, 0x0, 0x0, 0xea55338, 0x0, 0x0, ...)
	gapis/resolve/dependencygraph2/dependency_graph_builder.go:353 +0x2e5
github.com/google/gapid/gapis/resolve/dependencygraph2.(*DependencyGraph2Resolvable).Resolve(0xc000452150, 0x9e7fa80, 0xc000452360, 0xc000452360, 0xc0000e3f18, 0x2, 0x2)
	gapis/resolve/dependencygraph2/resolvables.go:76 +0x137
github.com/google/gapid/gapis/database.(*record).resolve(0xc000724120, 0x9e7fa80, 0xc000452360, 0x0, 0x0)
	gapis/database/memory.go:134 +0x228
github.com/google/gapid/gapis/database.(*memory).resolveLocked.func1()
	gapis/database/memory.go:238 +0xcc
github.com/google/gapid/core/app/crash.Go.func1(0xc000452210)
	core/app/crash/crash.go:65 +0x43
created by github.com/google/gapid/core/app/crash.Go
	core/app/crash/crash.go:63 +0x3f
```

**Comment by AWoloszyn** [comment]
https://github.com/google/gapid/pull/2601 Should fix this issue

**Comment by pmuetschard** [comment]
I think it did fix it.
