### ISSUE TITLE
The gapis server has exited with an error code of: 2

### ISSUE THREAD

**Issue by hevrard** [google/gapid#2620]
GAPID Version: 1.5.0:developer
OS: linux amd64

Reproduction steps:
- tracing the graphicsfuzz vulkan worker, asking for **10 frames** (the app produces only 5 frames)
- open capture

Maybe this appears when we request more frames than the app produces?

```
panic: runtime error: invalid memory address or nil pointer dereference [recovered]
	panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0xf74ed2]

goroutine 80 [running]:
github.com/google/gapid/core/app/crash.Crash(0x5f65500, 0xbfc65f0)
	core/app/crash/crash.go:89 +0xe1
github.com/google/gapid/core/app/crash.handler()
	core/app/crash/crash.go:56 +0x54
panic(0x5f65500, 0xbfc65f0)
	GOROOT/src/runtime/panic.go:513 +0x1b9
github.com/google/gapid/gapir/client.(*Connection).Shutdown(0x0, 0x71a1180, 0xc005f46f00, 0x0, 0x0)
	gapir/client/connection.go:117 +0x42
github.com/google/gapid/gapir/client.(*session).close(0xc000613e50, 0x71a1180, 0xc005f46f00)
	gapir/client/session.go:377 +0x4c
github.com/google/gapid/gapir/client.(*session).init(0xc000613e50, 0x71a1180, 0xc005f46f00, 0x71e83a0, 0xc0000efa10, 0xc000100200, 0x0, 0x0, 0x0, 0x0, ...)
	gapir/client/session.go:80 +0x1c3
github.com/google/gapid/gapir/client.(*Client).Connect(0xc0000ef670, 0x71a1180, 0xc005f46f00, 0x71e83a0, 0xc0000efa10, 0xc000100200, 0x0, 0x0, 0x0)
	gapir/client/client.go:66 +0x37f
github.com/google/gapid/gapis/replay.(*manager).connect(0xc00000df80, 0x71a1180, 0xc005f46e40, 0x71e83a0, 0xc0000efa10, 0xc000100200, 0x0, 0x0, 0x0)
	gapis/replay/replay_connection.go:180 +0x24e
github.com/google/gapid/gapis/replay.(*manager).execute(0xc00000df80, 0x71a1180, 0xc005f46e40, 0x71e83a0, 0xc0000efa10, 0xe17bebb8b73d1771, 0xa8fdcc7bca999dc5, 0xec8c272f17de7e05, 0x5b00f0bb3c6c82e6, 0x8cd498d92e1b7b5c, ...)
	gapis/replay/batch.go:270 +0xa66
github.com/google/gapid/gapis/replay.(*manager).batch.func1(0x71e83a0, 0xc0000efa10, 0xc0002f8290, 0x3c6c82e6ec8c272f, 0x2e1b7b5c5b00f0bb, 0xb73d17718cd498d9, 0xca999dc5e17bebb8, 0x17de7e05a8fdcc7b, 0x6517220, 0xc005eafce0, ...)
	gapis/replay/batch.go:86 +0x551
github.com/google/gapid/gapis/replay.(*manager).batch(0xc00000df80, 0x71a1180, 0xc005f4c180, 0xc0004d2820, 0x5, 0x5, 0x6495020, 0x70ac870, 0x64c2100, 0xc00012ef00, ...)
	gapis/replay/batch.go:87 +0x50c
github.com/google/gapid/gapis/replay.(*manager).batch-fm(0x71a1180, 0xc00023e0c0, 0xc0004d2820, 0x5, 0x5, 0x6495020, 0x70ac870, 0x64c2100, 0xc00012ef00, 0x1)
	gapis/replay/manager.go:146 +0x95
github.com/google/gapid/gapis/replay/scheduler.(*bin).exec(0xc005bf6380, 0x71a1180, 0xc00023e0c0, 0xc000390e20)
	gapis/replay/scheduler/scheduler.go:247 +0x2d3
github.com/google/gapid/gapis/replay/scheduler.(*Scheduler).run(0xc000306e80, 0x71a1180, 0xc00023e0c0)
	gapis/replay/scheduler/scheduler.go:180 +0x958
github.com/google/gapid/gapis/replay/scheduler.New.func1()
	gapis/replay/scheduler/scheduler.go:74 +0x50
github.com/google/gapid/core/app/crash.Go.func1(0xc000306ea0)
	core/app/crash/crash.go:65 +0x45
created by github.com/google/gapid/core/app/crash.Go
	core/app/crash/crash.go:63 +0x3f
```

**Comment by ben-clayton** [comment]
Looks like the connection error handling is crashing due to a null pointer

The gapir [`Client.Connect()` calls `session.init()`](https://github.com/google/gapid/blob/master/gapir/client/client.go#L66), something goes wrong in `session.init()`, [and defensively calls `session.close()`](https://github.com/google/gapid/blob/master/gapir/client/session.go#L80), and `session.close()` [incorrectly assumes there's a connection to close](https://github.com/google/gapid/blob/master/gapir/client/session.go#L377).

To fix the panic, wrap the call to `s.conn.Shutdown(ctx)` with `if s.conn != nil`.

There is another error being raised though, but this will allow you to at least see the error message.

**Comment by rawnsley** [comment]
In my duplicate post I said that Pixel 1 wasn't working, but this is no longer the case with the latest version. I assumed it was because the RockChip device was failing in the same way.

The failing device is an RK3288, which has a Mali-760 GPU on revision 11 of the driver. Here is the logcat from the device with notes made about the failure points: [logcat.txt](https://github.com/google/gapid/files/2961866/logcat.txt)
