### ISSUE TITLE
Error: Could not find tracer for device <device id>

### ISSUE THREAD

**Issue by pmuetschard** [google/gapid#2703]
Opening the application selection dialog, I have seen the following happening sometimes.
1. open the dialog
2. it's querying the apps
3. eventually it shows the tree, but all the children stay at "loading".
4. Each child logs the following exception with the above error coming from the server. (< app name> is the package of the app)

```
error in com.google.gapid.models.TraceTargets$1.onRpcThread
com.google.gapid.server.Client$InternalServerErrorException: Could not find tracer for device 2d387773e8cd90c887c073ad47798b7e67563dc1
	at com.google.gapid.server.Client.throwIfError(Client.java:301)
	at com.google.gapid.server.Client.lambda$getTraceTargetTreeNode$43(Client.java:231)
	at com.google.common.util.concurrent.AbstractTransformFuture$AsyncTransformFuture.doTransform(AbstractTransformFuture.java:213)
	at com.google.common.util.concurrent.AbstractTransformFuture$AsyncTransformFuture.doTransform(AbstractTransformFuture.java:202)
	at com.google.common.util.concurrent.AbstractTransformFuture.run(AbstractTransformFuture.java:118)
	at com.google.common.util.concurrent.MoreExecutors$5$1.run(MoreExecutors.java:982)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: com.google.gapid.server.Client$Stack: For request: RPC->traceTargetTreeNode(ID { data: 2d387773e8cd90c887c073ad47798b7e67563dc1 }, **<app name>**, 1.00000)
	at com.google.gapid.server.Client.call(Client.java:285)
	at com.google.gapid.server.Client.getTraceTargetTreeNode(Client.java:223)
	at com.google.gapid.models.TraceTargets.lambda$load$0(TraceTargets.java:107)
	at com.google.gapid.models.TraceTargets$Node.load(TraceTargets.java:203)
	at com.google.gapid.models.TraceTargets.load(TraceTargets.java:107)
	at com.google.gapid.models.TraceTargets.load(TraceTargets.java:111)
	at com.google.gapid.views.TraceTargetPickerDialog$2.getText(TraceTargetPickerDialog.java:184)
	at org.eclipse.jface.viewers.WrappedViewerLabelProvider.getText(WrappedViewerLabelProvider.java:99)
	at org.eclipse.jface.viewers.WrappedViewerLabelProvider.update(WrappedViewerLabelProvider.java:148)
	at org.eclipse.jface.viewers.ViewerColumn.refresh(ViewerColumn.java:144)
	at org.eclipse.jface.viewers.AbstractTreeViewer.doUpdateItem(AbstractTreeViewer.java:946)
	at org.eclipse.jface.viewers.AbstractTreeViewer$UpdateItemSafeRunnable.run(AbstractTreeViewer.java:120)
	at org.eclipse.jface.util.SafeRunnable$1.run(SafeRunnable.java:129)
	at org.eclipse.jface.util.SafeRunnable.run(SafeRunnable.java:176)
	at org.eclipse.jface.viewers.AbstractTreeViewer.doUpdateItem(AbstractTreeViewer.java:1025)
	at org.eclipse.jface.viewers.StructuredViewer$UpdateItemSafeRunnable.run(StructuredViewer.java:478)
	at org.eclipse.jface.util.SafeRunnable$1.run(SafeRunnable.java:129)
	at org.eclipse.jface.util.SafeRunnable.run(SafeRunnable.java:176)
	at org.eclipse.jface.viewers.StructuredViewer.updateItem(StructuredViewer.java:2161)
	at org.eclipse.jface.viewers.AbstractTreeViewer.createTreeItem(AbstractTreeViewer.java:840)
	at org.eclipse.jface.viewers.AbstractTreeViewer.createChildren(AbstractTreeViewer.java:818)
	at org.eclipse.jface.viewers.TreeViewer.createChildren(TreeViewer.java:604)
	at org.eclipse.jface.viewers.AbstractTreeViewer.createChildren(AbstractTreeViewer.java:766)
	at org.eclipse.jface.viewers.AbstractTreeViewer.internalInitializeTree(AbstractTreeViewer.java:1586)
	at org.eclipse.jface.viewers.TreeViewer.internalInitializeTree(TreeViewer.java:780)
	at org.eclipse.jface.viewers.AbstractTreeViewer.lambda$1(AbstractTreeViewer.java:1571)
	at org.eclipse.jface.viewers.StructuredViewer.preservingSelection(StructuredViewer.java:1449)
	at org.eclipse.jface.viewers.TreeViewer.preservingSelection(TreeViewer.java:363)
	at org.eclipse.jface.viewers.StructuredViewer.preservingSelection(StructuredViewer.java:1410)
	at org.eclipse.jface.viewers.AbstractTreeViewer.inputChanged(AbstractTreeViewer.java:1565)
	at com.google.gapid.widgets.VisibilityTrackingTreeViewer.inputChanged(VisibilityTrackingTreeViewer.java:76)
	at org.eclipse.jface.viewers.ContentViewer.setInput(ContentViewer.java:289)
	at org.eclipse.jface.viewers.StructuredViewer.setInput(StructuredViewer.java:1687)
	at com.google.gapid.views.TraceTargetPickerDialog.onTreeRootLoaded(TraceTargetPickerDialog.java:103)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.google.gapid.util.Events$ListenerCollectionImpl.invoke(Events.java:167)
	at com.sun.proxy.$Proxy20.onTreeRootLoaded(Unknown Source)
	at com.google.gapid.models.TraceTargets.fireLoadedEvent(TraceTargets.java:97)
	at com.google.gapid.models.ModelBase.updateSuccess(ModelBase.java:113)
	at com.google.gapid.models.ModelBase$1.onUiThreadSuccess(ModelBase.java:81)
	at com.google.gapid.rpc.UiErrorCallback.onUiThread(UiErrorCallback.java:34)
	at com.google.gapid.rpc.UiErrorCallback.onUiThread(UiErrorCallback.java:25)
	at com.google.gapid.rpc.UiCallback.lambda$onFinish$0(UiCallback.java:46)
	at com.google.gapid.widgets.Widgets.ifNotDisposed(Widgets.java:119)
	at com.google.gapid.widgets.Widgets.lambda$scheduleIfNotDisposed$1(Widgets.java:147)
	at com.google.gapid.widgets.Widgets.lambda$schedule$0(Widgets.java:139)
	at org.eclipse.swt.widgets.RunnableLock.run(RunnableLock.java:40)
	at org.eclipse.swt.widgets.Synchronizer.runAsyncMessages(Synchronizer.java:185)
	at org.eclipse.swt.widgets.Display.runAsyncMessages(Display.java:5026)
	at org.eclipse.swt.widgets.Display.readAndDispatch(Display.java:4586)
	at org.eclipse.jface.window.Window.runEventLoop(Window.java:821)
	at org.eclipse.jface.window.Window.open(Window.java:797)
	at com.google.gapid.views.TraceTargetPickerDialog.open(TraceTargetPickerDialog.java:118)
	at com.google.gapid.views.TracerDialog$TraceInputDialog$TraceInput.showTraceTargetPicker(TracerDialog.java:520)
	at com.google.gapid.views.TracerDialog$TraceInputDialog$TraceInput$1.createAndShowDialog(TracerDialog.java:291)
	at com.google.gapid.widgets.ActionTextbox.showDialog(ActionTextbox.java:51)
	at com.google.gapid.widgets.ActionTextbox.lambda$new$0(ActionTextbox.java:47)
	at org.eclipse.swt.widgets.EventTable.sendEvent(EventTable.java:89)
	at org.eclipse.swt.widgets.Display.sendEvent(Display.java:5797)
	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1374)
	at org.eclipse.swt.widgets.Display.runDeferredEvents(Display.java:5051)
	at org.eclipse.swt.widgets.Display.readAndDispatch(Display.java:4583)
	at org.eclipse.jface.window.Window.runEventLoop(Window.java:821)
	at org.eclipse.jface.window.Window.open(Window.java:797)
	at com.google.gapid.views.TracerDialog.loadDevicesAndShowDialog(TracerDialog.java:150)
	at com.google.gapid.views.TracerDialog.showTracingDialog(TracerDialog.java:129)
	at com.google.gapid.MainWindow.lambda$updateFileMenu$11(MainWindow.java:255)
	at com.google.gapid.MainWindow$MenuItems$1.run(MainWindow.java:399)
	at org.eclipse.jface.action.Action.runWithEvent(Action.java:476)
	at org.eclipse.jface.action.ActionContributionItem.handleWidgetSelection(ActionContributionItem.java:568)
	at org.eclipse.jface.action.ActionContributionItem.lambda$4(ActionContributionItem.java:400)
	at org.eclipse.swt.widgets.EventTable.sendEvent(EventTable.java:89)
	at org.eclipse.swt.widgets.Display.sendEvent(Display.java:5797)
	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1374)
	at org.eclipse.swt.widgets.Display.runDeferredEvents(Display.java:5051)
	at org.eclipse.swt.widgets.Display.readAndDispatch(Display.java:4583)
	at org.eclipse.jface.window.Window.runEventLoop(Window.java:821)
	at org.eclipse.jface.window.Window.open(Window.java:797)
	at com.google.gapid.Main$UI.show(Main.java:119)
	at com.google.gapid.Main.main(Main.java:68)
```

**Comment by anholt** [comment]
Also experiencing this when trying to use gapid to capture android apps here (gapid 1.6.1 .deb)
