### ISSUE TITLE
Crash when starting gapid in ubuntu 16.04 64bit

### ISSUE THREAD

**Issue by namtq-1780** [google/gapid#2707]
GAPID Version: 1.5.0:b33134fa99c398ce81dffd642aa11ea53c660518
OS: linux amd64

I can't start gapid, when start app, it show crash dialog: 
The application encountered an error:
Unhandled exception in the UI thread.
java.lang.NullPointerException
	at com.google.gapid.widgets.TabArea.layoutComputeSize(TabArea.java:344)
	at com.google.gapid.widgets.TabArea$1.computeSize(TabArea.java:68)
	at org.eclipse.swt.widgets.Composite.computeSizeInPixels(Composite.java:243)
	at org.eclipse.swt.widgets.Control.computeSize(Control.java:825)
	at org.eclipse.swt.layout.FormData.computeSize(FormData.java:120)
	at org.eclipse.swt.layout.FormData.getWidth(FormData.java:149)
	at org.eclipse.swt.layout.FormData.getRightAttachment(FormData.java:250)
	at org.eclipse.swt.layout.FormLayout.computeWidth(FormLayout.java:271)
	at org.eclipse.swt.layout.FormLayout.layout(FormLayout.java:338)
	at org.eclipse.swt.layout.FormLayout.computeSize(FormLayout.java:245)
	at org.eclipse.swt.widgets.Composite.computeSizeInPixels(Composite.java:243)
	at org.eclipse.swt.widgets.Control.computeSize(Control.java:825)
	at org.eclipse.swt.layout.GridData.computeSize(GridData.java:494)
	at org.eclipse.swt.layout.GridLayout.layout(GridLayout.java:224)
	at org.eclipse.swt.layout.GridLayout.computeSize(GridLayout.java:167)
	at org.eclipse.swt.widgets.Composite.computeSizeInPixels(Composite.java:243)
	at org.eclipse.swt.widgets.Control.computeSize(Control.java:825)
	at org.eclipse.swt.custom.StackLayout.computeSize(StackLayout.java:101)
	at org.eclipse.swt.widgets.Composite.computeSizeInPixels(Composite.java:243)
	at org.eclipse.swt.widgets.Control.computeSize(Control.java:825)
	at org.eclipse.swt.custom.StackLayout.computeSize(StackLayout.java:101)
	at org.eclipse.swt.widgets.Composite.computeSizeInPixels(Composite.java:243)
	at org.eclipse.swt.widgets.Control.computeSize(Control.java:825)
	at org.eclipse.swt.layout.GridData.computeSize(GridData.java:494)
	at org.eclipse.swt.layout.GridLayout.layout(GridLayout.java:224)
	at org.eclipse.swt.layout.GridLayout.layout(GridLayout.java:200)
	at org.eclipse.swt.widgets.Composite.updateLayout(Composite.java:1847)
	at org.eclipse.swt.widgets.Composite.updateLayout(Composite.java:1853)
	at org.eclipse.swt.widgets.Composite.setLayoutDeferred(Composite.java:1694)
	at org.eclipse.swt.widgets.Display.runDeferredLayouts(Display.java:5075)
	at org.eclipse.swt.widgets.Display.readAndDispatch(Display.java:4570)
	at org.eclipse.jface.window.Window.runEventLoop(Window.java:821)
	at org.eclipse.jface.window.Window.open(Window.java:797)
	at com.google.gapid.views.ErrorDialog.showErrorDialog(ErrorDialog.java:161)
	at com.google.gapid.views.ErrorDialog.showErrorDialog(ErrorDialog.java:62)
	at com.google.gapid.Main$UI.lambda$registerWindowExceptionHandler$0(Main.java:113)
	at org.eclipse.jface.window.Window.runEventLoop(Window.java:825)
	at org.eclipse.jface.window.Window.open(Window.java:797)
	at com.google.gapid.Main$UI.show(Main.java:119)
	at com.google.gapid.Main.main(Main.java:68)

**Comment by AWoloszyn** [comment]
@pmuetschard  This looks like something we have seen before.

**Comment by pmuetschard** [comment]
Sorry for the long wait. This is an error that comes from trying to show an error dialog for a different error. It would be helpful to have the original error.

@namtq-1780 could you please include the full gapic.log output? it should be in /tmp/gapic.log. Thanks.

**Comment by ravenclaw78** [comment]
I had the same error on a fresh installed Kubuntu 19.04.
In my gapic.log I found the following:
java.lang.UnsatisfiedLinkError: Failed to locate library: libX11.so

Problem was: I installed a headless openjre/jdk, 
Fix for me was: installing the normal openjdk-11-jdk

Root for me was the suggestion to install one of the headless jre's by ubuntu after entering "java" into the shell (without having it installed).
