### ISSUE TITLE
Tracing Failed   Cause: Could not start trace   Cause: Process returned error   Cause: exit status 1

### ISSUE THREAD

**Issue by LoveDaisy** [google/gapid#2717]
GAPID Version: 1.5.0:b33134fa99c398ce81dffd642aa11ea53c660518
OS: mac os x x86_64

Please provide detailed steps that led to the error and copy-paste the stack trace.
Extra details from the logs and the trace file would be extra helpful.

Hi all,
I'm trying to capture frames. When I checked "Clear package cache", and got this error. When I unchecked "Clear package cache", it seems OK, but it terminates immediately after initialization (waiting for debugger) and captured nothing.

It worked well several days ago, and I upgraded many brew packages these days. I'm not sure what causes this issue. Anyone can help?

And here is the error log:
```bash
com.google.gapid.server.Client$InternalServerErrorException: Tracing Failed
   Cause: Could not start trace
   Cause: Process returned error
   Cause: exit status 1
	at com.google.gapid.server.Client.throwIfError(Client.java:301)
	at com.google.gapid.server.Client.lambda$streamTrace$49(Client.java:275)
	at com.google.gapid.server.GapidClientGrpc$StreamHandler.onNext(GapidClientGrpc.java:217)
	at io.grpc.stub.ClientCalls$StreamObserverToCallListenerAdapter.onMessage(ClientCalls.java:421)
	at io.grpc.ForwardingClientCallListener.onMessage(ForwardingClientCallListener.java:33)
	at io.grpc.ForwardingClientCallListener.onMessage(ForwardingClientCallListener.java:33)
	at io.grpc.internal.ClientCallImpl$ClientStreamListenerImpl$1MessagesAvailable.runInContext(ClientCallImpl.java:519)
	at io.grpc.internal.ContextRunnable.run(ContextRunnable.java:37)
	at io.grpc.internal.SerializingExecutor.run(SerializingExecutor.java:123)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: com.google.gapid.server.Client$Stack: For request: RPC->streamTrace()
	at com.google.gapid.server.Client.streamTrace(Client.java:272)
	at com.google.gapid.server.Tracer.trace(Tracer.java:41)
	at com.google.gapid.views.TracerDialog.showTracingDialog(TracerDialog.java:132)
	at com.google.gapid.MainWindow.lambda$updateFileMenu$11(MainWindow.java:255)
	at com.google.gapid.MainWindow$MenuItems$1.run(MainWindow.java:399)
	at org.eclipse.jface.action.Action.runWithEvent(Action.java:476)
	at org.eclipse.jface.action.ActionContributionItem.handleWidgetSelection(ActionContributionItem.java:568)
	at org.eclipse.jface.action.ActionContributionItem.lambda$4(ActionContributionItem.java:400)
	at org.eclipse.swt.widgets.EventTable.sendEvent(EventTable.java:89)
	at org.eclipse.swt.widgets.Display.sendEvent(Display.java:4292)
	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1512)
	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1535)
	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1520)
	at org.eclipse.swt.widgets.Widget.notifyListeners(Widget.java:1324)
	at org.eclipse.swt.widgets.Display.runDeferredEvents(Display.java:4116)
	at org.eclipse.swt.widgets.Display.readAndDispatch(Display.java:3733)
	at org.eclipse.jface.window.Window.runEventLoop(Window.java:821)
	at org.eclipse.jface.window.Window.open(Window.java:797)
	at com.google.gapid.Main$UI.show(Main.java:119)
	at com.google.gapid.Main.main(Main.java:68)
```

**Comment by AWoloszyn** [comment]
Any ideas @pmuetschard

**Comment by pmuetschard** [comment]
@LoveDaisy could you please post the gapis.log output? You can find it in your temporary directory, or via the UI's help menu.
Also, if it's due to the application dying, can you please include the adb logcat output, especially of the stack trace?
Finally, what is the device you are trying to trace on? The output of `gapit device --os android` would help.

**Comment by AWoloszyn** [comment]
Closing, if you have more information please comment, and I will reopen.
