### ISSUE TITLE
The gapis server has exited with an error code of: -42

### ISSUE THREAD

**Issue by ieatbyte** [google/gapid#2718]
GAPID Version: 1.5.0:b33134fa99c398ce81dffd642aa11ea53c660518
OS: mac os x x86_64

Please provide detailed steps that led to the error and copy-paste the stack trace.
Extra details from the logs and the trace file would be extra helpful.

com.google.gapid.Server$GapisInitException: Failed to connect to the graphics debugger
	at com.google.gapid.Server.connectToServer(Server.java:103)
	at com.google.gapid.Server.connect(Server.java:71)
	at com.google.gapid.Main$UI.startup(Main.java:135)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)

**Comment by ieatbyte** [comment]
with all studio closed, kill-server start-server adb

**Comment by AWoloszyn** [comment]
Do you happen to have the logs? gapis.log and gapic.log would be helpful.

**Comment by AWoloszyn** [comment]
Closing, if you have more information please comment, and I will reopen.
