### ISSUE TITLE
Android inside Chromebook 

### ISSUE THREAD

**Issue by ricardoquesadawork** [google/gapid#2736]
Hi,
I'm trying to trace an Android application that runs inside Pixel Chromebook (it is an Intel Chromebook).
- Host is a Linux.
- Using Chrome M76.
- Android P.

Tried with Gapid 1.5, and 1.3.1. Got the same error from both. The error is:

The application encountered an error:
Tracing Failed
   Cause: Could not start trace
   Cause: Couldn't turn device screen on
   Cause: 
   Cause: Couldn't get screen-on state

Details:
com.google.gapid.server.Client$InternalServerErrorException: Tracing Failed
   Cause: Could not start trace
   Cause: Couldn't turn device screen on
   Cause: 
   Cause: Couldn't get screen-on state
	at com.google.gapid.server.Client.throwIfError(Client.java:301)
	at com.google.gapid.server.Client.lambda$streamTrace$49(Client.java:275)
	at com.google.gapid.server.GapidClientGrpc$StreamHandler.onNext(GapidClientGrpc.java:217)
	at io.grpc.stub.ClientCalls$StreamObserverToCallListenerAdapter.onMessage(ClientCalls.java:421)
	at io.grpc.ForwardingClientCallListener.onMessage(ForwardingClientCallListener.java:33)
	at io.grpc.ForwardingClientCallListener.onMessage(ForwardingClientCallListener.java:33)
	at io.grpc.internal.ClientCallImpl$ClientStreamListenerImpl$1MessagesAvailable.runInContext(ClientCallImpl.java:519)
	at io.grpc.internal.ContextRunnable.run(ContextRunnable.java:37)
	at io.grpc.internal.SerializingExecutor.run(SerializingExecutor.java:123)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: com.google.gapid.server.Client$Stack: For request: RPC->streamTrace()
	at com.google.gapid.server.Client.streamTrace(Client.java:272)
	at com.google.gapid.server.Tracer.trace(Tracer.java:41)
	at com.google.gapid.views.TracerDialog.showTracingDialog(TracerDialog.java:132)
	at com.google.gapid.MainWindow.lambda$updateFileMenu$11(MainWindow.java:255)
	at com.google.gapid.MainWindow$MenuItems$1.run(MainWindow.java:399)
	at org.eclipse.jface.action.Action.runWithEvent(Action.java:476)
	at org.eclipse.jface.action.ActionContributionItem.handleWidgetSelection(ActionContributionItem.java:568)
	at org.eclipse.jface.action.ActionContributionItem.lambda$4(ActionContributionItem.java:400)
	at org.eclipse.swt.widgets.EventTable.sendEvent(EventTable.java:89)
	at org.eclipse.swt.widgets.Display.sendEvent(Display.java:5797)
	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1374)
	at org.eclipse.swt.widgets.Display.runDeferredEvents(Display.java:5051)
	at org.eclipse.swt.widgets.Display.readAndDispatch(Display.java:4583)
	at org.eclipse.jface.window.Window.runEventLoop(Window.java:821)
	at org.eclipse.jface.window.Window.open(Window.java:797)
	at com.google.gapid.Main$UI.show(Main.java:119)
	at com.google.gapid.Main.main(Main.java:68)

**Comment by ricardoquesadawork** [comment]
same thing happens if I run it in an ARM device.
Tracing Android apk inside Chromebooks used to work (I believed I was able to make it run with Gapid v0.6.0)

**Comment by ricardoquesadawork** [comment]
And for reference, I've just tried it on a Samsung Intel device that has Android N, and the bug is still there.  using Gapid 1.5.0

**Comment by AWoloszyn** [comment]
Interesting that this fails there:

Cause: Could not start trace
Cause: Couldn't turn device screen on
Cause:
Cause: Couldn't get screen-on state

I can take a quick look at this. 
One note is that x86_64 APKs will definitely not work at the moment.

**Comment by ricardoquesadawork** [comment]
ok. thanks for the update. LMK if you need further info.

**Comment by ricardoquesadawork** [comment]
thanks!
