### ISSUE TITLE
Can't start GAPID on macOS: java.lang.IllegalArgumentException: Argument cannot be null

### ISSUE THREAD

**Issue by stellama0208** [google/gapid#2794]
GAPID version: most updated version of goog/master on May 31, 3c7767d
OS: macOS Mojave 10.14.5  (Pro 15-inch, 2018)

callstack:
Exception in thread "main" java.lang.IllegalArgumentException: Argument cannot be null
	at org.eclipse.swt.SWT.error(SWT.java:4576)
	at org.eclipse.swt.SWT.error(SWT.java:4510)
	at org.eclipse.swt.SWT.error(SWT.java:4481)
	at org.eclipse.swt.graphics.Image.init(Image.java:1422)
	at org.eclipse.swt.graphics.Image.<init>(Image.java:565)
	at com.google.gapid.widgets.Theme$Loader.loadImage(Theme.java:375)
	at com.google.gapid.widgets.Theme$Loader.loadIconSequence(Theme.java:355)
	at com.google.gapid.widgets.Theme$Loader.loadResource(Theme.java:336)
	at com.google.gapid.widgets.Theme$Loader.load(Theme.java:330)
	at com.google.gapid.widgets.Theme.load(Theme.java:170)
	at com.google.gapid.Main.main(Main.java:65)

This is the first time that I try to set up GAPID on my macOS. After I successfully built everything, I can't run GAPID by command ./bazel-bin/pkg/gapid.

* I can build and run this version of GAPID on my linux desktop, this error only happens on my macOS laptop.

**Comment by stellama0208** [comment]
After tracing along the code, it seems that the error happens when trying to get logo icon resources.
Somehow it will still try to load resource: logo_16@2x.png, logo_32@2x.png, logo_48@2x.png, logo_64@2x.png, which don't exist.

Adding dummy files with these names can bypass this error and successfully launch GAPID. Will look further into the code and see how to modify and solve it.

**Comment by stellama0208** [comment]
Update: after further investigation, the different performance on macOS and linux is that: the zooming level (scaling factor from the display device) are different. My linux desktop only ask for 1x version resources every time at initialization, so it has never noticed the missing 2x resources.

Suggestion: This should be a bug, cause the users with 2x zoom device will not be able to start GAPID. Adding these missing resources is enough to solve the problem.
