### ISSUE TITLE
THERE IS AN ERROR WHEN BUILDING

### ISSUE THREAD

**Issue by Zhang-Yun** [google/gapid#2810]
I have installed Bazel 0.26.0 and all dependencies as specified by BUILDING.md,but when I try to build gapid,build system report an error to me:
```
INFO: Call stack for the definition of repository 'remotejdk11_macos' which is a http_archive (rule definition at /private/var/tmp/_bazel_zhangyun/cc1e646be9e433fd6ba4a61ebdc97bcb/external/bazel_tools/tools/build_defs/repo/http.bzl:229:16):
 - /DEFAULT.WORKSPACE.SUFFIX:209:1
INFO: Call stack for the definition of repository 'com_github_grpc_grpc' which is a _github_repository (rule definition at /private/var/tmp/_bazel_zhangyun/cc1e646be9e433fd6ba4a61ebdc97bcb/external/gapid/tools/build/rules/repository.bzl:77:22):
 - /private/var/tmp/_bazel_zhangyun/cc1e646be9e433fd6ba4a61ebdc97bcb/external/gapid/tools/build/rules/repository.bzl:93:5
 - /private/var/tmp/_bazel_zhangyun/cc1e646be9e433fd6ba4a61ebdc97bcb/external/gapid/tools/build/rules/repository.bzl:100:9
 - /private/var/tmp/_bazel_zhangyun/cc1e646be9e433fd6ba4a61ebdc97bcb/external/gapid/tools/build/workspace.bzl:66:5
 - /work/gapid/gapid/WORKSPACE:18:1
INFO: Call stack for the definition of repository 'com_google_protobuf' which is a _github_repository (rule definition at /private/var/tmp/_bazel_zhangyun/cc1e646be9e433fd6ba4a61ebdc97bcb/external/gapid/tools/build/rules/repository.bzl:77:22):
 - /private/var/tmp/_bazel_zhangyun/cc1e646be9e433fd6ba4a61ebdc97bcb/external/gapid/tools/build/rules/repository.bzl:93:5
 - /private/var/tmp/_bazel_zhangyun/cc1e646be9e433fd6ba4a61ebdc97bcb/external/gapid/tools/build/rules/repository.bzl:100:9
 - /private/var/tmp/_bazel_zhangyun/cc1e646be9e433fd6ba4a61ebdc97bcb/external/gapid/tools/build/workspace.bzl:56:5
 - /work/gapid/gapid/WORKSPACE:18:1
ERROR: /private/var/tmp/_bazel_zhangyun/cc1e646be9e433fd6ba4a61ebdc97bcb/external/breakpad/BUILD:121:1: in filter_headers rule @breakpad//:breakpad_darwin_headers: 
Traceback (most recent call last):
	File "/private/var/tmp/_bazel_zhangyun/cc1e646be9e433fd6ba4a61ebdc97bcb/external/breakpad/BUILD", line 121
		filter_headers(name = 'breakpad_darwin_headers')
	File "/private/var/tmp/_bazel_zhangyun/cc1e646be9e433fd6ba4a61ebdc97bcb/external/gapid/tools/build/rules/mm.bzl", line 22, in _filter_headers_impl
		outs += [src]
`+` operator on a depset is forbidden. See https://docs.bazel.build/versions/master/skylark/depsets.html for recommendations. Use --incompatible_depset_union=false to temporarily disable this check.
ERROR: Analysis of target '//:pkg' failed; build aborted: Analysis of target '@breakpad//:breakpad_darwin_headers' failed; build aborted
INFO: Elapsed time: 1.664s
INFO: 0 processes.
FAILED: Build did NOT complete successfully (0 packages loaded, 4 targets c\
onfigured)
    Fetching ...leapis; Cloning 41d72d444fbe445f4da89e13be02078734fb7875 of\
 https://github.com/googleapis/googleapis
```

How can I fix it?

**Comment by pmuetschard** [comment]
This was fixed in c61a4a7, simply update to latest master and you should be good to go.
