### ISSUE TITLE
Unhandled exception in the UI thread.

### ISSUE THREAD

**Issue by AWoloszyn** [google/gapid#2869]
I tried to tear off and move the geometry tab, and got the following error.

GAPID Version: 1.7.0:developer
OS: linux amd64

Please provide detailed steps that led to the error and copy-paste the stack trace.
Extra details from the logs and the trace file would be extra helpful.

org.eclipse.swt.SWTException: Widget is disposed
	at org.eclipse.swt.SWT.error(SWT.java:4595)
	at org.eclipse.swt.SWT.error(SWT.java:4510)
	at org.eclipse.swt.SWT.error(SWT.java:4481)
	at org.eclipse.swt.widgets.Widget.error(Widget.java:506)
	at org.eclipse.swt.widgets.Widget.checkWidget(Widget.java:443)
	at org.eclipse.swt.widgets.Control.setBounds(Control.java:1015)
	at com.google.gapid.widgets.TabComposite$Folder.setBounds(TabComposite.java:836)
	at com.google.gapid.widgets.TabComposite$VerticalGroup.setChildBounds(TabComposite.java:696)
	at com.google.gapid.widgets.TabComposite$Group.setBounds(TabComposite.java:449)
	at com.google.gapid.widgets.TabComposite$HorizontalGroup.setChildBounds(TabComposite.java:577)
	at com.google.gapid.widgets.TabComposite$Group.setBounds(TabComposite.java:449)
	at com.google.gapid.widgets.TabComposite.layoutLayout(TabComposite.java:292)
	at com.google.gapid.widgets.TabComposite$1.layout(TabComposite.java:75)
	at org.eclipse.swt.widgets.Composite.updateLayout(Composite.java:1847)
	at org.eclipse.swt.widgets.Composite.updateLayout(Composite.java:1853)
	at org.eclipse.swt.widgets.Composite.updateLayout(Composite.java:1853)
	at org.eclipse.swt.widgets.Composite.updateLayout(Composite.java:1853)
	at org.eclipse.swt.widgets.Composite.updateLayout(Composite.java:1853)
	at org.eclipse.swt.widgets.Composite.updateLayout(Composite.java:1853)
	at org.eclipse.swt.widgets.Composite.updateLayout(Composite.java:1853)
	at org.eclipse.swt.widgets.Composite.updateLayout(Composite.java:1853)
	at org.eclipse.swt.widgets.Composite.setLayoutDeferred(Composite.java:1694)
	at org.eclipse.swt.widgets.Display.runDeferredLayouts(Display.java:5075)
	at org.eclipse.swt.widgets.Display.readAndDispatch(Display.java:4570)
	at org.eclipse.jface.window.Window.runEventLoop(Window.java:821)
	at org.eclipse.jface.window.Window.open(Window.java:797)
	at com.google.gapid.Main$UI.show(Main.java:119)
	at com.google.gapid.Main.main(Main.java:68)

**Comment by AWoloszyn** [comment]
Some data from the .gapic file.
`
tabs.hidden=
tabs=ApiCalls,Framebuffer,Textures,Shaders,Report,Log,Geometry,ApiState,Memory
shader.splitter.weights=700,300
tabs.iweights=-1,540,809,540
tabs.structure=g3;f1;f6;f2;
`

Let me know if there is anything else that would be useful
