### ISSUE TITLE
Fail to replay GLES SanAngeles sample

### ISSUE THREAD

**Issue by hevrard** [google/gapid#2873]
Replay error with the [SanAngeles sample](https://github.com/googlesamples/android-ndk/tree/master/san-angeles), apk is attached here (rename to remove ".zip", which was added to please github.)
[san-angeles-arm64-debug.apk.zip](https://github.com/google/gapid/files/3324646/san-angeles-arm64-debug.apk.zip)

:

```
W20190625-104717684[pool-1-thread-10][util.Logging.throttleLogRpcError] Failed to load image
W20190625-104717684[pool-1-thread-10][util.Logging.throttleLogRpcError] com.google.gapid.server.Client$InternalServerErrorException: Couldn't get framebuffer attachment
   Cause: Unsupported input format-type pair: (GL_ONE, GLenum(1767076705))
W20190625-104717684[pool-1-thread-10][util.Logging.throttleLogRpcError] 	at com.google.gapid.server.Client.throwIfError(Client.java:312)
W20190625-104717684[pool-1-thread-10][util.Logging.throttleLogRpcError] 	at com.google.gapid.server.Client.lambda$get$7(Client.java:100)
W20190625-104717684[pool-1-thread-10][util.Logging.throttleLogRpcError] 	at com.google.common.util.concurrent.AbstractTransformFuture$AsyncTransformFuture.doTransform(AbstractTransformFuture.java:213)
W20190625-104717684[pool-1-thread-10][util.Logging.throttleLogRpcError] 	at com.google.common.util.concurrent.AbstractTransformFuture$AsyncTransformFuture.doTransform(AbstractTransformFuture.java:202)
W20190625-104717684[pool-1-thread-10][util.Logging.throttleLogRpcError] 	at com.google.common.util.concurrent.AbstractTransformFuture.run(AbstractTransformFuture.java:118)
W20190625-104717684[pool-1-thread-10][util.Logging.throttleLogRpcError] 	at com.google.common.util.concurrent.MoreExecutors$5$1.run(MoreExecutors.java:982)
W20190625-104717684[pool-1-thread-10][util.Logging.throttleLogRpcError] 	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
W20190625-104717684[pool-1-thread-10][util.Logging.throttleLogRpcError] 	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
W20190625-104717684[pool-1-thread-10][util.Logging.throttleLogRpcError] 	at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:304)
W20190625-104717684[pool-1-thread-10][util.Logging.throttleLogRpcError] 	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
W20190625-104717684[pool-1-thread-10][util.Logging.throttleLogRpcError] 	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
W20190625-104717684[pool-1-thread-10][util.Logging.throttleLogRpcError] 	at java.base/java.lang.Thread.run(Thread.java:834)
W20190625-104717684[pool-1-thread-10][util.Logging.throttleLogRpcError] Caused by: com.google.gapid.server.Client$Stack: For request: RPC->get(blob { ID { data: cc9564b19d604899a58a94dbbbd1ea0f9c71d398 } }, ID { data: 940e615c83c9cf33b8e3c61d564db5b1c639febc })
W20190625-104717684[pool-1-thread-10][util.Logging.throttleLogRpcError] 	at com.google.gapid.server.Client.call(Client.java:296)
W20190625-104717684[pool-1-thread-10][util.Logging.throttleLogRpcError] 	at com.google.gapid.server.Client.get(Client.java:92)
W20190625-104717684[pool-1-thread-10][util.Logging.throttleLogRpcError] 	at com.google.gapid.image.FetchedImage$SingleFacedLevel.doLoad(FetchedImage.java:395)
W20190625-104717684[pool-1-thread-10][util.Logging.throttleLogRpcError] 	at com.google.gapid.image.FetchedImage$Level.get(FetchedImage.java:324)
W20190625-104717684[pool-1-thread-10][util.Logging.throttleLogRpcError] 	at com.google.gapid.image.FetchedImage$Layer.getImage(FetchedImage.java:283)
W20190625-104717684[pool-1-thread-10][util.Logging.throttleLogRpcError] 	at com.google.gapid.image.FetchedImage.getImage(FetchedImage.java:258)
W20190625-104717684[pool-1-thread-10][util.Logging.throttleLogRpcError] 	at com.google.gapid.image.FetchedImage.lambda$loadImage$6(FetchedImage.java:118)
W20190625-104717684[pool-1-thread-10][util.Logging.throttleLogRpcError] 	... 10 more
```

**Comment by pmuetschard** [comment]
This app fails due to it being a GLES1.0 app. We don't support GLES1.0. The linked PR improves the error message a bit.

**Comment by AWoloszyn** [comment]
I don't suppose there is an easy way to fail opening a GLES1.0 app. I doubt we can fail on trace, but we could just fail the loading of the capture if we detect GLES1.0? At least then it would be clear before we try and replay.
