### ISSUE TITLE
Failed to load the geometry exception.

### ISSUE THREAD

**Issue by stellama0208** [google/gapid#2889]
**OS:** Linux.
**GAPID version:** Version 1.7.0:developer
**Exception reproduction:** Select on some of the Draw call in Commands panel. Look into the Geometry View tab, if there's a message of "GlDrawElementsInstanced.getIndices() not implemented", the console would also show up an exception with stack trace.

**Stack Trace:**
W20190628-155232062[pool-1-thread-10][models.Geometries.processResult] Failed to load the geometry
W20190628-155232062[pool-1-thread-10][models.Geometries.processResult] com.google.gapid.server.Client$InternalServerErrorException: GlDrawElementsInstanced.getIndices() not implemented
W20190628-155232062[pool-1-thread-10][models.Geometries.processResult] 	at com.google.gapid.server.Client.throwIfError(Client.java:312)
W20190628-155232062[pool-1-thread-10][models.Geometries.processResult] 	at com.google.gapid.server.Client.lambda$8(Client.java:100)
W20190628-155232062[pool-1-thread-10][models.Geometries.processResult] 	at com.google.common.util.concurrent.AbstractTransformFuture$AsyncTransformFuture.doTransform(AbstractTransformFuture.java:213)
W20190628-155232062[pool-1-thread-10][models.Geometries.processResult] 	at com.google.common.util.concurrent.AbstractTransformFuture$AsyncTransformFuture.doTransform(AbstractTransformFuture.java:202)
W20190628-155232062[pool-1-thread-10][models.Geometries.processResult] 	at com.google.common.util.concurrent.AbstractTransformFuture.run(AbstractTransformFuture.java:118)
W20190628-155232062[pool-1-thread-10][models.Geometries.processResult] 	at com.google.common.util.concurrent.MoreExecutors$5$1.run(MoreExecutors.java:982)
W20190628-155232062[pool-1-thread-10][models.Geometries.processResult] 	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
W20190628-155232062[pool-1-thread-10][models.Geometries.processResult] 	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
W20190628-155232062[pool-1-thread-10][models.Geometries.processResult] 	at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:304)
W20190628-155232062[pool-1-thread-10][models.Geometries.processResult] 	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
W20190628-155232062[pool-1-thread-10][models.Geometries.processResult] 	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
W20190628-155232062[pool-1-thread-10][models.Geometries.processResult] 	at java.base/java.lang.Thread.run(Thread.java:834)
W20190628-155232062[pool-1-thread-10][models.Geometries.processResult] Caused by: com.google.gapid.server.Client$Stack: For request: RPC->get(as { vertex_buffer_format { streams { format { components { data_type { signed: true float { exponent_bits: 7 mantissa_bits: 24 } } sampling { } channel: X } components { data_type { signed: true float { exponent_bits: 7 mantissa_bits: 24 } } sampling { } channel: Y } components { data_type { signed: true float { exponent_bits: 7 mantissa_bits: 24 } } sampling { } channel: Z } } semantic { type: Position } } streams { format { components { data_type { signed: true float { exponent_bits: 7 mantissa_bits: 24 } } sampling { } channel: X } components { data_type { signed: true float { exponent_bits: 7 mantissa_bits: 24 } } sampling { } channel: Y } components { data_type { signed: true float { exponent_bits: 7 mantissa_bits: 24 } } sampling { } channel: Z } } semantic { type: Normal } } } mesh { options { vertex_semantics { name: "aa_bloat_and_coverage" } vertex_semantics { name: "color" } vertex_semantics { name: "corner_and_radius_outsets" } vertex_semantics { name: "radii_selector" } vertex_semantics { name: "radii_x" } vertex_semantics { name: "radii_y" } vertex_semantics { name: "skew" } vertex_semantics { name: "translate" } } command_tree_node { tree { data: 842d81fc2510cf9fa8d9e8dde6de9b474042a093 } indices: 18 indices: 23 } } }, ID { data: 1d0b6e75c72f6b4b1780248277de433313a983a0 })
W20190628-155232062[pool-1-thread-10][models.Geometries.processResult] 	at com.google.gapid.server.Client.call(Client.java:296)
W20190628-155232062[pool-1-thread-10][models.Geometries.processResult] 	at com.google.gapid.server.Client.get(Client.java:92)
W20190628-155232062[pool-1-thread-10][models.Geometries.processResult] 	at com.google.gapid.models.Geometries.fetchModel(Geometries.java:179)
W20190628-155232062[pool-1-thread-10][models.Geometries.processResult] 	at com.google.gapid.models.Geometries.lambda$0(Geometries.java:115)
W20190628-155232062[pool-1-thread-10][models.Geometries.processResult] 	... 10 more

Not sure whether it is considered a bug, but since the console would occasionally get flooded with these exception stack traces, it seems to be unwanted.

**Comment by stellama0208** [comment]
The exception only happens for the draw calls with GlDrawElementsInstanced type, but for the GlDrawArrays, GlDrawRangeElements, things works fine.

**Comment by hevrard** [comment]
Apparently getIndices() is implemented ONLY for glDrawArrays, glDrawElements and glDrawRangeElements, all others are marked as not implemented:

https://github.com/google/gapid/blob/72898f38d62aaabf6ef25bb8d362c82bf54cc308/gapis/api/gles/draw_call.go#L145

Stella would you be happy to have a look at implementing the others?
