### ISSUE TITLE
do build failure in Linux

### ISSUE THREAD

**Issue by XiaosongWei** [google/gapid#295]
./do build
ninja: error: loading 'build.ninja': No such file or directory
Error running /home/xiaosong/tools/depot_tools/ninja [install]: Process returned error
   Cause: exit status 1
exit status 1

Any idea?

**Comment by TheMartynBliss** [comment]
Try ./do clean and then ./do build

**Comment by XiaosongWei** [comment]
@TheMartynBliss Thanks for your quick reply.
The build can proceed now but fails in:
FAILED: test/test-test-integration-service 
: && /usr/bin/ccache "/home/xiaosong/cmake-3.7.1-Linux-x86_64/bin/cmake" -DGO_ENV=/home/xiaosong/gapid/release/go/goenv.cmake -DBUILDBOT=OFF -DGO_BUILD=test/test-test-integration-service -DGO_PACKAGE=github.com/google/gapid/test/integration/service -P /home/xiaosong/go/src/github.com/google/gapid/cmake/Modules/GoCompile.cmake && :
# github.com/google/gapid/gapis/shadertools
/usr/bin/ld: cannot find -lkhronos
collect2: error: ld returned 1 exit status

Am I missing something?

**Comment by TheMartynBliss** [comment]
Try this: 
<snip>
A workaround for now is to run ./do build khronos followed by ./do build
</snip>

**Comment by ben-clayton** [comment]
> /usr/bin/ld: cannot find -lkhronos

This should have been fixed by #285, @XiaosongWei please can you check whether you had this change in your git log? If you do, then we haven't fixed the problem.

**Comment by XiaosongWei** [comment]
@TheMartynBliss Thanks! The WA works for me!
@ben-clayton The issue also disappears after updating source to the latest.
But build still runs to failure:

> [3/7] Gradle: aarch64-gradle-gapid-apk
FAILED: aarch64/gapid-apk/app/build/outputs/apk/app-debug.apk 
cd /home/xiaosong/gapid/release/aarch64/gapid-apk && /home/xiaosong/cmake-3.7.1-Linux-x86_64/bin/cmake -DGRADLE_ENV=/home/xiaosong/gapid/release/gradleenv.cmake -DGRADLE_ARGS="-Pfilehash=/home/xiaosong/gapid/release/bin/filehash -Pinputs=/home/xiaosong/gapid/release/aarch64/gapid-apk/app/src/main/jniLibs/arm64-v8a//libgapir.so,/home/xiaosong/gapid/release/aarch64/gapid-apk/app/src/main/jniLibs/arm64-v8a//libgapii.so,/home/xiaosong/gapid/release/aarch64/gapid-apk/app/src/main/jniLibs/arm64-v8a//libinterceptor.so,/home/xiaosong/gapid/release/aarch64/gapid-apk/app/src/main/jniLibs/arm64-v8a//libdeviceinfo.so,/home/xiaosong/gapid/release/aarch64/gapid-apk/app/src/main/jniLibs/arm64-v8a//libVkLayerGraphicsSpy.so,/home/xiaosong/gapid/release/aarch64/gapid-apk/app/src/main/jniLibs/arm64-v8a//libVkLayer_VirtualSwapchain.so,/home/xiaosong/gapid/release/aarch64/gapid-apk/app/build.gradle,/home/xiaosong/gapid/release/aarch64/gapid-apk/app/src/main/java/com/google/android/gapid/DeviceInfoService.java,/home/xiaosong/gapid/release/aarch64/gapid-apk/app/src/main/java/com/google/android/gapid/PackageInfoService.java,/home/xiaosong/gapid/release/aarch64/gapid-apk/app/src/main/java/com/google/android/gapid/SocketWriter.java,/home/xiaosong/gapid/release/aarch64/gapid-apk/app/src/main/res/drawable-xxxhdpi/logo.png,/home/xiaosong/gapid/release/aarch64/gapid-apk/build.gradle,/home/xiaosong/gapid/release/aarch64/gapid-apk/gradle.properties,/home/xiaosong/gapid/release/aarch64/gapid-apk/gradle/wrapper/gradle-wrapper.jar,/home/xiaosong/gapid/release/aarch64/gapid-apk/gradle/wrapper/gradle-wrapper.properties,/home/xiaosong/gapid/release/aarch64/gapid-apk/gradlew,/home/xiaosong/gapid/release/aarch64/gapid-apk/gradlew.bat,/home/xiaosong/gapid/release/aarch64/gapid-apk/settings.gradle,/home/xiaosong/gapid/release/aarch64/gapid-apk/app/src/main/res/values/strings.xml,/home/xiaosong/gapid/release/aarch64/gapid-apk/app/src/main/AndroidManifest.xml" -P /home/xiaosong/go/src/github.com/google/gapid/cmake/Modules/RunGradle.cmake
Downloading https://services.gradle.org/distributions/gradle-2.4-all.zip

> Exception

 

> in thread "main" java.lang.RuntimeException: java.net.ConnectException: Connection timed out
	at org.gradle.wrapper.ExclusiveFileAccessManager.access(ExclusiveFileAccessManager.java:78)
	at org.gradle.wrapper.Install.createDist(Install.java:47)
	at org.gradle.wrapper.WrapperExecutor.execute(WrapperExecutor.java:129)
	at org.gradle.wrapper.GradleWrapperMain.main(GradleWrapperMain.java:48)

> Caused by: java.net.ConnectException: Connection timed out

My desktop is bebind a proxy and I had already set the proxy in gapidapk/android/gradle.properties.
Any suggestion to fix this? Thanks!

**Comment by ben-clayton** [comment]
Hi @XiaosongWei,

Unfortunately I'm not very familiar with Gradle, so you may have better luck asking the gradle team.
Please note that we're planning to move to a different, unified build system soon which will remove the need for Gradle.

Cheers,
Ben

**Comment by YotiSandy** [comment]
I was having a similar problem on Mac OSX Sierra, so I tried this. I did a get this morning then did ./do build -khronos and got:

```
[0/1] Re-running CMake...
-- Building GAPID 0.5.0:0:developer
-- Configuring done
-- Generating done
-- Build files have been written to: /Users/xx/gapid/release
ninja: no work to do.
xx-MacBook-Pro:gapid xx$ ./do build
```

then I did a ./do build and got the same error as previously:

```
FAILURE: Build failed with an exception.

* What went wrong:
A problem occurred configuring project ':app'.
> failed to find target with hash string 'android-21' in: /Users/sandylyons/opt/android-sdk

* Try:
Run with --debug option to get more log output.

* Exception is:
org.gradle.api.ProjectConfigurationException: A problem occurred configuring project ':app'.
...
BUILD FAILED

Total time: 7.844 secs
Stopped 0 compiler daemon(s).
Received result CommandFailure[value=org.gradle.launcher.exec.ReportedException: org.gradle.internal.exceptions.LocationAwareException: A problem occurred configuring project ':app'.] from daemon DaemonInfo{pid=57125, address=[e508bf83-f9a9-4de4-8255-0d33a22ff487 port:62224, addresses:[/0:0:0:0:0:0:0:1, /127.0.0.1]], idle=false, context=DefaultDaemonContext[uid=23a63840-1061-4565-9a96-1cb08892f28d,javaHome=/Library/Java/JavaVirtualMachines/jdk1.8.0_131.jdk/Contents/Home,daemonRegistryDir=/Users/sandylyons/.gradle/daemon,pid=57125,idleTimeout=10800000,daemonOpts=-XX:MaxPermSize=1024m,-Xmx5120m,-Dfile.encoding=UTF-8,-Duser.country=GB,-Duser.language=en,-Duser.variant]}.
CMake Error at /Users/sandylyons/go/src/github.com/google/gapid/cmake/Modules/RunGradle.cmake:34 (message):
  1
[52/86] Performing gapii step for 'x86_64'
ninja: build stopped: subcommand failed.
Error running /usr/local/bin/ninja [install]: Process returned error
   Cause: exit status 1
exit status 1
```

Any ideas for how to get this building?

Thanks :)

**Comment by ben-clayton** [comment]
Hi @YotiSandy,

The line of interest is:
> `failed to find target with hash string 'android-21' in: /Users/xx/opt/android-sdk`

I suspect you are missing the [Android 5.0.1 (API 21) SDK Platform](https://github.com/google/gapid/blob/master/BUILDING.md#install-android-sdk-1). Please can you confirm you have it downloaded?

**Comment by pmuetschard** [comment]
The easiest way to install the package is to run
```tools/bin/sdkmanager platforms\;android-21```
from the SDK.

**Comment by ben-clayton** [comment]
Closing due to inactivity.
