### ISSUE TITLE
Unhandled exception in the UI thread.

### ISSUE THREAD

**Issue by littleariel** [google/gapid#2977]
GAPID Version: 1.6.0:c0b6cac1c33fab1db1a9d3938201bea8ad581b45
OS: mac os x x86_64

Please provide detailed steps that led to the error and copy-paste the stack trace.
Extra details from the logs and the trace file would be extra helpful:

- Clicked on "Browse" to enter the path to adb in the first screen of gapid
- Note that I'm running MacOS Catalina, which is in beta. 

java.lang.NullPointerException
	at org.eclipse.swt.widgets.FileDialog.open(FileDialog.java:286)
	at com.google.gapid.widgets.FileTextbox$File.createAndShowDialog(FileTextbox.java:56)
	at com.google.gapid.widgets.ActionTextbox.showDialog(ActionTextbox.java:51)
	at com.google.gapid.widgets.ActionTextbox.lambda$new$0(ActionTextbox.java:47)
	at org.eclipse.swt.widgets.EventTable.sendEvent(EventTable.java:89)
	at org.eclipse.swt.widgets.Display.sendEvent(Display.java:4292)
	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1512)
	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1535)
	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1520)
	at org.eclipse.swt.widgets.Widget.notifyListeners(Widget.java:1324)
	at org.eclipse.swt.widgets.Display.runDeferredEvents(Display.java:4116)
	at org.eclipse.swt.widgets.Display.readAndDispatch(Display.java:3733)
	at org.eclipse.jface.window.Window.runEventLoop(Window.java:821)
	at org.eclipse.jface.window.Window.open(Window.java:797)
	at com.google.gapid.views.WelcomeDialog.showFirstTimeDialog(WelcomeDialog.java:112)
	at com.google.gapid.Main$UI.lambda$uiStartup$2(Main.java:156)
	at org.eclipse.swt.widgets.RunnableLock.run(RunnableLock.java:40)
	at org.eclipse.swt.widgets.Synchronizer.runAsyncMessages(Synchronizer.java:185)
	at org.eclipse.swt.widgets.Display.runAsyncMessages(Display.java:4068)
	at org.eclipse.swt.widgets.Display.readAndDispatch(Display.java:3735)
	at org.eclipse.jface.window.Window.runEventLoop(Window.java:821)
	at org.eclipse.jface.window.Window.open(Window.java:797)
	at com.google.gapid.Main$UI.show(Main.java:119)
	at com.google.gapid.Main.main(Main.java:68)

**Comment by pau-baiget** [comment]
@littleariel can you consistently reproduce this issue? Can you please try with the 1.6.1 version we recently released?
