### ISSUE TITLE
The gapis server has exited with an error code of: -42

### ISSUE THREAD

**Issue by appiot2014** [google/gapid#2978]
GAPID Version: 1.6.0:c0b6cac1c33fab1db1a9d3938201bea8ad581b45
OS: windows 7 amd64

com.google.gapid.Server$GapisInitException: Failed to connect to the graphics debugger
	at com.google.gapid.Server.connectToServer(Server.java:103)
	at com.google.gapid.Server.connect(Server.java:71)
	at com.google.gapid.Main$UI.startup(Main.java:135)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)

**Comment by AWoloszyn** [comment]
Does this happen if you try to open again?
Is there a popup for changing firewall settings?

**Comment by appiot2014** [comment]
Does this happen if you try to open again? => Yes, I can reproduce it.
Is there a popup for changing firewall settings? =>no popup for firewall settings.




发件人: Andrew Woloszyn [mailto:notifications@github.com]
发送时间: 2019年7月25日 0:50
收件人: google/gapid
抄送: Yun Pu (蒲云); Author
主题: Re: [google/gapid] The gapis server has exited with an error code of: -42 (#2978)


Does this happen if you try to open again?
Is there a popup for changing firewall settings?

**Comment by Ood-Tsen** [comment]
I got similar symptom on Ubuntu 16.04, but resolver it by run it as root.
 
sudo /opt/gapid/gapid
