### ISSUE TITLE
Fails detection for devices running on Android Lollipop (5.x)

### ISSUE THREAD

**Issue by ca1773130n** [google/gapid#2987]
**GAPID version : latest release (1.6.0 2a69ff)**

It seems the official user guide document (https://gapid.dev/trace/) should be updated - it's saying the minimum Android version is Lollipop but the latest GAPID apk fails when calling RPC GetDevices.

The logcat below shows the **__register_atfork()** function is missing which maybe due to the version mismatch of NDK native API level. The function is added since Android M so the minimum requirement of Android version should be changed to Android M, not L.

Otherwise the native API level should be downgraded or the use of that function should be removed.

I've never succeeded to get any Android L devices on the GAPID's detected devices list.

---------

**02-04 07:23:22.961 17241-17407/com.google.android.gapid.armeabiv7a E/gapid-pkginfo: Error occurred
    java.util.concurrent.ExecutionException: java.lang.UnsatisfiedLinkError: dlopen failed: cannot locate symbol "__register_atfork" referenced by "libdeviceinfo.so"...
        at java.util.concurrent.FutureTask.report(FutureTask.java:93)
        at java.util.concurrent.FutureTask.get(FutureTask.java:163)
        at com.google.android.gapid.SocketWriter.connectAndWrite(SocketWriter.java:46)
        at com.google.android.gapid.DeviceInfoService.handleSendDeviceInfo(DeviceInfoService.java:90)
        at com.google.android.gapid.DeviceInfoService.onHandleIntent(DeviceInfoService.java:71)
        at android.app.IntentService$ServiceHandler.handleMessage(IntentService.java:65)
        at android.os.Handler.dispatchMessage(Handler.java:102)
        at android.os.Looper.loop(Looper.java:145)
        at android.os.HandlerThread.run(HandlerThread.java:61)
     Caused by: java.lang.UnsatisfiedLinkError: dlopen failed: cannot locate symbol "__register_atfork" referenced by "libdeviceinfo.so"...
        at java.lang.Runtime.loadLibrary(Runtime.java:371)
        at java.lang.System.loadLibrary(System.java:989)
        at com.google.android.gapid.DeviceInfoService$1.call(DeviceInfoService.java:83)
        at com.google.android.gapid.DeviceInfoService$1.call(DeviceInfoService.java:80)
        at java.util.concurrent.FutureTask.run(FutureTask.java:237)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
        at java.lang.Thread.run(Thread.java:818)**

**Comment by pmuetschard** [comment]
The documentation for tracing is out of date and we are working on fixing that now. The requirements page https://gapid.dev/requirements/ is updated and does indicate that M is now the required version. You can use the previous GAPID release, which still supports L, if you require debugging on L.
