### ISSUE TITLE
Unhandled exception in the UI thread.

### ISSUE THREAD

**Issue by arieltal** [google/gapid#3019]
GAPID Version: 1.6.1:338bb67b0fe291f56f31d69f11ea1a45ed7cfeb6
OS: linux amd64

Please provide detailed steps that led to the error and copy-paste the stack trace.
Extra details from the logs and the trace file would be extra helpful.

tried to debug an app which crashes with a SIGSEGV.
when i click on the trace file it created i get this:
org.eclipse.swt.SWTException: Failed to execute runnable (java.lang.reflect.UndeclaredThrowableException)
	at org.eclipse.swt.SWT.error(SWT.java:4595)
	at org.eclipse.swt.SWT.error(SWT.java:4510)
	at org.eclipse.swt.widgets.Synchronizer.runAsyncMessages(Synchronizer.java:188)
	at org.eclipse.swt.widgets.Display.runAsyncMessages(Display.java:5026)
	at org.eclipse.swt.widgets.Display.readAndDispatch(Display.java:4586)
	at org.eclipse.jface.window.Window.runEventLoop(Window.java:821)
	at org.eclipse.jface.window.Window.open(Window.java:797)
	at com.google.gapid.Main$UI.show(Main.java:119)
	at com.google.gapid.Main.main(Main.java:68)
Caused by: java.lang.reflect.UndeclaredThrowableException
	at com.sun.proxy.$Proxy8.onCaptureLoaded(Unknown Source)
	at com.google.gapid.models.Capture.fireLoadedEvent(Capture.java:138)
	at com.google.gapid.models.ModelBase.updateSuccess(ModelBase.java:113)
	at com.google.gapid.models.ModelBase$1.onUiThreadSuccess(ModelBase.java:81)
	at com.google.gapid.rpc.UiErrorCallback.onUiThread(UiErrorCallback.java:34)
	at com.google.gapid.rpc.UiErrorCallback.onUiThread(UiErrorCallback.java:25)
	at com.google.gapid.rpc.UiCallback.lambda$onFinish$0(UiCallback.java:46)
	at com.google.gapid.widgets.Widgets.ifNotDisposed(Widgets.java:124)
	at com.google.gapid.widgets.Widgets.lambda$scheduleIfNotDisposed$1(Widgets.java:152)
	at com.google.gapid.widgets.Widgets.lambda$schedule$0(Widgets.java:144)
	at org.eclipse.swt.widgets.RunnableLock.run(RunnableLock.java:40)
	at org.eclipse.swt.widgets.Synchronizer.runAsyncMessages(Synchronizer.java:185)
	... 6 more
Caused by: java.lang.reflect.InvocationTargetException
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.google.gapid.util.Events$ListenerCollectionImpl.invoke(Events.java:167)
	... 18 more
Caused by: java.lang.UnsatisfiedLinkError: Failed to locate library: libX11.so
	at org.lwjgl.system.Library.loadNative(Library.java:293)
	at org.lwjgl.system.Library.loadNative(Library.java:187)
	at org.lwjgl.system.linux.X11.<clinit>(X11.java:404)
	at com.google.gapid.glcanvas.GlCanvas.createContext(GlCanvas.java:90)
	at com.google.gapid.glcanvas.GlCanvas.<init>(GlCanvas.java:65)
	at com.google.gapid.widgets.ScenePanel.<init>(ScenePanel.java:52)
	at com.google.gapid.widgets.ImagePanel$ImageComponent.<init>(ImagePanel.java:759)
	at com.google.gapid.widgets.ImagePanel.lambda$new$0(ImagePanel.java:154)
	at com.google.gapid.widgets.LoadablePanel.<init>(LoadablePanel.java:56)
	at com.google.gapid.widgets.LoadablePanel.create(LoadablePanel.java:61)
	at com.google.gapid.widgets.ImagePanel.<init>(ImagePanel.java:153)
	at com.google.gapid.views.FramebufferView.<init>(FramebufferView.java:100)
	at com.google.gapid.GraphicsTraceView$MainTab.lambda$getFolders$1(GraphicsTraceView.java:225)
	at com.google.gapid.widgets.TabArea$Folder.addTab(TabArea.java:525)
	at com.google.gapid.widgets.TabArea$Folder.<init>(TabArea.java:509)
	at com.google.gapid.widgets.TabArea.<init>(TabArea.java:80)
	at com.google.gapid.GraphicsTraceView$1.createBottomControl(GraphicsTraceView.java:89)
	at com.google.gapid.widgets.FixedTopSplitter.<init>(FixedTopSplitter.java:39)
	at com.google.gapid.GraphicsTraceView$1.<init>(GraphicsTraceView.java:81)
	at com.google.gapid.GraphicsTraceView.<init>(GraphicsTraceView.java:81)
	at com.google.gapid.MainWindow$MainViewContainer.updateAndGet(MainWindow.java:389)
	at com.google.gapid.MainWindow$1.onCaptureLoaded(MainWindow.java:126)
	... 23 more

**Comment by AWoloszyn** [comment]
```
Failed to locate library: libX11.so
```

This is very suspicious. What Linux distro are you running with what display manager.

**Comment by arieltal** [comment]
Hi, i have ubuntu 18.04.2, gnome 3.28.4
Does this mean i need to install something?
Please excuse me i'm fairly new to linux..

בתאריך 6 באוג׳ 2019 7:44 אחה״צ,‏ Andrew Woloszyn <notifications@github.com> כתב:

Failed to locate library: libX11.so


This is very suspicious. What Linux distro are you running with what display manager.

**Comment by pau-baiget** [comment]
Closing after 2 weeks since the needs-more-information label was added. @arieltal  Please re-open if you can provide more information. Thanks!
