### ISSUE TITLE
Tracing Failed   Cause: Could not start trace   Cause: Package 'com.tencent.avlab.xcast' not found

### ISSUE THREAD

**Issue by chraac** [google/gapid#3148]
GAPID Version: 1.6.1:338bb67b0fe291f56f31d69f11ea1a45ed7cfeb6
OS: windows 10 amd64
Device: MI 6 with Lineage OS 16 (Android 9)

```java

com.google.gapid.server.Client$InternalServerErrorException: Tracing Failed
   Cause: Could not start trace
   Cause: Package 'com.tencent.avlab.xcast' not found

	at com.google.gapid.server.Client.throwIfError(Client.java:312)

	at com.google.gapid.server.Client.lambda$streamTrace$52(Client.java:286)

	at com.google.gapid.server.GapidClientGrpc$StreamHandler.onNext(GapidClientGrpc.java:224)

	at io.grpc.stub.ClientCalls$StreamObserverToCallListenerAdapter.onMessage(ClientCalls.java:421)

	at io.grpc.ForwardingClientCallListener.onMessage(ForwardingClientCallListener.java:33)

	at io.grpc.ForwardingClientCallListener.onMessage(ForwardingClientCallListener.java:33)

	at io.grpc.internal.ClientCallImpl$ClientStreamListenerImpl$1MessagesAvailable.runInContext(ClientCallImpl.java:519)

	at io.grpc.internal.ContextRunnable.run(ContextRunnable.java:37)

	at io.grpc.internal.SerializingExecutor.run(SerializingExecutor.java:123)

	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)

	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)

	at java.lang.Thread.run(Thread.java:748)

Caused by: com.google.gapid.server.Client$Stack: For request: RPC->streamTrace()

	at com.google.gapid.server.Client.streamTrace(Client.java:283)

	at com.google.gapid.server.Tracer.trace(Tracer.java:41)

	at com.google.gapid.views.TracerDialog.showTracingDialog(TracerDialog.java:149)

	at com.google.gapid.LoadingScreen.lambda$createOptions$0(LoadingScreen.java:114)

	at org.eclipse.swt.widgets.EventTable.sendEvent(EventTable.java:89)

	at org.eclipse.swt.widgets.Display.sendEvent(Display.java:4145)

	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1055)

	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1079)

	at org.eclipse.swt.widgets.Widget.sendSelectionEvent(Widget.java:1096)

	at org.eclipse.swt.widgets.Link.WM_LBUTTONUP(Link.java:1014)

	at org.eclipse.swt.widgets.Control.windowProc(Control.java:4805)

	at org.eclipse.swt.widgets.Display.windowProc(Display.java:4784)

	at org.eclipse.swt.internal.win32.OS.DispatchMessageW(Native Method)

	at org.eclipse.swt.internal.win32.OS.DispatchMessage(OS.java:2309)

	at org.eclipse.swt.widgets.Display.readAndDispatch(Display.java:3559)

	at org.eclipse.jface.window.Window.runEventLoop(Window.java:821)

	at org.eclipse.jface.window.Window.open(Window.java:797)

	at com.google.gapid.Main$UI.show(Main.java:119)

	at com.google.gapid.Main.main(Main.java:68)

```

[gapis.log](https://github.com/google/gapid/files/3581867/gapis.log)

**Comment by AWoloszyn** [comment]
Might sound like a silly question, but is the package in question installed on the device?
` Cause: Package 'com.tencent.avlab.xcast' not found`

**Comment by chraac** [comment]
> Might sound like a silly question, but is the package in question installed on the device?
> ` Cause: Package 'com.tencent.avlab.xcast' not found`

Yes, And it's the package name of debugging app, so i was wandering how can it happen.

**Comment by hevrard** [comment]
Please note that we do not support Lineage OS, GAPID works on a best-effort there.

That being said, can you check that you meet all the Android requirements listed here:
https://gapid.dev/trace

As GAPID does not appear to find this package, can you confirm you can see the package in the output of `adb shell pm list packages` ?

**Comment by chraac** [comment]
> Please note that we do not support Lineage OS, GAPID works on a best-effort there.
> 
> That being said, can you check that you meet all the Android requirements listed here:
> https://gapid.dev/trace
> 
> As GAPID does not appear to find this package, can you confirm you can see the package in the output of `adb shell pm list packages` ?

Yes, I sure that ```com.tencent.avlab.xcast``` was in the output of  ```adb shell pm list packages```. And it's there a plan to support Lineage OS?

**Comment by AWoloszyn** [comment]
We will happily accept contributions to support various forks of Android, but don't intend on spending a great deal of time trying to support them ourselves.

**Comment by pau-baiget** [comment]
@chraac since this happens on an unsupported OS, I will close this issue as "Won't fix". However, please feel free to add a feature request and a PR to support Lineage O.S. in the future, as @AWoloszyn suggested.
