### ISSUE TITLE
System Profile - SIGTRAP in perfetto

### ISSUE THREAD

**Issue by nazgee** [google/gapid#3216]
Capturing system profile fails with error 133:
```
com.google.gapid.server.Client$InternalServerErrorException: Tracing Failed
   Cause: exit status 133
	at com.google.gapid.server.Client.throwIfError(Client.java:312)
	at com.google.gapid.server.Client.lambda$streamTrace$52(Client.java:286)
	at com.google.gapid.server.GapidClientGrpc$StreamHandler.onNext(GapidClientGrpc.java:224)
	at io.grpc.stub.ClientCalls$StreamObserverToCallListenerAdapter.onMessage(ClientCalls.java:421)
	at io.grpc.ForwardingClientCallListener.onMessage(ForwardingClientCallListener.java:33)
	at io.grpc.ForwardingClientCallListener.onMessage(ForwardingClientCallListener.java:33)
	at io.grpc.internal.ClientCallImpl$ClientStreamListenerImpl$1MessagesAvailable.runInContext(ClientCallImpl.java:519)
	at io.grpc.internal.ContextRunnable.run(ContextRunnable.java:37)
	at io.grpc.internal.SerializingExecutor.run(SerializingExecutor.java:123)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: com.google.gapid.server.Client$Stack: For request: RPC->streamTrace()
	at com.google.gapid.server.Client.streamTrace(Client.java:283)
	at com.google.gapid.server.Tracer.trace(Tracer.java:41)
	at com.google.gapid.views.TracerDialog.showTracingDialog(TracerDialog.java:154)
	at com.google.gapid.LoadingScreen.lambda$createOptions$0(LoadingScreen.java:114)
	at org.eclipse.swt.widgets.EventTable.sendEvent(EventTable.java:89)
	at org.eclipse.swt.widgets.Display.sendEvent(Display.java:5797)
	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1374)
	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1400)
	at org.eclipse.swt.widgets.Widget.sendSelectionEvent(Widget.java:1514)
	at org.eclipse.swt.widgets.Link.gtk_button_release_event(Link.java:387)
	at org.eclipse.swt.widgets.Widget.windowProc(Widget.java:1970)
	at org.eclipse.swt.widgets.Control.windowProc(Control.java:6524)
	at org.eclipse.swt.widgets.Display.windowProc(Display.java:6014)
	at org.eclipse.swt.internal.gtk.GTK._gtk_main_do_event(Native Method)
	at org.eclipse.swt.internal.gtk.GTK.gtk_main_do_event(GTK.java:4118)
	at org.eclipse.swt.widgets.Display.eventProc(Display.java:1414)
	at org.eclipse.swt.internal.gtk.OS._g_main_context_iteration(Native Method)
	at org.eclipse.swt.internal.gtk.OS.g_main_context_iteration(OS.java:1596)
	at org.eclipse.swt.widgets.Display.readAndDispatch(Display.java:4581)
	at org.eclipse.jface.window.Window.runEventLoop(Window.java:821)
	at org.eclipse.jface.window.Window.open(Window.java:797)
	at com.google.gapid.Main$UI.show(Main.java:120)
	at com.google.gapid.Main.main(Main.java:69)
```

At the same time, perfetto receives SIGTRAP (see [tombstone_09.txt](https://github.com/google/gapid/files/3690700/tombstone_09.txt) )
```
    #00 pc 0000000000022b7c  /system/bin/perfetto (perfetto::PerfettoCmd::OpenOutputFile()+480)
    #01 pc 00000000000225d8  /system/bin/perfetto (perfetto::PerfettoCmd::Main(int, char**)+1192)
    #02 pc 00000000000acac8  /system/lib64/libc.so (__libc_init+88)
```

gapir.log:
```
12:54:06.859 I: <gapis> New trace scheduler for device: 12312312312312312312 QUALCOMM xxxxx automotive
12:54:21.270 I: [start] <gapis> Unlocking device screen
12:54:22.639 I: <gapis> [perfetto] [90mperfetto_cmd.cc:372     [0m [31mPERFETTO_CHECK(trace_out_stream_)[0m
12:54:22.715 I: <gapis> [perfetto] Trap 
```

TBH I have not tried to understand what happens in perfetto... I just wanted to use System Profile with my device

**Comment by nazgee** [comment]
I guess it's just an issue with my perfetto version - will try to switch to a more recent one.
