### ISSUE TITLE
Push constant handling is broken, leading to gapis crashes while scrolling through commands

### ISSUE THREAD

**Issue by chrisforbes** [google/gapid#3234]
GAPID Version: 1.7.0:developer
OS: linux amd64

Scrolling up and down through the command list with the arrow keys:

```
panic: context canceled [recovered]
	panic: runtime error: invalid memory address or nil pointer dereference [recovered]
	panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x40 pc=0x100927e]

goroutine 7472 [running]:
github.com/google/gapid/core/app/crash.Crash(0x566a060, 0xc02e670)
	core/app/crash/crash.go:89 +0xa7
github.com/google/gapid/core/app/crash.handler()
	core/app/crash/crash.go:56 +0x52
panic(0x566a060, 0xc02e670)
	GOROOT/src/runtime/panic.go:522 +0x1b5
github.com/google/gapid/gapis/database.(*memory).resolvePanicHandler(0xc000495140, 0x6c631e0, 0xc003df70e0)
	gapis/database/debug.go:96 +0x43e
panic(0x5505ba0, 0xc0001aa1b0)
	GOROOT/src/runtime/panic.go:522 +0x1b5
github.com/google/gapid/gapis/api/vulkan.panicOnError(...)
	bazel-out/k8-fastbuild/bin/gapis/api/vulkan/api.go:554
github.com/google/gapid/gapis/api/vulkan.U8ˢ.MustReadʷ(0x0, 0x0, 0x10, 0x10, 0xb, 0x6c631e0, 0xc003df7350, 0x0, 0x0, 0xc0044cdea0, ...)
	bazel-out/k8-fastbuild/bin/gapis/api/vulkan/api_slices.go:3888 +0x126
github.com/google/gapid/gapis/api/vulkan.U8ˢ.MustRead(...)
	bazel-out/k8-fastbuild/bin/gapis/api/vulkan/api_slices.go:3882
github.com/google/gapid/gapis/api/vulkan.rebuildVkCmdPushConstants(0x6c631e0, 0xc003df7350, 0x0, 0x7fc9100015f0, 0x556d927c3520, 0xc0044cdea0, 0xc0044cdea0, 0xc001b75c00, 0x1dc7a4, 0x54bdaa0, ...)
	gapis/api/vulkan/command_buffer_rebuilder.go:911 +0xe4
github.com/google/gapid/gapis/api/vulkan.AddCommand(0x6c631e0, 0xc003df7350, 0x0, 0x7fc9100015f0, 0x556d927c3520, 0xc0044cdea0, 0xc0044cdea0, 0x6093f60, 0xc002937db0, 0x6c631e0, ...)
	gapis/api/vulkan/command_buffer_rebuilder.go:1623 +0x45d
github.com/google/gapid/gapis/api/vulkan.API.RecoverMidExecutionCommand(0x6c631e0, 0xc003df72c0, 0xc002340810, 0x61ab920, 0xc000400910, 0x5ac4f60, 0x5fc9880, 0x1352cea4620c9a01, 0x7fc9880253f8)
	gapis/api/vulkan/vulkan.go:675 +0x1c7
github.com/google/gapid/gapis/resolve.Cmd(0x6c631e0, 0xc003df72c0, 0xc001d4c800, 0x0, 0x6c631e0, 0xc003df72c0, 0xc0048244e0, 0x6c631e0)
	gapis/resolve/commands.go:108 +0x5fa
github.com/google/gapid/gapis/resolve.(*FramebufferAttachmentBytesResolvable).Resolve(0xc002626e40, 0x6c631e0, 0xc003df71d0, 0xc003df71d0, 0xc000817700, 0x2, 0x2)
	gapis/resolve/framebuffer_attachment_data.go:37 +0xdc
github.com/google/gapid/gapis/database.(*record).resolve(0xc002626ea0, 0x6c631e0, 0xc003df71d0, 0x0, 0x0)
	gapis/database/memory.go:137 +0x222
github.com/google/gapid/gapis/database.(*memory).resolveLocked.func1()
	gapis/database/memory.go:241 +0x134
github.com/google/gapid/core/app/crash.Go.func1(0xc003df7080)
	core/app/crash/crash.go:65 +0x43
created by github.com/google/gapid/core/app/crash.Go
	core/app/crash/crash.go:63 +0x3f
```
I'm actually not sure why it's trying to reconstruct a vkCmdPushConstants call -- the trace contains no calls to that function.

**Comment by chrisforbes** [comment]
I was being blind -- there is a vkCmdPushConstants call, so not so mysterious. Will fix the actual issue.
