### ISSUE TITLE
`gapit memory` crashes on trivial samples

### ISSUE THREAD

**Issue by chrisforbes** [google/gapid#3263]

**Comment by chrisforbes** [comment]
`gears.gfxtrace` is a MEC trace of the SW gears demo, containing 7 frames from frame 25

```
$ gapit memory gears.gfxtrace
18:17:58.661 I: <gapit> Exec: REDACTED/bin/pkg/gapis --enable-local-files --idle-timeout 1m --log-level Info --log-style brief --gapis-auth-token REDACTED
18:17:58.845 I: <gapis> 18:17:58.845 I: <gapis> Adding new device
18:17:58.845 I: <gapis> 18:17:58.845 I: <gapis> New scheduler for device: 852c6805e074657a35e684dbfccb452ff9c388ac
18:17:58.845 I: <gapis> 18:17:58.845 I: <gapis> New trace scheduler for device: REDACTED
18:17:58.847 I: <gapis> 18:17:58.847 W: <gapis> Could not scan for remote GGP devices. Error: Could not find ggp executable to list instances
18:17:58.847 I: <gapis>    Cause: ggp could not be found from GGP_SDK_PATH or PATH
18:17:58.847 I: <gapis> GGP_SDK_PATH: 
18:17:58.847 I: <gapis> PATH: REDACTED
18:17:58.847 I: <gapis> search: [ggp]
18:17:58.848 I: <gapis> Bound on port '38741'
18:17:58.848 I: <gapis> 18:17:58.848 I: <gapis> Starting grpc server
18:17:58.884 I: <gapit> Loaded capture; id: 4b481e6d24c957b6006c0bb5b5d03bd1962482dc
18:17:58.914 E: <gapis> panic: runtime error: invalid memory address or nil pointer dereference [recovered]
18:17:58.914 E: <gapis> 	panic: 
18:17:58.914 E: <gapis> --- *resolve.GetResolvable ---
18:17:58.914 E: <gapis>  path:<metrics:<command:<capture:<ID:<data:"KH\036m$\311W\266\000l\013\265\265\320;\321\226$\202\334" > > indices:55 > memory_breakdown:true > > 
18:17:58.914 E: <gapis>  Store():
18:17:58.914 E: <gapis>   gapis/database/database.go:56  github.com/google/gapid/gapis/database.Build
18:17:58.914 E: <gapis>   gapis/resolve/get.go:26  github.com/google/gapid/gapis/resolve.Get
18:17:58.914 E: <gapis>   gapis/server/server.go:413  github.com/google/gapid/gapis/server.(*server).Get
18:17:58.914 E: <gapis>   gapis/server/grpc.go:214  github.com/google/gapid/gapis/server.(*grpcServer).Get
18:17:58.914 E: <gapis>   bazel-out/k8-fastbuild/bin/gapis/service/linux_amd64_stripped/service_go_proto%/github.com/google/gapid/gapis/service/service.pb.go:9360  github.com/google/gapid/gapis/service._Gapid_Get_Handler.func1
18:17:58.914 E: <gapis>   core/app/auth/auth.go:110  github.com/google/gapid/core/app/auth.ServerInterceptor.func1
18:17:58.914 E: <gapis>   bazel-out/k8-fastbuild/bin/gapis/service/linux_amd64_stripped/service_go_proto%/github.com/google/gapid/gapis/service/service.pb.go:9362  github.com/google/gapid/gapis/service._Gapid_Get_Handler
18:17:58.914 E: <gapis>   external/org_golang_google_grpc/server.go:971  google.golang.org/grpc.(*Server).processUnaryRPC
18:17:58.914 E: <gapis>   external/org_golang_google_grpc/server.go:1250  google.golang.org/grpc.(*Server).handleStream
18:17:58.914 E: <gapis> 
18:17:58.914 E: <gapis>  Build() #0:
18:17:58.914 E: <gapis>   gapis/database/database.go:60  github.com/google/gapid/gapis/database.Build
18:17:58.914 E: <gapis>   gapis/resolve/get.go:26  github.com/google/gapid/gapis/resolve.Get
18:17:58.914 E: <gapis>   gapis/server/server.go:413  github.com/google/gapid/gapis/server.(*server).Get
18:17:58.914 E: <gapis>   gapis/server/grpc.go:214  github.com/google/gapid/gapis/server.(*grpcServer).Get
18:17:58.914 E: <gapis>   bazel-out/k8-fastbuild/bin/gapis/service/linux_amd64_stripped/service_go_proto%/github.com/google/gapid/gapis/service/service.pb.go:9360  github.com/google/gapid/gapis/service._Gapid_Get_Handler.func1
18:17:58.914 E: <gapis>   core/app/auth/auth.go:110  github.com/google/gapid/core/app/auth.ServerInterceptor.func1
18:17:58.914 E: <gapis>   bazel-out/k8-fastbuild/bin/gapis/service/linux_amd64_stripped/service_go_proto%/github.com/google/gapid/gapis/service/service.pb.go:9362  github.com/google/gapid/gapis/service._Gapid_Get_Handler
18:17:58.914 E: <gapis>   external/org_golang_google_grpc/server.go:971  google.golang.org/grpc.(*Server).processUnaryRPC
18:17:58.914 E: <gapis>   external/org_golang_google_grpc/server.go:1250  google.golang.org/grpc.(*Server).handleStream
18:17:58.914 E: <gapis>  [recovered]
18:17:58.914 E: <gapis> 	panic: 
18:17:58.914 E: <gapis> --- *resolve.GetResolvable ---
18:17:58.914 E: <gapis>  path:<metrics:<command:<capture:<ID:<data:"KH\036m$\311W\266\000l\013\265\265\320;\321\226$\202\334" > > indices:55 > memory_breakdown:true > > 
18:17:58.914 E: <gapis>  Store():
18:17:58.914 E: <gapis>   gapis/database/database.go:56  github.com/google/gapid/gapis/database.Build
18:17:58.914 E: <gapis>   gapis/resolve/get.go:26  github.com/google/gapid/gapis/resolve.Get
18:17:58.914 E: <gapis>   gapis/server/server.go:413  github.com/google/gapid/gapis/server.(*server).Get
18:17:58.914 E: <gapis>   gapis/server/grpc.go:214  github.com/google/gapid/gapis/server.(*grpcServer).Get
18:17:58.914 E: <gapis>   bazel-out/k8-fastbuild/bin/gapis/service/linux_amd64_stripped/service_go_proto%/github.com/google/gapid/gapis/service/service.pb.go:9360  github.com/google/gapid/gapis/service._Gapid_Get_Handler.func1
18:17:58.914 E: <gapis>   core/app/auth/auth.go:110  github.com/google/gapid/core/app/auth.ServerInterceptor.func1
18:17:58.914 E: <gapis>   bazel-out/k8-fastbuild/bin/gapis/service/linux_amd64_stripped/service_go_proto%/github.com/google/gapid/gapis/service/service.pb.go:9362  github.com/google/gapid/gapis/service._Gapid_Get_Handler
18:17:58.914 E: <gapis>   external/org_golang_google_grpc/server.go:971  google.golang.org/grpc.(*Server).processUnaryRPC
18:17:58.914 E: <gapis>   external/org_golang_google_grpc/server.go:1250  google.golang.org/grpc.(*Server).handleStream
18:17:58.914 E: <gapis> 
18:17:58.914 E: <gapis>  Build() #0:
18:17:58.914 E: <gapis>   gapis/database/database.go:60  github.com/google/gapid/gapis/database.Build
18:17:58.914 E: <gapis>   gapis/resolve/get.go:26  github.com/google/gapid/gapis/resolve.Get
18:17:58.914 E: <gapis>   gapis/server/server.go:413  github.com/google/gapid/gapis/server.(*server).Get
18:17:58.914 E: <gapis>   gapis/server/grpc.go:214  github.com/google/gapid/gapis/server.(*grpcServer).Get
18:17:58.914 E: <gapis>   bazel-out/k8-fastbuild/bin/gapis/service/linux_amd64_stripped/service_go_proto%/github.com/google/gapid/gapis/service/service.pb.go:9360  github.com/google/gapid/gapis/service._Gapid_Get_Handler.func1
18:17:58.914 E: <gapis>   core/app/auth/auth.go:110  github.com/google/gapid/core/app/auth.ServerInterceptor.func1
18:17:58.914 E: <gapis>   bazel-out/k8-fastbuild/bin/gapis/service/linux_amd64_stripped/service_go_proto%/github.com/google/gapid/gapis/service/service.pb.go:9362  github.com/google/gapid/gapis/service._Gapid_Get_Handler
18:17:58.914 E: <gapis>   external/org_golang_google_grpc/server.go:971  google.golang.org/grpc.(*Server).processUnaryRPC
18:17:58.914 E: <gapis>   external/org_golang_google_grpc/server.go:1250  google.golang.org/grpc.(*Server).handleStream
18:17:58.914 E: <gapis> 
18:17:58.914 E: <gapis> [signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x3be0557]
18:17:58.914 E: <gapis> 
18:17:58.914 E: <gapis> goroutine 179 [running]:
18:17:58.914 E: <gapis> github.com/google/gapid/core/app/crash.Crash(0x54d9400, 0xc001164130)
18:17:58.914 E: <gapis> 	core/app/crash/crash.go:89 +0xa7
18:17:58.914 E: <gapis> github.com/google/gapid/core/app/crash.handler()
18:17:58.914 E: <gapis> 	core/app/crash/crash.go:56 +0x52
18:17:58.914 E: <gapis> panic(0x54d9400, 0xc001164130)
18:17:58.914 E: <gapis> 	GOROOT/src/runtime/panic.go:522 +0x1b5
18:17:58.914 E: <gapis> github.com/google/gapid/gapis/database.(*memory).resolvePanicHandler(0xc000444320, 0x6c82a00, 0xc0002c4a50)
18:17:58.914 E: <gapis> 	gapis/database/debug.go:106 +0x76e
18:17:58.914 E: <gapis> panic(0x5688720, 0xc051670)
18:17:58.914 E: <gapis> 	GOROOT/src/runtime/panic.go:522 +0x1b5
18:17:58.914 E: <gapis> github.com/google/gapid/gapis/api/vulkan.subGetImagePlaneMemoryInfo(0x6c82980, 0xc0000b60c0, 0x0, 0x0, 0x7fffffffffffffff, 0x0, 0x0, 0xc00128c480, 0x0, 0x0, ...)
18:17:58.914 E: <gapis> 	bazel-out/k8-fastbuild/bin/gapis/api/vulkan/mutate.go:3552 +0x37
18:17:58.914 E: <gapis> github.com/google/gapid/gapis/api/vulkan.(*State).getAllocationBindings(0xc00128c480, 0xc0004f5a18, 0x0, 0x3117, 0x0, 0x0, 0x1, 0x1, 0x0, 0x0)
18:17:58.914 E: <gapis> 	gapis/api/vulkan/memory_breakdown.go:318 +0x27d
18:17:58.914 E: <gapis> github.com/google/gapid/gapis/api/vulkan.API.MemoryBreakdown(0xc000f982a0, 0x5fe84e0, 0x1, 0x7f7ea00ee720)
18:17:58.914 E: <gapis> 	gapis/api/vulkan/memory_breakdown.go:73 +0x489
18:17:58.914 E: <gapis> github.com/google/gapid/gapis/resolve.memoryBreakdown(0x6c82a00, 0xc0002c4db0, 0xc0005862c0, 0x0, 0x86, 0x10, 0xc0004f5d00)
18:17:58.915 E: <gapis> 	gapis/resolve/metrics.go:55 +0x276
18:17:58.915 E: <gapis> github.com/google/gapid/gapis/resolve.Metrics(0x6c82a00, 0xc0002c4db0, 0xc0002c42d0, 0x0, 0xc0005b7d90, 0x1, 0x1)
18:17:58.915 E: <gapis> 	gapis/resolve/metrics.go:31 +0x93
18:17:58.915 E: <gapis> github.com/google/gapid/gapis/resolve.ResolveInternal(0x6c82a00, 0xc0002c4c60, 0x6c83d40, 0xc0002c42d0, 0x0, 0x0, 0x0, 0x0, 0x0)
18:17:58.915 E: <gapis> 	gapis/resolve/resolve.go:335 +0x82d
18:17:58.915 E: <gapis> github.com/google/gapid/gapis/resolve.ResolveService(0x6c82a00, 0xc0002c4c60, 0x6c83d40, 0xc0002c42d0, 0x0, 0xc0002c4c60, 0xc0005b7e80, 0x10, 0xc0005b7e78)
18:17:58.915 E: <gapis> 	gapis/resolve/resolve.go:275 +0x57
18:17:58.915 E: <gapis> github.com/google/gapid/gapis/resolve.(*GetResolvable).Resolve(0xc0002c4960, 0x6c82a00, 0xc0002c4c60, 0xc0002c4ae0, 0xc00041ff00, 0x2, 0x2)
18:17:58.915 E: <gapis> 	gapis/resolve/get.go:33 +0x145
18:17:58.915 E: <gapis> github.com/google/gapid/gapis/database.(*record).resolve(0xc000fa25a0, 0x6c82a00, 0xc0002c4ae0, 0x0, 0x0)
18:17:58.915 E: <gapis> 	gapis/database/memory.go:137 +0x222
18:17:58.915 E: <gapis> github.com/google/gapid/gapis/database.(*memory).resolveLocked.func1()
18:17:58.915 E: <gapis> 	gapis/database/memory.go:241 +0x134
18:17:58.915 E: <gapis> github.com/google/gapid/core/app/crash.Go.func1(0xc0002c49f0)
18:17:58.915 E: <gapis> 	core/app/crash/crash.go:65 +0x43
18:17:58.915 E: <gapis> created by github.com/google/gapid/core/app/crash.Go
18:17:58.915 E: <gapis> 	core/app/crash/crash.go:63 +0x3f
18:17:58.927 E: <gapit> Main failed
Error: Failed to load metrics
   Cause: rpc error: code = Unavailable desc = transport is closing
18:17:58.927 E: <gapit> rpc error: code = Unavailable desc = transport is closing

```
