### ISSUE TITLE
DOS when opening Perfetto trace file

### ISSUE THREAD

**Issue by mattyclarkson** [google/gapid#3289]
When using `1.7.0-dev-20191021` I get a denial of service when opening the [trace.perfetto.gz](https://github.com/google/gapid/files/3755024/trace.perfetto.gz).

If I limit the memory through `ulimit` to around 14GB I can prevent it from making my system unresponsive. When opening the trace file a single thread is locked at 100% until I kill `gapid`. The trace viewer eventually renders but unresponsive.

![cpu](https://user-images.githubusercontent.com/1081113/67278075-2d27ec00-f4c0-11e9-996d-0523e3639931.png)

```
~ $ cat /etc/os-release 
NAME="Arch Linux"
PRETTY_NAME="Arch Linux"
ID=arch
BUILD_ID=rolling
ANSI_COLOR="0;36"
HOME_URL="https://www.archlinux.org/"
DOCUMENTATION_URL="https://wiki.archlinux.org/"
SUPPORT_URL="https://bbs.archlinux.org/"
BUG_REPORT_URL="https://bugs.archlinux.org/"
LOGO=archlinux
```
```
~ $ uname -a
Linux kratos 5.3.7-arch1-1-ARCH #1 SMP PREEMPT Fri Oct 18 00:17:03 UTC 2019 x86_64 
```
```
~ $ ~/Downloads/gapid/gapid --version
To get a suitable JVM on Linux, install a regular (non-Google) JVM version >= 8 (e.g. openjdk-jre-8)
No suitable JVM found
Use --verbose-startup for additional details
~ [1] $ /usr/bin/java --version
openjdk 13 2019-09-17
OpenJDK Runtime Environment (build 13+33)
OpenJDK 64-Bit Server VM (build 13+33, mixed mode)
~ $ ~/Downloads/gapid/gapid --version --vm /usr/bin/java
Starting /usr/bin/java /home/matt-clarkson/Downloads/gapid/lib/gapic.jar
GAPID version 1.7.0:dev-20191021-b198af2dc0ae304eb7531ad2e23ff570ae2ead9eGNU/Linux
```
```
~ $ pacman -Qi gnome-shell gdm nvidia jre-openjdk | rg Version
Version         : 1:3.34.1+5+g072a9a484-1
Version         : 3.34.1-1
Version         : 435.21-13
Version         : 13.u33-1
~ $ loginctl
SESSION  UID USER          SEAT  TTY 
      2 1000 matt-clarkson seat0 tty2
     c1  120 gdm           seat0 tty1

2 sessions listed.
~ $ loginctl show-session 2 -p Type
Type=x11
```

**Comment by pmuetschard** [comment]
Interesting. I just looked at the given trace and it open really fast using with very little memory usage. I also tried it with an OpenJDK 11, but I don't have a 13 readily available to install. Could you try it with a JRE between 1.8 and 11?

**Comment by pmuetschard** [comment]
Also, could you please note witch process is actually pegged at 100%? is it a java process or is it `gapis`?

**Comment by pmuetschard** [comment]
After launching GAPID, please run `killall -3 java`, which will cause the JVM to dump to stdout the stack trace of every thread. Please post the output here. Thanks.

**Comment by mattyclarkson** [comment]
Apologies for the lag. Have attached the trace
[dump.log](https://github.com/google/gapid/files/3763448/dump.log)

Defo the java process that is at the top of `top`. Looks like cairo is going HAM

**Comment by mattyclarkson** [comment]
cairo is `1.17.2+17+g52a7c79fd-2`

Same thing with Jre8, have attached dump
[dump.log](https://github.com/google/gapid/files/3763464/dump.log)

**Comment by mattyclarkson** [comment]
`top`: `791295 matt-cl+  20   0   13.8g 368072  48180 S 107.0   1.1   0:09.22 java`

**Comment by pmuetschard** [comment]
Something to try, to see if not forcing GTK2 would unblock you. Try running the UI directly (i.e. not through the `gapid` launcher):
```
java -jar <path/to/gapid>/lib/gapic.jar --gapid <path/to/gapid>
```

**Comment by mattyclarkson** [comment]
That still spins at 100% :disappointed:

**Comment by hevrard** [comment]
@mattyclarkson we have newer dev-releases that may have fixed your issue, you can grab the latest at: https://github.com/google/gapid-dev-releases/releases/latest

Can you give a try and tell us if you are still facing this issue?

**Comment by mattyclarkson** [comment]
@hevrard thanks. Just ran it up and it spins at 100% whilst *Enumerating Tracks*. Similar stack trace inside `org.eclipse.swt.internal.gtk.GDK._gdk_cairo_region_create_from_surface(Native Method)`

[dump.log](https://github.com/google/gapid/files/3803636/dump.log)

**Comment by pau-baiget** [comment]
@mattyclarkson we didn't really have the time to progress this issue in detail. Could you please try with the [latest dev release](https://github.com/google/gapid-dev-releases/releases) and tell us if you can still see this issue?

**Comment by mattyclarkson** [comment]
It's still an issue. The Java process just runs at 100%+ and the UI is unresponsive on _Enumerating Tracks_. It doesn't hose my system anymore though, I can close `gapid` by clicking the :x:

```
"main" #1 prio=5 os_prio=0 cpu=5018.80ms elapsed=11.34s tid=0x00007fc9e4018800 nid=0x1d9d26 runnable  [0x00007fc9e950f000]
   java.lang.Thread.State: RUNNABLE
	at org.eclipse.swt.internal.cairo.Cairo._cairo_fill(Native Method)
	at org.eclipse.swt.internal.cairo.Cairo.cairo_fill(Cairo.java:218)
	at org.eclipse.swt.graphics.Region.gdk_region_polygon(Region.java:127)
	at org.eclipse.swt.graphics.Region.addInPixels(Region.java:176)
	at org.eclipse.swt.graphics.Region.add(Region.java:167)
	at org.eclipse.swt.graphics.GC.limitClipping(GC.java:2980)
	at org.eclipse.swt.graphics.GC.setCairoClip(GC.java:2960)
	at org.eclipse.swt.graphics.GC.setClipping(GC.java:3039)
	at org.eclipse.swt.graphics.GC.setClippingInPixels(GC.java:3077)
	at org.eclipse.swt.graphics.GC.setClippingInPixels(GC.java:3146)
	at org.eclipse.swt.graphics.GC.setClipping(GC.java:3137)
	at com.google.gapid.perfetto.canvas.RenderContext.withClip(RenderContext.java:304)
	at com.google.gapid.perfetto.views.TrackContainer$Single.render(TrackContainer.java:144)
	at com.google.gapid.perfetto.canvas.PanelGroup.lambda$render$0(PanelGroup.java:110)
	at com.google.gapid.perfetto.canvas.PanelGroup$$Lambda$292/0x000000080032f040.run(Unknown Source)
	at com.google.gapid.perfetto.canvas.RenderContext.withClip(RenderContext.java:302)
	at com.google.gapid.perfetto.canvas.PanelGroup.lambda$render$1(PanelGroup.java:109)
	at com.google.gapid.perfetto.canvas.PanelGroup$$Lambda$291/0x000000080032ec40.run(Unknown Source)
	at com.google.gapid.perfetto.canvas.RenderContext.withTranslation(RenderContext.java:283)
	at com.google.gapid.perfetto.canvas.PanelGroup.render(PanelGroup.java:108)
	at com.google.gapid.perfetto.views.CopyablePanel$Group.render(CopyablePanel.java:69)
	at com.google.gapid.perfetto.views.TrackContainer$Group.lambda$render$0(TrackContainer.java:283)
	at com.google.gapid.perfetto.views.TrackContainer$Group$$Lambda$305/0x0000000800340840.run(Unknown Source)
	at com.google.gapid.perfetto.canvas.RenderContext.withTranslation(RenderContext.java:283)
	at com.google.gapid.perfetto.views.TrackContainer$Group.render(TrackContainer.java:282)
	at com.google.gapid.perfetto.canvas.PanelGroup.lambda$render$0(PanelGroup.java:110)
	at com.google.gapid.perfetto.canvas.PanelGroup$$Lambda$292/0x000000080032f040.run(Unknown Source)
	at com.google.gapid.perfetto.canvas.RenderContext.withClip(RenderContext.java:302)
	at com.google.gapid.perfetto.canvas.PanelGroup.lambda$render$1(PanelGroup.java:109)
	at com.google.gapid.perfetto.canvas.PanelGroup$$Lambda$291/0x000000080032ec40.run(Unknown Source)
	at com.google.gapid.perfetto.canvas.RenderContext.withTranslation(RenderContext.java:283)
	at com.google.gapid.perfetto.canvas.PanelGroup.render(PanelGroup.java:108)
	at com.google.gapid.perfetto.views.RootPanel.lambda$render$1(RootPanel.java:114)
	at com.google.gapid.perfetto.views.RootPanel$$Lambda$303/0x000000080033e440.run(Unknown Source)
	at com.google.gapid.perfetto.canvas.RenderContext.withTranslation(RenderContext.java:283)
	at com.google.gapid.perfetto.views.RootPanel.lambda$render$2(RootPanel.java:113)
	at com.google.gapid.perfetto.views.RootPanel$$Lambda$302/0x000000080033d040.run(Unknown Source)
	at com.google.gapid.perfetto.canvas.RenderContext.withClip(RenderContext.java:302)
	at com.google.gapid.perfetto.views.RootPanel.render(RootPanel.java:112)
	at com.google.gapid.perfetto.canvas.PanelCanvas.lambda$new$2(PanelCanvas.java:64)
	at com.google.gapid.perfetto.canvas.PanelCanvas$$Lambda$196/0x00000008002e2840.handleEvent(Unknown Source)
	at org.eclipse.swt.widgets.EventTable.sendEvent(EventTable.java:89)
	at org.eclipse.swt.widgets.Display.sendEvent(Display.java:5797)
	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1374)
	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1400)
	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1383)
	at org.eclipse.swt.widgets.Control.gtk_draw(Control.java:3698)
	at org.eclipse.swt.widgets.Composite.gtk_draw(Composite.java:435)
	at org.eclipse.swt.widgets.Canvas.gtk_draw(Canvas.java:181)
	at org.eclipse.swt.widgets.Widget.windowProc(Widget.java:1952)
	at org.eclipse.swt.widgets.Control.windowProc(Control.java:6524)
	at org.eclipse.swt.widgets.Display.windowProc(Display.java:6014)
	at org.eclipse.swt.internal.gtk.GTK._gtk_main_do_event(Native Method)
	at org.eclipse.swt.internal.gtk.GTK.gtk_main_do_event(GTK.java:4118)
	at org.eclipse.swt.widgets.Display.eventProc(Display.java:1414)
	at org.eclipse.swt.internal.gtk.OS._g_main_context_iteration(Native Method)
	at org.eclipse.swt.internal.gtk.OS.g_main_context_iteration(OS.java:1596)
	at org.eclipse.swt.widgets.Display.readAndDispatch(Display.java:4581)
	at org.eclipse.jface.window.Window.runEventLoop(Window.java:821)
	at org.eclipse.jface.window.Window.open(Window.java:797)
	at com.google.gapid.Main$UI.show(Main.java:120)
	at com.google.gapid.Main.main(Main.java:69)
```
My box at work is Arch Linux with NVIDIA proprietary driver as the QUADRO is unsupported in Noveau. This also forces X11 for GNOME.

I have a Arch Linux laptop at home that is using open source Intel drivers. I'm pretty sure that is running under Wayland. I'll try on my laptop to bisect.

I'm also happy to debug this myself if you could give me some hints at where one might look. Looking at the trace, it seems like Cairo is crunching trying to draw the into the canvas from Perfetto. I can drop in some breakpoints or try to get a flame graph out for that part of the code? What would be most useful?

**Comment by mattyclarkson** [comment]
Here is a [flame chart log](https://github.com/google/gapid/files/3961060/flame.hpl.gz) opening a trace under Java 8.

You can open it with [`honest-profiler`](https://github.com/jvm-profiling-tools/honest-profiler/wiki/How-to-Run). Here is a preview though:

![honest-profiler-flat-view](https://user-images.githubusercontent.com/1081113/70804876-78b79180-1daf-11ea-8921-25ea5c5945e3.png)

The profile has information about what the threads were doing and a flame chart.

**Comment by mattyclarkson** [comment]
I can give you an `rr` trace but it's not very useful. The equivalent for Java is Chronon which is...expensive so can't give you a Java replay.

**Comment by pau-baiget** [comment]
@mattyclarkson is this bug still relevant?

**Comment by mattyclarkson** [comment]
@pau-baiget it still doesn't work on Arch Linux. It's really up to you guys if you think that is relevant.

**Comment by mattyclarkson** [comment]
If I comment out the `gc.setClipping` calls in `withClip` the issue goes away.

**Comment by mattyclarkson** [comment]
I obviously get zero clipping of the tracks but I can at least view it.
