### ISSUE TITLE
Unhandled exception in the UI thread.

### ISSUE THREAD

**Issue by theee0703** [google/gapid#3332]
GAPID Version: 1.5.0:b33134fa99c398ce81dffd642aa11ea53c660518
OS: windows 10 amd64

Please provide detailed steps that led to the error and copy-paste the stack trace.
Extra details from the logs and the trace file would be extra helpful.

java.lang.NullPointerException
	at com.google.gapid.views.AboutDialog.showLogDir(AboutDialog.java:64)
	at com.google.gapid.views.ErrorDialog$1.lambda$createDetails$3(ErrorDialog.java:143)
	at org.eclipse.swt.widgets.EventTable.sendEvent(EventTable.java:89)
	at org.eclipse.swt.widgets.Display.sendEvent(Display.java:4145)
	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1055)
	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1079)
	at org.eclipse.swt.widgets.Widget.sendSelectionEvent(Widget.java:1096)
	at org.eclipse.swt.widgets.Link.WM_LBUTTONUP(Link.java:1014)
	at org.eclipse.swt.widgets.Control.windowProc(Control.java:4805)
	at org.eclipse.swt.widgets.Display.windowProc(Display.java:4784)
	at org.eclipse.swt.internal.win32.OS.DispatchMessageW(Native Method)
	at org.eclipse.swt.internal.win32.OS.DispatchMessage(OS.java:2309)
	at org.eclipse.swt.widgets.Display.readAndDispatch(Display.java:3559)
	at org.eclipse.jface.window.Window.runEventLoop(Window.java:821)
	at org.eclipse.jface.window.Window.open(Window.java:797)
	at com.google.gapid.views.ErrorDialog.showErrorDialog(ErrorDialog.java:161)
	at com.google.gapid.Main$UI.lambda$onServerExit$4(Main.java:171)
	at com.google.gapid.Main$UI.lambda$scheduleIfStillOpen$5(Main.java:181)
	at com.google.gapid.widgets.Widgets.ifNotDisposed(Widgets.java:119)
	at com.google.gapid.widgets.Widgets.lambda$scheduleIfNotDisposed$1(Widgets.java:147)
	at com.google.gapid.widgets.Widgets.lambda$schedule$0(Widgets.java:139)
	at org.eclipse.swt.widgets.RunnableLock.run(RunnableLock.java:40)
	at org.eclipse.swt.widgets.Synchronizer.runAsyncMessages(Synchronizer.java:185)
	at org.eclipse.swt.widgets.Display.runAsyncMessages(Display.java:3933)
	at org.eclipse.swt.widgets.Display.readAndDispatch(Display.java:3564)
	at org.eclipse.jface.window.Window.runEventLoop(Window.java:821)
	at org.eclipse.jface.window.Window.open(Window.java:797)
	at com.google.gapid.views.ErrorDialog.showErrorDialog(ErrorDialog.java:161)
	at com.google.gapid.Main$UI.lambda$onServerExit$4(Main.java:171)
	at com.google.gapid.Main$UI.lambda$scheduleIfStillOpen$5(Main.java:181)
	at com.google.gapid.widgets.Widgets.ifNotDisposed(Widgets.java:119)
	at com.google.gapid.widgets.Widgets.lambda$scheduleIfNotDisposed$1(Widgets.java:147)
	at com.google.gapid.widgets.Widgets.lambda$schedule$0(Widgets.java:139)
	at org.eclipse.swt.widgets.RunnableLock.run(RunnableLock.java:40)
	at org.eclipse.swt.widgets.Synchronizer.runAsyncMessages(Synchronizer.java:185)
	at org.eclipse.swt.widgets.Display.runAsyncMessages(Display.java:3933)
	at org.eclipse.swt.widgets.Display.readAndDispatch(Display.java:3564)
	at org.eclipse.jface.window.Window.runEventLoop(Window.java:821)
	at org.eclipse.jface.window.Window.open(Window.java:797)
	at com.google.gapid.Main$UI.show(Main.java:119)
	at com.google.gapid.Main.main(Main.java:68)

**Comment by hevrard** [comment]
Thanks for reporting!

You are apparently using an old version (1.5.0), please pick up the latest release here: https://github.com/google/gapid/releases/latest
