### ISSUE TITLE
The gapis server has exited with an error code of: 2

### ISSUE THREAD

**Issue by wenjiangye** [google/gapid#3532]
panic: runtime error: invalid memory address or nil pointer dereference [recovered]
	panic: 
--- *initialcmds.InitialCmdsResolvable ---
 capture:<ID:<data:"\354]\014\246\316\034\026\232\031{\264\177O\330\235\302\334/\320\366" > > 
 Store():
  gapis/database/database.go:56  github.com/google/gapid/gapis/database.Build
  gapis/resolve/initialcmds/initial_commands.go:40  github.com/google/gapid/gapis/resolve/initialcmds.InitialCommands
  gapis/resolve/resources.go:58  github.com/google/gapid/gapis/resolve.(*ResourcesResolvable).Resolve
  gapis/database/memory.go:137  github.com/google/gapid/gapis/database.(*record).resolve
  gapis/database/memory.go:241  github.com/google/gapid/gapis/database.(*memory).resolveLocked.func1
  core/app/crash/crash.go:65  github.com/google/gapid/core/app/crash.Go.func1

 Build() #0:
  gapis/database/database.go:60  github.com/google/gapid/gapis/database.Build
  gapis/resolve/initialcmds/initial_commands.go:40  github.com/google/gapid/gapis/resolve/initialcmds.InitialCommands
  gapis/resolve/resources.go:58  github.com/google/gapid/gapis/resolve.(*ResourcesResolvable).Resolve
  gapis/database/memory.go:137  github.com/google/gapid/gapis/database.(*record).resolve
  gapis/database/memory.go:241  github.com/google/gapid/gapis/database.(*memory).resolveLocked.func1
  core/app/crash/crash.go:65  github.com/google/gapid/core/app/crash.Go.func1

--- *resolve.ResourcesResolvable ---
 capture:<ID:<data:"\354]\014\246\316\034\026\232\031{\264\177O\330\235\302\334/\320\366" > > config:<replay_device:<ID:<data:"\200\016\264\023JuFmn\321\332\2150\273[Z\213\234Ka" > > > 
 Store():
  gapis/database/database.go:56  github.com/google/gapid/gapis/database.Build
  gapis/resolve/resources.go:33  github.com/google/gapid/gapis/resolve.Resources
  gapis/resolve/resolve.go:347  github.com/google/gapid/gapis/resolve.ResolveInternal
  gapis/resolve/resolve.go:275  github.com/google/gapid/gapis/resolve.ResolveService
  gapis/resolve/get.go:33  github.com/google/gapid/gapis/resolve.(*GetResolvable).Resolve
  gapis/database/memory.go:137  github.com/google/gapid/gapis/database.(*record).resolve
  gapis/database/memory.go:241  github.com/google/gapid/gapis/database.(*memory).resolveLocked.func1
  core/app/crash/crash.go:65  github.com/google/gapid/core/app/crash.Go.func1

 Build() #0:
  gapis/database/database.go:60  github.com/google/gapid/gapis/database.Build
  gapis/resolve/resources.go:33  github.com/google/gapid/gapis/resolve.Resources
  gapis/resolve/resolve.go:347  github.com/google/gapid/gapis/resolve.ResolveInternal
  gapis/resolve/resolve.go:275  github.com/google/gapid/gapis/resolve.ResolveService
  gapis/resolve/get.go:33  github.com/google/gapid/gapis/resolve.(*GetResolvable).Resolve
  gapis/database/memory.go:137  github.com/google/gapid/gapis/database.(*record).resolve
  gapis/database/memory.go:241  github.com/google/gapid/gapis/database.(*memory).resolveLocked.func1
  core/app/crash/crash.go:65  github.com/google/gapid/core/app/crash.Go.func1

--- *resolve.GetResolvable ---
 path:<resources:<capture:<ID:<data:"\354]\014\246\316\034\026\232\031{\264\177O\330\235\302\334/\320\366" > > > > config:<replay_device:<ID:<data:"\200\016\264\023JuFmn\321\332\2150\273[Z\213\234Ka" > > > 
 Store():
  gapis/database/database.go:56  github.com/google/gapid/gapis/database.Build
  gapis/resolve/get.go:26  github.com/google/gapid/gapis/resolve.Get
  gapis/server/server.go:425  github.com/google/gapid/gapis/server.(*server).Get
  gapis/server/grpc.go:214  github.com/google/gapid/gapis/server.(*grpcServer).Get
  bazel-out/x64_windows-opt/bin/gapis/service/windows_amd64_stripped/service_go_proto%/github.com/google/gapid/gapis/service/service.pb.go:9461  github.com/google/gapid/gapis/service._Gapid_Get_Handler.func1
  core/app/auth/auth.go:110  github.com/google/gapid/core/app/auth.ServerInterceptor.func1
  bazel-out/x64_windows-opt/bin/gapis/service/windows_amd64_stripped/service_go_proto%/github.com/google/gapid/gapis/service/service.pb.go:9463  github.com/google/gapid/gapis/service._Gapid_Get_Handler
  external/org_golang_google_grpc/server.go:971  google.golang.org/grpc.(*Server).processUnaryRPC
  external/org_golang_google_grpc/server.go:1250  google.golang.org/grpc.(*Server).handleStream

 Build() #0:
  gapis/database/database.go:60  github.com/google/gapid/gapis/database.Build
  gapis/resolve/get.go:26  github.com/google/gapid/gapis/resolve.Get
  gapis/server/server.go:425  github.com/google/gapid/gapis/server.(*server).Get
  gapis/server/grpc.go:214  github.com/google/gapid/gapis/server.(*grpcServer).Get
  bazel-out/x64_windows-opt/bin/gapis/service/windows_amd64_stripped/service_go_proto%/github.com/google/gapid/gapis/service/service.pb.go:9461  github.com/google/gapid/gapis/service._Gapid_Get_Handler.func1
  core/app/auth/auth.go:110  github.com/google/gapid/core/app/auth.ServerInterceptor.func1
  bazel-out/x64_windows-opt/bin/gapis/service/windows_amd64_stripped/service_go_proto%/github.com/google/gapid/gapis/service/service.pb.go:9463  github.com/google/gapid/gapis/service._Gapid_Get_Handler
  external/org_golang_google_grpc/server.go:971  google.golang.org/grpc.(*Server).processUnaryRPC
  external/org_golang_google_grpc/server.go:1250  google.golang.org/grpc.(*Server).handleStream
 [recovered]
	panic: 
--- *initialcmds.InitialCmdsResolvable ---
 capture:<ID:<data:"\354]\014\246\316\034\026\232\031{\264\177O\330\235\302\334/\320\366" > > 
 Store():
  gapis/database/database.go:56  github.com/google/gapid/gapis/database.Build
  gapis/resolve/initialcmds/initial_commands.go:40  github.com/google/gapid/gapis/resolve/initialcmds.InitialCommands
  gapis/resolve/resources.go:58  github.com/google/gapid/gapis/resolve.(*ResourcesResolvable).Resolve
  gapis/database/memory.go:137  github.com/google/gapid/gapis/database.(*record).resolve
  gapis/database/memory.go:241  github.com/google/gapid/gapis/database.(*memory).resolveLocked.func1
  core/app/crash/crash.go:65  github.com/google/gapid/core/app/crash.Go.func1

 Build() #0:
  gapis/database/database.go:60  github.com/google/gapid/gapis/database.Build
  gapis/resolve/initialcmds/initial_commands.go:40  github.com/google/gapid/gapis/resolve/initialcmds.InitialCommands
  gapis/resolve/resources.go:58  github.com/google/gapid/gapis/resolve.(*ResourcesResolvable).Resolve
  gapis/database/memory.go:137  github.com/google/gapid/gapis/database.(*record).resolve
  gapis/database/memory.go:241  github.com/google/gapid/gapis/database.(*memory).resolveLocked.func1
  core/app/crash/crash.go:65  github.com/google/gapid/core/app/crash.Go.func1

--- *resolve.ResourcesResolvable ---
 capture:<ID:<data:"\354]\014\246\316\034\026\232\031{\264\177O\330\235\302\334/\320\366" > > config:<replay_device:<ID:<data:"\200\016\264\023JuFmn\321\332\2150\273[Z\213\234Ka" > > > 
 Store():
  gapis/database/database.go:56  github.com/google/gapid/gapis/database.Build
  gapis/resolve/resources.go:33  github.com/google/gapid/gapis/resolve.Resources
  gapis/resolve/resolve.go:347  github.com/google/gapid/gapis/resolve.ResolveInternal
  gapis/resolve/resolve.go:275  github.com/google/gapid/gapis/resolve.ResolveService
  gapis/resolve/get.go:33  github.com/google/gapid/gapis/resolve.(*GetResolvable).Resolve
  gapis/database/memory.go:137  github.com/google/gapid/gapis/database.(*record).resolve
  gapis/database/memory.go:241  github.com/google/gapid/gapis/database.(*memory).resolveLocked.func1
  core/app/crash/crash.go:65  github.com/google/gapid/core/app/crash.Go.func1

 Build() #0:
  gapis/database/database.go:60  github.com/google/gapid/gapis/database.Build
  gapis/resolve/resources.go:33  github.com/google/gapid/gapis/resolve.Resources
  gapis/resolve/resolve.go:347  github.com/google/gapid/gapis/resolve.ResolveInternal
  gapis/resolve/resolve.go:275  github.com/google/gapid/gapis/resolve.ResolveService
  gapis/resolve/get.go:33  github.com/google/gapid/gapis/resolve.(*GetResolvable).Resolve
  gapis/database/memory.go:137  github.com/google/gapid/gapis/database.(*record).resolve
  gapis/database/memory.go:241  github.com/google/gapid/gapis/database.(*memory).resolveLocked.func1
  core/app/crash/crash.go:65  github.com/google/gapid/core/app/crash.Go.func1

--- *resolve.GetResolvable ---
 path:<resources:<capture:<ID:<data:"\354]\014\246\316\034\026\232\031{\264\177O\330\235\302\334/\320\366" > > > > config:<replay_device:<ID:<data:"\200\016\264\023JuFmn\321\332\2150\273[Z\213\234Ka" > > > 
 Store():
  gapis/database/database.go:56  github.com/google/gapid/gapis/database.Build
  gapis/resolve/get.go:26  github.com/google/gapid/gapis/resolve.Get
  gapis/server/server.go:425  github.com/google/gapid/gapis/server.(*server).Get
  gapis/server/grpc.go:214  github.com/google/gapid/gapis/server.(*grpcServer).Get
  bazel-out/x64_windows-opt/bin/gapis/service/windows_amd64_stripped/service_go_proto%/github.com/google/gapid/gapis/service/service.pb.go:9461  github.com/google/gapid/gapis/service._Gapid_Get_Handler.func1
  core/app/auth/auth.go:110  github.com/google/gapid/core/app/auth.ServerInterceptor.func1
  bazel-out/x64_windows-opt/bin/gapis/service/windows_amd64_stripped/service_go_proto%/github.com/google/gapid/gapis/service/service.pb.go:9463  github.com/google/gapid/gapis/service._Gapid_Get_Handler
  external/org_golang_google_grpc/server.go:971  google.golang.org/grpc.(*Server).processUnaryRPC
  external/org_golang_google_grpc/server.go:1250  google.golang.org/grpc.(*Server).handleStream

 Build() #0:
  gapis/database/database.go:60  github.com/google/gapid/gapis/database.Build
  gapis/resolve/get.go:26  github.com/google/gapid/gapis/resolve.Get
  gapis/server/server.go:425  github.com/google/gapid/gapis/server.(*server).Get
  gapis/server/grpc.go:214  github.com/google/gapid/gapis/server.(*grpcServer).Get
  bazel-out/x64_windows-opt/bin/gapis/service/windows_amd64_stripped/service_go_proto%/github.com/google/gapid/gapis/service/service.pb.go:9461  github.com/google/gapid/gapis/service._Gapid_Get_Handler.func1
  core/app/auth/auth.go:110  github.com/google/gapid/core/app/auth.ServerInterceptor.func1
  bazel-out/x64_windows-opt/bin/gapis/service/windows_amd64_stripped/service_go_proto%/github.com/google/gapid/gapis/service/service.pb.go:9463  github.com/google/gapid/gapis/service._Gapid_Get_Handler
  external/org_golang_google_grpc/server.go:971  google.golang.org/grpc.(*Server).processUnaryRPC
  external/org_golang_google_grpc/server.go:1250  google.golang.org/grpc.(*Server).handleStream

[signal 0xc0000005 code=0x0 addr=0x0 pc=0x1df5d25]

goroutine 414 [running]:
github.com/google/gapid/core/app/crash.Crash(0x5afdb40, 0xc01d5fb760)
	core/app/crash/crash.go:89 +0xae
github.com/google/gapid/core/app/crash.handler()
	core/app/crash/crash.go:56 +0x59
panic(0x5afdb40, 0xc01d5fb760)
	GOROOT/src/runtime/panic.go:522 +0x1c3
github.com/google/gapid/gapis/database.(*memory).resolvePanicHandler(0xc0002a32a0, 0x738c9c0, 0xc0208c77a0)
	gapis/database/debug.go:106 +0x775
panic(0x5cb88a0, 0x4dbc700)
	GOROOT/src/runtime/panic.go:522 +0x1c3
github.com/google/gapid/gapis/api/gles.TextureUnitʳ.ID(...)
	bazel-out/x64_windows-opt/bin/gapis/api/gles/api_amrp.go:23863
github.com/google/gapid/gapis/api/gles.(*stateBuilder).contextObjectPostEGLImage(0xc0001a9480, 0x738c9c0, 0xc0208c7890, 0x72969c5400, 0xc026b24c30, 0x1063b)
	gapis/api/gles/state_builder.go:495 +0x10c5
github.com/google/gapid/gapis/api/gles.API.RebuildState(0x738c9c0, 0xc0208c7890, 0xc022a73110, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0)
	gapis/api/gles/state_builder.go:102 +0x5d9
github.com/google/gapid/gapis/resolve/initialcmds.(*InitialCmdsResolvable).Resolve(0xc0208c76b0, 0x738c9c0, 0xc0208c7890, 0xc0208c7890, 0xc00045ff00, 0x2, 0x2)
	gapis/resolve/initialcmds/initial_commands.go:62 +0x1e6
github.com/google/gapid/gapis/database.(*record).resolve(0xc0211fdd40, 0x738c9c0, 0xc0208c7890, 0x0, 0x0)
	gapis/database/memory.go:137 +0x229
github.com/google/gapid/gapis/database.(*memory).resolveLocked.func1()
	gapis/database/memory.go:241 +0x13b
github.com/google/gapid/core/app/crash.Go.func1(0xc0208c7740)
	core/app/crash/crash.go:65 +0x4a
created by github.com/google/gapid/core/app/crash.Go
	core/app/crash/crash.go:63 +0x46

GAPID Version: 1.7.0:dev-20191206-c588accd00109397ab1729a2a5ebc2375ab5152d
OS: windows 10 amd64

Please provide detailed steps that led to the error and copy-paste the stack trace.
Extra details from the logs and the trace file would be extra helpful.

**Comment by AWoloszyn** [comment]
Relevant callstack 
```
github.com/google/gapid/gapis/api/gles.TextureUnitʳ.ID(...)
bazel-out/x64_windows-opt/bin/gapis/api/gles/api_amrp.go:23863
github.com/google/gapid/gapis/api/gles.(*stateBuilder).contextObjectPostEGLImage(0xc0001a9480, 0x738c9c0, 0xc0208c7890, 0x72969c5400, 0xc026b24c30, 0x1063b)
gapis/api/gles/state_builder.go:495 +0x10c5
```
