### ISSUE TITLE
Crash while opening a perfetto trace on the internal test cube app

### ISSUE THREAD

**Issue by pau-baiget** [google/gapid#3541]
Crash while opening a perfetto trace on the internal test cube app (20 seconds). FWIW, I waited a few minutes before clicking "Open trace".

GAPID Version: 1.7.0:developer
OS: linux amd64

Please provide detailed steps that led to the error and copy-paste the stack trace.
```fatal error: unexpected signal during runtime execution
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x4f8855e]

runtime stack:
runtime.throw(0x66e0c3b, 0x2a)
	GOROOT/src/runtime/panic.go:617 +0x72
runtime.sigpanic()
	GOROOT/src/runtime/signal_unix.go:374 +0x4a9

goroutine 5343 [syscall]:
runtime.cgocall(0x4c9e7a7, 0xc003e2d810, 0xc018000000)
	GOROOT/src/runtime/cgocall.go:128 +0x5b fp=0xc003e2d7e0 sp=0xc003e2d7a8 pc=0xadd4fb
github.com/google/gapid/gapis/perfetto._Cfunc_parse_data(0x7f4310001000, 0xc018000000, 0x7f7fc4c, 0x0)
	bazel-out/k8-fastbuild/bin/gapis/perfetto/linux_amd64_stripped/go_default_library%linux_amd64%cgo_codegen%/_cgo_gotypes.go:265 +0x4a fp=0xc003e2d810 sp=0xc003e2d7e0 pc=0x11c503a
github.com/google/gapid/gapis/perfetto.NewProcessor.func1(0x7f4310001000, 0xc003e2d8f0, 0x66a76c7)
	processor.go:38 +0x11c fp=0xc003e2d860 sp=0xc003e2d810 pc=0x11c524c
github.com/google/gapid/gapis/perfetto.NewProcessor(0x70fc160, 0xc001ad0f30, 0xc018000000, 0x7f7fc4c, 0x7fffe00, 0x7fffe00, 0x0, 0x0)
	processor.go:38 +0xc8 fp=0xc003e2d8e0 sp=0xc003e2d860 pc=0x11c49d8
github.com/google/gapid/gapis/capture.deserializePerfettoTrace(0x70fc160, 0xc001ad0f30, 0xc001ab0e40, 0x6f1ebc0, 0xc001ab0fc0, 0x0, 0x0, 0x0, 0x0)
	gapis/capture/perfetto.go:76 +0x163 fp=0xc003e2d948 sp=0xc003e2d8e0 pc=0x11d0bc3
github.com/google/gapid/gapis/capture.fromProto(0x70fc160, 0xc001ad0f30, 0xc001ab0e40, 0x0, 0x0, 0x0, 0x0)
	gapis/capture/capture.go:286 +0x464 fp=0xc003e2da10 sp=0xc003e2d948 pc=0x11c9c34
github.com/google/gapid/gapis/capture.fromProtoWrapped(0x70fc160, 0xc001ad0e40, 0xc001ab0e40, 0x0, 0x0, 0x0, 0x0)
	gapis/capture/capture.go:303 +0x3f fp=0xc003e2da58 sp=0xc003e2da10 pc=0x11c9f0f
runtime.call64(0xc000642210, 0x6733cb0, 0xc004593700, 0x1800000038)
	GOROOT/src/runtime/asm_amd64.s:520 +0x3b fp=0xc003e2daa8 sp=0xc003e2da58 pc=0xb3578b
reflect.Value.call(0x590e780, 0x6733cb0, 0x13, 0x6659cbc, 0x4, 0xc000560e30, 0x2, 0x2, 0x0, 0xc869680, ...)
	GOROOT/src/reflect/value.go:447 +0x461 fp=0xc003e2dcc8 sp=0xc003e2daa8 pc=0xb66c11
reflect.Value.Call(0x590e780, 0x6733cb0, 0x13, 0xc0003a4e30, 0x2, 0x2, 0x3, 0xc001ad0e40, 0xc0003a4db0)
	GOROOT/src/reflect/value.go:308 +0xa4 fp=0xc003e2dd30 sp=0xc003e2dcc8 pc=0xb66694
github.com/google/gapid/core/data/protoconv.ToObject(0x70fc160, 0xc001ad0e40, 0x703e620, 0xc001ab0e40, 0xc001ab0e40, 0xc0003a4e01, 0xc00090a300, 0xc000802230)
	core/data/protoconv/protoconv.go:156 +0x2c6 fp=0xc003e2de70 sp=0xc003e2dd30 pc=0x1073d96
github.com/google/gapid/gapis/database.(*record).resolve(0xc001ab0ea0, 0x70fc160, 0xc001ad0e40, 0x0, 0x0)
	gapis/database/memory.go:112 +0x302 fp=0xc003e2df30 sp=0xc003e2de70 pc=0x1080c02
github.com/google/gapid/gapis/database.(*memory).resolveLocked.func1()
	gapis/database/memory.go:241 +0x134 fp=0xc003e2dfb8 sp=0xc003e2df30 pc=0x1082dd4
github.com/google/gapid/core/app/crash.Go.func1(0xc001ad0de0)
	core/app/crash/crash.go:65 +0x43 fp=0xc003e2dfd8 sp=0xc003e2dfb8 pc=0xc07383
runtime.goexit()
	GOROOT/src/runtime/asm_amd64.s:1337 +0x1 fp=0xc003e2dfe0 sp=0xc003e2dfd8 pc=0xb37421
created by github.com/google/gapid/core/app/crash.Go
	core/app/crash/crash.go:63 +0x3f

goroutine 1 [select, 7 minutes]:
github.com/google/gapid/gapis/server.NewWithListener(0x70fc160, 0xc00006aa50, 0x7042fe0, 0xc0005ee7a0, 0xc0005fa060, 0xc0005ae008, 0x1, 0x1, 0x1, 0x7ffdd2423ece, ...)
	gapis/server/grpc.go:84 +0x3c6
github.com/google/gapid/gapis/server.Listen(0x70fc160, 0xc00006aa50, 0x666533e, 0xb, 0xc0005fa060, 0xc0005ae008, 0x1, 0x1, 0x1, 0x7ffdd2423ece, ...)
	gapis/server/grpc.go:50 +0xff
main.run(0x70fc160, 0xc00006aa50, 0xc000230380, 0x5)
	cmd/gapis/main.go:141 +0x764
github.com/google/gapid/core/app.doRun(0x6734690, 0x0)
	core/app/run.go:283 +0x3e3
github.com/google/gapid/core/app.Run(0x6734690)
	core/app/run.go:176 +0x2b
main.main()
	cmd/gapis/main.go:71 +0x75

goroutine 5 [syscall, 7 minutes]:
os/signal.signal_recv(0x0)
	GOROOT/src/runtime/sigqueue.go:139 +0x9c
os/signal.loop()
	GOROOT/src/os/signal/signal_unix.go:23 +0x22
created by os/signal.init.0
	GOROOT/src/os/signal/signal_unix.go:29 +0x41

goroutine 141 [select]:
github.com/google/gapid/core/app/analytics.(*batcher).run(0xc0004e5020)
	core/app/analytics/batcher.go:67 +0x1ea
created by github.com/google/gapid/core/app/analytics.newBatcher
	core/app/analytics/batcher.go:40 +0xca

goroutine 126 [chan receive, 5 minutes]:
github.com/google/gapid/core/log.Channel.func1()
	core/log/channel.go:30 +0xa7
github.com/google/gapid/core/app/crash.Go.func1(0xc000068210)
	core/app/crash/crash.go:65 +0x43
created by github.com/google/gapid/core/app/crash.Go
	core/app/crash/crash.go:63 +0x3f

goroutine 143 [chan receive, 7 minutes]:
github.com/google/gapid/core/app.handleAbortSignals.func1()
	core/app/atexit.go:95 +0x69
github.com/google/gapid/core/app/crash.Go.func1(0xc00006a690)
	core/app/crash/crash.go:65 +0x43
created by github.com/google/gapid/core/app/crash.Go
	core/app/crash/crash.go:63 +0x3f

goroutine 144 [chan receive, 7 minutes]:
github.com/google/gapid/core/app.AddCleanup.func1()
	core/app/atexit.go:59 +0x8b
github.com/google/gapid/core/app/crash.Go.func1(0xc00006a810)
	core/app/crash/crash.go:65 +0x43
created by github.com/google/gapid/core/app/crash.Go
	core/app/crash/crash.go:63 +0x3f

goroutine 145 [select, 7 minutes]:
reflect.rselect(0xc0005de080, 0x2, 0x2, 0xc0005de080, 0xc0005966d8)
	GOROOT/src/runtime/select.go:542 +0x38d
reflect.Select(0xc0005969a0, 0x2, 0x64, 0xc0005ac090, 0x0, 0x0, 0x0, 0x70fc160)
	GOROOT/src/reflect/value.go:2165 +0x171
github.com/google/gapid/gapis/replay/scheduler.(*Scheduler).run(0xc00006ab40, 0x70fc160, 0xc00006ab10)
	gapis/replay/scheduler/scheduler.go:200 +0x7f0
github.com/google/gapid/gapis/replay/scheduler.New.func1()
	gapis/replay/scheduler/scheduler.go:78 +0x3c
github.com/google/gapid/core/app/crash.Go.func1(0xc0004e55a0)
	core/app/crash/crash.go:65 +0x43
created by github.com/google/gapid/core/app/crash.Go
	core/app/crash/crash.go:63 +0x3f

goroutine 146 [select, 1 minutes]:
github.com/google/gapid/core/os/android/adb.Monitor(0x70fc160, 0xc00006aa50, 0xc00006a750, 0xb2d05e00, 0x0, 0x0)
	core/os/android/adb/device.go:92 +0x2eb
main.monitorAndroidDevices(0x70fc160, 0xc00006aa50, 0xc00006a750, 0xc000373f98)
	cmd/gapis/main.go:172 +0x79
main.run.func1()
	cmd/gapis/main.go:124 +0x63
github.com/google/gapid/core/app/crash.Go.func1(0xc00006ab70)
	core/app/crash/crash.go:65 +0x43
created by github.com/google/gapid/core/app/crash.Go
	core/app/crash/crash.go:63 +0x3f

goroutine 212 [select, 5 minutes]:
io.(*pipe).Read(0xc0005e0500, 0xc000639000, 0x1000, 0x1000, 0xc00018ecc8, 0x2, 0x0)
	GOROOT/src/io/pipe.go:50 +0xe7
io.(*PipeReader).Read(0xc00063c068, 0xc000639000, 0x1000, 0x1000, 0x6735038, 0xc1aed2, 0xc00018ed48)
	GOROOT/src/io/pipe.go:127 +0x4c
bufio.(*Reader).fill(0xc00018ef50)
	GOROOT/src/bufio/bufio.go:100 +0x10f
bufio.(*Reader).ReadSlice(0xc00018ef50, 0xc00018ee0a, 0xc17500, 0xc935bc0, 0xc0045750e0, 0x6683d97, 0x14)
	GOROOT/src/bufio/bufio.go:356 +0x3d
bufio.(*Reader).ReadBytes(0xc00018ef50, 0xc00006aa0a, 0x6683d97, 0x14, 0xc00018eed8, 0x1, 0x1)
	GOROOT/src/bufio/bufio.go:434 +0x70
bufio.(*Reader).ReadString(...)
	GOROOT/src/bufio/bufio.go:474
github.com/google/gapid/gapidapk.launchPerfettoProducerFromApk.func1()
	gapidapk/deviceinfo.go:183 +0x214
github.com/google/gapid/core/app/crash.Go.func1(0xc00063ed80)
	core/app/crash/crash.go:65 +0x43
created by github.com/google/gapid/core/app/crash.Go
	core/app/crash/crash.go:63 +0x3f

goroutine 162 [select, 7 minutes]:
github.com/google/gapid/gapis/replay/scheduler.(*Scheduler).run.func2()
	gapis/replay/scheduler/scheduler.go:181 +0x340
github.com/google/gapid/core/app/crash.Go.func1(0xc0005de040)
	core/app/crash/crash.go:65 +0x43
created by github.com/google/gapid/core/app/crash.Go
	core/app/crash/crash.go:63 +0x3f

goroutine 128 [IO wait, 7 minutes]:
internal/poll.runtime_pollWait(0x7f43e00a59c0, 0x72, 0x0)
	GOROOT/src/runtime/netpoll.go:182 +0x56
internal/poll.(*pollDesc).wait(0xc000600298, 0x72, 0x0, 0x0, 0x665d994)
	GOROOT/src/internal/poll/fd_poll_runtime.go:87 +0x9b
internal/poll.(*pollDesc).waitRead(...)
	GOROOT/src/internal/poll/fd_poll_runtime.go:92
internal/poll.(*FD).Accept(0xc000600280, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0)
	GOROOT/src/internal/poll/fd_unix.go:384 +0x1ba
net.(*netFD).accept(0xc000600280, 0xc0005ae401, 0x0, 0x0)
	GOROOT/src/net/fd_unix.go:238 +0x42
net.(*TCPListener).accept(0xc0005ee7a0, 0xc000562d28, 0xc000562d30, 0x18)
	GOROOT/src/net/tcpsock_posix.go:139 +0x32
net.(*TCPListener).Accept(0xc0005ee7a0, 0x6734198, 0xc00036a900, 0x712a480, 0xc0005ae4d8)
	GOROOT/src/net/tcpsock.go:260 +0x48
google.golang.org/grpc.(*Server).Serve(0xc00036a900, 0x7042fe0, 0xc0005ee7a0, 0x0, 0x0)
	external/org_golang_google_grpc/server.go:561 +0x1e9
github.com/google/gapid/core/net/grpcutil.ServeWithListener(0x70fc0a0, 0xc000645640, 0x7042fe0, 0xc0005ee7a0, 0xc0002c4000, 0xc000351770, 0x1, 0x1, 0x0, 0x0)
	core/net/grpcutil/server.go:53 +0x2a5
github.com/google/gapid/gapis/server.NewWithListener.func2()
	gapis/server/grpc.go:66 +0x188
github.com/google/gapid/core/app/crash.Go.func1(0xc0004f6120)
	core/app/crash/crash.go:65 +0x43
created by github.com/google/gapid/core/app/crash.Go
	core/app/crash/crash.go:63 +0x3f

goroutine 129 [select]:
github.com/google/gapid/gapis/server.(*grpcServer).stopIfIdle(0xc000645600, 0x70fc0a0, 0xc000645640, 0xc00036a900, 0xdf8475800, 0xc0005fe5b0)
	gapis/server/grpc.go:143 +0x205
github.com/google/gapid/gapis/server.NewWithListener.func2.1.1()
	gapis/server/grpc.go:76 +0x57
github.com/google/gapid/core/app/crash.Go.func1(0xc000600300)
	core/app/crash/crash.go:65 +0x43
created by github.com/google/gapid/core/app/crash.Go
	core/app/crash/crash.go:63 +0x3f

goroutine 198 [IO wait]:
internal/poll.runtime_pollWait(0x7f43e00a58f0, 0x72, 0xffffffffffffffff)
	GOROOT/src/runtime/netpoll.go:182 +0x56
internal/poll.(*pollDesc).wait(0xc0005ca298, 0x72, 0x8000, 0x8000, 0xffffffffffffffff)
	GOROOT/src/internal/poll/fd_poll_runtime.go:87 +0x9b
internal/poll.(*pollDesc).waitRead(...)
	GOROOT/src/internal/poll/fd_poll_runtime.go:92
internal/poll.(*FD).Read(0xc0005ca280, 0xc0005b0000, 0x8000, 0x8000, 0x0, 0x0, 0x0)
	GOROOT/src/internal/poll/fd_unix.go:169 +0x19b
net.(*netFD).Read(0xc0005ca280, 0xc0005b0000, 0x8000, 0x8000, 0x0, 0x800010601, 0x7f4300000000)
	GOROOT/src/net/fd_unix.go:202 +0x4f
net.(*conn).Read(0xc0005ae4d8, 0xc0005b0000, 0x8000, 0x8000, 0x0, 0x0, 0x0)
	GOROOT/src/net/net.go:177 +0x69
bufio.(*Reader).Read(0xc0005f4360, 0xc0002343b8, 0x9, 0x9, 0xc0001ae380, 0x7f43e3b306d0, 0x0)
	GOROOT/src/bufio/bufio.go:223 +0x23e
io.ReadAtLeast(0x6f1ebc0, 0xc0005f4360, 0xc0002343b8, 0x9, 0x9, 0x9, 0xbf74bb0005bb3c8a, 0x6cfcc61110, 0xc9360a0)
	GOROOT/src/io/io.go:310 +0x88
io.ReadFull(...)
	GOROOT/src/io/io.go:329
golang.org/x/net/http2.readFrameHeader(0xc0002343b8, 0x9, 0x9, 0x6f1ebc0, 0xc0005f4360, 0x0, 0x0, 0xc0001ce140, 0x7070e0910100402)
	external/org_golang_x_net/http2/frame.go:237 +0x88
golang.org/x/net/http2.(*Framer).ReadFrame(0xc000234380, 0xc000732000, 0xc000732000, 0x0, 0x0)
	external/org_golang_x_net/http2/frame.go:492 +0xa1
google.golang.org/grpc/internal/transport.(*http2Server).HandleStreams(0xc0003a9e00, 0xc0005a2120, 0x67341f0)
	external/org_golang_google_grpc/internal/transport/http2_server.go:429 +0x7c
google.golang.org/grpc.(*Server).serveStreams(0xc00036a900, 0x712b620, 0xc0003a9e00)
	external/org_golang_google_grpc/server.go:686 +0xdd
google.golang.org/grpc.(*Server).handleRawConn.func1(0xc00036a900, 0x712b620, 0xc0003a9e00)
	external/org_golang_google_grpc/server.go:648 +0x43
created by google.golang.org/grpc.(*Server).handleRawConn
	external/org_golang_google_grpc/server.go:647 +0x583

goroutine 197 [select, 7 minutes]:
google.golang.org/grpc/internal/transport.(*http2Server).keepalive(0xc0003a9e00)
	external/org_golang_google_grpc/internal/transport/http2_server.go:921 +0x1ed
created by google.golang.org/grpc/internal/transport.newHTTP2Server
	external/org_golang_google_grpc/internal/transport/http2_server.go:282 +0xfdf

goroutine 105 [select, 7 minutes]:
github.com/google/gapid/gapidapk.launchPerfettoProducerFromApk(0x70fc160, 0xc00006aa50, 0x7172340, 0xc0005fc040, 0xc0004f2ea0, 0x1, 0xc000352fa8)
	gapidapk/deviceinfo.go:214 +0x5b8
github.com/google/gapid/gapidapk.fetchDeviceInfo.func1()
	gapidapk/deviceinfo.go:113 +0x61
github.com/google/gapid/core/app/crash.Go.func1(0xc0005a44e0)
	core/app/crash/crash.go:65 +0x43
created by github.com/google/gapid/core/app/crash.Go
	core/app/crash/crash.go:63 +0x3f

goroutine 196 [select]:
google.golang.org/grpc/internal/transport.(*controlBuffer).get(0xc0005deb80, 0x1, 0x0, 0x0, 0x0, 0x0)
	external/org_golang_google_grpc/internal/transport/controlbuf.go:317 +0x104
google.golang.org/grpc/internal/transport.(*loopyWriter).run(0xc0005fa0c0, 0x0, 0x0)
	external/org_golang_google_grpc/internal/transport/controlbuf.go:435 +0x1b6
google.golang.org/grpc/internal/transport.newHTTP2Server.func2(0xc0003a9e00)
	external/org_golang_google_grpc/internal/transport/http2_server.go:276 +0xcb
created by google.golang.org/grpc/internal/transport.newHTTP2Server
	external/org_golang_google_grpc/internal/transport/http2_server.go:273 +0xfba

goroutine 200 [select]:
github.com/google/gapid/core/event/task.Poll(0x70fc0a0, 0xc000671300, 0x3b9aca00, 0x6733e38, 0x0, 0xc0001e4730)
	core/event/task/task.go:77 +0x10d
github.com/google/gapid/gapis/server.(*server).Status.func1(0x70fc0a0, 0xc000671300, 0xb06a4f, 0x0)
	gapis/server/server.go:690 +0x4a
github.com/google/gapid/core/event/task.Async.func1()
	core/event/task/task.go:91 +0x43
github.com/google/gapid/core/app/crash.Go.func1(0xc0005ac900)
	core/app/crash/crash.go:65 +0x43
created by github.com/google/gapid/core/app/crash.Go
	core/app/crash/crash.go:63 +0x3f

goroutine 244 [select, 5 minutes]:
reflect.rselect(0xc003d17f80, 0x2, 0x2, 0xc003d17f80, 0xc00059a6d8)
```

[gapic.log](https://github.com/google/gapid/files/3957000/gapic.log)
[gapis.log](https://github.com/google/gapid/files/3957001/gapis.log)

**Comment by pau-baiget** [comment]
UI now says:

```UNAVAILABLE: End of stream or IOException```

**Comment by pau-baiget** [comment]
[com.google.android.gapid.arm64v8a_20191212_1715.perfetto.zip](https://github.com/google/gapid/files/3957032/com.google.android.gapid.arm64v8a_20191212_1715.perfetto.zip)

**Comment by pmuetschard** [comment]
C++ stack trace:
```
#0  0x0000000004fa2cde in perfetto::trace_processor::GraphicsEventParser::ParseGpuRenderStageEvent(long, protozero::ConstBytes) ()
#1  0x0000000004fc23f1 in perfetto::trace_processor::ProtoTraceParser::ParseTracePacket(long, perfetto::trace_processor::TimestampedTracePiece) ()
#2  0x0000000004e90a5d in perfetto::trace_processor::TraceSorter::SortAndExtractEventsBeyondWindow(long) ()
#3  0x0000000004e8f87b in perfetto::trace_processor::TraceProcessorStorageImpl::NotifyEndOfFile() ()
#4  0x0000000004e6bc4a in perfetto::trace_processor::TraceProcessorImpl::NotifyEndOfFile() ()
#5  0x0000000004e5f601 in parse_data ()
```

**Comment by pmuetschard** [comment]
With line numbers:
```
#0  0x00005555556c2a4e in perfetto::trace_processor::GraphicsEventParser::ParseGpuRenderStageEvent(long, protozero::ConstBytes) () at /usr/include/c++/8/bits/stl_vector.h:930
#1  0x00005555556e8171 in perfetto::trace_processor::ProtoTraceParser::ParseTracePacket(long, perfetto::trace_processor::TimestampedTracePiece) ()
    at external/perfetto/src/trace_processor/trace_blob_view.h:104
#2  0x000055555571141d in perfetto::trace_processor::TraceSorter::SortAndExtractEventsBeyondWindow(long) () at external/perfetto/src/trace_processor/trace_blob_view.h:104
#3  0x0000555555710eeb in perfetto::trace_processor::TraceSorter::ExtractEventsForced (this=0x555555b58c90) at external/perfetto/src/trace_processor/trace_sorter.h:147
#4  perfetto::trace_processor::TraceProcessorStorageImpl::NotifyEndOfFile (this=0x555555ac6508) at external/perfetto/src/trace_processor/trace_processor_storage_impl.cc:109
#5  perfetto::trace_processor::TraceProcessorStorageImpl::NotifyEndOfFile (this=this@entry=0x555555ac6508) at external/perfetto/src/trace_processor/trace_processor_storage_impl.cc:104
#6  0x0000555555676c6a in perfetto::trace_processor::TraceProcessorImpl::NotifyEndOfFile() () at external/perfetto/src/trace_processor/trace_processor_impl.cc:472
```

**Comment by pmuetschard** [comment]
So the problem here is that we get a GPU slice data packet before we ever get a packet with a specification. Looking at the trace processor code, this is quite brittle. We make a bunch of assumptions that can way to easily be broken.

**Comment by AWoloszyn** [comment]
Also a note: perfetto can/does drop packets from time to time, so the trace processor should be resilient to that

**Comment by pau-baiget** [comment]
This needs to be fixed soon since it renders the application unusable for a potential common use case (taking 20 seconds of any app)

@rschiu is this something you could look at?

**Comment by rschiu** [comment]
It's definitely a bug and not meant to be this brittle.  I will work on it.

**Comment by rschiu** [comment]
aosp/1190030

**Comment by rschiu** [comment]
fixed
