### ISSUE TITLE
Unhandled Exception opening Trace

### ISSUE THREAD

**Issue by mattyclarkson** [google/gapid#3647]
**Environment information:**
 - GAPID version: 1.7.0:dev-20200109-144f23e08a5e5bd413d4bb75dca9ea65bf5dc6e4
 - Host OS: Windows 10
 If tracing on Android:
 - Device model: Samsung 9820 Exynos
 - Android Version: 10

**Bug description**
Unhandled exception opening trace.

**Reproduction steps**
Open `trace.perfetto` in [trace.zip](https://github.com/google/gapid/files/4059410/trace.zip)

**Stacktrace**
```
java.lang.IllegalArgumentException: %d > %d [85040352460800, 77309411328000]
	at com.google.common.base.Preconditions.checkArgument(Preconditions.java:370)
	at com.google.gapid.perfetto.TimeSpan.<init>(TimeSpan.java:46)
	at com.google.gapid.perfetto.TimeSpan.align(TimeSpan.java:78)
	at com.google.gapid.perfetto.models.Track$DataRequest.pageAlign(Track.java:192)
	at com.google.gapid.perfetto.models.Track.getData(Track.java:80)
	at com.google.gapid.perfetto.views.GpuQueuePanel.onTrackMouseMove(GpuQueuePanel.java:158)
	at com.google.gapid.perfetto.views.TrackPanel.onMouseMove(TrackPanel.java:122)
	at com.google.gapid.perfetto.views.TrackContainer$Single.onMouseMove(TrackContainer.java:191)
	at com.google.gapid.perfetto.canvas.PanelGroup.onMouseMove(PanelGroup.java:148)
	at com.google.gapid.perfetto.views.CopyablePanel$Group.onMouseMove(CopyablePanel.java:79)
	at com.google.gapid.perfetto.views.TrackContainer$Group.onMouseMove(TrackContainer.java:365)
	at com.google.gapid.perfetto.canvas.PanelGroup.onMouseMove(PanelGroup.java:148)
	at com.google.gapid.perfetto.views.CopyablePanel$Group.onMouseMove(CopyablePanel.java:79)
	at com.google.gapid.perfetto.views.TrackContainer$Group.onMouseMove(TrackContainer.java:365)
	at com.google.gapid.perfetto.canvas.PanelGroup.onMouseMove(PanelGroup.java:148)
	at com.google.gapid.perfetto.views.RootPanel.onMouseMove(RootPanel.java:377)
	at com.google.gapid.perfetto.canvas.PanelCanvas.updateMousePosition(PanelCanvas.java:145)
	at com.google.gapid.perfetto.canvas.PanelCanvas.lambda$new$5(PanelCanvas.java:92)
	at org.eclipse.swt.widgets.EventTable.sendEvent(EventTable.java:89)
	at org.eclipse.swt.widgets.Display.sendEvent(Display.java:4145)
	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1055)
	at org.eclipse.swt.widgets.Display.runDeferredEvents(Display.java:3958)
	at org.eclipse.swt.widgets.Display.readAndDispatch(Display.java:3561)
	at org.eclipse.jface.window.Window.runEventLoop(Window.java:821)
	at org.eclipse.jface.window.Window.open(Window.java:797)
	at com.google.gapid.Main$UI.show(Main.java:120)
	at com.google.gapid.Main.main(Main.java:69)
```

**Additional debugging information**
[gapic.log](https://github.com/google/gapid/files/4059393/gapic.log)
[gapis.log](https://github.com/google/gapid/files/4059394/gapis.log)

**Comment by pmuetschard** [comment]
This has been fixed and is no longer present on master.

**Comment by pmuetschard** [comment]
Wow, oops, never mind. It didn't repro for me on master, because my window was just big enough not to trigger this bug.... try making your window wider than 800px. yikes.

**Comment by hevrard** [comment]
@mattyclarkson today's dev-release contains Pascal fix, you can grab it from there:
https://github.com/google/gapid-dev-releases/releases/latest
