### ISSUE TITLE
The application encountered an error: Tracing Failed    Cause: EOF

### ISSUE THREAD

**Issue by dario-DI** [google/gapid#3823]
**Environment information:**
 - GAPID version:
 - Host OS: [e.g. Linux]
 If tracing on Android:
 - Device model:
 - Android Version: 8.1

**Bug description**
Cannot capture traces

**Reproduction steps**

**Stacktrace**
com.google.gapid.server.Client$InternalServerErrorException: Tracing Failed
   Cause: EOF
	at com.google.gapid.server.Client.throwIfError(Client.java:312)
	at com.google.gapid.server.Client.lambda$streamTrace$52(Client.java:286)
	at com.google.gapid.server.GapidClientGrpc$StreamHandler.onNext(GapidClientGrpc.java:224)
	at io.grpc.stub.ClientCalls$StreamObserverToCallListenerAdapter.onMessage(ClientCalls.java:421)
	at io.grpc.ForwardingClientCallListener.onMessage(ForwardingClientCallListener.java:33)
	at io.grpc.ForwardingClientCallListener.onMessage(ForwardingClientCallListener.java:33)
	at io.grpc.internal.ClientCallImpl$ClientStreamListenerImpl$1MessagesAvailable.runInContext(ClientCallImpl.java:519)
	at io.grpc.internal.ContextRunnable.run(ContextRunnable.java:37)
	at io.grpc.internal.SerializingExecutor.run(SerializingExecutor.java:123)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: com.google.gapid.server.Client$Stack: For request: RPC->streamTrace()
	at com.google.gapid.server.Client.streamTrace(Client.java:283)
	at com.google.gapid.server.Tracer.trace(Tracer.java:41)
	at com.google.gapid.views.TracerDialog.showTracingDialog(TracerDialog.java:159)
	at com.google.gapid.LoadingScreen.lambda$createOptions$0(LoadingScreen.java:119)
	at org.eclipse.swt.widgets.EventTable.sendEvent(EventTable.java:89)
	at org.eclipse.swt.widgets.Display.sendEvent(Display.java:4292)
	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1512)
	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1535)
	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1520)
	at org.eclipse.swt.widgets.Widget.notifyListeners(Widget.java:1324)
	at org.eclipse.swt.widgets.Display.runDeferredEvents(Display.java:4116)
	at org.eclipse.swt.widgets.Display.readAndDispatch(Display.java:3733)
	at org.eclipse.jface.window.Window.runEventLoop(Window.java:821)
	at org.eclipse.jface.window.Window.open(Window.java:797)
	at com.google.gapid.Main$UI.show(Main.java:120)
	at com.google.gapid.Main.main(Main.java:69)

**Screenshots**
![image](https://user-images.githubusercontent.com/1464564/83113406-333b1680-a0fa-11ea-80a6-510bb8cf7fcd.png)

**Additional debugging information**
- Please attach the generated _gapis.log_ and _gapic.log_ files you will find in the temp folder (e.g. /tmp/ on linux). 
- If using Android: Please attach a full logcat dump (```adb logcat -d > logcat-full.txt```) that contains logs since GAPID was started.

**Comment by pau-baiget** [comment]
Thanks @dario-DI for reporting this issue. The GAPID project has been moved to [maintenance mode](https://github.com/google/gapid#maintenance-mode) and therefore no active development is done on this repository.

We are focusing our efforts on the Android GPU Inspector: https://github.com/google/agi
