### ISSUE TITLE
The gapis server has exited with an error code of: -42

### ISSUE THREAD

**Issue by idloafer** [google/gapid#3870]
GAPID Version: 1.6.1:338bb67b0fe291f56f31d69f11ea1a45ed7cfeb6
OS: mac os x x86_64 12.0.1

GAPID can't start up when my mac min OS update to Monterey. Here is the error trace

com.google.gapid.Server$GapisInitException: Failed to connect to the graphics debugger
	at com.google.gapid.Server.connectToServer(Server.java:103)
	at com.google.gapid.Server.connect(Server.java:71)
	at com.google.gapid.Main$UI.startup(Main.java:135)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)

**Comment by idloafer** [comment]
Here is some from gapic.log
I20211110-235828459[pool-1-thread-1][server.GapiPaths.checkForTools] Looking for GAPID in /Applications/GAPID.app/Contents/MacOS -> /Applications/GAPID.app/Contents/MacOS/gapis
I20211110-235828476[server.ChildProcess-gapis][server.ChildProcess.runProcess] Starting gapis as [/Applications/GAPID.app/Contents/MacOS/gapis, -enable-local-files, -crashreport, -analytics, e43c856a-75e3-4460-9976-17f20aff4ba4, -log-file, /var/folders/n8/fmbx1dtj6776_q5zvx9fk7k80000gn/T/gapis.log, -log-level, Info, -gapir-args, --log /var/folders/n8/fmbx1dtj6776_q5zvx9fk7k80000gn/T/gapir.log --log-level I, --strings, /Applications/GAPID.app/Contents/MacOS/strings, --gapis-auth-token, kQhwGuNC, --idle-timeout, 60000ms, --adb, /Users/shenhui/Library/Android/sdk/platform-tools/adb]
I20211110-235828527[server.ChildProcess$LoggingStringHandler][server.ChildProcess$LoggingStringHandler.lambda$new$0] gapis: 15:58:28.526 I: <gapis> Logging to: /var/folders/n8/fmbx1dtj6776_q5zvx9fk7k80000gn/T/gapis.log
I20211110-235828583[server.ChildProcess$LoggingStringHandler][server.ChildProcess$LoggingStringHandler.lambda$new$0] gapis: 23:58:28.582 F : [core/cc/dl_loader.cpp:77] Can't load library /System/Library/Frameworks/OpenGL.framework/OpenGL: dlopen(/tmp/dlopen.bcnqo1, 0x0106): tried: '/tmp/dlopen.bcnqo1' (no such file), '/usr/local/lib/dlopen.bcnqo1' (no such file), '/usr/lib/dlopen.bcnqo1' (no such file), '/private/tmp/dlopen.bcnqo1' (no such file), '/usr/local/lib/dlopen.bcnqo1' (no such file), '/usr/lib/dlopen.bcnqo1' (no such file)
W20211110-235828587[server.ChildProcess-gapis][server.ChildProcess.onExit] The gapis process exited with a non-zero exit value: 1
I20211110-235828587[server.ChildProcess-gapis][server.ChildProcess.shutdown] Shutting down gapis
W20211110-235828587[pool-1-thread-1][server.GapisProcess.connect] Failed while waiting for gapis
W20211110-235828587[pool-1-thread-1][server.GapisProcess.connect] java.util.concurrent.ExecutionException: com.google.gapid.server.ChildProcess$EarlyExitException: gapis has exited with exit code 1

**Comment by dryganets** [comment]
You could try latest dev version.
It is working for me.

The monteray doesn't have opengl anymore.
