### ISSUE TITLE
The gapis server has exited with an error code of: -42

### ISSUE THREAD

**Issue by mymottoissh** [google/gapid#3898]
GAPID Version: 1.6.1:338bb67b0fe291f56f31d69f11ea1a45ed7cfeb6
OS: mac os x x86_64

[gapid-1.6.1-macos.dmg](https://github.com/google/gapid/releases/download/v1.6.1/gapid-1.6.1-macos.dmg)
dmg software downloaded from the link above can not be opened on my mac pro device. 
error message was reported as below:

com.google.gapid.Server$GapisInitException: Failed to connect to the graphics debugger
	at com.google.gapid.Server.connectToServer(Server.java:103)
	at com.google.gapid.Server.connect(Server.java:71)
	at com.google.gapid.Main$UI.startup(Main.java:135)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)

I've tried several times, none of which succeeded.

**Comment by shanewu921** [comment]
the same to me

**Comment by urkle** [comment]
The issue here is macOS 11+ "hides" the the system libraries into an internal file and they dropped an old alias for OpenGL, thus the dlopen call as is being used by `gapis` cannot load OpenGL.framework/OpenGL.

this same issue affects apitrace and required some hackery to get it working again.  https://github.com/apitrace/apitrace/issues/826
