### ISSUE TITLE
Crash in UpdateImageData

### ISSUE THREAD

**Issue by ben-clayton** [google/gapid#512]
Appears to be introduced in https://github.com/google/gapid/commit/2c8486e8e6082afb90a821333b35ebd9d929600f:

```
./do run gapit commands capture.gfxtrace

20:51:56.191 E: <gapis> panic: uint8(0@0)[0].Slice(0, 16) - out of bounds
20:51:56.191 E: <gapis>
20:51:56.191 E: <gapis> goroutine 15 [running]:
20:51:56.191 E: <gapis> github.com/google/gapid/gapis/gfxapi/gles.U8ˢ.Slice(0x0, 0x0, 0x0, 0xc400000000, 0x0, 0x10, 0xc42001f800, 0x0, 0x0, 0x10, ...)
20:51:56.191 E: <gapis>         /Users/bclayton/src/go/src/github.com/google/gapid/gapis/gfxapi/gles/api.go:22109 +0x1ec
20:51:56.191 E: <gapis> github.com/google/gapid/gapis/gfxapi/gles.subUpdateImageData(0x6cde8a0, 0xc420204630, 0x6cf53a0, 0xc42038f860, 0x0, 0xc42ea9684
0, 0xc42eae4140, 0x0, 0xc430880400, 0x0, ...)
20:51:56.191 E: <gapis>         /Users/bclayton/src/go/src/github.com/google/gapid/gapis/gfxapi/gles/mutate.go:4898 +0x5a9
20:51:56.191 E: <gapis> github.com/google/gapid/gapis/gfxapi/gles.subTexImage(0x6cde8a0, 0xc420204630, 0x6cf53a0, 0xc42038f860, 0x0, 0xc42ea96840, 0xc4
2eae4140, 0x0, 0xde100000004, 0x0, ...)
20:51:56.191 E: <gapis>         /Users/bclayton/src/go/src/github.com/google/gapid/gapis/gfxapi/gles/mutate.go:4839 +0xdb8
20:51:56.191 E: <gapis> github.com/google/gapid/gapis/gfxapi/gles.(*GlTexImage2D).Mutate(0xc42038f860, 0x6cde8a0, 0xc420204630, 0xc42ea96840, 0x0, 0xc4
269d7050, 0xc42ea96840)
20:51:56.191 E: <gapis>         /Users/bclayton/src/go/src/github.com/google/gapid/gapis/gfxapi/gles/mutate.go:42770 +0x2ad
20:51:56.191 E: <gapis> github.com/google/gapid/gapis/resolve.(*CommandTreeResolvable).Resolve(0xc4203ac070, 0x6cde8a0, 0xc420204630, 0xa41f720, 0xc420
3ac070, 0x1, 0x6cb9260)
20:51:56.191 E: <gapis>         /Users/bclayton/src/go/src/github.com/google/gapid/gapis/resolve/command_tree.go:261 +0x314
20:51:56.191 E: <gapis> github.com/google/gapid/gapis/database.(*record).resolve(0xc420204210, 0x6cde7e0, 0xc420016640, 0xc42000a700, 0xc420148960)
20:51:56.191 E: <gapis>         /Users/bclayton/src/go/src/github.com/google/gapid/gapis/database/memory.go:72 +0x8a
20:51:56.191 E: <gapis> github.com/google/gapid/gapis/database.(*memory).resolveLocked.func1(0xc420204210, 0xc420016680, 0xc420388100)
20:51:56.191 E: <gapis>         /Users/bclayton/src/go/src/github.com/google/gapid/gapis/database/memory.go:144 +0x45
20:51:56.191 E: <gapis> created by github.com/google/gapid/gapis/database.(*memory).resolveLocked
20:51:56.191 E: <gapis>         /Users/bclayton/src/go/src/github.com/google/gapid/gapis/database/memory.go:151 +0x4ff
```

**Comment by dsrbecky** [comment]
Can you double check it happens with current head?

**Comment by dsrbecky** [comment]
Actually it looks different then what I fixed earlier today

**Comment by ben-clayton** [comment]
I'm uploading a trace that has a simple repro - my upload rate is horrific though, and it's failed twice already...

**Comment by ben-clayton** [comment]
Made P0 as this seems to affect a whole lot of traces.
