### ISSUE TITLE
Unresolved symbol "strtof" on Android 4.4.4

### ISSUE THREAD

**Issue by andrey-logvinov** [google/gapid#652]
```
E/dalvikvm(23163): dlopen("/data/app-lib/com.google.android.gapid.armeabi-1/libdeviceinfo.so") failed: dlopen failed: cannot locate symbol "strtof" referenced by "libdeviceinfo.so"...
E/gapid-pkginfo(23163): Error occurred
E/gapid-pkginfo(23163): java.util.concurrent.ExecutionException: java.lang.UnsatisfiedLinkError: dlopen failed: cannot locate symbol "strtof" referenced by "libdeviceinfo.so"...
E/gapid-pkginfo(23163): 	at java.util.concurrent.FutureTask.report(FutureTask.java:93)
E/gapid-pkginfo(23163): 	at java.util.concurrent.FutureTask.get(FutureTask.java:163)
E/gapid-pkginfo(23163): 	at com.google.android.gapid.SocketWriter.connectAndWrite(SocketWriter.java:45)
E/gapid-pkginfo(23163): 	at com.google.android.gapid.DeviceInfoService.handleSendDeviceInfo(DeviceInfoService.java:107)
E/gapid-pkginfo(23163): 	at com.google.android.gapid.DeviceInfoService.onHandleIntent(DeviceInfoService.java:88)
E/gapid-pkginfo(23163): 	at android.app.IntentService$ServiceHandler.handleMessage(IntentService.java:65)
E/gapid-pkginfo(23163): 	at android.os.Handler.dispatchMessage(Handler.java:110)
E/gapid-pkginfo(23163): 	at android.os.Looper.loop(Looper.java:193)
E/gapid-pkginfo(23163): 	at android.os.HandlerThread.run(HandlerThread.java:61)
E/gapid-pkginfo(23163): Caused by: java.lang.UnsatisfiedLinkError: dlopen failed: cannot locate symbol "strtof" referenced by "libdeviceinfo.so"...
E/gapid-pkginfo(23163): 	at java.lang.Runtime.loadLibrary(Runtime.java:378)
E/gapid-pkginfo(23163): 	at java.lang.System.loadLibrary(System.java:540)
E/gapid-pkginfo(23163): 	at com.google.android.gapid.DeviceInfoService$1.call(DeviceInfoService.java:100)
E/gapid-pkginfo(23163): 	at com.google.android.gapid.DeviceInfoService$1.call(DeviceInfoService.java:97)
E/gapid-pkginfo(23163): 	at java.util.concurrent.FutureTask.run(FutureTask.java:237)
E/gapid-pkginfo(23163): 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
E/gapid-pkginfo(23163): 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
E/gapid-pkginfo(23163): 	at java.lang.Thread.run(Thread.java:848)
```

I think it is related to https://stackoverflow.com/questions/43745312/unsatisfiedlinkerror-dlopen-failed-cannot-locate-symbol-strtof-referenced-by

**Comment by andrey-logvinov** [comment]
I figured out it is because gapid apk native is build with ANDROID_NDK_VERSION 21, there are differences in system libraries which makes the build incompatible with previous versions. Changing ANDROID_NDK_VERSION to 19 causes compilation errors.
Maybe it is worth stating in the documentation that the minimum supported Android version is in fact Lollipop?

**Comment by ben-clayton** [comment]
Hi @andrey-logvinov,

You're correct - the NDK has pulled things in and out of the standard libraries between versions, and it's clear we haven't been testing on devices pre-L. Given that [there's still ~18%](https://developer.android.com/about/dashboards/index.html) of devices running K, we should attempt to support it.

Cheers,
Ben

**Comment by ben-clayton** [comment]
[Now down to ~10%](https://developer.android.com/about/dashboards/index.html).
