### ISSUE TITLE
java.lang.ArrayIndexOutOfBoundsException

### ISSUE THREAD

**Issue by dsrbecky** [google/gapid#799]
```
W20170726-142102573[pool-4-thread-9][util.LoggingCallback.onFailure] Caused by: java.lang.ArrayIndexOutOfBoundsException: 1949
W20170726-142102573[pool-4-thread-9][util.LoggingCallback.onFailure] 	at com.google.gapid.models.AtomStream$Node.getChild(AtomStream.java:361)
W20170726-142102573[pool-4-thread-9][util.LoggingCallback.onFailure] 	at com.google.gapid.views.AtomTree.getTreePathForLoadedNode(AtomTree.java:522)
W20170726-142102573[pool-4-thread-9][util.LoggingCallback.onFailure] 	at com.google.gapid.views.AtomTree.lambda$getTreePath$11(AtomTree.java:515)
W20170726-142102573[pool-4-thread-9][util.LoggingCallback.onFailure] 	at com.google.common.util.concurrent.AbstractTransformFuture$AsyncTransformFuture.doTransform(AbstractTransformFuture.java:211)
W20170726-142102573[pool-4-thread-9][util.LoggingCallback.onFailure] 	at com.google.common.util.concurrent.AbstractTransformFuture$AsyncTransformFuture.doTransform(AbstractTransformFuture.java:200)
W20170726-142102573[pool-4-thread-9][util.LoggingCallback.onFailure] 	at com.google.common.util.concurrent.AbstractTransformFuture.run(AbstractTransformFuture.java:130)
W20170726-142102573[pool-4-thread-9][util.LoggingCallback.onFailure] 	at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:435)
W20170726-142102573[pool-4-thread-9][util.LoggingCallback.onFailure] 	at com.google.common.util.concurrent.AbstractFuture.executeListener(AbstractFuture.java:900)
W20170726-142102573[pool-4-thread-9][util.LoggingCallback.onFailure] 	at com.google.common.util.concurrent.AbstractFuture.complete(AbstractFuture.java:811)
W20170726-142102573[pool-4-thread-9][util.LoggingCallback.onFailure] 	at com.google.common.util.concurrent.AbstractFuture.set(AbstractFuture.java:653)
W20170726-142102573[pool-4-thread-9][util.LoggingCallback.onFailure] 	at com.google.common.util.concurrent.SettableFuture.set(SettableFuture.java:47)
W20170726-142102573[pool-4-thread-9][util.LoggingCallback.onFailure] 	at com.google.gapid.widgets.Widgets.lambda$submitIfNotDisposed$2(Widgets.java:160)
W20170726-142102573[pool-4-thread-9][util.LoggingCallback.onFailure] 	at com.google.gapid.widgets.Widgets.lambda$schedule$0(Widgets.java:137)
W20170726-142102573[pool-4-thread-9][util.LoggingCallback.onFailure] 	at org.eclipse.swt.widgets.RunnableLock.run(Unknown Source)
W20170726-142102573[pool-4-thread-9][util.LoggingCallback.onFailure] 	at org.eclipse.swt.widgets.Synchronizer.runAsyncMessages(Unknown Source)
W20170726-142102573[pool-4-thread-9][util.LoggingCallback.onFailure] 	at org.eclipse.swt.widgets.Display.runAsyncMessages(Unknown Source)
W20170726-142102573[pool-4-thread-9][util.LoggingCallback.onFailure] 	at org.eclipse.swt.widgets.Display.readAndDispatch(Unknown Source)
W20170726-142102573[pool-4-thread-9][util.LoggingCallback.onFailure] 	at org.eclipse.jface.window.Window.runEventLoop(Window.java:818)
W20170726-142102573[pool-4-thread-9][util.LoggingCallback.onFailure] 	at org.eclipse.jface.window.Window.open(Window.java:794)
W20170726-142102573[pool-4-thread-9][util.LoggingCallback.onFailure] 	at com.google.gapid.Main$UI.show(Main.java:111)
W20170726-142102573[pool-4-thread-9][util.LoggingCallback.onFailure] 	at com.google.gapid.Main.main(Main.java:70)
```

**Comment by pmuetschard** [comment]
Could you share the trace with me, please?
