### ISSUE TITLE
Can not connect to emulator or genymotion

### ISSUE THREAD

**Issue by stcdalyc** [google/gapid#822]
the main error is :
Cause: Invalid path 'device<0000000000000000000000000000000000000000>': ID 'id' is invalid

**Comment by tom3q** [comment]
I'm getting the same error when trying to connect to a device with adb over network. Here's the backtrace:

`E20170824-073012141[grpc-default-executor-1][models.Devices$3.onRpcThread] LoadData error
E20170824-073012141[grpc-default-executor-1][models.Devices$3.onRpcThread] com.google.gapid.server.Client$InternalServerErrorException: Invalid path: device<0000000000000000000000000000000000000000>
   Cause: Invalid path 'device<0000000000000000000000000000000000000000>': ID 'id' is invalid
E20170824-073012141[grpc-default-executor-1][models.Devices$3.onRpcThread]      at com.google.gapid.server.Client.throwIfError(Client.java:215)
E20170824-073012141[grpc-default-executor-1][models.Devices$3.onRpcThread]      at com.google.gapid.server.Client.lambda$get$5(Client.java:91)
E20170824-073012141[grpc-default-executor-1][models.Devices$3.onRpcThread]      at com.google.common.util.concurrent.AbstractTransformFuture$AsyncTransformFuture.doTransform(AbstractTransformFuture.java:211)
E20170824-073012141[grpc-default-executor-1][models.Devices$3.onRpcThread]      at com.google.common.util.concurrent.AbstractTransformFuture$AsyncTransformFuture.doTransform(AbstractTransformFuture.java:200)
E20170824-073012141[grpc-default-executor-1][models.Devices$3.onRpcThread]      at com.google.common.util.concurrent.AbstractTransformFuture.run(AbstractTransformFuture.java:130)
E20170824-073012141[grpc-default-executor-1][models.Devices$3.onRpcThread]      at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:435)
E20170824-073012141[grpc-default-executor-1][models.Devices$3.onRpcThread]      at com.google.common.util.concurrent.AbstractFuture.executeListener(AbstractFuture.java:900)
E20170824-073012141[grpc-default-executor-1][models.Devices$3.onRpcThread]      at com.google.common.util.concurrent.AbstractFuture.complete(AbstractFuture.java:811)
E20170824-073012141[grpc-default-executor-1][models.Devices$3.onRpcThread]      at com.google.common.util.concurrent.AbstractFuture.set(AbstractFuture.java:653)
E20170824-073012141[grpc-default-executor-1][models.Devices$3.onRpcThread]      at com.google.common.util.concurrent.AbstractTransformFuture$TransformFuture.setResult(AbstractTransformFuture.java:245)
E20170824-073012141[grpc-default-executor-1][models.Devices$3.onRpcThread]      at com.google.common.util.concurrent.AbstractTransformFuture.run(AbstractTransformFuture.java:177)
E20170824-073012141[grpc-default-executor-1][models.Devices$3.onRpcThread]      at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:435)
E20170824-073012141[grpc-default-executor-1][models.Devices$3.onRpcThread]      at com.google.common.util.concurrent.AbstractFuture.executeListener(AbstractFuture.java:900)
E20170824-073012141[grpc-default-executor-1][models.Devices$3.onRpcThread]      at com.google.common.util.concurrent.AbstractFuture.complete(AbstractFuture.java:811)
E20170824-073012141[grpc-default-executor-1][models.Devices$3.onRpcThread]      at com.google.common.util.concurrent.AbstractFuture.set(AbstractFuture.java:653)
E20170824-073012141[grpc-default-executor-1][models.Devices$3.onRpcThread]      at io.grpc.stub.ClientCalls$GrpcFuture.set(ClientCalls.java:461)
E20170824-073012141[grpc-default-executor-1][models.Devices$3.onRpcThread]      at io.grpc.stub.ClientCalls$UnaryStreamToFuture.onClose(ClientCalls.java:440)
E20170824-073012141[grpc-default-executor-1][models.Devices$3.onRpcThread]      at io.grpc.internal.ClientCallImpl$ClientStreamListenerImpl.close(ClientCallImpl.java:481)
E20170824-073012141[grpc-default-executor-1][models.Devices$3.onRpcThread]      at io.grpc.internal.ClientCallImpl$ClientStreamListenerImpl.access$600(ClientCallImpl.java:398)
E20170824-073012141[grpc-default-executor-1][models.Devices$3.onRpcThread]      at io.grpc.internal.ClientCallImpl$ClientStreamListenerImpl$1StreamClosed.runInContext(ClientCallImpl.java:513)
E20170824-073012141[grpc-default-executor-1][models.Devices$3.onRpcThread]      at io.grpc.internal.ContextRunnable.run(ContextRunnable.java:52)
E20170824-073012141[grpc-default-executor-1][models.Devices$3.onRpcThread]      at io.grpc.internal.SerializingExecutor$TaskRunner.run(SerializingExecutor.java:154)
E20170824-073012141[grpc-default-executor-1][models.Devices$3.onRpcThread]      at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
E20170824-073012141[grpc-default-executor-1][models.Devices$3.onRpcThread]      at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
E20170824-073012141[grpc-default-executor-1][models.Devices$3.onRpcThread]      at java.lang.Thread.run(Thread.java:748)
E20170824-073012141[grpc-default-executor-1][models.Devices$3.onRpcThread] Caused by: com.google.gapid.server.Client$Stack: For request: RPC->get(device { id { data: 0000000000000000000000000000000000000000 } })
E20170824-073012141[grpc-default-executor-1][models.Devices$3.onRpcThread]      at com.google.gapid.server.Client.get(Client.java:88)
E20170824-073012141[grpc-default-executor-1][models.Devices$3.onRpcThread]      at com.google.gapid.models.Devices.lambda$loadDevices$0(Devices.java:121)
E20170824-073012141[grpc-default-executor-1][models.Devices$3.onRpcThread]      at com.google.common.util.concurrent.AbstractTransformFuture$AsyncTransformFuture.doTransform(AbstractTransformFuture.java:211)
E20170824-073012141[grpc-default-executor-1][models.Devices$3.onRpcThread]      at com.google.common.util.concurrent.AbstractTransformFuture$AsyncTransformFuture.doTransform(AbstractTransformFuture.java:200)
E20170824-073012141[grpc-default-executor-1][models.Devices$3.onRpcThread]      at com.google.common.util.concurrent.AbstractTransformFuture.run(AbstractTransformFuture.java:130)
E20170824-073012141[grpc-default-executor-1][models.Devices$3.onRpcThread]      at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:435)
E20170824-073012141[grpc-default-executor-1][models.Devices$3.onRpcThread]      at com.google.common.util.concurrent.AbstractFuture.executeListener(AbstractFuture.java:900)
E20170824-073012141[grpc-default-executor-1][models.Devices$3.onRpcThread]      at com.google.common.util.concurrent.AbstractFuture.complete(AbstractFuture.java:811)
E20170824-073012141[grpc-default-executor-1][models.Devices$3.onRpcThread]      at com.google.common.util.concurrent.AbstractFuture.setFuture(AbstractFuture.java:711)
E20170824-073012141[grpc-default-executor-1][models.Devices$3.onRpcThread]      at com.google.common.util.concurrent.AbstractTransformFuture$AsyncTransformFuture.setResult(AbstractTransformFuture.java:221)
E20170824-073012141[grpc-default-executor-1][models.Devices$3.onRpcThread]      at com.google.common.util.concurrent.AbstractTransformFuture$AsyncTransformFuture.setResult(AbstractTransformFuture.java:200)
E20170824-073012141[grpc-default-executor-1][models.Devices$3.onRpcThread]      ... 15 more
`

**Comment by ben-clayton** [comment]
I've made some improvements that may help with the invalid ID issue.
I've also fixed the gapid apk name for x86.

That said, I see a crash in Java framework applications when tracing, just after the `eglMakeCurrent` call. I haven't had time to investigate why it's crashing yet.
